retired cli framework from _extended header and refactored _posix framework to replace it
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-util/script_header_joetoo/joetoo_cli_example b/dev-util/script_header_joetoo/joetoo_cli_example
--- a/dev-util/script_header_joetoo/joetoo_cli_example
+++ b/dev-util/script_header_joetoo/joetoo_cli_example
@@ -10,12 +10,12 @@ echo "header: $header"
 
 if [ -f "$header" ]; then . "$header"; else printf '%s' "failed to source header; cannot continue"; exit 1; fi
 printf '%s' "Checking for header commands to confirm sourcing"
-if command -v toc >/dev/null 2>&1 && command -v run_sequence_posix >/dev/null 2>&1 ; then
+if command -v toc >/dev/null 2>&1 && command -v run_sequence >/dev/null 2>&1 ; then
 handle_result $? ; else printf '%s\n' "Failed; header not sourced; cannot continue"; exit 1; fi
 
 #-----[ variables ]----------------------------------------------------
 
-# NOTE: varlist variables are initialized by app_configure_posix() and displayed by show_config();
+# NOTE: varlist variables are initialized by app_configure() and displayed by show_config();
 # the basic set of varlist variables is defined in script_header_joetoo and can be extended
 # either in the using script or in its .conf files.
 # An example is provided in the joetoo_cli_example script and in the template joetoo_cli_example.conf
@@ -33,20 +33,20 @@ handle_result $? ; else printf '%s\n' "Failed; header not sourced; cannot contin
 #
 # CAVEAT: varlist is instantiated when script_header_joetoo is sourced (above), so it IS safe to add
 # variable names to it in a "variables" section at the top of your main script, but note that
-# the standard joetoo cli script layout calls app_configure_posix() after that --
-# so anything you add to varlist before app_configure_posix will be over-written when app_configure_posix
+# the standard joetoo cli script layout calls app_configure() after that --
+# so anything you add to varlist before app_configure will be over-written when app_configure
 # calls initialize_var. which sets all bool. to $FALSE, all yn. to "no" and all others to ""
 #
 # Bottom line: you can append variable names to varlist at the top of your script, but if you do, you
-# ALSO need to reassign them AFTER app_configure_posix runs. Thus it is "easier" to just append
-# variable names to varlist in the .conf file, which app_configure_posix() loads AFTER it calls
+# ALSO need to reassign them AFTER app_configure runs. Thus it is "easier" to just append
+# variable names to varlist in the .conf file, which app_configure() loads AFTER it calls
 # initialize_vars, but be sure to also assign them, b/c they will not be initialized otherwise
 LOCALIZED=$FALSE; INITIALIZED_ME="no"
 varlist="${varlist} BREAK bool.LOCALIZED yn.INITIALIZED_ME"
 
 #-----[ functions ]----------------------------------------------------
 
-initialize_command_sequence_posix() # (POSIX) initialize command sequence for joetoo cli framework
+initialize_command_sequence() # (POSIX) initialize command sequence for joetoo cli framework
 { ics_ret=0
   _ics_FLAGGED=$FALSE
   info_msg_n "creating tempfile for command sequnce"
@@ -89,7 +89,7 @@ EOF
   unset -v _ics_entry _ics_FLAGGED _ics_result
   return $ics_ret
 }
-# @usage initialize_command_sequence_posix || die "failed to initialize_command_sequence_posix"
+# @usage initialize_command_sequence || die "failed to initialize_command_sequence"
 # @vars sets global num_cmds, cmd_seq_file
 # @vars initializes global starting_step=1, stopping_step=$num_cmds
 # @rule creates a temporary file for command execution and sets an EXIT trap for cleanup
@@ -109,10 +109,10 @@ test_function() {
 # @usage test_function <message>
 #-----[ main script ]----------------------------------------------------
 
-app_configure_posix || die "failed to app_configure_posix"
+app_configure || die "failed to app_configure"
 
 # re-assign varlist variables appended at the top of the script and thus
-# over-written by app_configure_posix
+# over-written by app_configure
 info_msg_n "(re)assigning LOCALIZED"
 LOCALIZED=$TRUE
 info_handle_result $? "$(TrueFalse $LOCALIZED)" "failed to reassign LOCALIZED"
@@ -121,14 +121,14 @@ INITIALIZED_ME="yes"
 info_handle_result $? "$INITIALIZED_ME" "failed to reassign INITIALIZED_ME" "$notice"
 
 d_do show_config "$info"  # show config prior to processing cmdline only at info/debug verbosity
-info_msg "(BEFORE process_cmdline_posix)"
+info_msg "(BEFORE process_cmdline)"
 
-process_cmdline_posix "$@" || die "failed to process_cmdline_posix"
+process_cmdline "$@" || die "failed to process_cmdline"
 
 show_config
-info_msg "(AFTER process_cmdline_posix)"
+info_msg "(AFTER process_cmdline)"
 
-run_sequence_posix "$status_file" "$starting_step" "$stopping_step"
+run_sequence "$status_file" "$starting_step" "$stopping_step"
 result=$?
 separator "$PN-$BUILD" "(Done)"
 notice_msg_n "$PN complete. Results:"
