script_header_joetoo-0.5.9.tbz2 - now with demonstrate_header as stand-alone script modeled on joetoo_cli_example
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-util/script_header_joetoo/joetoo_cli_example b/dev-util/script_header_joetoo/joetoo_cli_example
--- a/dev-util/script_header_joetoo/joetoo_cli_example
+++ b/dev-util/script_header_joetoo/joetoo_cli_example
@@ -3,17 +3,30 @@
 #
 script_header_installed_dir="/usr/sbin"
 #script_header_installed_dir=/home/joe/myUtilities/dev-util/script_header_joetoo
-# source script_header
 header="${script_header_installed_dir%/}/script_header_joetoo"
-
 echo "header: $header"
 
-if [ -f "$header" ]; then . "$header"; else printf '%s' "failed to source header; cannot continue"; exit 1; fi
+# source script_header
+# shellcheck source="/usr/sbin/script_header_joetoo"
+if [ -f "$header" ]; then
+  # source it if it isn't already sourced
+  # (redundant since it should also make this same check at its top section)
+  if [ "$JOETOO_ENVIRONMENT_ALREADY_SOURCED" ]; then
+    source_finding="was already sourced"
+  else
+    . "$header"
+    source_finding="sourced"
+  fi
+else
+  printf '%s' "failed to source header; cannot continue"
+  exit 1
+fi
+# verify sourced script_header
 printf '%s' "Checking for header commands to confirm sourcing"
 if command -v toc >/dev/null 2>&1 && command -v run_sequence >/dev/null 2>&1 ; then
-  printf '%s\n' " success; header sourced"
+  printf '%s\n' " success; header ${source_finding}"
 else
-   printf '%s\n' " Failed; header not sourced; cannot continue"; exit 1
+  printf '%s\n' " Failed; header not sourced; cannot continue"; exit 1
 fi
 
 #-----[ variables ]----------------------------------------------------
