add debug severity level functions to handle_result, right_status, etc
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-util/script_header_joetoo/script_header_joetoo b/dev-util/script_header_joetoo/script_header_joetoo
--- a/dev-util/script_header_joetoo/script_header_joetoo
+++ b/dev-util/script_header_joetoo/script_header_joetoo
@@ -2326,6 +2326,30 @@ info_handle_result() # (POSIX) "demote" handle_result() to INFO severity, and lo
 # @cont (it would run anyway since it operates at notice severity),
 # @cont  this is to make it NOT run when verbosity is 5
 
+debug_right_status() # (POSIX) "demote" right_status() to DEBUG severity, and local verbosity++ if DEBUG
+{ drs_ret=0
+  if [ "$DEBUG" ]; then
+    verbosity=7 d_do right_status "$@" "$debug"; drs_ret=$?
+  else
+    d_do right_status "$@" "$debug"; drs_ret=$?
+  fi; return $drs_ret ; }
+# @usage debug_right_status <status> || <fail-action>
+# @note this is not to make the command wrapped by d_do ... $debug run when verbosity=$debug
+# @cont (it would run anyway since it operates at notice severity),
+# @cont  this is to make it NOT run when verbosity is 5
+
+debug_handle_result() # (POSIX) "demote" handle_result() to DEBUG severity, and local verbosity++ if DEBUG
+{ dhr_ret=0
+  if [ "$DEBUG" ]; then
+    verbosity=7 d_do handle_result "$@" "$debug"; dhr_ret=$?
+  else
+    d_do handle_result "$@" "$debug"; dhr_ret=$?
+  fi; return $dhr_ret ; }
+# @usage debug_handle_result <status> <ok_msg> <err_msg> || <fail-action>
+# @note this is not to make the command wrapped by d_do ... $debug run when verbosity=$debug
+# @cont (it would run anyway since it operates at notice severity),
+# @cont  this is to make it NOT run when verbosity is 5
+
 notice_echo_msg() # (POSIX) "conditionalize" echo_msg() at NOTICE severity, and local verbosity++ if DEBUG
 { iem_ret=0
   if [ "$DEBUG" ]; then
@@ -2347,6 +2371,18 @@ info_echo_msg() # (POSIX) "conditionalize" echo_msg() at INFO severity, and loca
   fi; return $iem_ret ; }
 # @usage info_echo_msg <message>
 # @note this is not to make the command wrapped by d_do ... $info run when verbosity=$info
+# @cont (it would run anyway since it operates at notice severity),
+# @cont  this is to make it NOT run when verbosity is 5
+
+debug_echo_msg() # (POSIX) "conditionalize" echo_msg() at INFO severity, and local verbosity++ if DEBUG
+{ dem_ret=0
+  if [ "$DEBUG" ]; then
+    verbosity=7 d_do echo_msg "$@" "$debug"; dem_ret=$?
+  else
+    d_do echo_msg "$@" "$debug"; dem_ret=$?
+  fi; return $dem_ret ; }
+# @usage debug_echo_msg <message>
+# @note this is not to make the command wrapped by d_do ... $debug run when verbosity=$debug
 # @cont (it would run anyway since it operates at notice severity),
 # @cont  this is to make it NOT run when verbosity is 5
 
@@ -2378,6 +2414,18 @@ info_echo_msg_n() # (POSIX) "conditionalize" echo_msg_n() at INFO severity, and 
 # @cont (it would run anyway since it operates at notice severity),
 # @cont  this is to make it NOT run when verbosity is 5
 
+debug_echo_msg_n() # (POSIX) "conditionalize" echo_msg_n() at INFO severity, and local verbosity++ if DEBUG
+{ demn_ret=0
+  if [ "$DEBUG" ]; then
+    verbosity=7 d_do echo_msg_n "$@" "$debug"; demn_ret=$?
+  else
+    d_do echo_msg_n "$@" "$debug"; demn_ret=$?
+  fi; return $demn_ret ; }
+# @usage debug_echo_msg_n <message>
+# @note this is not to make the command wrapped by d_do ... $debug run when verbosity=$debug
+# @cont (it would run anyway since it operates at notice severity),
+# @cont  this is to make it NOT run when verbosity is 5
+
 echo_e_msg_n()  # (POSIX) interpreted echo with optional logging
 { echo_e_msg_ret=0; _msg="$*"
   _bitmask="$(( STDOUT | INTERPRET ))"
@@ -2403,6 +2451,18 @@ info_echo_e_msg_n() # (POSIX) "conditionalize" echo_e_msg_n() at INFO severity, 
   fi; return $ieemn_ret ; }
 # @usage info_echo_msg_n <message>
 # @note this is not to make the command wrapped by d_do ... $info run when verbosity=$info
+# @cont (it would run anyway since it operates at notice severity),
+# @cont  this is to make it NOT run when verbosity is 5
+
+debug_echo_e_msg_n() # (POSIX) "conditionalize" echo_e_msg_n() at INFO severity, and local verbosity++ if DEBUG
+{ deemn_ret=0
+  if [ "$DEBUG" ]; then
+    verbosity=7 d_do echo_e_msg_n "$@" "$debug"; deemn_ret=$?
+  else
+    d_do echo_e_msg_n "$@" "$debug"; deemn_ret=$?
+  fi; return $deemn_ret ; }
+# @usage debug_echo_msg_n <message>
+# @note this is not to make the command wrapped by d_do ... $debug run when verbosity=$debug
 # @cont (it would run anyway since it operates at notice severity),
 # @cont  this is to make it NOT run when verbosity is 5
 
