add script_header_joetoo/joetoo_cli_example.conf and update header to find local_usage file
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-util/script_header_joetoo/script_header_joetoo b/dev-util/script_header_joetoo/script_header_joetoo
--- a/dev-util/script_header_joetoo/script_header_joetoo
+++ b/dev-util/script_header_joetoo/script_header_joetoo
@@ -2979,7 +2979,6 @@ app_configure_posix() {
     head -n 1 )
   log_handle_result $? "$local_cmdline_arguments" "error finding local_cmdline_arguments" || _c_FLAGGED=$TRUE
 
-
   # find (validates) *_example_local.cmdline_compound_arguments; assign first match
   log_message_n "looking for local_cmdline_compound_arguments"
   local_cmdline_compound_arguments=$( \
@@ -2988,10 +2987,18 @@ app_configure_posix() {
     head -n 1 )
   log_handle_result $? "$local_cmdline_compound_arguments" "error finding local_cmdline_compound_arguments" || _c_FLAGGED=$TRUE
 
+  # find (validates) *_example_local.cmdline_compound_arguments; assign first match
+  log_message_n "looking for local_usage file"
+  local_usage=$( \
+    find "${app_customization_root%/}/" \
+      -name "[[:alnum:]]*_local.usage" | \
+    head -n 1 )
+  log_handle_result $? "$local_usage" "error finding local_usage" || _c_FLAGGED=$TRUE
+
   # set default verbosity if not set externally
   log_message_n "maybe assigning verbosity"
   if [ -z "$verbosity" ] ; then
-    verbosity=3
+    verbosity=5
     log_handle_result $? "now set: $verbosity" '' || _c_FLAGGED=$TRUE
   else
     log_handle_result $TRUE "already set: $verbosity" ''
@@ -3004,7 +3011,7 @@ app_configure_posix() {
   log_handle_result $_c_result '' '' || _c_FLAGGED=$TRUE
 
   [ "$_c_FLAGGED" ] && ret=1
-  unset -v _c_FLAGGED _c_file _c_result
+  un#set -v _c_FLAGGED _c_file _c_result
   return $ret
 }
 # @usage app_configure_posix
@@ -3042,7 +3049,7 @@ usage_posix()                # explain default usage; mod with local "usage modu
   log_message "   -[0-${N}] sets starting_step (default 0 otherwise)"
   # source user-script specific usage-module which should be built in the same format
   log_message "${BMon}additional ${app_customization_root} - commandline options:${Boff}"
-  [ -f ${app_customization_root%/}/local.usage ] && source ${app_customization_root%/}/local.usage
+  [ -f ${local_usage} ] && . ${local_usage}
   printf '\n'
   log_message "${BYon}${PN} workflow sequence (steps):${Boff}"
   for _u_step in $(seq 1 $num_cmds); do
