move ash-incompatible functions from script_header_joetoo to _extended
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-util/script_header_joetoo/script_header_joetoo_extended b/dev-util/script_header_joetoo/script_header_joetoo_extended
--- a/dev-util/script_header_joetoo/script_header_joetoo_extended
+++ b/dev-util/script_header_joetoo/script_header_joetoo_extended
@@ -9,6 +9,60 @@
 # note: this header expects this to be assigned already
 #script_header_installed_dir=/usr/sbin
 
+# CPR, QCR, and QCC moved here due to ash-incompatibility (uses bash array and ${var:n} form)
+CPR()       # CPR [r|c] - echo # of cursor row, col, or both (w/o leading ESC[, trailing R)
+{ QUERY="${CSI}6n"; echo -en "${QUERY}" ; read -sdR CURPOS
+  IFS=';' read -ra COORDS <<< "${CURPOS:2}" ; case ${1:0:1} in
+    [rR]) echo "${COORDS[0]}" | cut -d';' -f1 ;; # report row
+    [cC]) echo "${COORDS[1]}" | cut -d';' -f2 ;; # report col
+    [sS]) :  ;;                                  # be silent
+    *   ) echo "${COORDS[@]}" ;; esac ; }        # report both
+QCR()       # use silent CPR to report row
+{ CPR s; echo "${COORDS[0]}" ; }
+QCC()       # use silent CPR to report column
+{ CPR s; echo "${COORDS[1]}" ; }
+
+# isfloat moved here due to ash-incompatibility (uses regec compare =~)
+isfloat()       # test if $1 is a floating point number; return true/false
+{ inputstring="$1" ; [[ "$inputstring" =~ ^[+-]?([0-9]*\.)?[0-9]+([eE][+-]?[0-9]+)?$ ]] && return $TRUE || return $FALSE ; }
+
+# isfloat moved here due to ash-incompatibility (uses isfloat())
+map()           # linearly map input number from input range to output range
+{ # trap non-numeric input  
+! isfloat $1 && E_message "invalid map_val for ${FUNCNAME[0]} [$1]" && return 1
+! isfloat $2 && E_message "invalid from_lower bound for ${FUNCNAME[0]} [$2]" && return 1
+! isfloat $3 && E_message "invalid from_upper bound for ${FUNCNAME[0]} [$3]" && return 1
+! isfloat $4 && E_message "invalid to_lower bound for ${FUNCNAME[0]} [$4]" && return 1
+! isfloat $5 && E_message "invalid to_upper bound for ${FUNCNAME[0]} [$5]" && return 1
+[ ! -z "$6" ] && ! isfloat $6 && echo "invalid scale for ${FUNCNAME[0]} [$6]" && return 1  
+ map_val=$1 ; from_lower=$2 ; from_upper=$3 ; to_lower=$4 ; to_upper=$5
+ scale=${6:-1} # Set default scale to 1 if not provided (number of digits after .)
+# trap invalid map_val (not within input range) (( $(... | bc) )) for float #s
+(( $(echo "$map_val < $from_lower" | bc -l) )) || \
+    (( $(echo "$map_val > $from_upper" | bc -l) )) && \
+    E_message "invalid map_val [${map_val}], not w/in input range [${from_lower} - ${from_upper}]" && return 1
+  
+# trap invalid input or output ranges - leave this unless prohibiting "reverse mapping"
+#[ $to_upper -lt $to_lower ] && E_message "invalid input range [ $to_upper - $to_lower ]" && return 1
+#[ $from_upper -lt $from_lower ] && E_message "invalid input range [ $from_upper - $from_lower ]" && return 1
+# initialize result variable  
+result=999999
+# calculate scaling factor
+ from_delta=$(echo "scale=$scale; $from_upper - $from_lower" | bc -l)
+ to_delta=$(echo "scale=$scale; $to_upper - $to_lower" | bc -l) 
+ from_offset=$(echo "scale=$scale; $map_val - $from_lower" | bc -l)   # how far (above from_lower) offest into from-range
+ map_factor=$(echo "scale=$scale; $to_delta / $from_delta" | bc -l)
+# ratio > 1 means scaling up to a "wider" range (even if lower numbers)
+# ratio < 1 means scaling down to a "narrower" range (even if higher numbers)
+
+# scale the input offset against the output range
+ to_offset=$(echo "scale=$scale; $from_offset * $map_factor" | bc -l)
+
+# now offset (above the to_lower bound) the scaled number into the output range
+result=$(echo "scale=$scale; $to_lower + $to_offset" | bc -l)
+return 0
+}
+
 countdown() # output text message (arg $2, optional), and count-down seconds (arg $1)
 {
   # special note: use base#number notation with prefix 10# to ensure interpretation as base 10
@@ -723,4 +777,8 @@ summarize_my_extension()  # generate this helpful display
   # print summary of included functions (indent left)
   grep "()" ${script_header_installed_dir%/}/script_header_joetoo_extended | grep -v "grep" | sed 's|^|  |'
   echo
+  message "${BYon}Map input value 16 from input range 10-30 to output range 10-100 (scale to one decimal point) with ${BGon}map${Boff} 16 10 30 10 100 1" && \
+  map 16 10 30 10 100 1 && echo "result: $result"
+  echo
+
 }
