added alpha_words and moved vercomp and show_results to script_header_brendlfly.  The extended header is now only box drawing

diff --git a/script_header_brendlefly b/script_header_brendlefly
--- a/script_header_brendlefly
+++ b/script_header_brendlefly
@@ -151,7 +151,8 @@ d_echo()        # echo all arguments if "external" boolean VERBOSE tests true
 { [ $VERBOSE ] && echo "$@"; }
 
 status_color()  # emit to stdout the escape seq for color based on arg $1 (T/F Y/N 1/0)
-{ case $1 in "1"|"y"|"Y"|$TRUE) echo -en ${BGon};; "0"|"n"|"N"|$FALSE) echo -en ${BRon};; *) echo -en ${BYon};; esac ; }
+{ case $1 in "1"|"y"|"Y"|$TRUE) echo -en ${BGon};; "0"|"n"|"N"|$FALSE) echo -en ${BRon};; \
+                             *) echo -en ${BYon};; esac ; }
 
 prompt() {      # get answer to a y/n question - return response in "external" variable $answer
   ps=$1; SCP; echo -en $ps; answer="x";
@@ -162,6 +163,17 @@ prompt() {      # get answer to a y/n question - return response in "external" v
       case ${answer:0:1} in "" | "n" | "N" ) answer="n" ;; "y" | "Y" ) answer="y" ;; *) answer="x";; esac;
   done;
 }
+
+alpha_words()   # alphabetize the words in a quoted input string
+{ words=($1); echo $( for ((i=0; i<${#words[@]}; i++)); do echo ${words[i]}; done | sort ); }
+
+vercomp()       # compare two version numbers return [0:equal|1:greaterthan|2:lessthan]
+{ if [[ "$1" == "$2" ]]; then return 0; else first=$(echo -en "$1\n$2" | sort -V | head -n1);
+  [[ "$first" == "$2" ]] && return 1 || return 2; fi }
+
+show_result()   # show the result of vercomp comparison, in english
+{ case $1 in 1) echo "${LBon}>${Boff}";; 2) echo "${BRon}<${Boff}";; \
+             0) echo "${BGon}=${Boff}";; *) echo "${BYon}*** Error ***${Boff}";; esac }
 
 my_date()       # echo a simply formatted date string (DDD MM dd hh:mm:ss AP TZ yyyy)
 {
@@ -334,6 +346,22 @@ summarize_me()  # list contents of this script header (employ me with "source" o
   msg="${msg}${BGon})${BYon}\"${BGon}; ${BBon}echo${Boff}" && echo -e "${msg}" && \
   echo && \
   message "  ${BYon}VERBOSE is currently $(status_color $VERBOSE)$( [[ $VERBOSE ]] && echo -en true || echo -en false)" && echo && \
+  message_n "${BYon}Compare version number ${BWon}1 ${BYon}to${BWon} 1${Boff}  " && \
+  vercomp 1 1; echo -e "$(show_result $?)" && \
+  message_n "${BYon}Compare version number ${BWon}2 ${BYon}to${BWon} 1${Boff}  " && \
+  vercomp 2 1; echo -e "$(show_result $?)" && \
+  message_n "${BYon}Compare version number ${BWon}1 ${BYon}to${BWon} 2${Boff}  " && \
+  vercomp 1 2; echo -e "$(show_result $?)" && \
+  message_n "${BYon}Compare version number ${BWon}1.2.0 ${BYon}to${BWon} 1.2.1${Boff}  " && \
+  vercomp 1.2.0 1.2.1; echo -e "$(show_result $?)" && \
+  message_n "${BYon}Compare version number ${BWon}1.2.0-r1 ${BYon}to${BWon} 1.2.0${Boff}  " && \
+  vercomp 1.2.0-r1 1.2.0; echo -e "$(show_result $?)" && \
+  message_n "${BYon}Compare version number ${BWon}1..1 ${BYon}to${BWon} 1.2${Boff}  " && \
+  vercomp 1..1 1.2; echo -e "$(show_result $?)" && \
+  message_n "${BYon}Compare version number ${BWon}1.0 ${BYon}to${BWon} 1.0-r10${Boff}  " && \
+  vercomp 1.0 1.0-r10; echo -e "$(show_result $?)" && \
+  message_n "${BYon}Compare version number ${BWon}3.4 ${BYon}to${BWon} 3.4-r2${Boff}  " && \
+  vercomp 3.4 3.4-r2; echo -e "$(show_result $?)" && echo && \
   message "  ${BYon}About to run:\n        ${BBon}sh_countdown ${Boff}6 ${BGon}&& \\ ${Boff}" && \
   echo -e "        ${BBon}message_n${Boff} "'"\\nFinishing with status of summarization --->" '"${BGon}; ${BBon}right_status ${BRon}"'$?'"${BGon}; ${BBon}echo${Boff}" && \
   echo && \
