bump script_header, new hardened vn kernel

diff --git a/script_header_brendlefly b/script_header_brendlefly
--- a/script_header_brendlefly
+++ b/script_header_brendlefly
@@ -184,8 +184,8 @@ d_echo()        # echo all arguments if "external" boolean VERBOSE tests true
 { [[ $VERBOSE && $2 -le $verbosity ]] && echo "$@"; }
 
 status_color()  # emit to stdout the escape seq for color based on arg $1 (T/F Y/N 1/0)
-{ case $1 in "1"|"y"|"Y"|$TRUE) echo -en ${BGon};; "0"|"n"|"N"|$FALSE) echo -en ${BRon};; \
-                             *) echo -en ${BYon};; esac ; }
+{ case $1 in "1"|"y"|"Y"|"up"|$TRUE   ) echo -en ${BGon};;
+             "0"|"n"|"N"|"down"|$FALSE) echo -en ${BRon};; *) echo -en ${BYon};; esac ; }
 
 TrueFalse()     # echo to stdout "True" or "False", depending on truth of arg $1
 {  [[ $1 ]] && echo -en "True" || echo -en "False" ; }
@@ -218,6 +218,18 @@ my_short_date() # echo a short formatted date string (yyyymmdd)
 {
   month=$(date +%b); monthday=$(date +%d); year=$(date +%Y); timehack=$(date +%H:%M:%S);
   echo "${monthday}${month}${year}-${timehack}";
+}
+
+loggit()        # send a job completion status message to the cron logger
+{
+[[ $# -gt 2 ]] && E_message "invalid loggit arguments" && exit 1
+[[ -z $2 ]] && EXIT_STATUS=0 || EXIT_STATUS="$2"
+[[ -z $1 ]] && PROGRAM=Unspecified || PROGRAM="$1"
+case $EXIT_STATUS in
+  0 ) PRIORITY="notice" && MESSAGE="succeeded.";;
+  * ) PRIORITY="err" && MESSAGE="failed with exit status ${EXIT_STATUS}";;
+esac
+/usr/bin/logger -p cron.$PRIORITY "$PROGRAM $MESSAGE"
 }
 
 repeat()        # output a repeated string of character (arg $1) of length (arg $2)
