cosmetic udate to script_header [d_]right_status() functions

diff --git a/script_header_brendlefly b/script_header_brendlefly
--- a/script_header_brendlefly
+++ b/script_header_brendlefly
@@ -162,16 +162,16 @@ checkshell()    # reset colors if this shell is not interactive
 { if [[ $- != *i* ]]; then source ${non_interactive_header}; fi; }
 
 message()       # echo a simply formatted message (arg $1) to the screen
-{ echo -e "${BGon}*${Boff} ${1}" && return 0 || return 1; }
+{ echo -e " ${BGon}*${Boff} ${1}" && return 0 || return 1; }
 
 message_n()     # echo -n a simply formatted message (arg $1) to the screen
-{ echo -en "${BGon}*${Boff} ${1}" && return 0 || return 1; }
+{ echo -en " ${BGon}*${Boff} ${1}" && return 0 || return 1; }
 
 E_message()     # echo a simply formatted error message (arg $1) to the screen
-{ echo -e "${BRon}*${Boff} ${1}" && return 0 || return 1; }
+{ echo -e " ${BRon}*${Boff} ${1}" && return 0 || return 1; }
 
 E_message_n()   # echo -n a simply formatted error message (arg $1) to the screen
-{ echo -en "${BRon}*${Boff} ${1}" && return 0 || return 1; }
+{ echo -en " ${BRon}*${Boff} ${1}" && return 0 || return 1; }
 
 d_message()     # pass argument $1 to message() if "external" boolean VERBOSE tests true
 { [[ $VERBOSE && $2 -le $verbosity ]] && message "$1"; }
@@ -189,8 +189,8 @@ d_echo()        # echo all arguments if "external" boolean VERBOSE tests true
 { [[ $VERBOSE && $2 -le $verbosity ]] && echo "$@"; }
 
 status_color()  # emit to stdout the escape seq for color based on arg $1 (T/F Y/N 1/0)
-{ case $1 in "1"|[yY]*|"up"|$TRUE   ) echo -en ${BGon};;
-             "0"|[nN]*|"down"|$FALSE) echo -en ${BRon};; *) echo -en ${BYon};; esac ; }
+{ case $1 in "1"|[yY]*|[tT]*|"up"|$TRUE   ) echo -en ${BGon};;
+             "0"|[nN]*|[fF]*|"down"|$FALSE) echo -en ${BRon};; *) echo -en ${BYon};; esac ; }
 
 TrueFalse()     # echo to stdout "True" or "False", depending on truth of arg $1
 {  [[ $1 ]] && echo -en "True" || echo -en "False" ; }
@@ -275,26 +275,18 @@ separator()     # draw a horizontal line with a simple title (arg $1) and prefac
 right_status()  # output 8 char [ ok/fail ] status at the right margin
 { # test message_n "good_test" ; right_status $?
   #      E_message_n "fail_test" && cat unexistent 2>/dev/null; right_status $?
-  local status msg lpad rpad
-  if [ $1 -eq 0 ]; then msg="${BGon}Ok${Boff}"; lpad=2; rpad=2
-  else msg="${BRon}Fail${Boff}"; lpad=1; rpad=1; fi
-  msg="${BBon}[$(repeat ' ' $lpad)${msg}$(repeat ' ' $rpad)${BBon}]${Boff}"
-  let "msg_len=8"    # it's always 8, I made it that way
-  # go to start of line, *then* move fwd to the right distance (9 chars) from the right margin
-  echo -en "\r" && CUF $(( $(termwidth) - $msg_len -1 )) && echo -e "$msg" && return 0 || return 1
+  local msg status=$1
+  [[ $status -eq 0 ]] && msg="${BBon}[ ${BGon}Ok ${BBon}]${Boff}" || msg="${BBon}[ ${BRon}!! ${BBon}]${Boff}"
+  # go to start of line, *then* move fwd to 7 chars from the right margin ("[ xx ]" is 6)
+  echo -en "\r" && CUF $(( $(termwidth) - 7 )) && echo -e "$msg" && return 0 || return 1
 }
 
 d_right_status()  # output 8 char [ ok/fail ] status at the right margin, if $VERBOSE
-{ # test d_message_n "good_test" 1; d_right_status $? 1
-  #      dE_message_n "fail_test" 1 && cat unexistent 2>/dev/null; d_right_status $? 1
-  local status msg lpad rpad
-  if [ $1 -eq 0 ]; then msg="${BGon}Ok${Boff}"; lpad=2; rpad=2
-  else msg="${BRon}Fail${Boff}"; lpad=1; rpad=1; fi
-  msg="${BBon}[$(repeat ' ' $lpad)${msg}$(repeat ' ' $rpad)${BBon}]${Boff}"
-  let "msg_len=8"    # it's always 8, I made it that way
-  # go to start of line, *then* move fwd to the right distance (9 chars) from the right margin
-  [[ $VERBOSE && $2 -le $verbosity ]] && echo -en "\r" && CUF $(( $(termwidth) - $msg_len -1 )) && \
-    echo -e "$msg" && return 0 || return 1
+{ # test with v=((verbosity+1)) and v=(($verbosity-1))
+  # d_message_n "good_test" $v; d_right_status $? $v
+  #      dE_message_n "fail_test" $v && cat unexistent 2>/dev/null; d_right_status $? $v
+  local status=$1
+  [[ $VERBOSE && $2 -le $verbosity ]] && right_status $status && return 0 || return 1
 }
 
 sh_countdown()  # count-down seconds (arg $1)
