comment-out attempt to protect qemu from removal
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-sbc/crossbuild-tools/mkupd-files/common/usr/sbin/finalize-chroot-for-update b/dev-sbc/crossbuild-tools/mkupd-files/common/usr/sbin/finalize-chroot-for-update
--- a/dev-sbc/crossbuild-tools/mkupd-files/common/usr/sbin/finalize-chroot-for-update
+++ b/dev-sbc/crossbuild-tools/mkupd-files/common/usr/sbin/finalize-chroot-for-update
@@ -403,23 +403,43 @@ protect-qemu-for-chroot() {
         echo -e -n " (${BMon}${VERSION}${Boff})"
         right_status $TRUE
     fi
-    # add qemu to world set (to prevent removal)
-    message "adding qemu to world set"
-    "${chroot_emerge}" --noreplace "${qemu_pkg}"  || die "failed to add qemu to world set"
-    echo -e -n " (${BGon}added${Boff})"
-    right_status $TRUE
 
-    # create (or update) package.mask (to prevent "upgrade" beyond current version)
-    mask="/etc/portage/package.mask/99-qemu-frozen"
-    message_n "looking for (to create/update) ${mask}"
-    if [ -f "${mask}" ] ; then
-        action="updated"
-    else
-        action="created"
-    fi
-    echo ">${qemu_pkg}-${VERSION}" > "${mask}" 2>/dev/null || die "failed to create package.mask for qemu"
-    echo -e -n " (${BGon}${action}${Boff})"
-    right_status $TRUE
+# Goal was to prevent removal or upgrade of this specific qemu
+# (a build-host [x86_64] binary on the $TARGET system)
+#
+#   $ file /usr/armv6j-unknown-linux-gnueabihf/usr/bin/qemu-system-arm
+#   /usr/armv6j-unknown-linux-gnueabihf/usr/bin/qemu-system-arm: \
+#       ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), \
+#       dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for \
+#       GNU/Linux 3.2.0, stripped
+#
+# (cannot qemu-chroot into TARGET w/o it, but it is not in
+#  TARGET system's @world set, so a chroot "emerge --depclean"
+#  would remove it, and a chroot "emerge -uavDN world" would replace it
+#  with a TARGET_ARCH binary
+#
+# Problem with this approach (add to world, mask future versions) --
+#    adding to TARGET's world causes a portage world update to
+#    build the stabilized version again (as a TARGET_ARCH binary, along with its dependencies
+#    (keeping it here comemmented out until I figure out how to handle)
+#
+#    # add qemu to world set (to prevent removal)
+#    message "adding qemu to world set"
+#    "${chroot_emerge}" --noreplace "${qemu_pkg}"  || die "failed to add qemu to world set"
+#    echo -e -n " (${BGon}added${Boff})"
+#    right_status $TRUE
+#
+#    # create (or update) package.mask (to prevent "upgrade" beyond current version)
+#    mask="/etc/portage/package.mask/99-qemu-frozen"
+#    message_n "looking for (to create/update) ${mask}"
+#    if [ -f "${mask}" ] ; then
+#        action="updated"
+#    else
+#        action="created"
+#    fi
+#    echo ">${qemu_pkg}-${VERSION}" > "${mask}" 2>/dev/null || die "failed to create package.mask for qemu"
+#    echo -e -n " (${BGon}${action}${Boff})"
+#    right_status $TRUE
 
     return 0
 }
