joetoolkit-0.8.11.tbz2 - refactor check_resilient_services for j_msg and array of services
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-util/joetoolkit/joetoolkit/check_resilient_services b/dev-util/joetoolkit/joetoolkit/check_resilient_services
--- a/dev-util/joetoolkit/joetoolkit/check_resilient_services
+++ b/dev-util/joetoolkit/joetoolkit/check_resilient_services
@@ -5,7 +5,7 @@
 # source headers
 #script_header_installed_dir=./         ## only when testing, pre-ebuild
 script_header_installed_dir=/usr/sbin   # this is where it should be installed
-source ${script_header_installed_dir%/}/script_header_joetoo
+source "${script_header_installed_dir%/}/script_header_joetoo"
 
 # only needed for testing sources pending package build
 #script_header_installed_dir=/home/joe/myUtilities/dev-util/script_header_joetoo
@@ -19,14 +19,14 @@ cmdseq_statusfile="/root/${PN}_status"
 #   /etc/${BPN}/ stores local custom conent employing cli processing, etc --
 #     local.useage ; local.cmdline_arguments ; local.cmdline_compound_arguments
 BPN="joetoolkit/${PN}"
-source ${script_header_installed_dir%/}/script_header_joetoo_extended
+source "${script_header_installed_dir%/}/script_header_joetoo_extended"
 
-FLAGGED=$FALSE
+FLAGGED="$FALSE"
 result=0
 
 varlist=" PN BPN BUILD starting_step stopping_step cmdseq_statusfile"
 varlist+=" services_list sleepwait"
-varlist+=" BREAK bool.INTERACTIVE bool.FLAGGED bool.VERBOSE verbosity"
+varlist+=" BREAK bool.INTERACTIVE bool.FLAGGED verbosity"
 
 hidden_varlist="result response answer "
 
@@ -47,71 +47,58 @@ initialize_variables() {
     initialize_vars ${varlist}
     initialize_vars ${hidden_varlist}
 
-    FLAGGED=$FALSE
+    FLAGGED="$FALSE"
     # assign initial values
-    message_n "Assigning PN = $(basename $0) ..."
-    PN=$(basename $0) ; result=$? ; right_status $result
-    [ ! $result -eq 0 ] && FLAGGED=$TRUE
+    j_msg -${info} -m -n "Assigning PN = $(basename $0) ..."
+    PN=$(basename $0) ; right_status $? ${info} || FLAGGED="$TRUE"
 
-    message_n "Assigning BPN = ${PN} ..."
-    BPN="joetoolkit/${PN}" ; result=$? ; right_status $result
-    [ ! $result -eq 0 ] && FLAGGED=$TRUE
+    j_msg -${info} -m -n "Assigning BPN = ${PN} ..."
+    BPN="joetoolkit/${PN}" ; right_status $? ${info} || FLAGGED="$TRUE"
 
-    message_n "Assigning INTERACTIVE = \$TRUE ..."
-    INTERACTIVE=$TRUE ; result=$? ; right_status $result
-    [ ! $result -eq 0 ] && FLAGGED=$TRUE
+    j_msg -${info} -m -n "Assigning INTERACTIVE = \$TRUE ..."
+    INTERACTIVE="$TRUE" ; right_status $? ${info} || FLAGGED="$TRUE"
 
-    message_n "Assigning VERBOSE = \$TRUE ..."
-    VERBOSE=$TRUE ; result=$? ; right_status $result
-    [ ! $result -eq 0 ] && FLAGGED=$TRUE
+    j_msg -${info} -m -n "Assigning verbosity = 3 ..."
+    verbosity=3 ; right_status $? ${info} || FLAGGED="$TRUE"
 
-    message_n "Assigning verbosity = 3 ..."
-    verbosity=3 ; result=$? ; right_status $result
-    [ ! $result -eq 0 ] && FLAGGED=$TRUE
+    j_msg -${info} -m -n "Sourcing BUILD ..."
+    source /etc/${BPN}/BUILD ; right_status $? ${info} || FLAGGED="$TRUE"
 
-    message_n "Sourcing BUILD ..."
-    source /etc/${BPN}/BUILD ; result=$? ; right_status $result
-    [ ! $result -eq 0 ] && FLAGGED=$TRUE
+    j_msg -${info} -m -n "Assigning starting_step = 0 ..."
+    starting_step=0 ; right_status $? ${info} || FLAGGED="$TRUE"
 
-    message_n "Assigning starting_step = 0 ..."
-    starting_step=0 ; result=$? ; right_status $result
-    [ ! $result -eq 0 ] && FLAGGED=$TRUE
+    j_msg -${info} -m -n "Assigning sleepwait = 0.5 ..."
+    sleepwait=0.5 ; right_status $? ${info} || FLAGGED="$TRUE"
 
-    message_n "Assigning sleepwait = 0.5 ..."
-    sleepwait=0.5 ; result=$? ; right_status $result
-    [ ! $result -eq 0 ] && FLAGGED=$TRUE
+    j_msg -${info} -m -n "Assigning stopping_step = \${#command_sequence[@]} - 1 ..."
+    stopping_step=$(( ${#command_sequence[@]} - 1 )) ; right_status $? ${info} || FLAGGED="$TRUE"
 
-    message_n "Assigning stopping_step = \${#command_sequence[@]} - 1 ..."
-    stopping_step=$(( ${#command_sequence[@]} - 1 )) ; result=$? ; right_status $result
-    [ ! $result -eq 0 ] && FLAGGED=$TRUE
+    j_msg -${info} -m -n "Assigning cmdseq_statusfile = /root/${PN}_status ..."
+    cmdseq_statusfile="/root/${PN}_status" ; right_status $? ${info} || FLAGGED="$TRUE"
 
-    message_n "Assigning cmdseq_statusfile = /root/${PN}_status ..."
-    cmdseq_statusfile=/root/${PN}_status ; result=$? ; right_status $result
-    [ ! $result -eq 0 ] && FLAGGED=$TRUE
-
-    message_n "Assigning runlevels ..."
+    j_msg -${info} -m -n "Assigning runlevels ..."
     # runlevels=$(find /etc/runlevels/ -mindepth 1 -maxdepth 1 -printf '%f\n')
-    runlevels="boot sysinit default"  # dont check nonetwork or shutdown
-    result=$? ; right_status $result
-    [ ! $result -eq 0 ] && FLAGGED=$TRUE
+    runlevels=("boot" "sysinit" "default")  # dont check nonetwork or shutdown
+    right_status $? ${info} || FLAGGED="$TRUE"
 
     [ $FLAGGED ] && return 1 || return 0
 }
 
 check_all_services() {
-    for runlevel in ${runlevels}; do
-        check_runlevel_services ${runlevel} || die "failed to check_runlevel_services ${runlevel}"
+    for runlevel in "${runlevels[@]}"; do
+        check_runlevel_services "${runlevel}" || die "failed to check_runlevel_services ${runlevel}"
     done
 }
 
 check_runlevel_services() {
     rl=$1
-    separator ${PN} "(${rl} services)"
-    runlevel_services=$(find /etc/runlevels/${rl}/ -mindepth 1 -maxdepth 1 -printf '%f\n')
-    for service in ${runlevel_services} ; do
-        d_message_n "checking service ${service} ..." 2
-        check_fix_one_service ${service}
-        right_status $?
+    separator "${PN}" "(${rl} services)"
+    # load array of services using find to create \0 delimited list of service names
+    readarray -d '' -t runlevel_services < <(find "/etc/runlevels/${rl}/" -mindepth 1 -maxdepth 1 -printf '%f\0')
+    for service in "${runlevel_services[@]}" ; do
+         j_msg -${info} -m -n "checking service ${service} ..."
+        check_fix_one_service "${service}"
+        right_status $? ${info}
     done
     echo
     return 0
@@ -121,44 +108,44 @@ check_fix_one_service() {
     local svc="$1"
 
     # get the status of service named by $1 and act accordingly
-    status=$(get_svc_status ${svc})
+    status=$(get_svc_status "${svc}")
     d_message "svc: ${svc}   status: $(service_status_color ${status})${status}${Boff}" 4
     # if status is stopped or crashed, try to restart
     if [[ "${status}" =~ ^("stopped"|"crashed")$ ]] ; then
         debug_do 'echo -e -n " (restarting)"' 2
-        restart_service ${svc} && sleep ${sleepwait}
+        restart_service "${svc}" && sleep ${sleepwait}
 
         # check again, and if still stopped or crashed, try to stop and then start
-        status=$(get_svc_status ${svc})
+        status=$(get_svc_status "${svc}")
         d_message "svc: ${svc}   status: $(service_status_color ${status})${status}${Boff}" 4
         # if status is stopped or crashed, try to stop and then start
         if [[ "${status}" =~ ^("stopped"|"crashed")$ ]] ; then
             debug_do 'echo -e -n "(stop-starting)"' 2
-            stop_start_service ${svc} && sleep ${sleepwait}
+            stop_start_service "${svc}" && sleep ${sleepwait}
 
             # check again, and if still stopped or crashed, try to look for and remove the running pid tracking file, then restart
-            status=$(get_svc_status ${svc})
+            status=$(get_svc_status "${svc}")
             d_message "svc: ${svc}   status: $(service_status_color ${status})${status}${Boff}" 4
             # if status is stopped or crashed, try remove pid file and then restart
             if [[ "${status}" =~ ^("stopped"|"crashed")$ ]] ; then
                 debug_do 'echo -e -n "(removing pidfile)"' 2
-                rmpid_restart_service ${svc} && sleep ${sleepwait}
+                rmpid_restart_service "${svc}" && sleep ${sleepwait}
                 # if still stopped or crashed, return 1
                 if [[ "${status}" =~ ^("stopped"|"crashed")$ ]] ; then
                     debug_do 'echo -e -n "(${BRon}still down${Boof})"' 2
                     loggit "${PN}" 1
                     return 1
                 else
-                    /usr/bin/logger -p cron.notice ${PN} "${svc} successfully restarted after rm pidfile"
+                    /usr/bin/logger -p cron.notice "${PN}" "${svc} successfully restarted after rm pidfile"
                 fi # still down
             else
-                /usr/bin/logger -p cron.notice ${PN} "${svc} successfully started after stop"
+                /usr/bin/logger -p cron.notice "${PN}" "${svc} successfully started after stop"
             fi # third check
         else
-            /usr/bin/logger -p cron.notice ${PN} "${svc} successfully restarted"
+            /usr/bin/logger -p cron.notice "${PN}" "${svc} successfully restarted"
         fi # second check
     else
-        debug_do '/usr/bin/logger -p cron.info ${PN} "${svc} status checked - ok"' 3
+        debug_do '/usr/bin/logger -p cron.info "${PN}" "${svc} status checked - ok"' 3
     fi # first check
     return 0
 }
@@ -167,26 +154,26 @@ restart_service() {
     # restart the service named by $1
     d_message "in ${FUNCNAME[0]}}" 5
     local svc="$1"
-    /etc/init.d/${svc} restart >/dev/null 2>&1
+    "/etc/init.d/${svc}" restart >/dev/null 2>&1
 }
 
 stop_start_service() {
     # restart the service named by $1
     d_message "in ${FUNCNAME[0]}}" 5
     local svc="$1"
-    /etc/init.d/${svc} stop >/dev/null 2>&1
+    "/etc/init.d/${svc}" stop >/dev/null 2>&1
     sleep ${sleepwait}
-    /etc/init.d/${svc} start >/dev/null 2>&1
+    "/etc/init.d/${svc}" start >/dev/null 2>&1
 }
 
 rmpid_restart_service() {
     # restart the service named by $1
     d_message "in ${FUNCNAME[0]}}" 5
     local svc="$1"
-    if [ -e /run/${svc}.pid ] ; then
-        rm /run/${svc}.pid >/dev/null 2>&1
+    if [ -e "/run/${svc}.pid" ] ; then
+        rm "/run/${svc}.pid" >/dev/null 2>&1
         sleep ${sleepwait}
-        /etc/init.d/${svc} restart >/dev/null 2>&1
+        "/etc/init.d/${svc}" restart >/dev/null 2>&1
     fi
 }
 
@@ -194,13 +181,13 @@ get_svc_status() {
     # get status of service named by $1
     local svc="$1"
     # read last word of last line of status info and drop trailing period
-    local result=$(/etc/init.d/${svc} status | tail -n1 | awk '{print $NF}' | sed 's|\.$||' )
+    local result=$("/etc/init.d/${svc}" status | tail -n1 | awk '{print $NF}' | sed 's|\.$||' )
     echo -n ${result}
 }
 
 service_status_color() {
     local status=$( echo "$1" | awk '{print $1}')
-    case $status in
+    case "$status" in
         "started"|"running"      ) echo -en "${BGon}" ;;
         "inactive"|"placeholder" ) echo -en "${BYon}" ;;
         "stopped"|"crashed"      ) echo -en "${BRon}" ;;
@@ -208,7 +195,7 @@ service_status_color() {
 }
 
 display_configuration() {
-    separator ${PN} "(display configuration)"
+    separator "${PN}" "(display configuration)"
     # use script_header_joetoo functions
     longest=$(get_longest ${varlist})
     display_vars $longest ${varlist} || return 1
@@ -216,29 +203,29 @@ display_configuration() {
 }
 
 sanity_check() {
-    separator ${PN} "(sanity check)"
+    separator "${PN}" "(sanity check)"
     # put some code here to catch dumb stuff like cmdline option assignments that should
     # be mutually exclusive
-    [ ! $INTERACTIVE ] && [ $EXAMPLE ] && E_message "(demonstration) INTERACTIVE and EXAMPLE should NOT both be TRUE; quitting" && return 1
+    [ ! "$INTERACTIVE" ] && [ "$EXAMPLE" ] && j_msg -${err} "(demonstration) INTERACTIVE and EXAMPLE should NOT both be TRUE; quitting" && return 1
     return 0
 }
 
 show_all_service_status() {
     # list all service status
     for runlevel in ${runlevels}; do
-        separator ${PN} "rc-status ${runlevel}"
-        rc-status ${runlevel}
+        separator "${PN}" "rc-status ${runlevel}"
+        rc-status "${runlevel}"
     done
 }
 
 #-----[ main script ]----------------------------------------------------
 checkroot
-separator ${PN} $(hostname)
+separator "${PN}" $(hostname)
 
 
 # basic common approach -
 # initialize variables (local function)
-# validate_status_file  (script_header_joetoo_extended)
+# validate status_file  (script_header_joetoo_extended)
 # process_cmdline (script_header_joetoo_extended)
 # local validation, configuration, and variable assignment (local function(s))
 # display_configuration so we can see what's what if insane (script_header_joetoo_extended)
@@ -248,10 +235,10 @@ separator ${PN} $(hostname)
 # initialize variables and set default values
 initialize_variables || die "Failed to initialize_variables"
 
-validate_status_file $cmdseq_statusfile || die "Failed to validate_status_file"
+validate_file "$cmdseq_statusfile" || die "Failed to validate status_file"
 
 # over-ride configuration with commandline input
-separator ${PN} "(process_cmdline)"
+separator "${PN}" "(process_cmdline)"
 process_cmdline $@  || die "Failed to process_cmdline"
 
 display_configuration || die "Failed to display_configuration"
@@ -260,9 +247,9 @@ display_configuration || die "Failed to display_configuration"
 sanity_check || die "Failed sanity_check"
 
 # use script_header_joetoo_extended (bash) functions
-run_array $cmdseq_statusfile '' '' || die "Failed to run_array"
+run_array "$cmdseq_statusfile" '' '' || die "Failed to run_array"
 
-message "${PN} Complete"
+j_msg -${notice} -p "${PN} Complete"
 echo
 
 
