script_header_joetoo-0.4.31.tbz2 - completed consolidation to three messaging/UI/layout primitieves - j_msg, handle_result, right_status, with compatibility wrappers for t28 now-retired legacy functions
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-util/joetoolkit/joetoolkit/dbh-conversion b/dev-util/joetoolkit/joetoolkit/dbh-conversion
--- a/dev-util/joetoolkit/joetoolkit/dbh-conversion
+++ b/dev-util/joetoolkit/joetoolkit/dbh-conversion
@@ -1,5 +1,6 @@
-#!/bin/bash
-source /usr/sbin/script_header_joetoo
+#!/bin/sh
+. /usr/sbin/script_header_joetoo || { printf '%s\n' "error: failed to source /usr/sbin/script_header_joetoo"; exit 1 ; }
+if ! command -v j_msg >/dev/null 2>&1; then printf '%s\n' "error: cannot find command j_msg"; exit 2 ; fi
 
 #-----[ variables ]------------------------------------
 binary_chars="01\."
@@ -9,123 +10,132 @@ allowed_bases="dbh"
 
 filtered_string=""
 
-VERBOSE=$TRUE
-verbosity=0  # change to >= 2 for debug output
-
 #-----[ functions ]------------------------------------
 
 b2d() {
     float_num=$1
-    dec_num=$(echo "scale=10; ibase=2; $float_num" | bc)
-    message "decimal: $dec_num"
+    dec_num=$(printf '%s\n' "scale=10; ibase=2; $float_num" | bc)
+    j_msg "decimal: $dec_num"
 }
 
 d2b() {
     float_num=$1
-    binary_num=$(echo "scale=10; obase=2; $float_num" | bc)
-    message "binary: $binary_num"
+    binary_num=$(printf '%s\n' "scale=10; obase=2; $float_num" | bc)
+    j_msg "binary: $binary_num"
 }
 
 d2h() {
     float_num=$1
-    hex_num=$(echo "scale=10; obase=16; $float_num" | bc)
-    message "hex: $hex_num"
+    hex_num=$(printf '%s\n' "scale=10; obase=16; $float_num" | bc)
+    j_msg "hex: $hex_num"
 }
 
 b2h(){
     float_num=$1
-    hex_num=$(echo "scale=10; obase=16; ibase=2; $float_num" | bc)
-    message "hex: $hex_num"
+    hex_num=$(printf '%s\n' "scale=10; obase=16; ibase=2; $float_num" | bc)
+    j_msg "hex: $hex_num"
 }
 
 h2d(){
     float_num=$1
-    dec_num=$(echo "scale=10; ibase=16; $float_num" | bc)
-    message "decimal: $dec_num"
+    float_num=$(printf '%s' "$float_num" | tr 'a-f' 'A-F')
+    dec_num=$(printf '%s\n' "scale=10; ibase=16; $float_num" | bc)
+    j_msg "decimal: $dec_num"
 }
 
 h2b() {
     float_num=$1
-    binary_num=$(echo "scale=10; obase=2; ibase=16; $float_num" | bc)
-    message "binary: $binary_num"
+    float_num=$(printf '%s' "$float_num" | tr 'a-f' 'A-F')
+    binary_num=$(printf '%s\n' "scale=10; obase=2; ibase=16; $float_num" | bc)
+    j_msg "binary: $binary_num"
 }
 
 usage() {
-    message "Usage:  ${Gon}dbh-conversion <number> [<out_base>]${Boff}"
-    message "  input $1 can be floating point, binary, decimal, or hex"
-    message "  Specify input base with \"<base>#\" convention; examples --"
-    message "    2#101.01 (base 2)"
-    message "    8#77.63 (base 8)"
-    message "    16#FF.2A (base 16)"
-    message "    36#abc.0c (base 36)"
-    message "  out_base $2 can be b|2, d|10, or h|16"
-    exit
-}
-
-filter_string() {
-    input_string="$1" ; allowed_chars="$2"
-    # filter allowed characters from input_string and assign remnants to ${filtered_string}
-    filtered_string=$(echo "$input_string" | sed "s/[$allowed_chars]//g")
+    j_msg "Usage:  ${Gon}dbh-conversion ${Mon}<number> ${Con}[<out_base>]${Boff}"
+    j_msg "  input \$1 can be floating point, binary, decimal, or hex"
+    j_msg "  Specify input base with \"<base>#\" convention; examples --"
+    j_msg "    2#101.01 (base 2)"
+    j_msg "    8#77.63 (base 8)"
+    j_msg "    16#FF.2A (base 16)"
+    j_msg "    36#abc.0c (base 36)"
+    j_msg "  out_base \$2 can be b|2, d|10, or h|16"
+    exit 1
 }
 
 #-----[ main script ]----------------------------------
 
 # one (inputnumber) or two (inputnumber OBASE) allowed
-( [ $# -gt 2 ] || [ $# -eq 0 ] ) && useage
+[ $# -gt 2 ] && usage # guard: no more than 2 args
+[ $# -lt 1 ] && usage # guard: no less than 1 arg
+OBASE="${2:-d}"       # guard: if no $2, default OBASE to decimal
 
 # $2 specifies OBASE; default to decimal
 if [ $# -eq 2 ] ; then
-    case ${2:0:1} in
-        "b"|"2" ) OBASE="b" ;;
-        "d"     ) OBASE="d" ;;
-        "h"     ) OBASE="h" ;;
-        "1"     )
-            if [ "${2:1:1}" == "0" ] ; then OBASE="d" ;
-            elif [ "${2:1:1}" == "6" ] ; then OBASE="h" ;
-            else E_message "invalid out_base: [ $2 ]"; usage
-            fi ;;
-        *       ) E_message "invalid out_base: [ $2 ]"; usage ;;
+    case "$OBASE" in
+        b|d|h) : ;; # already good
+        2    ) OBASE="b" ;;
+        10   ) OBASE="d" ;;
+        16   ) OBASE="h" ;;
+        *       ) j_msg "${err:+-$err}" "Invalid output base"; usabe ;;
     esac
 fi
 
 # sanity check OBASE
-input_string=$OBASE
-filter_string "$input_string" "$allowed_bases"
-[ ! -z "$filtered_string" ] && ( E_message "invalid OBASE: [ $OBASE ]" ; usage )
-d_message "just set OBASE = [ $OBASE ]" 2
+input_string="$OBASE"
+case "$OBASE" in
+  d|b|h) : ;; # do nothing (goog)
+  *    ) j_msg "${err:+-$err}" "invalid OBASE: [ $OBASE ]" ; usage ;;
+esac
+j_msg "${debug:+-$debug}" "OBASE: [ $OBASE ]"
 
 # get input base
-if [[ "$1" == *"#"* ]] ; then
+case "$1" in
+  *"#"* )
     # there is a # - figure out base
-    input_base="$(echo $1 | cut -d'#' -f1)"
+    input_base="${1%#*}" # extract bb from bb#nnnn
     case "$input_base" in
         "2"  ) IBASE="b" ;;
         "10" ) IBASE="d" ;;
         "16" ) IBASE="h" ;;
-        *    ) E_message "invlid input base: [ $input_base ]"; usage ;;
+        *    ) j_msg "${err:+-$err}" "invlid input base: [ $input_base ]"; usage ;;
     esac
-else
+    ;;
+  * )
     # there is no # - assume decimal
     IBASE="d"
-fi
-d_message "just set IBASE = [ $IBASE ]" 2
+    ;;
+esac
+j_msg "${debug:+-$debug}" "IBASE: [ $IBASE ]"
 
 # sanity check input number digits
-input_string="$(echo $1 | cut -d'#' -f2)"
-d_message "just set input_string = [ $input_string ]" 2
+input_string="${1#*#}"   # extract nnnn from bb#nnnn
+j_msg "${debug:+-$debug}" "just set input_string = [ $input_string ]"
 
 case "$IBASE" in
-    "b" ) filter_string "$input_string" "$binary_chars" ;;
-    "d" ) filter_string "$input_string" "$decimal_chars" ;;
-    "h" ) filter_string "$input_string" "$hex_chars" ;;
-    *   ) E_message "invalid IBASE: [ $IBASE ]" ; usage ;;
+    "b" )
+      case "$input_string" in
+        *[!01.]* )
+          j_msg "${err:+-$err}" "non-binary digits in input_string: [ $input_string ]"
+          exit 1
+          ;;
+      esac ;;
+    "d" )
+      case "$input_string" in
+        *[!0-9.]* )
+          j_msg "${err:+-$err}" "non-decimal digits in input_string: [ $input_string ]"
+          exit 1
+          ;;
+      esac ;;
+    "h" )
+      case "$input_string" in
+        *[!0-9a-fA-F.]* )
+          j_msg "${err:+-$err}" "non-hex digits in input_string: [ $input_string ]"
+          exit 1
+          ;;
+      esac ;;
+    *   ) j_msg "${err:+-$err}" "invalid IBASE: [ $IBASE ]" ; usage ;;
 esac
-d_message "result of filte_string(): [ $filtered_string ]" 2
 
-if [ ! -z "$filtered_string" ] ; then
-    E_message "invalid digits in input_string: [ $1 ]. Remnants: [ $filtered_string ]"
-    usage
-else
-   d_message "about to call conversion function wth command ${Gon}eval ${IBASE}2${OBASE} ${input_string}${Boff}" 2
-    eval "${IBASE}2${OBASE}" "${input_string}"
-fi
+j_msg "${debug:+-$debug}" "about to run ${Gon}${IBASE}2${OBASE} ${Con}${input_string}${Boff}"
+func="${IBASE}2${OBASE}"
+"$func" "${input_string}"
diff --git a/dev-util/script_header_joetoo/script_header_joetoo_compat b/dev-util/script_header_joetoo/script_header_joetoo_compat
--- a/dev-util/script_header_joetoo/script_header_joetoo_compat
+++ b/dev-util/script_header_joetoo/script_header_joetoo_compat
@@ -44,6 +44,154 @@ echo_n_long() # deprecated - use smart_wrap_n
 
 # @note =====[ Section 6: Logging, Messaging, & UI ]==================================================================
 
+#-----[ new generation info_msg era created in feb26 now already deprecated in feb26 ]------------------------------------------------------------------
+
+_j_msg_compat_warn()
+{ # help recently retired legacy msg functions transition to j_msg
+  _jcw_legacy="$1"; _jcw_flags="$2"
+#echo "warning: $warning"
+  [ "$DEBUG" ] && j_msg "-$warning" "${BYon}Warning:${Boff} $_jcw_legacy is deprecated; use \"j_msg $_jcw_flags\""
+  unset -v _jcw_legacy _jcw_flags
+}
+# @usage _j_msg_compat_warn <legacy_func_name> <replacement_flags>
+# @args $1: name of the calling function
+# @args $2: the flags that should be used instead (e.g. -6)
+
+emerg_msg() { e_ret=0; _j_msg_compat_warn "emerg_msg" "-0"; j_msg -0 "$@"; e_ret=$?; return $e_ret ; }
+alert_msg() { a_ret=0; _j_msg_compat_warn "alert_msg" "-1"; j_msg -1 "$@"; a_ret=$?; return $a_ret ; }
+crit_msg() { c_ret=0; _j_msg_compat_warn "crit_msg" "-2"; j_msg -2 "$@"; c_ret=$?; return $c_ret ; }
+error_msg() { er_ret=0; _j_msg_compat_warn "error_msg" "-3"; j_msg -3 "$@"; er_ret=$?; return $er_ret ; }
+warn_msg() { w_ret=0; _j_msg_compat_warn "warn_msg" "-4"; j_msg -4 "$@"; w_ret=$?; return $w_ret ; }
+notice_msg() { n_ret=0; _j_msg_compat_warn "notice_msg" "-5"; j_msg -5 "$@"; n_ret=$?; return $n_ret ; }
+info_msg() { i_ret=0; _j_msg_compat_warn "notice_msg" "-6"; j_msg -6 "$@"; i_ret=$?; return $i_ret ; }
+debug_msg() { d_ret=0; _j_msg_compat_warn "debug_msg" "-7"; j_msg -7 "$@"; d_ret=$?; return $d_ret ; }
+echo_e_msg()   { eem_ret=0;  _j_msg_compat_warn "echo_e_msg" "-ue";  j_msg -ue "$@";  eem_ret=$?;  return $eem_ret; }
+echo_e_msg_n() { eemn_ret=0; _j_msg_compat_warn "echo_e_msg_n" "-uen"; j_msg -uen "$@"; eemn_ret=$?; return $eemn_ret; }
+echo_msg()     { em_ret=0;   _j_msg_compat_warn "echo_msg" "-u";    j_msg -u "$@";   em_ret=$?;   return $em_ret; }
+echo_msg_n()   { emn_ret=0;  _j_msg_compat_warn "echo_msg_n" "-un";  j_msg -un "$@";  emn_ret=$?;  return $emn_ret; }
+notice_echo_msg()    { nem_ret=0;  _j_msg_compat_warn "notice_echo_msg" "-5u";  j_msg -5u "$@";  nem_ret=$?;  return $nem_ret; }
+info_echo_msg()      { iem_ret=0;  _j_msg_compat_warn "info_echo_msg" "-6u";  j_msg -6u "$@";  iem_ret=$?;  return $iem_ret; }
+debug_echo_msg()     { dem_ret=0;  _j_msg_compat_warn "debug_echo_msg" "-7u";  j_msg -7u "$@";  dem_ret=$?;  return $dem_ret; }
+info_echo_msg_n()    { iemn_ret=0; _j_msg_compat_warn "info_echo_msg_n" "-6un"; j_msg -6un "$@"; iemn_ret=$?; return $iemn_ret; }
+debug_echo_msg_n()   { demn_ret=0; _j_msg_compat_warn "debug_echo_msg_n" "-7un"; j_msg -7un "$@"; demn_ret=$?; return $demn_ret; }
+info_echo_e_msg_n()  { ieemn_ret=0; _j_msg_compat_warn "info_echo_e_msg_n" "-6uen"; j_msg -6uen "$@"; ieemn_ret=$?; return $ieemn_ret; }
+debug_echo_e_msg_n() { deemn_ret=0; _j_msg_compat_warn "debug_echo_e_msg_n" "-7uen"; j_msg -7uen "$@"; deemn_ret=$?; return $deemn_ret; }
+notice_msg_n() { nmn_ret=0; _j_msg_compat_warn "notice_msg_n" "-5n"; j_msg -5n "$@"; nmn_ret=$?; return $nmn_ret; }
+info_msg_n()   { imn_ret=0; _j_msg_compat_warn "info_msg_n" "-6n"; j_msg -6n "$@"; imn_ret=$?; return $imn_ret ; }
+debug_msg_n()  { dmn_ret=0; _j_msg_compat_warn "debug_msg_n" "-7n"; j_msg -7n "$@"; dmn_ret=$?; return $dmn_ret ; }
+
+info_right_status()  { irs_ret=0; _j_msg_compat_warn "info_right_status" "right_status <status> \$info";
+  right_status "$1" "$info"; irs_ret=$?; return $irs_ret; }
+info_handle_result() { ihr_ret=0; _j_msg_compat_warn "info_handle_result" "handle_result <status> <ok> <err> \$info";
+  handle_result "$1" "$2" "$3" "$info"; ihr_ret=$?; return $ihr_ret; }
+debug_right_status() { drs_ret=0; _j_msg_compat_warn "debug_right_status" "right_status <status> \$debug";
+ right_status "$1" "$debug"; drs_ret=$?; return $drs_ret; }
+debug_handle_result(){ dhr_ret=0; _j_msg_compat_warn "debug_handle_result" "handle_result <status> <ok> <err> \$debug";
+ handle_result "$1" "$2" "$3" "$debug"; dhr_ret=$?; return $dhr_ret; }
+
+# comment-out these two (BASH) tests below, so they don't cause errors in ash, busybox, etc.
+#   They can be un-commented to enable for testing in a bash environment if needed, but must be commented out
+#   otherwise, to prevent errors in sh environments
+#test_rs() {
+#  for x in "5:notice:" "6:info:info" "7:debug:debug" ; do
+#    IFS=':' read -ra prefix <<< "$x";
+#    echo "x: $x  #prefix: ${#prefix[@]}";
+#    verbosity=5 loglevel=5 ${prefix[1]}_msg_n "testing [${prefix[1]}]";
+#    verbosity=5 loglevel=5 ${prefix[2]+${prefix[2]}_}right_status $? ${prefix[0]};
+#  done
+#  for x in "5:notice:" "6:info:info" "7:debug:debug" ; do
+#    IFS=':' read -ra prefix <<< "$x";
+#    echo "x: $x  #prefix: ${#prefix[@]}";
+#    verbosity=${prefix[0]} loglevel=${prefix[0]} ${prefix[1]}_msg_n "testing [${prefix[1]}]";
+#    verbosity=${prefix[0]} loglevel=${prefix[0]} ${prefix[2]+${prefix[2]}_}right_status $? ${prefix[0]};
+#  done
+#}
+#
+#test_rs_hr() {
+#  for x in "5:notice:" "6:info:info" "7:debug:debug" ; do
+#    IFS=':' read -ra prefix <<< "$x";
+#    echo "x: $x  #prefix: ${#prefix[@]}";
+#    verbosity=5 loglevel=5 ${prefix[1]}_msg_n "testing [${prefix[1]}]";
+#    verbosity=5 loglevel=5 ${prefix[2]+${prefix[2]}_}handle_result $? "" "" ${prefix[0]};
+#  done
+#  for x in "5:notice:" "6:info:info" "7:debug:debug" ; do
+#    IFS=':' read -ra prefix <<< "$x";
+#    echo "x: $x  #prefix: ${#prefix[@]}";
+#    verbosity=${prefix[0]} loglevel=${prefix[0]} ${prefix[1]}_msg_n "testing [${prefix[1]}]";
+#    verbosity=${prefix[0]} loglevel=${prefix[0]} ${prefix[2]+${prefix[2]}_}handle_result $? "" "" ${prefix[0]};
+#  done
+#}
+
+#-----[ previous generation deprecated messaging functions ]------------------------------------------------
+
+legacy_wrapper_dispatch()
+{ lwd_ret=0
+  [ $# -lt 3 ] && die "insufficient args. legacy_wrapper_dispatch requires legacy_func target_func + args"
+  _lwd_legacy_func=$1; _lwd_target_func=$2
+  _lwd_SEVERITY="$FALSE"; _lwd_LOGGING="$FALSE"
+  shift 2 # remove the legacy and new function names from the argument list
+
+  # formulate an appropriate deprecation warning based on name of legcy function
+  case "$_lwd_legacy_func" in log_*|*_log_*) _lwd_LOGGING="$TRUE" ;; esac
+  case "$_lwd_legacy_func" in d_*|de_*|dE_*) _lwd_SEVERITY="$TRUE" ;; esac
+  if [ "$_lwd_LOGGING" ]; then
+    _lwd_dep_msg="$_lwd_legacy_func is deprecated; use \"LOGGING=\$TRUE $_lwd_target_func\"."
+  else
+    _lwd_dep_msg="$_lwd_legacy_func is deprecated; use \"$_lwd_target_func\"."
+  fi
+  if [ "$_lwd_SEVERITY" ]; then
+    _lwd_dep_msg="${_lwd_dep_msg} (stripping severity arg if integer)"
+  fi
+  [ "$DEBUG" ] && j_msg -4 "${BYon}Warning:${Boff} $_lwd_dep_msg"
+  # consider legacy *E* messages to be used in error, inconsistent with severity model
+  # so issue a second (error) message
+  case "$_lwd_legacy_func" in
+    *E*)
+      _lwd_err_msg="$_lwd_legacy_func is obsolete and inconsistent"
+      _lwd_err_msg="${_lwd_err_msg} with the severity model; use $_lwd_target_func instead"
+      j_msg -3 "${BRon}Deprecated:${Boff} $_lwd_err_msg" ;;
+  esac
+  # if severity is "claimed" check if last arg is integer before bothering to rotate
+  _lwd_last_arg=""
+  for _lwd_last_arg; do : ; done
+  if ! isint "$_lwd_last_arg"; then _lwd_SEVERITY="$FALSE"; fi
+  # iterate over all args but not w while $# -gt 0 b/c rotation "puts them back"
+  _lwd_n=$#
+   # guard: only want to strip for d_ w a severity arg
+   #   but if there is only one integer arg, I am going to assume it is NOT severity
+   #   (therefor the quantitative guard is -gt 1 rather than -gt 0)
+  if [ "$_lwd_SEVERITY" ] && [ "$_lwd_n" -gt 1 ]; then
+    _lwd_i=1    # now rotate (move first (n-1) args to the end of $@ args
+    while [ "$_lwd_i" -lt "$_lwd_n" ]; do
+      set -- "$@" "$1"
+      shift
+      _lwd_i=$(( _lwd_i + 1 ))
+    done
+    shift # discard what was originally the last argument (the severity level)
+  fi
+  # hand-off from legacy to new target function
+  if [ "$_lwd_LOGGING" ]; then
+    LOGGING=$TRUE "$_lwd_target_func" "$@"  # hand off from legacy to inheriting function
+  else
+    "$_lwd_target_func" "$@"
+  fi
+  lwd_ret=$?
+  unset -v _lwd_legacy_func _lwd_target_func _lwd_SEVERITY _lwd_LOGGING
+  unset -v _lwd_n _lwd_i _lwd_last_arg
+  return $lwd_ret
+}
+# @note routes legacy calls, handles logging state, and strips severity args
+# @usage legacy_wrapper_dispatch <legacy_func> <target_func> [args ...]
+# @args $1: Name of the calling legacy function (for pattern matching)
+# @args $2: Name of the new function to be executed
+# @args $@: Positional parameters to be processed and passed
+# @vars _lwd_legacy_func, _lwd_target_func, _lwd_SEVERITY, _lwd_LOGGING
+# @ret exit status of the executed <target_func>
+# @rule mode is inferred from legacy_name prefix (d_, *_log_*, *E*)
+# @rule uses parameter rotation to avoid eval/subshell limits (POSIX safe)
+# @ex legacy_wrapper_dispatch "d_message" "info_msg" "Hello" "critical"
+# @cont results in: info_msg "Hello"
+
 log_separator() # (deprecated; use LOGGING="$TRUE" separator() instead)
 { legacy_wrapper_dispatch log_separator separator "$@" ; }
 
