joetoolkit-0.8.0.tbz2 - total re-write/re-factor/update prior to consolidation with script_header_joetoo
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-util/joetoolkit/joetoolkit/ebup b/dev-util/joetoolkit/joetoolkit/ebup
--- a/dev-util/joetoolkit/joetoolkit/ebup
+++ b/dev-util/joetoolkit/joetoolkit/ebup
@@ -2,73 +2,69 @@
 # ebup - (c) joe brendler 2025-2055
 # create an ebuild with version-upgraded filename
 #
+
 source /usr/sbin/script_header_joetoo
-source /usr/sbin/script_header_joetoo_unicode
 
-VERBOSE=$TRUE
-[ -z $verbosity ] && verbosity=3  # assign default if null; allow calling program to dictate
+PN=${0##*/}   #  like =$(basename $0) but w/o subshell and function call
 
-PN=$(basename $0)
+if [ -f /etc/joetoolkit/BUILD ]; then . /etc/joetoolkit/BUILD; else BUILD="0.0.1"; fi
 
-separator ${PN} $(hostname)
+[ -z $verbosity ] && verbosity=${notice}  # assign default if null; allow calling program to dictate
 
 user="joe"
 archived_ebuilds_dir="/home/${user}/archived_ebuilds"
 
-# temporary, until I add this to script_header
-VS16="\UFE0F"
-
 #-----[ variables ]--------------------------------------------------
 
-to_be_archived_ebuild_version=""  # oldest (to-be-archived) version string (to be determined)
-latest_ebuild_version=""          # latest version string (to be determined)
-new_ebuild_version=""             # new version string (to be calculated)
-output_ebuild_filename=""         # filename for the new version's ebuild
+to_be_archived_ebuild_version=""   # oldest (to-be-archived) version string (to be determined)
+latest_ebuild_version=""           # latest version string (to be determined)
+new_ebuild_version=""              # new version string (to be calculated)
+output_ebuild_filename=""          # filename for the new version's ebuild
 
-declare -a ebuild_versions        # array of version strings
+declare -a ebuild_versions         # indexed array of version strings
 
 current_version_numbers=( 0 0 0 )  # array of digits constituting the parts (major minor patch) of current version number
 new_version_numbers=()             # array to hold new version's digits, when calculated
 
 old_dir=$(pwd)
- 
+
 #-----[ functions ]--------------------------------------------------
 usage() {
-    E_message "${BRon}usage: ${BGon}${PN} <SOURCE_DIR> [-major|-minor]${Boff}"
-    message "${BYon}Notes:${Boff}"
-    message "${LBon}(1)${Boff} ${BMon}SOURCE_DIR${Boff} must be a directory (containing a package's ebuilds)"
-    message "${LBon}(2)${Boff} only one of the semantic versioning format numbers will be incremented"
-    message "    automatically (major.minor.patch)"
-    message "${LBon}(3)${BWon} upgrade type [-pa|ma|mi] is optional${Boff}"
-    message "  -pa[tch] optionally indicates a patch upgrade (${BWon}default${Boff})"
-    message "  -ma[jor] optionally indicates a major upgrade"
-    message "  -mi[nor] optionally indicates a minor upgrade"
+    j_msg -${err} -p "${BRon}usage: ${BGon}${PN} <SOURCE_DIR> [-major|-minor]${Boff}"
+    j_msg -${notice} -p "${BYon}Notes:${Boff}"
+    j_msg -${notice} -m "${BCon}(1)${Boff} ${BMon}SOURCE_DIR${Boff} must be a directory (containing a package's ebuilds)"
+    j_msg -${notice} -m "${BCon}(2)${Boff} only one of the semantic versioning format numbers will be incremented"
+    j_msg -${notice} -m "    automatically (major.minor.patch)"
+    j_msg -${notice} -p "${BCon}(3)${BWon} upgrade type [-pa|ma|mi] is optional${Boff}"
+    j_msg -${notice} -m "  -pa[tch] optionally indicates a patch upgrade (${BWon}default${Boff})"
+    j_msg -${notice} -m "  -ma[jor] optionally indicates a major upgrade"
+    j_msg -${notice} -m "  -mi[nor] optionally indicates a minor upgrade"
     exit 1
 }
 
 load-ebuild_versions() {
     # check SOURCE_DIR
     if [[ "$SOURCE_DIR" == "." ]] ; then
-        message_n "updating SOURCE_DIR [$SOURCE_DIR]"
-        SOURCE_DIR=$(basename $(pwd)) || die "failed to set SOURCE_DIR to pwd"
-        echo -e -n " (${BGon}${SOURCE_DIR}${Boff})"
-        right_status $TRUE
+        j_msg -${notice} -p -n "updating SOURCE_DIR [$SOURCE_DIR]"
+        SOURCE_DIR=$(pwd) || die "failed to set SOURCE_DIR to pwd"
+        j_msg -${notice} -mp -n " (${BGon}${SOURCE_DIR##*/}${Boff})"   # display only basename for brevity
+        right_status $TRUE ${notice}
     elif [[ "$SOURCE_DIR" == ".." ]] ; then
-        message_n "moving to .."
+        j_msg -${notice} -p -n "moving to .."
         cd .. || die "failed to move to .."
-        right_status $TRUE
-        message_n "updating SOURCE_DIR [$SOURCE_DIR]"
-        SOURCE_DIR=$(basename $(pwd)) || die "failed to set SOURCE_DIR to pwd"
-        echo -e -n " (${BGon}${SOURCE_DIR}${Boff})"
-        right_status $TRUE
+        right_status $TRUE ${notice}
+        j_msg -${notice} -p -n "updating SOURCE_DIR [$SOURCE_DIR]"
+        SOURCE_DIR=$(pwd) || die "failed to set SOURCE_DIR to pwd"
+        j_msg -${notice} -mp -n " (${BGon}${SOURCE_DIR##*/}${Boff})"   # display only basename for brevity
+        right_status $TRUE ${notice}
     elif [[ "$SOURCE_DIR" == *"/"* ]] ; then
-        message_n "moving to .."
-        cd .. || die "failed to move to .."
-        right_status $TRUE
-        message_n "updating SOURCE_DIR [$SOURCE_DIR]"
-        SOURCE_DIR=$(basename $(pwd)) || die "failed to set SOURCE_DIR to pwd"
-        echo -e -n " (${BGon}${SOURCE_DIR}${Boff})"
-        right_status $TRUE
+        j_msg -${notice} -p -n "moving to .."
+        cd "$SOURCE_DIR" || die "failed to move to [$SOURCE_DIR]"
+        right_status $TRUE ${notice}
+        j_msg -${notice} -p -n "updating SOURCE_DIR [$SOURCE_DIR]"
+        SOURCE_DIR=$(pwd) || die "failed to set SOURCE_DIR to pwd"
+        j_msg -${notice} -mp -n " (${BGon}${SOURCE_DIR##*/}${Boff})"   # display only basename for brevity
+        right_status $TRUE ${notice}
     else
         [ ! -d $SOURCE_DIR ] && die "SOURCE_DIR [$SOURCE_DIR] does not exist"
     fi
@@ -80,62 +76,73 @@ load-ebuild_versions() {
     # subsititutions strip the package name and .ebuild extension to leave just the version number
     # sort -rV puts them in reverse version order , -z tells sort to use the \0 delimiter
     readarray -d $'\0' ebuild_versions < <(
-        find ./ -name "${SOURCE_DIR}*.ebuild" -printf '%f\0' |
-        sed -z "s|${SOURCE_DIR}-||g" |
-        sed -z "s|.ebuild$||g" |
+        find ./ -maxdepth 1 -name "${SOURCE_DIR}*.ebuild" -printf '%f\0' |
+        sed -z "s|^${SOURCE_DIR}-|| ; s|.ebuild$||" |
         sort -rVz
     )
     result=$?
-    d_message "#: [$#ebuild_versions[@]}] ebuild_versions: [${ebuild_versions[*]}]" 5
+    j_msg -${debug} -p "#: [$#ebuild_versions[@]}] ebuild_versions: [${ebuild_versions[*]}]"
+
+    # return to old_dir
+    j_msg -${notice} -p -n "moving back to old_dir [$old_dir]"
+    cd "$old_dir" || die "failed to cd to old_dir"
+    right_status $TRUE ${notice}
+
     return $result
 }
 
 get-current-version() {
-    d_message "in ${FUNCNAME[0]}" 5
+    j_msg -${debug} -p "in ${FUNCNAME[0]}"
     # put the latest version number string into latest_ebuild_version variable
     local result=""
-    d_message "ebuild_versions #: ${#ebuild_versions[@]}" 2
-    # identify the latest version
+    j_msg -${debug} -p "ebuild_versions #: ${#ebuild_versions[@]}"
+    # identify the latest version (sort -r puts it at array index 0)
     if [ ${#ebuild_versions[@]} -eq 0 ] ; then
         # there are no ebuilds matching SOURCE_DIR,
         # so current ebuild version = 0.0.0 [i.e. none]
-        message "no ebuilds matching SOURCE_DIR [${SOURCE_DIR}] found"
-        message " so current ebuild version = 0.0.0 [i.e. none]"
+        j_msg -${notice} -p "no ebuilds matching SOURCE_DIR [${SOURCE_DIR}] found"
+        j_msg -${notice} -m " so current ebuild version = 0.0.0 [i.e. none]"
     else
         latest_ebuild_version="${ebuild_versions[0]}"
-        d_message "latest_ebuild_version: [$latest_ebuild_version]" 5
+        j_msg -${debug} -p "latest_ebuild_version: [$latest_ebuild_version]"
         # ignore any revision number that may be part of the current version number
         # final substitution sed -z 's|-r.*$|| removes such a trailing revision number
-        latest_ebuild_version=$(echo $latest_ebuild_version | sed -z 's|-r.*$||' )
-        message "current version: [${latest_ebuild_version}]"
+        # (ok here, b/c the new version just bumps patch, minor, or major // never rev)
+        latest_ebuild_version=$(printf '%s\n' "$latest_ebuild_version" | sed -z 's|-r.*$||' )
+        j_msg -${notice} -p "current version: [${latest_ebuild_version}]"
         # split version into ( major minor patch )
-        IFS='.' read -ra current_version_numbers <<< $latest_ebuild_version
+        IFS='.' read -ra current_version_numbers <<< "$latest_ebuild_version"
         result=$?
-        # Reset IFS to its default value
-        IFS=$' \t\n'
+         # bash/ksh/zsh non-portable idiom: $'...'
+         #(ANSI-C Quoting): tells shel to interpret backslash-escaped chars as literal control chars
+#        IFS=$' \t\n'
+        # Reset IFS to its default value (portable version)
+        IFS=$(printf ' \t\n')
     fi
-    message "  current major: ${current_version_numbers[0]}"
-    message "  current minor: ${current_version_numbers[1]}"
-    message "  current patch: ${current_version_numbers[2]}"
+    j_msg -${notice} -m "  current major: ${current_version_numbers[0]}"
+    j_msg -${notice} -m "  current minor: ${current_version_numbers[1]}"
+    j_msg -${notice} -m "  current patch: ${current_version_numbers[2]}"
     return $result
 }
 
 get-archive-version() {
+    local _gav_count="${#ebuild_versions[@]}"
+    local _gav_idx=$(( _gav_count - 1 ))  # index of the oldest version
     # put the oldest (to-be-archived) version number string into to_be_archived_ebuild_version variable
-    d_message "ebuild_versions #: ${#ebuild_versions[@]}" 2
+    j_msg -${debug} -p "ebuild_versions #: ${#ebuild_versions[@]}"
     # identify the latest version
-    if [ ${#ebuild_versions[@]} -le 1 ] ; then
+    if [ "${#ebuild_versions[@]}" -le 1 ] ; then
         # if there are no ebuilds matching SOURCE_DIR, or
         # if there is only 1, then there is nothing to archive
-        case ${#ebuild_versions[@]} in
-            0 ) message "no ebuilds matching SOURCE_DIR [${SOURCE_DIR}] found" ;;
-            1 ) message "not archiving the only ebuild present" ;;
-            * ) E_message "Error: this cannot happen"; return 1 ;;
+        case "${#ebuild_versions[@]}" in
+            0 ) j_msg -${notice} -m "no ebuilds matching SOURCE_DIR [${SOURCE_DIR}] found" ;;
+            1 ) j_msg -${notice} -m "not archiving the only ebuild present" ;;
+            * ) j_msg -${err} -p "Error: this cannot happen"; return 1 ;;
         esac
         to_be_archived_ebuild_version="none"
     else
-        to_be_archived_ebuild_version="${ebuild_versions[ -1 ]}" || die "failed to assign to_be_archived_ebuild_version="
-        message "archive version: [${to_be_archived_ebuild_version}]"
+        to_be_archived_ebuild_version="${ebuild_versions[_gav_idx]}" || die "failed to assign to_be_archived_ebuild_version="
+        j_msg -${notice} -m "archive version: [${to_be_archived_ebuild_version}]"
     fi
     return 0
 }
@@ -144,7 +151,7 @@ calculate-new-version() {
     # increment the version number appropriately
     local result=""
     local UPGR="$1"
-    case ${UPGR} in
+    case "${UPGR}" in
         "major" )
             # increment major number and reset minor patch number to 0
             new_version_numbers[0]="$(( ${current_version_numbers[0]} + 1 ))"
@@ -163,37 +170,45 @@ calculate-new-version() {
             new_version_numbers[1]="${current_version_numbers[1]}"
             new_version_numbers[2]="$(( ${current_version_numbers[2]} + 1 ))"
             ;;
-        * )  E_message "invalid UPGRADE type [${UPGR}]" && exit ;;
+        * )  j_msg -${err} -p "invalid UPGRADE type [${UPGR}]" && exit ;;
     esac
-    message "  new major: ${new_version_numbers[0]}"
-    message "  new minor: ${new_version_numbers[1]}"
-    message "  new patch: ${new_version_numbers[2]}"
+    j_msg -${notice} -p "  new major: ${new_version_numbers[0]}"
+    j_msg -${notice} -p "  new minor: ${new_version_numbers[1]}"
+    j_msg -${notice} -p "  new patch: ${new_version_numbers[2]}"
     new_ebuild_version="${new_version_numbers[0]}.${new_version_numbers[1]}.${new_version_numbers[2]}"
     result=$?
-    message "new version: ${new_ebuild_version}"
+    j_msg -${notice} -p "new version: ${new_ebuild_version}"
     return $result
 }
 
 archive-old-version() {
     # move the oldest version to the archived_ebuilds_dir
+    local msg=""
     archive_ebuild_filename="${SOURCE_DIR}-${to_be_archived_ebuild_version}.ebuild"
+
+    # ensure the archive directory exists before attempting mv
+    [ -d "${archived_ebuilds_dir}" ] || mkdir -p "${archived_ebuilds_dir}" || die "failed to create archive directory"
+
     if [[ "${to_be_archived_ebuild_version}" == "none" ]] ; then
-        d_message "no ebuild to archive" 3
+        j_msg -${debug} -p "no ebuild to archive"
     elif [ -f "${archive_ebuild_filename}" ] ; then
         response=""
         msg="${BYon}About to run command:\n${Boff}"
-        msg+="    ${BGon}mv  ${archive_ebuild_filename} ${archived_ebuilds_dir%/}/${Boff}\n"
-        msg+="    ${BYon}Please confirm ( ${BWon}y|Y[es]: yes; s|S[kip]: skip; n|N[o]: No (abort program)${Boff} )"
-        new_prompt "${msg}"
-        case ${response:0:1} in
-            [yY] )
-                 mv "${archive_ebuild_filename}" "${archived_ebuilds_dir%/}/" || die "failed to archive old ebuild" ;;
-            [sS] ) message "${BMon}Skipping archive as instructed${Boff}" ;;
-            [nN] ) E_message "Aborting as instructed" ; return 1;;
-            *    ) E_message "Invalid response [$response]" ; return 1;;
+        msg+="    ${BGon}mv  ${archive_ebuild_filename} "
+        msg+="${archived_ebuilds_dir%/}/${Boff}"
+        j_msg -${notice} -p "$msg"
+        msg="${BYon}Please confirm ( ${BWon}y|Y[es]; "
+        msg+=" s|S[kip]; n|N[o] (abort) ${BYon})${Boff}"
+        yns_prompt "${msg}"
+        case "$response" in
+            [yY]*) mv "${archive_ebuild_filename}" "${archived_ebuilds_dir%/}/" || \
+                     die "failed to archive old ebuild" ;;
+            [sS]*) j_msg -${notice} -p "${BMon}Skipping archive as instructed${Boff}" ;;
+            [nN]*) j_msg -${err} -p "Aborting as instructed" ; return 1;;
+            *) j_msg -${err} -p "Invalid response [$response]" ; return 1;;
         esac
     else
-        E_message "Error: ebuild [${archive_ebuild_filename}] not found"
+        j_msg -${err} -p "Error: ebuild [${archive_ebuild_filename}] not found"
         return 1
     fi
     return 0
@@ -202,9 +217,9 @@ archive-old-version() {
 create-new-ebuild() {
     current_ebuild_filename="${SOURCE_DIR}-${latest_ebuild_version}.ebuild"
     output_ebuild_filename="${SOURCE_DIR}-${new_ebuild_version}.ebuild"
-    msg="${BYon}About to run command:\n${Boff}"
+    local msg="${BYon}About to run command:\n${Boff}"
     msg+="    ${BGon}cp ${current_ebuild_filename} ${output_ebuild_filename}${Boff}"
-    message "${msg}"
+    j_msg -${notice} -p "${msg}"
     confirm_continue_or_exit
     cp "${current_ebuild_filename}" "${output_ebuild_filename}"
     return $?
@@ -212,58 +227,60 @@ create-new-ebuild() {
 
 edit-new-ebuild() {
     response=""
-    new_prompt "${BYon}Ready to edit new ebuild [${BMon}${output_ebuild_filename}${BYon}]?${Boff}"
+    local msg="${BYon}Ready to edit new ebuild "
+    msg+="[${BMon}${output_ebuild_filename}${BYon}]?${Boff}"
+    yns_prompt "$msg"
     case ${response:0:1} in
-        [yY] )
-            nano "${output_ebuild_filename}" ; result=$? ;;
-        [sS] ) message "${BMon}Skipping edit as instructed${Boff}" ; result=0 ;;
-        [nN] ) E_message "Aborting as instructed" ; return 1;;
-        *    ) E_message "Invalid response [$response]" ; return 1;;
+        [yY] ) nano "${output_ebuild_filename}" ; result=$? ;;
+        [sS] ) j_msg -${notice} -p "${BMon}Skipping edit as instructed${Boff}" ; result=0 ;;
+        [nN] ) j_msg -${err} -p "Aborting as instructed" ; return 1;;
+        *    ) j_msg -${err} -p "Invalid response [$response]" ; return 1;;
     esac
     return $result
 }
 
 pkgdev_manifest_new-ebuild() {
     response=""
-    new_prompt "${BYon}Ready to run pkgdev manifest -f for the new ebuild [${BMon}${output_ebuild_filename}${BYon}]?${Boff}"
-    case ${response:0:1} in
-        [yY] )
-            pkgdev manifest -f "${output_ebuild_filename}" ; result=$? ;;
-        [sS] ) message "${BMon}Skipping edit as instructed${Boff}" ; result=0 ;;
-        [nN] ) E_message "Aborting as instructed" ; return 1;;
-        *    ) E_message "Invalid response [$response]" ; return 1;;
+    local msg="${BYon}Ready to run pkgdev manifest -f for the new ebuild "
+    msg+="[${BMon}${output_ebuild_filename}${BYon}]?${Boff}"
+    yns_prompt "$msg"
+    case "$response" in
+        [yY]*) pkgdev manifest -f "${output_ebuild_filename}" ; result=$? ;;
+        [sS]*) j_msg -${notice} -p "${BMon}Skipping edit as instructed${Boff}" ; result=0 ;;
+        [nN]*) j_msg -${err} -p "Aborting as instructed" ; return 1;;
+        *) j_msg -${err} -p "Invalid response [$response]" ; return 1;;
     esac
     return $result
 }
 
 debug_marker() {
-    bremoji "${heart_red}${VS16}" ; echo -n " "
-    echo -e -n "${Ron}D${BRon}e${Yon}b${BYon}u${Gon}g${BGon}_${LBon}M${Bon}a${BBon}r${Mon}k${BMon}e${Won}r${BWon}!${Boff}"
-    echo -n " " ; bremoji $explosion; echo
-    exit 1
+    # note: close double-quotes, single-quote the !, then re-open double quotes, else bash interprets ! as history expansion
+    j_msg -${notice} -M $idx_heart_red -p "${Ron}D${BRon}e${Yon}b${BYon}u${Gon}g${BGon}_${BCon}M${Bon}a${BBon}r${Mon}k${BMon}e${Won}r${BWon}"'!'"${Boff} ${bin_explosion}"
+    leave
 }
 
 #-----[ main script ]------------------------------------------------
 checknotroot
 
-[ $# -eq 0 ] && E_message "SOURCE_DIR not specified" && usage
-[ $# -gt 2 ] && E_message "invalid arguments" && usage
-[ ! -d "$1" ] && E_message "SOURCE_DIR: [$1] does not exist" && usage || SOURCE_DIR="$1"
+[ $# -eq 0 ] && { j_msg -${err} -p "SOURCE_DIR not specified" ; usage ; }
+[ $# -gt 2 ] && { j_msg -${err} -p "invalid arguments" ; usage ; }
+if [ ! -d "$1" ]; then j_msg -${err} -p "SOURCE_DIR: [$1] does not exist" ; usage; else SOURCE_DIR="$1"; fi
 
 
 if [ $# -eq 2 ] ; then
-    [[ "${2:0:1}" != "-" ]] && E_message "prefix option with \"-|\"" && usage
-    case ${2:1:2} in
-        "ma" ) UPGRADE="major"; message "initiating major upgrade ..." ;;
-        "mi" ) UPGRADE="minor"; message "initiating minor upgrade ..." ;;
-        "pa" ) UPGRADE="patch"; message "initiating patch upgrade ..." ;;
-        *    ) E_message "invalid option: [$2]"; usage ;;
+    [[ "${2:0:1}" != "-" ]] && j_msg -${err} -p "prefix option with \"-|\"" && usage
+    case "$2" in
+        "ma"*) UPGRADE="major" ;;
+        "mi"*) UPGRADE="minor" ;;
+        "pa"*) UPGRADE="patch" ;;
+        *) j_msg -${err} -p "invalid option: [$2]"; usage ;;
     esac
+    j_msg -${notice} -p "initiating ${UPGRADE=} upgrade ..."
 else
-    UPGRADE="patch"; message "initiating patch upgrade (as default) ..."
+    UPGRADE="patch"; j_msg -${notice} -p "initiating patch upgrade (as default) ..."
 fi
 
-separator $(hostname) ${PN}
+separator "$(hostname)" "${PN}-${BUILD}"
 
 load-ebuild_versions || die "failed to load-ebuild_versions"
 get-current-version || die "failed to get-current-version"
@@ -279,10 +296,10 @@ edit-new-ebuild || die "failed to edit-new-ebuild"
 
 pkgdev_manifest_new-ebuild || die "failed to pkgdev_manifest_new-ebuild"
 
-message_n "moving back to old_dir [$old_dir]"
+j_msg -${notice} -p -n "moving back to old_dir [$old_dir]"
 cd "$old_dir" || die "failed to cd to old_dir"
-right_status $TRUE
+right_status $TRUE ${notice}
 
-message "${BGon}Done${Boff}"
+j_msg -${notice} -p "${BGon}Done${Boff}"
 
 #debug_marker
diff --git a/dev-util/joetoolkit/joetoolkit/kernel-clean b/dev-util/joetoolkit/joetoolkit/kernel-clean
--- a/dev-util/joetoolkit/joetoolkit/kernel-clean
+++ b/dev-util/joetoolkit/joetoolkit/kernel-clean
@@ -3,71 +3,67 @@
 #
 # joe brendler, 2 Aug 2014
 #
-#BUILD=
-# if no argument provided, list installed kernel versions
-# otherwise delete the residue of kernel version specified in arg
-#
-# include basic re-used functions checkroot(), message(), E_message(),
-# and separator()
 source /usr/sbin/script_header_joetoo
+
+PN=${0##*/}   # basename
+
+if [ -f /etc/joetoolkit/BUILD ]; then . /etc/joetoolkit/BUILD; else BUILD=0.0.1; fi
 
 get_yn_reply()
 {
   unset reply
-  while [[ ! "$reply" == "y" ]] && [[ ! "$reply" == "n" ]]
-  do
-    echo -n "delete $1 residual for of kernel "$2" [y/n]? " && read reply
-  done
-  [ "$reply" = "y" ] && return 0 || return 1
+  yn_prompt  "delete $1 residual for of kernel "$2" [y/n]? "
+  case "$answer" in
+    [yY]*) return 0 ;;
+    [nN]*) return 1 ;;
+    *) die "invalid answer from yn_prompt" ;;
+  esac
+  return 0
 }
 
 clean_residue()
 {
-  message "sources found:"
+  j_msg -${notice} -p "sources found:"
   ls -al /usr/src/linux-*$1*
-  if get_yn_reply "sources" $1
-  then
-    message "deleting sources residual for kernel $1"
+  if get_yn_reply "sources" $1; then
+    j_msg -${notice} -p "deleting sources residual for kernel $1"
     rm -rfv /usr/src/linux-*$1*
   else
-    message "Aborting at user direction"
-    exit
+    j_msg -${notice} -p "Aborting at user direction"
+    exit 1
   fi
 
-  message "modules found:"
+  j_msg -${notice} -p "modules found:"
   ls -al /lib/modules/*$1*
-  if get_yn_reply "modules" $1
-  then
-    message "deleting modules residual for kernel $1"
+  if get_yn_reply "modules" $1; then
+    j_msg -${notice} -p "deleting modules residual for kernel $1"
     rm -rfv /lib/modules/*$1*
   else
-    message "Aborting at user direction"
-    exit
+    j_msg -${notice} -p "Aborting at user direction"
+    exit 1
   fi
 
-  message "boot images found:"
+  j_msg -${notice} -p "boot images found:"
   ls -al /boot/*$1*
-  if get_yn_reply "images" $1
-  then
-    message "deleting images residual for kernel $1"
+  if get_yn_reply "images" $1; then
+    j_msg -${notice} -p "deleting images residual for kernel $1"
     rm -rfv /boot/*$1*
   else
-    message "Aborting at user direction"
-    exit
+    j_msg -${notice} -p "Aborting at user direction"
+    exit 1
   fi
-
 }
 
 #---[ main script ]---------------------------
-separator "kernel-clean-${BUILD}"
+separator "$(hostname)" "${PN}-${BUILD}"
 
 if [[ -z "$1" ]]
 then
-  message "listing kernel versions found..."
-  message "sources:" && ls -al /usr/src/
-  message "modules:" && ls -al /lib/modules/
-  message "images:"  && ls -al /boot/
+  j_msg -${notice} -p "listing kernel versions found..."
+  j_msg -${notice} -p "sources:" && ls -al /usr/src/
+  j_msg -${notice} -p "modules:" && ls -al /lib/modules/
+  j_msg -${notice} -p "images:"  && ls -al /boot/
 else
-  message "cleaning residue of kernels identified by filter [$1]"
-  clean_residue $1
+  j_msg -${notice} -p "cleaning residue of kernels identified by filter [$1]"
+  clean_residue "$1"
 fi
diff --git a/dev-util/joetoolkit/joetoolkit/nextcloud_allow_local_remote_servers b/dev-util/joetoolkit/joetoolkit/nextcloud_allow_local_remote_servers
--- a/dev-util/joetoolkit/joetoolkit/nextcloud_allow_local_remote_servers
+++ b/dev-util/joetoolkit/joetoolkit/nextcloud_allow_local_remote_servers
@@ -18,16 +18,18 @@ checkroot
 
 #-----[ variables ]-----------------------------------------------------
 
-PN=$(basename $0)
+PN=${0##*/}
+
+if [ -f /etc/joetoolkit/BUILD ]; then . /etc/joetoolkit/BUILD; else BUILD="0.0.1"; fi
+
 nextcloud_dir="/var/www/localhost/htdocs/myCloud"
 silent=">/dev/null 2>&1"
 
-VERBOSE=$TRUE
 # don't set verbosity unless it is not already set (allow calling program to set it)
-[ -z $verbosity ] && verbosity=3
+[ -z $verbosity ] && verbosity=${notice}
 
 
-separator $(hostname) ${PN}
+separator "$(hostname)" "${PN}-${BUILD}"
 command_sequence=(
     "sudo -u apache php occ config:system:set allow_local_remote_servers --value true --type bool ${silent}"
 )
@@ -39,19 +41,22 @@ msg_sequence=(
 #-----[ main script ]--------------------------------------------------
 
 old_dir=$(pwd)
-message_n "${BYon}Moving to ${BMon}${nextcloud_dir}${Boff}"
-cd ${nextcloud_dir} || die "failed to move to ${nextcloud_dir}"
-right_status $TRUE
-d_message "${BWon}pwd: ${LBon}$(pwd)${Boff}" 3
+j_msg -${notice} -p -n "${BYon}Moving to ${BMon}${nextcloud_dir}${Boff}"
+cd "${nextcloud_dir}" || die "failed to move to ${nextcloud_dir}"
+right_status $TRUE ${notice}
+j_msg -${info} -m "${BWon}pwd: ${LBon}$(pwd)${Boff}"
 
+# mini run_sequence
 for ((i=0; i< ${#command_sequence[@]}; i++)) ; do
-    message_n "${BWon}running ${BGon}${msg_sequence[$i]}${Boff} ..."
+    j_msg -${notice} -p -n "${BWon}running ${BGon}${msg_sequence[$i]}${Boff} ..."
     eval "${command_sequence[$i]}" || die "failed: ${command_sequence[$i]}"
-    right_status $TRUE
+    right_status $TRUE ${notice}
 done
-echo
-message_n "${BYon}Moving back to ${BMon}${old_dir}${Boff}"
+j_msg -${notice} -mp "" # newline
+
+j_msg -${notice} -p -n "${BYon}Moving back to ${BMon}${old_dir}${Boff}"
 cd ${nextcloud_dir} || die "failed to move to ${nextcloud_dir}"
-right_status $TRUE
-d_message "${BWon}pwd: ${LBon}$(pwd)${Boff}" 3
-message "${BGon}Done${Boff}"
+right_status $TRUE ${notice}
+j_msg -${info} -m "${BWon}pwd: ${LBon}$(pwd)${Boff}"
+
+j_msg -${notice} -p "${BGon}Done${Boff}"
diff --git a/dev-util/joetoolkit/joetoolkit/nextcloud_check_version b/dev-util/joetoolkit/joetoolkit/nextcloud_check_version
--- a/dev-util/joetoolkit/joetoolkit/nextcloud_check_version
+++ b/dev-util/joetoolkit/joetoolkit/nextcloud_check_version
@@ -1,76 +1,75 @@
 #!/bin/bash
-source /usr/sbin/script_header_joetoo
-program="nextcould_check_version"
-BUILD=0
-VERBOSE=$TRUE
-verbosity=0
+# joetoo_cli_example - template app for joetoo CLI (c) Joe Brendler 2026-7789
 
-emerged_version_list=()
-version=""
+script_header_installed_dir="/usr/sbin"
+#script_header_installed_dir=/home/joe/myUtilities/dev-util/script_header_joetoo
+# source script_header
+header="${script_header_installed_dir%/}/script_header_joetoo"
 
-#-----[ functions ]------------------------------------------------------
+echo "header: $header"
 
-usage() {
-  E_message "Error: invalid cmdline options [$@]"
-  message "usage:  nextcould_check_version <options>"
-  message "options:"
-  message "  -[v|V] increase verbosity"
-  message "  -[q|Q] decrease verbosity"
-  exit
-}
+if [ -f "$header" ]; then . "$header"; else printf '%s' "failed to source header; cannot continue"; exit 1; fi
+printf '%s' "Checking for header commands to confirm sourcing"
+if command -v toc >/dev/null 2>&1 && command -v run_sequence >/dev/null 2>&1 ; then
+handle_result $? ; else printf '%s\n' "Failed; header not sourced; cannot continue"; exit 1; fi
 
-process_cmdline() {
-  while [ $# -gt 0 ]
-  do
-    # option ok w or w/o '-' or '--'
-    option=$( echo $1 | sed 's/^-//' | sed 's/^-//' )
-    case ${option} in
-       [vV] | verbose ) let verbosity++ ;;
-       [qQ] | quiet   ) let verbosity-- ;;
-       *              ) process_compound_option "$option" ;;
-    esac
-    shift
-  done
-}
+#-----[ variables ]----------------------------------------------------
 
-process_compound_option() {
-  myargs=$1
-  while [ -n "${myargs}" ]
-  do
-    #handle first char
-    case ${myargs:0:1} in
-       [vV] ) [ ! VERBOSE ] && VERBOSE=$TRUE; let verbosity++ ;;
-       [qQ] ) let verbosity--; [ verbosity -le 0 ] && VERBOSE=$FALSE ;;
-       *    ) usage "${myargs}" ;;
-    esac
-    #strip first char from myargs (i.e. "shift")
-    myargs=${myargs:1}
-  done
-}
+# NOTE: varlist variables are initialized by app_configure() and displayed by show_config();
+# the basic set of varlist variables is defined in script_header_joetoo and can be extended
+# either in the using script or in its .conf files.
+# An example is provided in the joetoo_cli_example script and in the template joetoo_cli_example.conf
+#
+# BREAK tells display_vars to add a newline spacer in its output
+# $LOCALIZED exemplifies use of the joetoo pseudo-boolean data type for POSIX scripts
+# $EXAMPLE and $DEFAULTS are pseudo-booleans defined in joetoo_cli_example_local.cmdline_arg_handler
+# $INITIALIZED_ME and $SOURCED_ME exemplify use of the joetoo yn data type
+# Note how each is named and how these types are prefixed in the varlist, to inform initialize_vars
+# and display_vars how to handle them.
+# $longone is a long string defined in script_header_joetoo to test and illustrate smart wrapping
+# by the smart_wrap_n() function. its name is prefixed "lv." in this localized extension of varlist
+# to indicate (long variable), so display_vars will use smart_wrap_n() to display the content of
+# $longone (which is long-one btw, not long-gone)
+#
+# CAVEAT: varlist is instantiated when script_header_joetoo is sourced (above), so it IS safe to add
+# variable names to it in a "variables" section at the top of your main script, but note that
+# the standard joetoo cli script layout calls app_configure() after that --
+# so anything you add to varlist before app_configure will be over-written when app_configure
+# calls initialize_var. which sets all bool. to $FALSE, all yn. to "no" and all others to ""
+#
+# Bottom line: you can append variable names to varlist at the top of your script, but if you do, you
+# ALSO need to reassign them AFTER app_configure runs. Thus it is "easier" to just append
+# variable names to varlist in the .conf file, which app_configure() loads AFTER it calls
+# initialize_vars, but be sure to also assign them, b/c they will not be initialized otherwise
+LOCALIZED=$FALSE; INITIALIZED_ME="no"
+varlist="${varlist} BREAK bool.LOCALIZED yn.INITIALIZED_ME"
 
-display_config() {
-  echo -e ${BYon}"Congiguration:"${Boff}
-  echo -e ${LBon}"VERBOSE................: "$(status_color ${VERBOSE})$(TrueFalse ${VERBOSE})${Boff}
-  echo -e ${LBon}"verbosity..............: "${Boff}${verbosity}
-}
+#-----[ functions ]----------------------------------------------------
 
-get_webapp_installed_version(){
+# note: this is based on the "mini" version (joetoo_cli_example_mini) is a template for scripts
+#  wherein the tasks do not require seqencing and interactive oversight.
+#  Thus, they can be coded directly into the scripts main body, or its
+#  internal functions, or both, as illustrated in this template
+# As such this "mini" version does not have or need an
+#   initialize_command_sequence() function
+
+get_webapp_installed_version() {
   if [ -z "$(find /var/www/localhost/htdocs/myCloud/ 2>/dev/null)" ]
   then
-    E_message "nextcloud has not been installed by webapp-config"
+    j_msg -${err} "nextcloud has not been installed by webapp-config"
     exit
   else
     webapp_installed_version=$(basename $(find /var/www/localhost/htdocs/myCloud/ -maxdepth 1 -iname '.webapp-nextcloud*') | \
       sed 's/\.webapp-nextcloud-//')
-    message "webapp_installed_version: ${webapp_installed_version}"
+    j_msg -${notice} -p "webapp_installed_version: ${webapp_installed_version}"
   fi
 }
 
 get_emerged_versions() {
   ev_string="$(eix-update -q && eix -eIc nextcloud)"
-  d_message "ev_string: ${ev_string}" 2
+  j_msg -${debug} -p "ev_string: ${ev_string}"
   ev_string_l="${ev_string#*\(}"
-  d_message "ev_string_l: ${ev_string_l}" 2
+  j_msg -${debug} -p "ev_string_l: ${ev_string_l}"
   ev_string_lr="${ev_string_l%)*}"
 #  emerged_versions=$(echo ${answer} | awk -F[\(\)] '{print $3,$5,$7 }' )
   cut=""; version=""
@@ -78,62 +77,88 @@ get_emerged_versions() {
 #  while [ -n "${ev_string_lr}" ]
   while [[ "${ev_string_lr}" ==  *"("* ]]
   do
-    d_message "ev_string_lr: ${ev_string_lr}" 2
+    j_msg -${debug} -p "ev_string_lr: ${ev_string_lr}"
     # cut out the first parenthetically enclosed version
     cut="${ev_string_lr#*\(}"
-    d_message "  cut: ${cut}" 3
+    j_msg -${debug} -p "  cut: ${cut}"
     version="${cut%%)*}"
-    d_message "  version: ${version}" 2
+    j_msg -${debug} -p "  version: ${version}"
     emerged_version_list+=("${version}")
     msg="  emerged_version_list: [${emerged_version_list[@]}]"
-    d_message "${msg}" 2
+    j_msg -${debug} -p "${msg}"
     # re-set ev_string_lr to the remainder
     ev_string_lr="${cut#*)}"
- done
-msg="emerged_version_list: [${emerged_version_list[@]}]"
-message "${msg}"
-
+  done
+  msg="emerged_version_list: [${emerged_version_list[@]}]"
+  j_msg -${notice} -p "${msg}"
 }
 
-# supercede script_header's built-in d_message
-#d_message () { echo "1: $1"; echo "2: $2"; [[ $VERBOSE ]] && [[ $2 -le $verbosity ]] && message "$1" ; }
-d_message () { [[ $VERBOSE ]] && [[ $2 -le $verbosity ]] && message "$1" ; }
 
 check_emerged_versions() {
-  for ((i=0; i<${#emerged_version_list[@]}; i++))
+  for (( i=0; i<${#emerged_version_list[@]}; i++ ))
   do
     myver="${emerged_version_list[$i]}"
     vercomp ${myver} ${webapp_installed_version} ; result=$?
-    echo -e "${BGon} * ${BWon}(emerged version) ${myver} $(show_result ${result}) ${BWon}${webapp_installed_version} (webapp-installed version)${Boff}"
+    j_msg -${notice} -p "${BWon}(emerged version) ${myver} $(show_result ${result}) ${BWon}${webapp_installed_version} (webapp-installed version)${Boff}"
     case ${result} in
-      2 ) message "${BRon}  version $myver should be removed${Boff}" ;; # 2 is <
-      0 ) message "${BWon}  version $myver is current; no action required${Boff}" ;; # 0 is =
-      1 ) message "${BYon}  version $myver is newer ; please run ${BGon}nextcloud_upgrade ${myver}${Boff}" ; maybe_do_upgrade "${myver}" ;; # 1 is >
-      * ) E_message "  error: bad version comparison"; exit ;;
+      2 ) j_msg -${notice} -p "${BRon}  version $myver should be removed${Boff}" ;; # 2 is <
+      0 ) j_msg -${notice} -p "${BWon}  version $myver is current; no action required${Boff}" ;; # 0 is =
+      1 ) j_msg -${notice} -p "${BYon}  version $myver is newer ; please run ${BGon}nextcloud_upgrade ${myver}${Boff}" ; maybe_do_upgrade "${myver}" ;; # 1 is >
+      * ) j_msg -${err} "  error: bad version comparison"; exit ;;
     esac
   done
 }
 
+
 maybe_do_upgrade() {
   myver="$1"
   answer=""
-  prompt "${BYon}  would you like to run ${BRon}# ${BGon}nextcloud_upgrade ${myver}${BYon} now?${Boff}"
+  yn_prompt "${BYon}  would you like to run ${BRon}# ${BGon}nextcloud_upgrade ${myver}${BYon} now?${Boff}"
   case ${answer:0:1} in
     [yY] ) eval "nextcloud_upgrade ${myver}" ;;
-    [nN] ) message "${BRon}Not${Boff} running nextcloud_upgrade; user declined" ;;
-    *    ) E_message "error; bad response to upgrade question" ;;
+    [nN] ) j_msg -${notice} -p "${BRon}Not${Boff} running nextcloud_upgrade; user declined" ;;
+    *    ) j_msg -${err} "error; bad response to upgrade question" ;;
   esac
 }
 
 
-#-----[ main script ]--------------------------------------------
-separator "${program}-${BUILD}"
-#checkroot
-process_cmdline $@
-display_config
+#-----[ main script ]----------------------------------------------------
+
+app_configure || die "failed to app_configure"
+
+# re-assign varlist variables appended at the top of the script and thus
+# over-written by app_configure
+j_msg -${debug} -n -m "(re)assigning LOCALIZED"
+LOCALIZED=$TRUE
+handle_result $? "$(TrueFalse $LOCALIZED)" "failed to reassign LOCALIZED" "$debug"
+j_msg -${debug} -n -m "(re)assigning INITIALIZED_ME"
+INITIALIZED_ME="yes"
+handle_result $? "$INITIALIZED_ME" "failed to reassign INITIALIZED_ME" "$debug"
+
+
+d_do show_config "$debug"  # show config prior to processing cmdline only at info/debug verbosity
+j_msg -${debug} -m "(BEFORE process_cmdline)"
+
+# note that without a defined command sequence and  the use of run_sequence
+# the INTERACTIVE, RESUME envinronment variables and their corresponding
+# command line flags (-r|--resume, -i|--interactive, -[0-9]* are all meaningless
+process_cmdline "$@" || die "failed to process_cmdline"
+
+d_do show_config "$info"  # show config prior to processing cmdline only at info/debug verbosity
+j_msg -${info} -m "(AFTER process_cmdline)"
+
+# instead of calling run_sequence for interactive oversight of complex
+# processes, simple tasks can be coded directly, right here
+
 
 get_webapp_installed_version
 
 get_emerged_versions
 
 check_emerged_versions
+
+result=$?
+separator "$PN-$BUILD" "(Done)"
+j_msg -n -p -M $idx_package "$PN complete. Results:"
+handle_result $result "" "" "$notice"
+exit $result
diff --git a/dev-util/joetoolkit/joetoolkit/nextcloud_import_root_ca_certificate b/dev-util/joetoolkit/joetoolkit/nextcloud_import_root_ca_certificate
--- a/dev-util/joetoolkit/joetoolkit/nextcloud_import_root_ca_certificate
+++ b/dev-util/joetoolkit/joetoolkit/nextcloud_import_root_ca_certificate
@@ -3,14 +3,14 @@ source /usr/sbin/script_header_joetoo
 
 #-----[ variables ]------------------------------------------------------------------
 
-PN=$(basename $0)
+PN=${0##*/}
+if [ -f /etc/joetoolkit/BUILD ]; then . /etc/joetoolkit/BUILD; else BUILD="0.0.1"; fi
 
 nextcloud_dir="/var/www/localhost/htdocs/myCloud"
 silent=">/dev/null 2>&1"
 
-VERBOSE=$TRUE
 # don't set verbosity unless it is not already set
-[ -z $verbosity ] && verbosity=3
+[ -z $verbosity ] && verbosity=${notice}
 
 #-----[ functions ]------------------------------------------------------------------
 
@@ -28,31 +28,30 @@ initialize() {
 }
 
 usage() {
-    echo
-    E_message "${BRon}Error: ${Boff}Invalid argument(s) [$@]"
-    E_message "${BYon}usage: ${BGon}${PN} ${BMon}/path/to/root_ca_certificate.crt${Boff}"
+    j_msg -${err} "\n${BRon}Error: ${Boff}Invalid argument(s) [$@]"
+    j_msg -${err} "${BYon}usage: ${BGon}${PN} ${BMon}/path/to/root_ca_certificate.crt${Boff}"
     exit 1
 }
 
 # Function to check if a file is a valid SSL certificate
 check_ssl_certificate() {
     local cert_file="$1"
-    echo -e -n " (${Yon}$(basename ${cert_file})${Boff})"
+    j_msg -${notice} -mp -n " (${Yon}$(basename ${cert_file})${Boff})"
 
     if [ ! -f "$cert_file" ]; then
-        E_message "Error: Certificate file '$cert_file' not found."
+        j_msg -${err} "Error: Certificate file '$cert_file' not found."
         return 1
     else
-        echo -e -n "(${Gon}exists${Boff})"
+        j_msg -${notice} -mp -n "(${Gon}exists${Boff})"
     fi
-    d_echo 3
+    j_msg -${notice} -mp ""  # newline
 
     # Attempt to parse the certificate file
     # openssl x509 will return an error if the file is not a valid certificate
     if openssl x509 -in "$cert_file" -noout &>/dev/null; then
         msg="Certificate file '$(basename $cert_file)'"
         msg+=" has a ${BGon}valid SSL certificate format${Boff}."
-        d_message "${msg}" 3
+        j_msg -${notice} -p "${msg}"
 
         # Extract validity dates
         start_date=$(openssl x509 -in "$cert_file" -noout -startdate | cut -d'=' -f2)
@@ -65,46 +64,49 @@ check_ssl_certificate() {
 
         msg="  ${LBon}Valid period is from: ${BMon}${start_date}"
         msg+="${LBon} to ${BMon}${end_date}${Boff}"
-        d_message "${msg}" 4
+        j_msg -${notice} -p "${msg}"
 
         if (( current_epoch < start_epoch )); then
-            E_message "Certificate is ${BRon}not yet valid${Boff}."
+            j_msg -${err} "Certificate is ${BRon}not yet valid${Boff}."
             return 1
         elif (( current_epoch > end_epoch )); then
-            E_message "Certificate has ${BRon}expired${Boff}."
+            j_msg -${err} "Certificate has ${BRon}expired${Boff}."
             return 1
         else
-            d_message "Certificate is currently ${BGon}valid${Boff} (within its validity period)." 3
+            j_msg -${notice} -p "Certificate is currently ${BGon}valid${Boff} (within its validity period)."
             return 0
         fi
     else
-        E_message "Error: Certificate file '$cert_file' is ${BRon}not a valid SSL certificate format${Boff}."
+        j_msg -${err} "Error: Certificate file '$cert_file' is ${BRon}not a valid SSL certificate format${Boff}."
         return 1
     fi
 }
 
 #-----[ main script ]---------------------------------------------------------------
 checkroot
-separator $(hostname) ${PN}
+separator "$(hostname)" "${PN}-${BUILD}"
 [ $# -ne 1 ] && usage
 rootcacert_path=$1
 initialize || die "failed to initialize"
 
 old_dir=$(pwd)
-message_n "${BYon}Moving to ${BMon}${nextcloud_dir}${Boff}"
+j_msg -${info} -m -n "${BYon}Moving to ${BMon}${nextcloud_dir}${Boff}"
 cd ${nextcloud_dir} || die "failed to move to ${nextcloud_dir}"
-right_status $TRUE
-d_message "${BWon}pwd: ${LBon}$(pwd)${Boff}" 3
+right_status $TRUE ${info}
+j_msg -${info} -m "${BWon}pwd: ${LBon}$(pwd)${Boff}"
+j_msg -${info} -m "rootcacert_path: $rootcacert_path"
 
-d_message "rootcacert_path: $rootcacert_path" 3
-for ((i=0; i< ${#command_sequence[@]}; i++)) ; do
-    message_n "${BWon}running ${BGon}${msg_sequence[$i]}${Boff} ..."
+# mini run_sequence
+for ((i=0; i<${#command_sequence[@]}; i++)) ; do
+    j_msg -${notice} -p -n "${BWon}running ${BGon}${msg_sequence[$i]}${Boff} ..."
     eval "${command_sequence[$i]}" || die "failed: ${command_sequence[$i]}"
-    right_status $TRUE
+    right_status $TRUE ${notice}
 done
-echo
-message_n "${BYon}Moving back to ${BMon}${old_dir}${Boff}"
-cd ${nextcloud_dir} || die "failed to move to ${nextcloud_dir}"
-right_status $TRUE
-d_message "${BWon}pwd: ${LBon}$(pwd)${Boff}" 3
+j_msg -${notice} -mp "" # newline
+
+j_msg -${info} -m -n "${BYon}Moving back to ${BMon}${old_dir}${Boff}"
+cd "${nextcloud_dir}" || die "failed to move to ${nextcloud_dir}"
+right_status $TRUE ${info}
+
+j_msg -${debug} -p "${BWon}pwd: ${LBon}$(pwd)${Boff}"
 message "${BGon}Done${Boff}"
diff --git a/dev-util/joetoolkit/joetoolkit/nextcloud_upgrade b/dev-util/joetoolkit/joetoolkit/nextcloud_upgrade
--- a/dev-util/joetoolkit/joetoolkit/nextcloud_upgrade
+++ b/dev-util/joetoolkit/joetoolkit/nextcloud_upgrade
@@ -3,59 +3,54 @@
 # joe brendler 6 August 2023
 #
 source /usr/sbin/script_header_joetoo
-newversion=""
+new_version=""
 myCloud_dir="/var/www/localhost/htdocs/myCloud/"
 old_dir=$PWD
-BUILD=0.1.3
-VERBOSE=$TRUE
-verbosity=2
+
+#BUILD=0.1.3
+if [ -f /etc/joetoolkit/BUILD ]; then . /etc/joetoolkit/BUILD; else BUILD=0.1.4; fi
 
 #-----[ variables ]-------------------
 result=""     # result of version check
-answer=""     # answer to new_prompt
-newver=""     # new version requested
-curver=""     # currently installed version (to be determined analytically)
+answer=""     # answer to yns_prompt
+new_ver=""     # new version requested
+cur_ver=""     # currently installed version (to be determined analytically)
 WEBAPP_UP=$FALSE
 OCC_UP=$FALSE
 
 #-----[ functions ]-------------------
-new_prompt()        # set external variable $answer based on reponse to prompt $1
-{ ps=$1; echo; echo; CUU; SCP; message_n "$ps [Yes/no/skip|Yns]: " && read answer; # '=~' not in busybox
-while ! expr "${answer:0:1}" : [yYnNsS] >/dev/null;  # answer not a regex match
-do RCP; echo -en "$(repeat ' ' $(termwidth))";  ## blank the line
-RCP; message_n "$ps [Yes/no/skip|Yns]: " && read answer; done; }
 
 version_check()     # check the new ($1) and currently installed versions and set external result
 {
-  newver="$1"
-  message "${BYon}Checing current version${Boff}"
+  new_ver="$1"
+  j_msg -${notice} -p "${BYon}Checing current version${Boff}"
   filename=$(find ${myCloud_dir} -maxdepth 1 -iname '*nextcloud*')
-  curver=${filename##*-}  # aggressively cut everything left of the last "-" character
+  cur_ver=${filename##*-}  # strip longest match for *- from the left - leaving version installed by webapp
   # start output comparison line with new version info
-  message_n "Requested Version: ${newver}"
-  vercomp ${newver} ${curver}; result=$?
+  j_msg -${notice} -p -n "Requested Version: ${new_ver}"
+  vercomp ${new_ver} ${cur_ver}; result=$?
   # print comparison indicator (< = >)
-  echo -en " $(show_result $result)"
+  j_msg -${notice} -mp -n " $(show_result $result)"
   # finish output line with comparison target info
-  echo -e " ${curver} (currently installed)"
-  d_message "result: $result" 3
+  j_msg -${notice} -p " ${cur_ver} (currently installed)"
+  j_msg -${notice} -p "result: $result"
 }
 
 webappconfig_upgrade()
 {
-  newver="$1"
-  d_message "${BWon}About to upgrade with command:  [ ${BGon}webapp-config -d $(basename ${myCloud_dir}) -U nextcloud ${newversion} ${BWon}] ${BRon}CTRL-C to abort${Boff}" 1
-  sh_countdown 5
-  webapp-config -d $(basename ${myCloud_dir}) -U nextcloud ${newver}
+  new_ver="$1"
+  j_msg -${notice} -p "${BWon}About to upgrade with command:  [ ${BGon}webapp-config -d $(basename ${myCloud_dir}) -U nextcloud ${new_version} ${BWon}] ${BRon}CTRL-C to abort${Boff}"
+  sh_countdown 4
+  webapp-config -d $(basename ${myCloud_dir}) -U nextcloud ${new_ver}
 }
 
 occ_upgrade()
 {
   cd ${myCloud_dir}
-  d_message "switched from ${old_dir} to $PWD" 2
-  d_message "do not forget to switch back to ${old_dir} when complete" 3
+  j_msg -${notice} -p "switched from ${old_dir} to $PWD"
+  j_msg -${notice} -p "do not forget to switch back to ${old_dir} when complete"
   echo
-  d_message "${BWon}About to upgrade with command:  [ ${BGon}sudo -u apache php ./occ upgrade ${BWon}] ${BRon}CTRL-C to abort${Boff}" 1
+  j_msg -${notice} -p "${BWon}About to upgrade with command:  [ ${BGon}sudo -u apache php ./occ upgrade ${BWon}] ${BRon}CTRL-C to abort${Boff}"
   sh_countdown 5
   sudo -u apache php ./occ upgrade
   cd ${old_dir}
@@ -63,49 +58,49 @@ occ_upgrade()
 
 double_check()
 {
-  message "${BYon}Currently configured as follows${Boff}"
-  message "${LBon} Currently installed nextcloud version.............: ${BWon}${curver}${Boff}"
-  message "${LBon} Requested new nextcloud version...................: ${BWon}${newver}${Boff}"
-  message "${LBon} WEBAPP_UP (upgrade nextcloud with webapp-config)...: $(status_color ${WEBAPP_UP})$(TrueFalse ${WEBAPP_UP})${Boff}"
-  message "${LBon} OCC_UP (upgrade installed app with occ)............: $(status_color ${OCC_UP})$(TrueFalse ${OCC_UP})${Boff}"
-  new_prompt "${BMon}Continue?${Boff}"
+  j_msg -${notice} -p "${BYon}Currently configured as follows${Boff}"
+  j_msg -${notice} -m "${LBon} Currently installed nextcloud version.............: ${BWon}${cur_ver}${Boff}"
+  j_msg -${notice} -m "${LBon} Requested new nextcloud version...................: ${BWon}${new_ver}${Boff}"
+  j_msg -${notice} -m "${LBon} WEBAPP_UP (upgrade nextcloud with webapp-config)...: $(status_color ${WEBAPP_UP})$(TrueFalse ${WEBAPP_UP})${Boff}"
+  j_msg -${notice} -m "${LBon} OCC_UP (upgrade installed app with occ)............: $(status_color ${OCC_UP})$(TrueFalse ${OCC_UP})${Boff}"
+  yns_prompt "${BMon}Continue?${Boff}"
 }
 
 #-----[ main script ]-----------------
 separator "nextcloud_upgrade-${BUILD}"
 checkroot
 [ $# -gt 1 -o $# -eq 0 ] && echo "please provide exactly one argument (new version #)" && exit 1
-newversion="$1"
-version_check ${newversion}
+new_version="$1"
+version_check ${new_version}
 
 # configure logical flags, to proceed as directed
 case ${result} in
   0) # =
     answer=""
-    new_prompt "Requested version is already installed by webapp-config. Continue or skip to occ upgrade?"
+    yns_prompt "Requested version is already installed by webapp-config. Continue or skip to occ upgrade?"
     case ${answer} in
-      [yY]*) message "Proceeding with reinstall..."; WEBAPP_UP=$TRUE; OCC_UP=$TRUE ;;
-      [nN]*) message "Exiting..."; WEBAPP_UP=$FALSE; OCC_UP=$FALSE ;;
-      [sS]*) message "Skipping webapp upgrade; continuing to occ upgrade..."; WEBAPP_UP=$FALSE; OCC_UP=$TRUE  ;;
-      *    ) E_message "Invalid answer to prompt [${answer}]; exiting..."; exit 1 ;;
+      [yY]*) j_msg -${notice} -p "Proceeding with reinstall..."; WEBAPP_UP=$TRUE; OCC_UP=$TRUE ;;
+      [nN]*) j_msg -${notice} -p "Exiting..."; WEBAPP_UP=$FALSE; OCC_UP=$FALSE ;;
+      [sS]*) j_msg -${notice} -p "Skipping webapp upgrade; continuing to occ upgrade..."; WEBAPP_UP=$FALSE; OCC_UP=$TRUE  ;;
+      *    ) j_msg -${err} "Invalid answer to prompt [${answer}]; exiting..."; exit 1 ;;
     esac
     ;;
   1) # >
-    message "Proceeding with both webapp-config and occ upgrades..."
+    j_msg -${notice} -p "Proceeding with both webapp-config and occ upgrades..."
     WEBAPP_UP=$TRUE; OCC_UP=$TRUE
     ;;
   2) # <
     answer=""
-    new_prompt "Are you sure you want to downgrade?"
+    yns_prompt "Are you sure you want to downgrade?"
     case ${answer} in
-      [yY]*) message "Proceeding with downgrade..."; WEBAPP_UP=$TRUE; OCC_UP=$TRUE ;;
-      [nN]*) message "Exiting..."; WEBAPP_UP=$FALSE; OCC_UP=$FALSE ;;
-      [sS]*) message "Skipping webapp upgrade; continuing to occ upgrade..."; WEBAPP_UP=$FALSE; OCC_UP=$TRUE  ;;
-      *    ) E_message "Invalid answer to prompt [${answer}]; exiting..."; exit 1 ;;
+      [yY]*) j_msg -${notice} -p "Proceeding with downgrade..."; WEBAPP_UP=$TRUE; OCC_UP=$TRUE ;;
+      [nN]*) j_msg -${notice} -p "Exiting..."; WEBAPP_UP=$FALSE; OCC_UP=$FALSE ;;
+      [sS]*) j_msg -${notice} -p "Skipping webapp upgrade; continuing to occ upgrade..."; WEBAPP_UP=$FALSE; OCC_UP=$TRUE  ;;
+      *    ) j_msg -${err} "Invalid answer to prompt [${answer}]; exiting..."; exit 1 ;;
     esac
     ;;
   *) # <
-    E_message "Invalid result from version_check() [${result}]; exiting"
+    j_msg -${err} "Invalid result from version_check() [${result}]; exiting"
     exit 1
     ;;
 esac
@@ -114,14 +109,14 @@ esac
 answer=""
 double_check
 case ${answer} in
-  [yY]*) message "Proceeding..." ;;
-  [nNsS]*) message "Aborting at user's request..."; WEBAPP_UP=$FALSE; OCC_UP=$FALSE ;;
-  *    ) E_message "Invalid answer to prompt [${answer}]; exiting..."; exit 1 ;;
+  [yY]*) j_msg -${notice} -p "Proceeding..." ;;
+  [nNsS]*) j_msg -${notice} -p "Aborting at user's request..."; WEBAPP_UP=$FALSE; OCC_UP=$FALSE ;;
+  *    ) j_msg -${err} "Invalid answer to prompt [${answer}]; exiting..."; exit 1 ;;
 esac
 
 # execute the selected upgrade/downgrade steps
-[[ ${WEBAPP_UP} ]] && webappconfig_upgrade ${newversion}
+[[ ${WEBAPP_UP} ]] && webappconfig_upgrade ${new_version}
 [[ ${OCC_UP} ]] && occ_upgrade
 
-d_message "All done" 1
+j_msg -${notice} -p "All done"
 exit 0
diff --git a/dev-util/joetoolkit/joetoolkit/text2pdf b/dev-util/joetoolkit/joetoolkit/text2pdf
--- a/dev-util/joetoolkit/joetoolkit/text2pdf
+++ b/dev-util/joetoolkit/joetoolkit/text2pdf
@@ -2,36 +2,21 @@
 # text2pdf - (c) joe brendler 2025-2055
 #
 source /usr/sbin/script_header_joetoo
-source /usr/sbin/script_header_joetoo_unicode
 
-VERBOSE=$TRUE
-[ -z $verbosity ] && verbosity=3  # assign default if null; allow calling program to dictate
+PN=${0##*/}   #  like =$(basename $0) but w/o subshell and function call
 
-PN=$(basename $0)
+if [ -f /etc/joetoolkit/BUILD ]; then . /etc/joetoolkit/BUILD; else BUILD="0.0.1"; fi
 
-separator ${PN} $(hostname)
+[ -z $verbosity ] && verbosity=${notice}  # assign default if null; allow calling program to dictate
 
 user="joe"
-
-# temporary, until I add this to script_header
-VS16="\UFE0F"
 
 #-----[ variables ]--------------------------------------------------
 
 old_dir=$(pwd)
 
 #-----[ functions ]--------------------------------------------------
-usage() {
-    E_message "${BRon}usage: ${BGon}${PN} <INPUT_TEXT_FILE>${Boff}"
-    exit 1
-}
-
-debug_marker() {
-    bremoji "${heart_red}${VS16}" ; echo -n " "
-    echo -e -n "${Ron}D${BRon}e${Yon}b${BYon}u${Gon}g${BGon}_${LBon}M${Bon}a${BBon}r${Mon}k${BMon}e${Won}r${BWon}!${Boff}"
-    echo -n " " ; bremoji $explosion; echo
-    exit 1
-}
+usage() {  j_msg -${err} "${BRon}usage: ${BGon}${PN} <INPUT_TEXT_FILE>${Boff}"; exit 1 ; }
 
 convert_text_to_pdf() {
     cat "${input_file}" | enscript -o - | ps2pdf - "${output_file}"
@@ -40,25 +25,20 @@ convert_text_to_pdf() {
 
 #-----[ main script ]------------------------------------------------
 
-[ $# -eq 0 ] && E_message "input file not specified" && usage
-[ $# -gt 2 ] && E_message "invalid arguments" && usage
+[ $# -eq 0 ] && {  j_msg -${err} "input file not specified" ; usage ; }
+[ $# -gt 2 ] && {  j_msg -${err} "invalid arguments" ; usage ; }
 input_file="$1"
-if [ ! -z "$2" ] ; then
-    output_file="$2"
-else
-    output_file="${input_file}.pdf"
-fi
+output_file="${2:-${input_file}.pdf}"
 
-separator $(hostname) ${PN}
+separator "$(hostname)" "${PN}-${BUILD}"
 
 convert_text_to_pdf || die "failed to convert_text_to_pdf"
-bremoji "$face_beam"
-echo -e -n " (${BGon}success!${Boff})"
+j_msg -${notice} -M $idx_face_beam -p " (${BGon}success"'!'"${Boff})"
 
-message_n "moving back to old_dir [$old_dir]"
+j_msg -${notice} -m -n "moving back to old_dir [$old_dir]"
 cd "$old_dir" || die "failed to cd to old_dir"
-right_status $TRUE
+right_status $TRUE ${notice}
 
-message "${BGon}Done${Boff}"
+j_msg -${notice} -p "${BGon}Done${Boff}"
 
 #debug_marker
diff --git a/dev-util/joetoolkit/joetoolkit/x_arg_clean_blockers b/dev-util/joetoolkit/joetoolkit/x_arg_clean_blockers
--- a/dev-util/joetoolkit/joetoolkit/x_arg_clean_blockers
+++ b/dev-util/joetoolkit/joetoolkit/x_arg_clean_blockers
@@ -1,50 +1,52 @@
 #!/bin/bash
 source /usr/sbin/script_header_joetoo
-BUILD=0.0
-separator "x_arg_clean_blockers-${BUILD}"
+
+PN=${0##*/}
+
+#BUILD=0.0
+if [ -f /etc/joetoolkig/BUILD ]; then . /etc/joetoolkig/BUILD; else BUILD="0.0.1"; fi
+
+separator "${PN}-${BUILD}"
 checkroot
-[[ ! $1 == "go" ]] && echo "Error: provide a \"dependency confilict\" list in /home/joe/temp. Then run w argument \"go\"" && exit
+if [[ ! $1 == "go" ]]; then
+  j_msg -${err} "Error: provide a \"dependency confilict\" list in /home/joe/temp. Then run w argument \"go\""
+  exit 1
+fi
 
 blockerlist=()
-blockerlist=()
+blockerlist2=()
 
 cmd='emerge -avC '
 # eliminate instances of " and (-)
-message "clearing out \" characters"
-sed -i 's/\"//g' /home/joe/temp
-message "clearing out instances of \"(-)\""
-sed -i 's/(-)//g' /home/joe/temp
-message "clearing out instances of \"(+)\""
-sed -i 's/(+)//g' /home/joe/temp
+j_msg -${notice} -p -n "clearing out \" characters"
+sed -i 's/\"//g' /home/joe/temp; right_status $? ${notice}
+j_msg -${notice} -p -n "clearing out instances of \"(-)\""
+sed -i 's/(-)//g' /home/joe/temp; right_status $? ${notice}
+j_msg -${notice} -p -n "clearing out instances of \"(+)\""
+sed -i 's/(+)//g' /home/joe/temp; right_status $? ${notice}
 
 blockerlist=($(cat /home/joe/temp | grep installed | cut -d'(' -f2 | cut -d':' -f1))
-#echo "-----[ cmd: $cmd ]-----"
-#separator "blockerlist"
-message "atoms in blockerlist: ${#blockerlist[@]}"
-#echo -e "blockerlist: [\n${blockerlist[@]}\n]"
+j_msg -${notice} -p "atoms in blockerlist: ${#blockerlist[@]}"
 
-message "clearing out redundant and invalid atoms"
-#separator "blockerlist2"
-for x in ${blockerlist[@]}
-do
+j_msg -${notice} -p -n "clearing out redundant and invalid atoms"
+for x in "${blockerlist[@]}"; do
   blockerlist2+=($(qatom \
     $(qatom "$x" | awk '{ print  $1"/"$2 }') \
     | awk '{ print  $1"/"$2 }'))
 done
-#echo "'\${#blockerlist2[@]}': ${#blockerlist2[@]}"
-#echo -e "blockerlist2: [\n${blockerlist2[@]}\n]"
+j_msg -${debug} -p "'\${#blockerlist2[@]}': ${#blockerlist2[@]}"
+j_msg -${debug} -p  "blockerlist2: [\n${blockerlist2[@]}\n]"
 
 count=0
-for z in $(for x in ${blockerlist2[@]}; do echo "$x"; done | sort -u | grep -v "unset")
+# output the list of blockers
+for z in $(for x in "${blockerlist2[@]}"; do printf '%s\n' "$x"; done | sort -u | grep -v "unset")
 do
   cmd+=" $z"
   let count++
 done
-message "unique blockers: ${count}"
-echo
+j_msg -${notice} -p -n "unique blockers: ${count}\n"
 separator "clear blocker command follows"
-echo "${cmd}"
-sh_countdown 3
+j_msg -${notice} -mp "${cmd}"
+#sh_countdown 3
 ## todo - interactive prompt to run the command
 #eval ${cmd}
-
