fix sort uniqe by timestamp for openvpn_dns_updater.sh; bugfix ebup and add pkgdev manifest -f step
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-util/joetoolkit/joetoolkit/ebup b/dev-util/joetoolkit/joetoolkit/ebup
--- a/dev-util/joetoolkit/joetoolkit/ebup
+++ b/dev-util/joetoolkit/joetoolkit/ebup
@@ -220,7 +220,19 @@ edit-new-ebuild() {
         [nN] ) E_message "Aborting as instructed" ; return 1;;
         *    ) E_message "Invalid response [$response]" ; return 1;;
     esac
-    nano "${output_ebuild_filename}"
+    return $result
+}
+
+pkgdev_manifest_new-ebuild() {
+    response=""
+    new_prompt "${BYon}Ready to run pkgdev manifest -f for the new ebuild [${BMon}${output_ebuild_filename}${BYon}]?${Boff}"
+    case ${response:0:1} in
+        [yY] )
+            pkgdev manifest -f "${output_ebuild_filename}" ; result=$? ;;
+        [sS] ) message "${BMon}Skipping edit as instructed${Boff}" ; result=0 ;;
+        [nN] ) E_message "Aborting as instructed" ; return 1;;
+        *    ) E_message "Invalid response [$response]" ; return 1;;
+    esac
     return $result
 }
 
@@ -264,6 +276,8 @@ calculate-new-version "${UPGRADE}" || die "failed to calculate-new-version ${UPG
 create-new-ebuild || die "failed to create-new-ebuild"
 
 edit-new-ebuild || die "failed to edit-new-ebuild"
+
+pkgdev_manifest_new-ebuild || die "failed to pkgdev_manifest_new-ebuild"
 
 message_n "moving back to old_dir [$old_dir]"
 cd "$old_dir" || die "failed to cd to old_dir"
