update move_joetoo_kernels_to_webserver to process armbian and joetoo kernels
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-util/joetoolkit/joetoolkit/move_joetoo_kernels_to_webserver b/dev-util/joetoolkit/joetoolkit/move_joetoo_kernels_to_webserver
--- a/dev-util/joetoolkit/joetoolkit/move_joetoo_kernels_to_webserver
+++ b/dev-util/joetoolkit/joetoolkit/move_joetoo_kernels_to_webserver
@@ -5,7 +5,14 @@ PN=$(basename $0)
 
 #-----[ variables ]-------------------------------------------------------
 user="joe"
+# currently supporting joetoo and armbian (rockchip, amlogic, or uefi)
+# ( presently no armbian kernels for nxp/imx/fsl nor raspi )
+# ( joetoo kernels available for raspi and some rockchip sbcs)
+# ( where properly patched upstream sources are available )
 joetoo_kernel_webserver_dir="/var/www/localhost/htdocs/joetoo-kernels"
+rockchip_kernel_webserver_dir="/var/www/localhost/htdocs/rockchip-kernels"
+amlogic_kernel_webserver_dir="/var/www/localhost/htdocs/amlogic-kernels"
+arm64-uefi-kernel_webserver_dir="/var/www/localhost/htdocs/arm64-uefi-kernels"
 
 SIZE_CHECK_INTERVAL=2    # seconds to wait between size-change checks
 SIZE_CHECK_ITERATIONS=3  # of times to check (must be >= 2)
@@ -112,10 +119,19 @@ for tarball in $(find /home/${user}/ -maxdepth 1 -name 'linux*.tar.bz2') ; do
         right_status $TRUE
     fi
 
-    # copy tarball to webserver
+    # copy tarball to (correct) webserver (presently no nxp/imx/fsl kernels supported)
+    case $tarball in
+        *"joetoo"*             ) webserver_dir=${joetoo_kernel_webserver_dir} ;;
+        *"rk3"*"armbian"*      ) webserver_dir=${rockchip_kernel_webserver_dir} ;;
+        *"mes"*"armbian"*      ) webserver_dir=${amlogic_kernel_webserver_dir} ;;
+        *"arm64-uefi_armbian"* ) webserver_dir=${arm64-uefi-kernel_webserver_dir} ;;
+        *                 )
+            /usr/bin/logger -p cron.err "${PN} failed to copy tarball and sha512sum to webserver" ;
+            die "invalid tarball, please investigate" ;;
+    esac
     message_n "moving tarball and sha512sum to webserver ..."
-    cp "${tarball}" ${joetoo_kernel_webserver_dir%/}/ 2>/dev/null ; result=$?
-    cp "${tarball}.sha512sum" ${joetoo_kernel_webserver_dir%/}/ 2>/dev/null ; result2=$?
+    cp "${tarball}" ${webserver_dir%/}/ 2>/dev/null ; result=$?
+    cp "${tarball}.sha512sum" ${webserver_dir%/}/ 2>/dev/null ; result2=$?
     if [ ! $result -eq 0 ] || [ ! $result2 -eq 0 ] ; then
         ERROR=$TRUE ; right_status 1
         /usr/bin/logger -p cron.err "${PN} failed to copy tarball and sha512sum to webserver"
