joetoolkit-0.8.7.tbz2 - patch nextcloud_upgrade for yns_prompt response vs answer
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-util/joetoolkit/joetoolkit/nextcloud_upgrade b/dev-util/joetoolkit/joetoolkit/nextcloud_upgrade
--- a/dev-util/joetoolkit/joetoolkit/nextcloud_upgrade
+++ b/dev-util/joetoolkit/joetoolkit/nextcloud_upgrade
@@ -12,7 +12,7 @@ if [ -f /etc/joetoolkit/BUILD ]; then . /etc/joetoolkit/BUILD; else BUILD=0.1.4;
 
 #-----[ variables ]-------------------
 result=""     # result of version check
-answer=""     # answer to yns_prompt
+response=""     # response to yns_prompt
 new_ver=""     # new version requested
 cur_ver=""     # currently installed version (to be determined analytically)
 WEBAPP_UP=$FALSE
@@ -76,13 +76,13 @@ version_check ${new_version}
 # configure logical flags, to proceed as directed
 case ${result} in
   0) # =
-    answer=""
+    response=""
     yns_prompt "Requested version is already installed by webapp-config. Continue or skip to occ upgrade?"
-    case ${answer} in
+    case ${response} in
       [yY]*) j_msg -${notice} -p "Proceeding with reinstall..."; WEBAPP_UP=$TRUE; OCC_UP=$TRUE ;;
       [nN]*) j_msg -${notice} -p "Exiting..."; WEBAPP_UP=$FALSE; OCC_UP=$FALSE ;;
       [sS]*) j_msg -${notice} -p "Skipping webapp upgrade; continuing to occ upgrade..."; WEBAPP_UP=$FALSE; OCC_UP=$TRUE  ;;
-      *    ) j_msg -${err} "Invalid answer to prompt [${answer}]; exiting..."; exit 1 ;;
+      *    ) j_msg -${err} "Invalid response to prompt [${response}]; exiting..."; exit 1 ;;
     esac
     ;;
   1) # >
@@ -90,13 +90,13 @@ case ${result} in
     WEBAPP_UP=$TRUE; OCC_UP=$TRUE
     ;;
   2) # <
-    answer=""
+    response=""
     yns_prompt "Are you sure you want to downgrade?"
-    case ${answer} in
+    case ${response} in
       [yY]*) j_msg -${notice} -p "Proceeding with downgrade..."; WEBAPP_UP=$TRUE; OCC_UP=$TRUE ;;
       [nN]*) j_msg -${notice} -p "Exiting..."; WEBAPP_UP=$FALSE; OCC_UP=$FALSE ;;
       [sS]*) j_msg -${notice} -p "Skipping webapp upgrade; continuing to occ upgrade..."; WEBAPP_UP=$FALSE; OCC_UP=$TRUE  ;;
-      *    ) j_msg -${err} "Invalid answer to prompt [${answer}]; exiting..."; exit 1 ;;
+      *    ) j_msg -${err} "Invalid response to prompt [${response}]; exiting..."; exit 1 ;;
     esac
     ;;
   *) # <
@@ -106,12 +106,12 @@ case ${result} in
 esac
 
 # double-check user comittment to contiue as directed
-answer=""
+response=""
 double_check
-case ${answer} in
+case ${response} in
   [yY]*) j_msg -${notice} -p "Proceeding..." ;;
   [nNsS]*) j_msg -${notice} -p "Aborting at user's request..."; WEBAPP_UP=$FALSE; OCC_UP=$FALSE ;;
-  *    ) j_msg -${err} "Invalid answer to prompt [${answer}]; exiting..."; exit 1 ;;
+  *    ) j_msg -${err} "Invalid response to prompt [${response}]; exiting..."; exit 1 ;;
 esac
 
 # execute the selected upgrade/downgrade steps
