joetoolkit-0.8.3.tbz2 - bugfix tarup and ebup invalid options
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-util/joetoolkit/joetoolkit/tarup b/dev-util/joetoolkit/joetoolkit/tarup
--- a/dev-util/joetoolkit/joetoolkit/tarup
+++ b/dev-util/joetoolkit/joetoolkit/tarup
@@ -67,7 +67,7 @@ get-current-version() {
         j_msg -${notice} -m " so current tarball version = 0.0.0 [i.e. none]"
     else
         latest_tarball_version="${tarball_versions[0]}"
-        j_msg -${notice} -p "current version: [${latest_tarball_version}]"
+        j_msg -${notice} -p "${Bon}current version${Boff}: [${latest_tarball_version}]"
         # split version into ( major minor patch )
         IFS='.' read -ra current_version_numbers <<< $latest_tarball_version
         result=$?
@@ -93,7 +93,7 @@ get-archive-version() {
     else
         to_be_archived_tarball_version="${tarball_versions[ -1 ]}" || \
             die "failed to assign to_be_archived_tarball_version="
-        j_msg -${notice} -p "archive version: [${to_be_archived_tarball_version}]"
+        j_msg -${notice} -p "${Ron}archive version${Boff}: [${to_be_archived_tarball_version}]"
     fi
     return 0
 }
@@ -128,7 +128,7 @@ calculate-new-version() {
     j_msg -${notice} -m "  new patch: ${new_version_numbers[2]}"
     new_tarball_version="${new_version_numbers[0]}.${new_version_numbers[1]}.${new_version_numbers[2]}"
     result=$?
-    j_msg -${notice} -p "new version: ${new_tarball_version}"
+    j_msg -${notice} -p "${Gon}new version${Boff}: ${new_tarball_version}"
     return $result
 }
 
@@ -178,7 +178,8 @@ if [ ! -d "$1" ]; then j_msg -${err} -p "SOURCE_DIR: [$1] does not exist" ; usag
 
 if [ $# -eq 2 ] ; then
     [[ "${2:0:1}" != "-" ]] && { j_msg -${err} -p "prefix option with \"-|\"" ; usage ; }
-    case "$2" in
+    _opt=${2#*-}  # stript the shortest match for '*-' from the left (-) - leaving opt w/o dash
+    case "$_opt" in
         "ma"*) UPGRADE="major" ;;
         "mi"*) UPGRADE="minor" ;;
         "pa"*) UPGRADE="patch" ;;
@@ -192,10 +193,10 @@ fi
 load-tarball_versions || die "failed to load-tarball_versions"
 get-current-version || die "failed to get-current-version"
 get-archive-version || die "failed to get-archive-version"
+calculate-new-version "${UPGRADE}" || die "failed to calculate-new-version ${UPGRADE}"
 
 archive-old-version || die "failed to archive-old-version"
 
-calculate-new-version "${UPGRADE}" || die "failed to calculate-new-version ${UPGRADE}"
 
 create-new-tarball || die "failed to create-new-tarball"
 
