updated unlock-drives; added unlock-drives-minima
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-util/joetoolkit/joetoolkit/unlock-drives b/dev-util/joetoolkit/joetoolkit/unlock-drives
--- a/dev-util/joetoolkit/joetoolkit/unlock-drives
+++ b/dev-util/joetoolkit/joetoolkit/unlock-drives
@@ -1,27 +1,66 @@
 #!/bin/bash
-key_device=$(blkid | grep -i 'key\|card\|thumb' | cut -d':' -f1)
-mount ${key_device} /mnt/key
 
+source /usr/sbin/script_header_joetoo
+
+PN=$(basename 0)
+checkroot
+separator "$(hostname)" "${PN}"
+
+message "looking for key_device ..."
+key_device=$(blkid | grep -i 'key\|card\|thumb' | cut -d':' -f1 | head -n1)
+
+if [ -z "${key_device}" ] ; then
+    E_message "no key_device found; you will be asked for passphrase"
+else
+    message "found key_device: [${key_device}]"
+    if [ -d /mnt/key ] ; then
+        message "key_device mountpoint /mnt/key found"
+    else
+        message_n "creating key_device mountpoint /mnt/key ..."
+        mkdir /mnt/key || die "failed to mkdir /mnt/key"
+        right_status $TRUE
+    fi
+    message_n "mounting key_device [$key_device] on mountpoint /mnt/key ..."
+    mount "${key_device}" /mnt/key || die "failed to mount key_device"
+    right_status $TRUE
+fi
+
+message "looking for luks encrypted block devices ..."
 for x in $(blkid | grep -i luks | cut -d':' -f1 | cut -d'/' -f3)
 do
-  echo "unlocking $x..."
-  p_dev="/dev/${x}"; c_dev=$(echo $x | sed 's|sd|ed|')
-  cryptsetup luksOpen -d /mnt/key/crypt/dat ${p_dev} ${c_dev}
+    message "unlocking $x..."
+    p_dev="/dev/${x}"; c_dev=$(echo $x | sed 's|sd|ed|')
+    if [ -z "${key_device}" ] ; then
+        cryptsetup luksOpen "${p_dev}" "${c_dev}" || die "failed cryptsetup luksOpen ${p_dev} (w/o key)"
+    else
+        cryptsetup luksOpen -d /mnt/key/crypt/dat "${p_dev}" "${c_dev}" || die "failed cryptsetup luksOpen ${p_dev} (with key)"
+    fi
+    message "${p_dev} ${BGon}unlocked${Boff} as crypt device ${c_dev}"
 done
 
-echo "vgscan; vgchange -ay"
+message "vgscan; vgchange -ay"
 vgscan; vgchange -ay
 
-root_vg=$(lvs | grep root | awk '{print $2}')
-mount /dev/mapper/${root_vg}-root /mnt/gentoo
+message "identifying root_vg ..."
+root_vg=$(lvs | grep root | awk '{print $2}') || die "failed to identify root_vg"
 
-echo "unmounting /mnt/key..."
-umount /mnt/key
+if [ ! -z "${root_vg}" ] ; then
+    message_n "mounting [${root_vg}-root] ..."
+    mount "/dev/mapper/${root_vg}-root" /mnt/gentoo || die "failed to mount ${root_vg}-root"
+    right_status $TRUE
+else
+    E_message "no root_vg found"
+    exit 1
+fi
 
-echo "mount | grep gentoo..."
-mount | grep gentoo
+message_n "unmounting /mnt/key..."
+umount /mnt/key || die "failed to umount /mnt/key"
+right_status $TRUE
+
+message "${BBon}mount${Boff} | ${BBon}mount${Boff}grep gentoo ..."
+mount | grep gentoo | sed "s/^/ |   /"
 
 echo
-echo "now cd /mnt/gentoo, run ./mount-the-rest, and cat chroot-commands..."
+message "now cd /mnt/gentoo, run ${BGon}./mount-the-rest.xxxx${Boff}, and cat chroot-commands..."
 echo
-echo "mount /boot AFTER chroot..."
+message "don't forget to also mount /boot before or after chroot..."
