init script and make_sources.sh bugfix to add function headers to content,

diff --git a/mkinitramfs/init b/mkinitramfs/init
--- a/mkinitramfs/init
+++ b/mkinitramfs/init
@@ -36,13 +36,13 @@ VERBOSE=$TRUE; verbosity=2
 
 #----[ reassign local variables with values from config files ]----------------------------------
 # source the BUILD number generated by the make_sources.sh script,
-echo -n "sourcing /BUILD ..."
+d_message_n "sourcing /BUILD ..." 1
 source /BUILD
 right_status $? || echo "sourcing failed"
 sleep .5
 
 # source variables assigned in init.conf. Note cmdline may override root=, usr=, verbosity=
-echo -n "sourcing /init.conf ..."
+d_message_n "sourcing /init.conf ..." 1
 source /init.conf
 right_status $? || echo "sourcing failed"
 sleep .5
@@ -56,11 +56,14 @@ separator "Running /init" "initramfs-$BUILD"
 
 #----[ Define functions local to initramfs ]-----------------------------------------------------
 
-source ./validated_functions_header
+d_message_n "sourcing /validated_functions_header ..." 1
+source /validated_functions_header
+right_status $? || echo "sourcing failed"
 
 #### ***** for testing, when ready, move still-testing functions to validated_functions_header ***** ---------
-source ./testing_functions_header
-
+d_message_n "sourcing /testing_functions_header ..." 1
+source /testing_functions_header
+right_status $? || echo "sourcing failed"
 
 rescue_shell() {
     # echo a simply formatted message explaining the source of our problem
