bugfix - script_header now called brendlefly

diff --git a/mkinitramfs/script_header_brendlefly b/mkinitramfs/script_header_brendlefly
--- a/mkinitramfs/script_header_brendlefly
+++ b/mkinitramfs/script_header_brendlefly
@@ -1,6 +1,6 @@
 #!/bin/bash
 #   script header with basic functions
-# Author: Joe Brendler 19 Jul 2014
+# Author: brendlefly 19 Jul 2014
 #
 
 #---[ Define common variables for use in various scripts ]---
@@ -8,6 +8,7 @@ BUILD="0.0.0 (19620207)"  #redefine in base script
 ROOT_UID=0       # Only users with $UID 0 have root privileges
 #  Error message used by various scripts
 E_NOTROOT="Must be root to run this script."
+E_ROOT="Please run this script as user, not root."
 E_BAD_ARGS="Improperly formatted command line argument."
 
 #--[ Easy ANSI Escape sequences to put color in my scripts ]---
@@ -50,6 +51,30 @@ BMon="${CSI}${MAG};${BOLD}m"
 LBon="${CSI}${LBLUE};${BOLD}m"
 BWon="${CSI}${WHITE};${BOLD}m"
 Boff="${CSI}${SGRoff}m"          # Bold off (reset all SGR (e.g. blink, underline)
+#---[ Box Drawing escape sequence stuff ]--------------------------
+#  See: https://en.wikipedia.org/wiki/Box-drawing_character
+ESCon='\e(0'
+ESCoff='\e(B'
+H_wall='\x71'
+V_wall='\x78'
+UL_wall='\x6C'
+UR_wall='\x6B'
+LL_wall='\x6D'
+LR_wall='\x6A'
+# we can also use unicode characters, which do not require the esc seq intro
+uH_wall='\u2500'
+uV_wall='\u2502'
+uUL_wall='\u250C'
+uUR_wall='\u2510'
+uLL_wall='\u2514'
+uLR_wall='\u2518'
+uD_H_wall='\u2550'
+uD_V_wall='\u2551'
+uD_UL_wall='\u2554'
+uD_UR_wall='\u2557'
+uD_LL_wall='\u255A'
+uD_LR_wall='\u255D'
+
 #---[ Cursor Movement Commands ]-----------------------------------
 SCP()  # save the current cursor position
 { echo -en "${CSI}s" && return 0 || return 1; }
@@ -93,11 +118,32 @@ checkroot()     # Run as root, of course.
   if [ "$UID" -ne "$ROOT_UID" ]; then E_message "${E_NOTROOT}"; echo; exit 1; else return 0; fi
 }
 
+checknotroot()     # Run as root, of course.
+{
+  if [ "$UID" -eq "$ROOT_UID" ]; then E_message "${E_ROOT}"; echo; exit 1; else return 0; fi
+}
+
 message()       # echo a simply formatted message (arg $1) to the screen
 { echo -e "${BGon}*${Boff} ${1}" && return 0 || return 1; }
 
+message_n()     # echo -n a simply formatted message (arg $1) to the screen
+{ echo -en "${BGon}*${Boff} ${1}" && return 0 || return 1; }
+
 E_message()     # echo a simply formatted error message (arg $1) to the screen
 { echo -e "${BRon}*${Boff} ${1}" && return 0 || return 1; }
+
+my_date()       # echo a simply formatted date string (DDD MM dd hh:mm:ss AP TZ yyyy)
+{
+  day=$(date +%a); month=$(date +%b); monthday=$(date +%d); year=$(date +%Y)
+  timeofday=$(date +%X); timezone=$(date +%Z)
+  echo "$day $month $monthday $timeofday $timezone $year"
+}
+
+my_short_date()       # echo a short formatted date string (yyyymmdd)
+{
+  month=$(date +%b); monthday=$(date +%d); year=$(date +%Y); timehack=$(date +%H:%M:%S);
+  echo "${monthday}${month}${year}-${timehack}";
+}
 
 repeat()        # output a repeated string of character (arg $1) of length (arg $2)
 {
@@ -237,6 +283,199 @@ progress()      # display an arrow depicting progress (visualize $1 of $2 steps 
   CUP $myrow $middlestart; echo -en "( ${pct_color}$percent%${Boff} )"; RCP
 }
 
+myBOX()         # draw an esc-seq single-line box w/ u/l corner at row $1, col $2, width $3, height $4
+{
+  ULrow=$1; ULcol=$2; WT=$3; HT=$4; myBOX=""
+  myBOX=${myBOX}${ESCon}
+  myBOX=${myBOX}$(repeat " " ${ULcol})${UL_wall}$(repeat ${H_wall} ${WT})${UR_wall}"\n"
+  for ((i=1;i<${HT};i++)); do myBOX=${myBOX}$(repeat " " ${ULcol})${V_wall}$(repeat " " ${WT})${V_wall}"\n"; done
+  myBOX=${myBOX}$(repeat " " ${ULcol})${LL_wall}$(repeat ${H_wall} ${WT})${LR_wall}"\n"
+  myBOX=${myBOX}${ESCoff}
+  CLR; CUP ${ULrow} 1
+  printf "${myBOX}"
+  return 0
+}
+
+my_u_BOX()      # draw a unicode single-line box with u/l corner at row $1, col $2, width $3, height $4
+{
+  ULrow=$1; ULcol=$2; WT=$3; HT=$4; myBOX=""
+  myBOX=${myBOX}$(repeat " " ${ULcol})${uUL_wall}$(repeat ${uH_wall} ${WT})${uUR_wall}"\n"
+  for ((i=1;i<${HT};i++)); do myBOX=${myBOX}$(repeat " " ${ULcol})${uV_wall}$(repeat " " ${WT})${uV_wall}"\n"; done
+  myBOX=${myBOX}$(repeat " " ${ULcol})${uLL_wall}$(repeat ${uH_wall} ${WT})${uLR_wall}"\n"
+  CLR; CUP ${ULrow} 1
+  printf "${myBOX}"
+  return 0
+}
+
+my_uD_BOX()     # draw a unicode double-line box with u/l corner at row $1, col $2, width $3, height $4
+{
+  ULrow=$1; ULcol=$2; WT=$3; HT=$4; myBOX=""
+  myBOX=${myBOX}$(repeat " " ${ULcol})${uD_UL_wall}$(repeat ${uD_H_wall} ${WT})${uD_UR_wall}"\n"
+  for ((i=1;i<${HT};i++)); do myBOX=${myBOX}$(repeat " " ${ULcol})${uD_V_wall}$(repeat " " ${WT})${uD_V_wall}"\n"; done
+  myBOX=${myBOX}$(repeat " " ${ULcol})${uD_LL_wall}$(repeat ${uD_H_wall} ${WT})${uD_LR_wall}"\n"
+  CLR; CUP ${ULrow} 1
+  printf "${myBOX}"
+  return 0
+}
+
+watchdistcc()  # until interrupted, display the count of distcc compile jobs done for clients
+{ CLR; while [ 1 ]; do CUP 1 1; echo | count_distcc_jobs 2>/dev/null; sleep 2; done; }
+
+vercomp()      # compare two version numbers (e.g. 2.0.1-r4), returns =:0, >:1, <:2
+{
+    VERBOSE="false"
+    # process arguments
+    local optioncount=0 operandcount=0
+    while [ ! -z $1 ]
+    do
+        # accept one option indicated by leading "-" and two operands indicated by no leading "-" error if there's more
+        if [ "${1:0:1}" == "-" ]
+        then
+            if (($optioncount < 1)) && [[ "$1" == "-v" ]]
+            then
+                VERBOSE="true"
+                let "optioncount++"
+            else
+                echo "Error: only one option (-v) allowed" && exit 1
+            fi
+        else
+            if (($operandcount < 2))
+            then
+                (($operandcount < 1)) && OP1=$1 || OP2=$1
+                let "operandcount++"
+            else
+                echo "Error: only two operands (version numbers) allowed" && exit 1
+            fi
+        fi
+        shift
+    done
+
+    #---[ additional local definitions ]--------------
+
+    if [[ $OP1 == $OP2 ]]
+    then
+        [ "$VERBOSE" == "true" ] && echo "$OP1 == $OP2; return 0"
+        return 0
+    fi
+    local IFS=.
+    local ver1=($OP1) ver2=($OP2)
+    if [ "$VERBOSE" == "true" ]
+    then
+      echo '$OP1:'" $OP1"
+      echo '$OP2:'" $OP2"
+      echo '${ver1}:'" ${ver1}"
+      echo '${ver2|:'" ${ver2}"
+      echo '${#ver1[@]}:'" ${#ver1[@]}"
+      echo '${#ver2[@]}:'" ${#ver2[@]}"
+      echo "To zero empty fields in ver1, i will range from = ${#ver1[@]} to < ${#ver2[@]}"
+    fi
+    # fill empty fields in ver1 with zeros
+    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
+    do
+        ver1[i]=0
+        [ "$VERBOSE" == "true" ] && echo "setting to zero for i=$i, ver1[$i]=${ver1[i]}"
+    done
+    [ "$VERBOSE" == "true" ] && echo "compare ith fields from most to least significant; return immediately if they differ"
+    [ "$VERBOSE" == "true" ] && echo "( i will range from = 0 to < ${#ver1[@]} )"
+    for ((i=0; i<${#ver1[@]}; i++))
+    do
+        [ "$VERBOSE" == "true" ] && echo "i=$i; ver1[$i]=${ver1[i]}; ver2[$i]=${ver2[i]}"
+        if [[ -z ${ver2[i]} ]]
+        then
+            # fill empty fields in ver2 with zeros
+            ver2[i]=0
+            [ "$VERBOSE" == "true" ] && echo "  setting to zero for i=$i, ver2[$i]=${ver2[i]}"
+        else
+            [ "$VERBOSE" == "true" ] && echo "  for i = $i, ${ver2[i]} is not empty, nothing to do"
+        fi
+
+        if ((10#${ver1[i]} > 10#${ver2[i]}))
+        then
+            [ "$VERBOSE" == "true" ] && echo "  i=$i; 10#${ver1[i]} > 10#${ver2[i]}; return 1"
+            return 1
+        fi
+        if ((10#${ver1[i]} < 10#${ver2[i]}))
+        then
+            [ "$VERBOSE" == "true" ] && echo "  i=$i; 10#${ver1[i]} < 10#${ver2[i]}; return 2"
+            return 2
+        fi
+    done
+
+    [ "$VERBOSE" == "true" ] && echo "testing final field for revision numbers"
+    i=$(($i -1))    # back to index of final field
+    tst1=$(expr index "${ver1[i]}" "-")
+    tst2=$(expr index "${ver2[i]}" "-")
+    [ "$VERBOSE" == "true" ] && echo "i=$i, tst1=[$tst1], tst2=[$tst2]"
+    if [ $tst1 -gt 0 ]
+    then
+        [ "$VERBOSE" == "true" ] && echo "ver1 HAS a rev #"
+        v1=$(echo ${ver1[i]} | cut -d- -f1)
+        r1=$(echo ${ver1[i]} | cut -d- -f2 | sed 's/^r//')
+        [ "$VERBOSE" == "true" ] && echo "v1=[$v1], r1=[$r1]"
+    else
+        [ "$VERBOSE" == "true" ] && echo "ver1 has NO rev #"
+        v1=${ver1[i]}; r1=""
+        [ "$VERBOSE" == "true" ] && echo "v1=[$v1], r1=[$r1]"
+    fi
+    if [ $tst2 -gt 0 ]
+    then
+        [ "$VERBOSE" == "true" ] && echo "ver2 HAS a rev #"
+        v2=$(echo ${ver2[i]} | cut -d- -f1)
+        r2=$(echo ${ver2[i]} | cut -d- -f2 | sed 's/^r//')
+        [ "$VERBOSE" == "true" ] && echo "v2=[$v2], r2=[$r2]"
+    else
+        [ "$VERBOSE" == "true" ] && echo "ver2 has NO rev #"
+        v2=${ver2[i]}; r2=""
+        [ "$VERBOSE" == "true" ] && echo "v2=[$v2], r2=[$r2]"
+    fi
+    [ "$VERBOSE" == "true" ] && echo "v1=[$v1], r1=[$r1], v2=[$v2], r2=[$r2]"
+    if [ -z $r1 ] && [ -z $r2 ]
+    then
+        [ "$VERBOSE" == "true" ] && echo "no rev #s, already determined 10#${ver1[i]} neither < nor > 10#${ver2[i]}; return 0"
+        return 0
+    else
+        [ "$VERBOSE" == "true" ] && echo "either or both have a rev #; compare"
+    	if ((10#${v1} > 10#${v2}))
+        then
+            [ "$VERBOSE" == "true" ] && echo "Final field, i=$i; 10#${v1} > 10#${v2}; return 1"
+            return 1
+        fi
+    	if ((10#${v1} < 10#${v2}))
+        then
+            [ "$VERBOSE" == "true" ] && echo "Final field, i=$i; 10#${v1} < 10#${v2}; return 2"
+            return 2
+        fi
+        # at this point only the rev #s might differ, compare. note: blank is less
+        [ "$VERBOSE" == "true" ] && echo "r1=$r1, r2=$r2"
+        if [ -z $r2 ] && [ ! -z $r1 ]
+        then
+            [ "$VERBOSE" == "true" ] && echo "Rev # [$r1] > [$r2]; return 1"
+            return 1
+        fi
+        if [ -z $r1 ] && [ ! -z $r2 ]
+        then
+            [ "$VERBOSE" == "true" ] && echo "Rev # [$r1] < [$r2]; return 2"
+            return 2
+        fi
+        if ((10#$r1 > 10#$r2))
+        then
+            [ "$VERBOSE" == "true" ] && echo "Rev # [$r1] > [$r2]; return 1"
+            return 1
+        fi
+        if ((10#$r1 < 10#$r2))
+        then
+            [ "$VERBOSE" == "true" ] && echo "Rev # [$r1] < [$r2]; return 2"
+            return 2
+        fi
+    fi
+
+    [ "$VERBOSE" == "true" ] && echo "Fell through everything, must be equal; return 0"
+    return 0
+}
+
+show_result()   # show the result of vercomp comparison, in english
+{ case $1 in 1) echo Greater;; 2) echo Lesser;; 0) echo Equal;; *) echo "*** Error ***";; esac }
+
 summarize_me()  # list contents of this script header (employ me with "source" or ".")
 {
   echo
@@ -247,6 +486,8 @@ summarize_me()  # list contents of this script header (employ me with "source" o
   message "  ${BYon}cursor${Boff} movement in my scripts, and it provides a number of" && \
   message "  useful ${BGon}functions${Boff}, for some routine tasks, as described below\n" && \
   grep "()" /usr/local/sbin/script_header_brendlefly | grep -v "grep" && echo && \
+  echo
+  message_n "Compare version number 3.4 to 3.4-r2  " && vercomp 3.4 3.4-r2; echo ">> $(show_result $?) <<"
   sh_countdown 6 && \
   echo -en "\nFinishing with status of summarization --->" ; right_status $?
 
