mkinitramfs-9.0.1 - fix ckinitramfs, form common_functions_header

diff --git a/mkinitramfs/validated_functions_header b/mkinitramfs/validated_functions_header
--- a/mkinitramfs/validated_functions_header
+++ b/mkinitramfs/validated_functions_header
@@ -1,24 +1,11 @@
 #!/bin/ash
 
-echo_long_string() {
-  #  spread a long string over several lines, if needed.  Assume external variable $longest has been set to identify start for 1st line
-  input="$@"
-  tw=$(termwidth)
-  newline=""
-  start=$longest
-  for x in $input
-  do
-    if [[  $(( ${start} + ${#newline} + ${#x} + 1)) -le ${tw} ]] ; then
-      newline="${newline} ${x}"
-    else
-      echo "${newline}"
-      start=0   # since next will be a new line
-      newline="${x}"
-    fi
-  done
-  echo "${newline}"
-}
-
+### -----[ duplicated functions ]--------------------------------------------------------------
+### These scripts exist in both "validated_" and "testing_" headers but have been modified in each
+### In the live init script, source the "testing_" header first and "validated_" header second
+### In the testing script, source "validated_" header first and the "testing_" header second
+### The later-sourced will override, and this avoid having the "testing" script mess with
+###    non-testing luks devices on a testing host system
 assign_volume() {
     # given string volume name (root_ usr_volume), scan lvs and make volume pathname assignment
     volume_name=$1
@@ -40,6 +27,123 @@ assign_volume() {
         message "No action. ${prefix} volume already assigned [ ${my_volume} ]"
     fi
 }
+
+unlock_devices() {
+    # for version 4.x and beyond, this is a complete re-write of the unlocking procedure.
+    # The unlock method has already been determined, and the script will now "scan" for LUKS
+    # devices and automatically use the selected method (key vs prompt) to unlock all of them
+    local method=$1;
+    local device="";
+    local line="";
+
+    [[ "$method" = "prompt" ]] && read -s -p "Enter your LUKS passphrase: " pass && echo;
+
+### substitute for testing only
+###    for device in $(blkid | grep -i luks | grep -v 'UUID="ef4195f0-6c4a-4116-86dd-fc469ddb6e21"' |cut -d':' -f1 )
+    for device in $(blkid | grep -i luks | cut -d':' -f1)
+    do
+        # use cryptsetup luksOpen to open each device /dev/sdxn with corresponding name edxn
+        # 27 Oct 23 - generalize to scsi or nvme devices (sdXX or nvmeXnXpX)
+        bn=$(basename ${device})
+        case ${bn:0:2} in
+          "sd" ) # scsi device
+            edev=$(echo ${bn} | sed 's/^s/e/')
+            ;;
+          "nv" ) # nvme device
+            edev=$(echo ${bn} | sed 's/^nvme/ev/' | sed 's/[np]//g')
+            ;;
+          "mm" ) # mmc device
+            edev=$(echo ${bn} | sed 's/^mmcblk/em/' | sed 's/p//g')
+            ;;
+          *    ) # tbd
+            echo "Error: bad luks device name [$device]"
+            ;;
+        esac
+        line="${device} ${edev}"
+        case "$method" in
+            "prompt")
+                mycmd="echo $pass | cryptsetup luksOpen $line"
+                d_message 'about to execute [eval "${mycmd}"]' 3
+                eval "${mycmd}"
+                if [[ $? -eq 0 ]]
+                then
+                    message "Unlocked $line with passphrase provided"
+                else
+                    E_message "${BRon}mycmd failed. Dropping to a shell. ${Boff}"
+                    sh_countdown $(( $init_wait * 5 ))
+                    [[ ${init_lock_down} ]] && rescue_shell
+                fi;
+                ;;
+            "key")
+                # passdevice already mounted,
+                # Use cryptsetup option for key file -d <mount_point><keyfile> and -S <key slot #>
+                # unmount the passdevice when we are done with it
+                message "About to execute command [ cryptsetup -d ${init_passdevice_mount_point}${init_keyfile} -S 1 luksOpen $line ]"
+                cryptsetup -d $(echo "${init_passdevice_mount_point%/}${init_keyfile}") -S 1 luksOpen $line
+                if [[ $? -eq 0 ]]
+                then  # cryptsetup luksOpen with key worked
+                    message "Unlocked $line with key found at $(echo ${init_passdevice_mount_point}${init_keyfile})"
+                else  # cryptsetup luksOpen with key failed
+                    E_message $BRon"Error: Could not unlock ${BYon}$line ${BRon}with key found at ${BMon}$(echo ${init_passdevice_mount_point}${init_keyfile})"$Boff
+                    E_message $BRon"Dropping to a shell"$Boff
+                    sh_countdown $(( $init_wait * 5 ))
+                    [[ ${init_lock_down} ]] && rescue_shell
+                fi
+                # since we are done with it, we will now un-mount the keying device
+                ;;
+        esac
+    done
+}
+### ----[ end duplicated functions ]--------------------------------------------------------------------------------------------------------------
+
+display_logical_volumes() {
+    # show what we've found...
+    separator "The following volume groups are available" "initramfs-$BUILD"
+    vgs
+    separator "The following volumes are available" "initramfs-$BUILD"
+    lvs
+    [[ $verbosity -gt 4 ]] && sh_countdown $init_wait
+}
+
+mount_new_root_and_prepare_to_switch_root() {
+    separator "Attempting to mount new root ..." "initramfs-$BUILD"
+    # previous version re-scanned here, but that now occurs after unlock
+    d_message "$(color ${RED} ${BBACK} ${BOLD})running fsck.${root_fs} on $root_volume${Boff}" 1 && fsck.${root_fs} -p $root_volume
+    d_message "$(color ${RED} ${BBACK} ${BOLD})running fsck.${usr_fs} on $usr_volume${Boff}" 1 && fsck.${usr_fs} -p $usr_volume
+    [[ $verbosity -gt 4 ]] && sh_countdown $init_wait
+    # mount root - drop to shell if not locked down
+    d_message_n "Mounting new root volume ..." 1
+    mount -r -t ${root_fs} ${root_volume} /newroot ; result=$?
+    right_status $result
+    if  [[ ! $result ]]; then
+        E_message "failed to mount root volume"
+        [[ "$init_lock_down" = "no" ]] && rescue_shell "Failed to mount root volume"
+    fi
+    d_message_n "Mounting new usr volume ..." 1
+    mount -t ${usr_fs} -o defaults,noatime $usr_volume /newroot/usr ; result=$?
+    right_status $result
+    if  [[ ! $result ]]; then
+        E_message "failed to mount usr volume"
+        [[ "$init_lock_down" = "no" ]] && rescue_shell "Failed to mount usr volume"
+    fi
+
+    separator "Mounts" "initramfs-$BUILD"
+    mount
+
+    # clean up in preparation to actually switch root
+    message "Cleaning up initramfs mounts prior to actual switch_root"
+    d_message_n "umount /proc ..." 1
+    umount /proc ; right_status $?
+    d_message_n "umount /dev/pts ..." 1
+    umount /dev/pts ; right_status $?
+    d_message_n "umount /dev ..." 1
+    umount /dev ; right_status $?
+    d_message_n "umount /sys ..." 1
+    umount /sys ; right_status $?
+
+    [[ $verbosity -gt 4 ]] && ssh_countdown $init_wait
+}
+
 
 validate_volume_and_assign_fs() {
     # given the string name of the volume, validate its existence and assign fs type
@@ -294,69 +398,3 @@ select_keying_device_and_unlock_method() {
         d_message "${BWon}Result: ${LBon}unlock_method = ${Mon}[ $unlock_method ]${Boff}" 2
 }
 
-unlock_devices() {
-    # for version 4.x and beyond, this is a complete re-write of the unlocking procedure.
-    # The unlock method has already been determined, and the script will now "scan" for LUKS
-    # devices and automatically use the selected method (key vs prompt) to unlock all of them
-    local method=$1;
-    local device="";
-    local line="";
-
-    [[ "$method" = "prompt" ]] && read -s -p "Enter your LUKS passphrase: " pass && echo;
-
-### substitute for testing only
-###    for device in $(blkid | grep -i luks | grep -v 'UUID="ef4195f0-6c4a-4116-86dd-fc469ddb6e21"' |cut -d':' -f1 )
-    for device in $(blkid | grep -i luks | cut -d':' -f1)
-    do
-        # use cryptsetup luksOpen to open each device /dev/sdxn with corresponding name edxn
-        # 27 Oct 23 - generalize to scsi or nvme devices (sdXX or nvmeXnXpX)
-        bn=$(basename ${device})
-        case ${bn:0:2} in
-          "sd" ) # scsi device
-            edev=$(echo ${bn} | sed 's/^s/e/')
-            ;;
-          "nv" ) # nvme device
-            edev=$(echo ${bn} | sed 's/^nvme/ev/' | sed 's/[np]//g')
-            ;;
-          "mm" ) # mmc device
-            edev=$(echo ${bn} | sed 's/^mmcblk/em/' | sed 's/p//g')
-            ;;
-          *    ) # tbd
-            echo "Error: bad luks device name [$device]"
-            ;;
-        esac
-        line="${device} ${edev}"
-        case "$method" in
-            "prompt")
-                mycmd="echo $pass | cryptsetup luksOpen $line"
-                d_message 'about to execute [eval "${mycmd}"]' 3
-                eval "${mycmd}"
-                if [[ $? -eq 0 ]]
-                then
-                    message "Unlocked $line with passphrase provided"
-                else
-                    E_message "${BRon}mycmd failed. Dropping to a shell. ${Boff}"
-                    sh_countdown $(( $init_wait * 5 ))
-                    [[ ${init_lock_down} ]] && rescue_shell
-                fi;
-                ;;
-            "key")
-                # passdevice already mounted,
-                # Use cryptsetup option for key file -d <mount_point><keyfile> and -S <key slot #>
-                # unmount the passdevice when we are done with it
-                message "About to execute command [ cryptsetup -d ${init_passdevice_mount_point}${init_keyfile} -S 1 luksOpen $line ]"
-                cryptsetup -d $(echo "${init_passdevice_mount_point%/}${init_keyfile}") -S 1 luksOpen $line
-                if [[ $? -eq 0 ]]
-                then  # cryptsetup luksOpen with key worked
-                    message "Unlocked $line with key found at $(echo ${init_passdevice_mount_point}${init_keyfile})"
-                else  # cryptsetup luksOpen with key failed
-                    E_message $BRon"Error: Could not unlock ${BYon}$line ${BRon}with key found at ${BMon}$(echo ${init_passdevice_mount_point}${init_keyfile})"$Boff
-                    E_message $BRon"Dropping to a shell"$Boff
-                    sh_countdown $(( $init_wait * 5 ))
-                    [[ ${init_lock_down} ]] && rescue_shell
-                fi
-                # since we are done with it, we will now un-mount the keying device
-                ;;
-        esac
-    done
-}
