update to xdotool_open_windows logrotate, etc.

diff --git a/dev-util/xdotool_open_windows/xdotool_open_windows b/dev-util/xdotool_open_windows/xdotool_open_windows
--- a/dev-util/xdotool_open_windows/xdotool_open_windows
+++ b/dev-util/xdotool_open_windows/xdotool_open_windows
@@ -12,9 +12,10 @@ PN=$(basename $0)
 user=joe
 
 config_dir="/etc/xdotool_open_windows"
-config_file="${config_dir}/xdotool_open_windows.conf"
-build_file=$"${config_dir}/BUILD"
-logFile="/home/${user}/xdotool_open_windows.log"
+config_file="${config_dir%/}/xdotool_open_windows.conf"
+build_file=$"${config_dir%/}/BUILD"
+log_dir="/home/${user}"
+logFile="${log_dir%/}/xdotool_open_windows.log"
 
 terminal_program=/usr/bin/konsole
 #terminal_program=/usr/bin/lxterminal
@@ -34,6 +35,11 @@ ssh_session_list=( \
  x_blank x_blank \
  )
 
+varlist="config_dir lv.config_file build_file log_dir lv.logFile"
+varlist+=" numdesktops sleepWait longWait width height X1 Y1 X2"
+varlist+=" control_window BREAK bool.VERBOSE verbosity"
+
+#------[ function blocks ]-------------------------------------------
 # load custom configuration, if it exists
 message_n "sourcing config_file: ${config_file} ..."
 [[ -f ${config_file} ]] || die "${config_file} does not exist"
@@ -50,16 +56,15 @@ d_message "(DEBUG $(my_short_date)) Top of script. Just set global variables." 3
 #-----[ function blocks ]-------------------------------------------------
 print_ssh_session_list() {
   d_message "now running print_ssh_session_list" 3
-#echo "ssh_session_list= [ ${ssh_session_list[@]} ]"
-#echo  "cutoff=${#ssh_session_list[@]}"
+  d_echo 3
   for ((j=0; j<${#ssh_session_list[@]}; j+=2 ))
   do
-#    echo "j=$j"
     cmd_target=${ssh_session_list[$j]}
     d_message "$(my_short_date) debug ssh_session_list: j=$j ssh_session_list[\$j]=${ssh_session_list[$j]} cmd_target=$cmd_target" 3
     let k=$(( $j + 1 ))
     cmd_target=${ssh_session_list[$k]}
     d_message "$(my_short_date) debug ssh_session_list: k=$k ssh_session_list[\$k]=${ssh_session_list[$k]} cmd_target=$cmd_target" 3
+    d_echo 3
   done
 }
 
@@ -109,10 +114,75 @@ setup_window_for_idx() {
     fi
 }
 
+show_config() {
+    longest=$(get_longest ${varlist})
+    display_vars ${longest} ${varlist}
+}
+
+open_windows() {
+    msg="$(my_short_date) Openning $(basename ${terminal_program})"
+    msg+=" terminals and starting ssh sessions. Please wait..."
+    d_message "${msg}" 1
+
+    d_message "$(my_short_date) about to enumerate ssh session list..." 1
+    print_ssh_session_list
+
+    d_message "$(my_short_date) now openning new windows" 1
+    for ((i=0; i<${#ssh_session_list[@]}; i+=2 ))
+    do   # launch two terminal windows per desktop
+      let index=$(( $i / 2 ))
+      d_message "setting desktop ${index}" 1
+      xdotool set_desktop ${index}
+      sleep $sleepWait
+      d_message "launching terminals on desktop ${index}" 1
+      if [[ $index -eq 0 ]] # this desktop is for the control window - don't make a new one
+      then
+        ## TODO - rename control window; move it to desktop 0
+        d_message "moving control_window $control_window to ${X1} ${Y1}" 2
+        xdotool windowmove --sync $control_window ${X1} ${Y1}
+        sleep $sleepWait
+        d_message "setting size of control_window $control_window to ${width} ${height}" 2
+        xdotool windowsize --sync --usehints $control_window ${width} ${height}
+        sleep $sleepWait
+      else
+        setup_window_for_idx $i
+        sleep $sleepWait
+        setup_window_for_idx $(( $i + 1 ))
+        sleep $sleepWait
+      fi
+    done
+    xdotool set_desktop 0
+    sleep $sleepWait
+    xdotool windowfocus window=${control_window}
+    #xdotool mousemove --window ${control_window} 5% 5% click 1
+    #xdotool mousemove --window ${control_window} 20 20 click 1
+}
+
+rotate_logfile() {
+    ## TODO - rotate logfile
+    message_n "rotating logfile ..."
+    gzip -c ${logFile} > ${log_dir%/}/$(basename ${logFile})-$(my_short_date).gz || \
+        die "failed to archive logfile"
+    rm $logFile || die "failed to remove old logfile"
+    right_status $TRUE
+}
+
+redirect_output_to_logfile() {
+    exec 6>&1 2>/dev/null           # Link file descriptor #6 with stdout. Saves stdout.
+    exec > $logFile  2>/dev/null    # stdout replaced with file.
+    # ----------------------------------------------------------- #
+    # All output from commands in this block sent to file $logFile
+}
+
+redirect_output_back_to_stdout() {
+    exec 1>&6 6>&-  2>/dev/null     # Restore stdout and close file descriptor #6.
+}
+
 #-----[ main script ]-----------------------------------------------------
 d_message "now in main script" 3
 #checknotroot
-checknotroot
+message_n "checking not root ..."
+checknotroot && right_status $? || die "failed checknotroot"
 
 # don't do this - it will close all windows in both (all) activities
 #d_message "$(my_short_date) first closing open windows..." 1
@@ -128,53 +198,20 @@ xdotool set_num_desktops ${numdesktops}
 num_desktops=$(xdotool get_num_desktops)
 control_window=$(xdotool getactivewindow)
 
-# TODO -- showconfig ()
-d_message "numdesktops: $numdesktops (calculated)" 1
-d_message "num_desktops: $num_desktops (set)" 1
-d_message "control_window: $control_window" 1
+# move the control window to desktop zero
+message_n "moving control_window ${control_window} to desktop 0 ..."
+xdotool set_desktop_for_window ${control_window} 0 || \
+    die "failed tomove control_window ${control_window} to desktop 0"
+right_status $?
 
-d_message "$(my_short_date) Openning $(basename ${terminal_program}) terminals and starting ssh sessions. Please wait..." 1
-## TODO - rotate logfile
-d_message "$(my_short_date) removing old log file" 1
-rm -v $logFile
-exec 6>&1 2>/dev/null           # Link file descriptor #6 with stdout. Saves stdout.
-exec > $logFile  2>/dev/null    # stdout replaced with file.
-# ----------------------------------------------------------- #
-# All output from commands in this block sent to file $logFile
+rotate_logfile
 
-d_message "$(my_short_date) about to enumerate ssh session list..." 1
-print_ssh_session_list
+redirect_output_to_logfile
 
-d_message "$(my_short_date) now openning new windows" 1
-for ((i=0; i<${#ssh_session_list[@]}; i+=2 ))
-do   # launch two terminal windows per desktop
-  let index=$(( $i / 2 ))
-  d_message "setting desktop ${index}" 1
-  xdotool set_desktop ${index}
-  sleep $sleepWait
-  d_message "launching terminals on desktop ${index}" 1
-  if [[ $index -eq 0 ]] # this desktop is for the control window - don't make a new one
-  then
-    ## TODO - rename control window; move it to desktop 0
-    d_message "moving control_window $control_window to ${X1} ${Y1}" 2
-    xdotool windowmove --sync $control_window ${X1} ${Y1}
-    sleep $sleepWait
-    d_message "setting size of control_window $control_window to ${width} ${height}" 2
-    xdotool windowsize --sync --usehints $control_window ${width} ${height}
-    sleep $sleepWait
-  else
-    setup_window_for_idx $i
-    sleep $sleepWait
-    setup_window_for_idx $(( $i + 1 ))
-    sleep $sleepWait
-  fi
-done
-xdotool set_desktop 0
-sleep $sleepWait
-xdotool windowfocus window=${control_window}
-#xdotool mousemove --window ${control_window} 5% 5% click 1
-#xdotool mousemove --window ${control_window} 20 20 click 1
+show_config
 
-exec 1>&6 6>&-  2>/dev/null     # Restore stdout and close file descriptor #6.
+open_windows
+
+redirect_output_back_to_stdout
 
 cat $logFile
