xdotool_open_windows-0.2.0.tbz2
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-util/xdotool_open_windows/xdotool_close_windows b/dev-util/xdotool_open_windows/xdotool_close_windows
--- a/dev-util/xdotool_open_windows/xdotool_close_windows
+++ b/dev-util/xdotool_open_windows/xdotool_close_windows
@@ -94,7 +94,7 @@ SCREEN_HEIGHT=$(echo $SCREEN_DIMENSIONS | cut -dx -f2)
 silent=">/dev/null 2>&1"  # append this to a command to silence it
 
 varlist="PN BUILD config_dir lv.config_file old_log_dir log_dir lv.logFile"
-varlist+=" BREAK control_window numdesktops sleepWait longWait timeout"
+varlist+=" BREAK control_window numdesktops sleepWait longWait typeWait timeout"
 varlist+=" bool.VERBOSE verbosity"
 
 
@@ -156,62 +156,31 @@ set_terminal_window_dimensions() {
 }
 
 close_windows() {
+    local result=""
     d_log_message "in ${FUNCNAME[0]} with arg(s) [$@]" 5
-    # identify all terminal windows (use --any but not --onlyvisible to get minimized, too)
-    window_list=()
-    window_list=($(xdotool search --any lxterminal 2>/dev/null))
-    window_list+=($(xdotool search --any Konsole))
-    window_list+=($(xdotool search --any xterm 2>/dev/null))
-    log_message "Currently tracking [${BMon}${#window_list[@]}${Boff}] terminal windows"
-    d_log_message "Current window list:" 3
-    d_log_echo ${window_list[@]} 3 ; d_log_echo "" 3
     log_message "Now closing all terminal windows except control_window [${BMon}${control_window}${Boff}] ..."
     # close all these windows
     for win in $(for x in ${window_list[@]}; do echo $x; done | sort -n)
     do
-        # since windows come and go (some closed as dependents of ones we closed)
-        # we need to test for the continued existence of the window before running
-        # commands like below, which would produce errors/unexptected results otherwise
-        # xdotool getwindowname $win queries the X server for the window name
+        # use getwindowname to test for the continued existence of the window before running commands on them
         # if $win exists, the command succeeds and prints its name to stdout
         # if $win has been closed, the command will fail and write an error message to stderr
-        xdotool getwindowname "$win" >/dev/null 2>&1
-        [ ! "$?" -eq 0 ] && continue  # skips code below and continues w next iteration of loop
+        log_message_n "looking for window: [${BMon}${win}${Boff}]"
+        xdotool getwindowname "$win" >/dev/null 2>&1 ; result=$?
+        log_handle_result "$?" "exists" "does not exist"   # don't use || return 1 (drive on)
+
+        [ ! "$result" -eq 0 ] && continue  # skips code below and continues w next iteration of loop
         log_message_n "getting desktop for win: [${BMon}$win${Boff}]"
         desktop=$(xdotool get_desktop_for_window $win 2>/dev/null)
-        # get_desktop_for_window will exit status 1 for non-visible desktops
-        # ( so don't use log_handle_result with " || return 1" )
-        log_handle_result "$?" "${desktop}" "${desktop}"
+        log_handle_result "$?" "${desktop}" "${desktop}"   # don't use || return 1 (drive on)
         log_message_n "Examining window [${BMon}$win${Boff}] on desktop [${BMon}$desktop${Boff}]"
-        if [[ $win -ne $control_window ]]
-        then
-            # use xprop to get the window's type and only close "normal" windows
-            # this is to avoid disrupting windowmanager/compositor (e.g. kwin) functionaliy
-            if xprop -id $win | grep -q "_NET_WM_WINDOW_TYPE_NORMAL" ; then
-                log_echo_e_n " (${BGon}Normal${Boff})"
- #               xdotool windowclose $win 2>/dev/null
-                # gracefully close this window by sending it an exit command
-                # (--sync to wait till it actually has focus)
-                log_echo_e_n " (${BRon}closing${Boff})"
-                xdotool windowactivate --sync "$win" && \
-                sleep $typeWait && \
-                    xdotool type "exit" && sleep $sleepWait && xdotool key Return
-                    sleep $typeWait
-#                log_handle_result "$?" "closed" "tried but failed to close" || return 1
-                # command chain will return failed exit status of first step that fails
-                # ( so don't use log_handle_result with " || return 1" )
-                log_handle_result "$?" "closed" "tried but failed to close"
-            else
-                sleep $sleepWait
-                log_echo_e_n " (${BMon}Special${Boff})"
-                log_handle_result "0" "skipping" "error while skipping" || return 1
-                debug_do 'xprop -id "$win" | grep -E "WM_NAME|WM_CLASS|_NET_WM_STATE" | sed "s|^|    |"' 4
-           fi
-        else
-            sleep $sleepWait
-            log_echo_e_n " (${BYon}control window${Boff})"
-            log_handle_result "0" "skipping" "error while skipping" || return 1
-        fi
+        # control_window should be excluded from window_list, and the xprop check should not be
+        # necessary since we are using top-level terminal application windows as the search scope
+        # see versions prior to 0.1.8 for use of check here for control_window and use of xprop
+        log_echo_e_n " (${BRon}closing${Boff})"
+        wmctrl -ic "$win"
+        poll_for_window_closed "$win"
+        log_handle_result "$?" "closed" "failed to close"
     done
     # move the active window to desktop 0, if it isn't already there
     if [[ ${current_desktop} -eq 0 ]]
@@ -231,6 +200,23 @@ close_windows() {
     xdotool windowactivate --sync "${control_window}"
     log_handle_result "$?" "activated and re-set ctrl" "failed to re-activate control_window" || return 1
     return 0
+}
+
+poll_for_window_closed() {
+    local myWin="$1"
+    local elapsed=0
+    while [[ ! -z $(wmctrl -l | grep -q "$myWin") ]] && [[ "$( echo "$elapsed <= $timeout" | bc -l )" -eq 1 ]] ; do
+        sleep $sleepWait
+        elapsed=$(echo "scale=2; ( ${elasped:-0} + $sleepWait )" | bc -l )
+    done
+    # return 1 if this timed out
+    if [[ ! -z $(wmctrl -l | grep -q "$myWin") ]] ; then
+        # myWin still not closed; timed out
+        log_E_message "timed out waiting for myWin to close"
+        return 1
+    else
+        return 0
+    fi
 }
 
 kill_pids() {
@@ -270,6 +256,59 @@ kill_pids() {
     return 0
 }
 
+dump_terminal_window_list() {
+    local buffer=5  # leave room for padding, etc.
+    local ts_buffer=23  # leave room for timestamp, etc.
+    local np_chars=26   # discount for non-visible characters in msg
+    msg="${BYon}----------[ ${LBon}Current window list ${BYon}]"
+    msg+="$( repeat '-' $(( $(termwidth) - ( ${#msg} + $ts_buffer -$np_chars ) )) )${Boff}"
+    log_message "${msg}"
+    win_list_line=""
+    for win in ${window_list[@]}; do
+        # print as many window ids on each line as will fit
+        d_log_message "#win_list_line: [${#win_list_line}] #win: [${#win}]" 5
+        d_log_message " sum: [$((${#win_list_line} + ${#win}))] termwidth: [$(termwidth)]" 5
+        if [ $((${#win_list_line} + ${#win})) -lt $(($(termwidth) - $buffer)) ] ; then
+            # this line is not full; append
+            d_log_message "comparison true (room for win)" 5
+            win_list_line+="$win "
+        else
+            # this line is already full; output this one, and then start a new one
+            d_log_message "comparison false (room for win)" 5
+            log_echo "    ${win_list_line}"
+            win_list_line="$win"
+        fi
+        # output whatever is left in any remaining un-full line
+    done
+    log_echo "    ${win_list_line}"
+    return 0
+}
+
+get_terminal_window_list() {
+    # populate window_list array with window ids of activa and minimized terminal windows only
+    # versions prior to 0.1.8 used xdotool search --any (too broad scope)
+    # xdotool search returns decimal window ids // wmctrl -l returns hex window ids
+    # look for all three terminal types using regex, convert hex to decimal and exclude control_window
+    re_filter="konsole\.Konsole|lxterminal\.Lxterminal|xterm\.XTerm"
+    window_list=($(wmctrl -lx | grep -Ei "${re_filter}" | awk '{print strtonum($1)}' | grep -v "${control_window}"))
+    return 0
+}
+
+close_windows_wrapper() {
+    # run close_windows and repeat until there are no more open windows
+    local round=0
+    get_terminal_window_list || return 1
+    log_message "Currently tracking [${BMon}${#window_list[@]}${Boff}] terminal windows"
+    d_do 'dump_terminal_window_list' 3
+    while [[ ! -z "${window_list[@]}" ]] ; do
+        log_message "round (${BMon}${round}${Boff}) closing ${#window_list[@]} terminal windows"
+        close_windows || return 1
+        get_terminal_window_list || return 1
+        ((round+=1))
+    done
+    return 0
+}
+
 #-----[ main script ]-----------------------------------------------
 d_message "now in main script" 3
 message_n "checking not root ..."
@@ -291,8 +330,8 @@ num_desktops=$(xdotool get_num_desktops)
 log_message "num_desktops: $num_desktops"
 
 # run sequence
-show_config || die "failed to show_config"
-close_windows || die "failed to close_windows"
+show_config || die "failed show_config"
+close_windows_wrapper || die "failed close_windows_wrapper"
 kill_pids "${xdotool_filter}"  || die "failed to kill_pids for filter [${BYon}${filter}${Boff}]"
 kill_pids "${ssh_filter}" || die "failed to kill_pids for filter [${BYon}${filter}${Boff}]"
 
