stabilized, enhanced
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-util/xdotool_open_windows/xdotool_close_windows b/dev-util/xdotool_open_windows/xdotool_close_windows
--- a/dev-util/xdotool_open_windows/xdotool_close_windows
+++ b/dev-util/xdotool_open_windows/xdotool_close_windows
@@ -4,23 +4,112 @@ source /usr/sbin/script_header_joetoo
 #-----[ initialize variables ]-------------------------------------------------
 PN=$(basename $0)
 
+### defaults - override in config file
 user=joe
 
-logFile="/home/${user}/xdotool_close_windows.log"
+#log_dir="/home/${user}"
+log_dir="/var/log"
+#old_log_dir="/var/log"
+old_log_dir="/var/log/old_logs"
+logFile="${log_dir%/}/xdotool_close_windows.log"
 
 config_dir="/etc/xdotool_open_windows"
 build_file=$"${config_dir}/BUILD"
+config_file=$"${config_dir}/xdotool_open_windows.conf"
 
-sleepWait=0.1
+# customized timing and detailed output (increase for debugging)
+#sleepWait=0.5    # default - set in .conf
+sleepWait=0.15    # default - set in .conf
+#longWait=2       # default - set in .conf
+longWait=1.1      # default - set in .conf
+timeout=10        # seconds to wait while trying to close a window or identify a new one
+
 VERBOSE=$TRUE
-verbosity=4
+#VERBOSE=$FALSE
+# set verbosity only if not already set (allow calling program to do so)
+[ -z $verbosity ] && verbosity=3
 
 message_n "sourcing build_file: ${build_file} ..."
 [[ -f ${build_file} ]] || die "${build_file} does not exist"
 source ${build_file} || die "failed to source ${build_file}"
 right_status $?
 
-rm $logFile
+message_n "sourcing config_file: ${config_file} ..."
+[[ -f ${config_file} ]] || die "${config_file} does not exist"
+source ${config_file} || die "failed to source ${config_file}"
+right_status $?
+
+# over-ride the open_windows config on this one (for now)
+logFile="${log_dir%/}/xdotool_close_windows.log"
+
+# to do: rotate log file like in open_windows
+sudo rm $logFile
+
+#-----[ functions ]-------------------------------------------------
+
+kill_pids() {
+    # kill processes identified by ${filter}
+    pids=($(eval "ps -aef | ${filter} | awk '{print \$2}'"))
+    filter_name="$(echo ${filter} | awk '{print $2}')"
+    if [[ -z "${pids[@]}" ]] ; then
+         message "Found [${#pids[@]}] processes for filter [${filter_name}]"
+    else
+        elapsed=0
+        round=1
+        while [[ ! -z "${pids[@]}" && $elapsed -le $timeout ]] ; do
+             message "Found [${#pids[@]}] processes for filter [${filter_name}]..."
+            for x in ${pids[@]}
+            do
+                message "(${round}) killing process x: [${x}] for filter [${filter_name}]"
+                kill -9 $x 2>/dev/null
+                # To Do: get and handle result (exit/return status)
+            done # for
+            sleep $longWait
+            elapsed=$(( $elapsed + $longWait ))
+            round+=1
+            pids=($(eval "ps -aef | ${filter} | awk '{print \$2}'"))
+        done # while
+        x=""
+    fi # -z pids
+    return 0
+}
+
+close_windows() {
+    my_window=$(xdotool getactivewindow)
+    message "my_window: ${my_window}"
+    # identify all terminal windows (use --any but not --onlyvisible to get minimized, too)
+    window_list=()
+    window_list=($(xdotool search --any lxterminal 2>/dev/null))
+    window_list+=($(xdotool search --any Konsole))
+    window_list+=($(xdotool search --any xterm 2>/dev/null))
+    message "Current window list:"
+    echo ${window_list[@]} ; echo
+    message "Now closing all terminal windows except my_window [${my_window}] ..."
+    # close all these windows
+    for win in ${window_list[@]}
+    do
+        desktop=$(xdotool get_desktop_for_window $win 2>/dev/null)
+        message_n "Examining window [ $win ] on desktop [ $desktop ] ... "
+        if [[ $win -ne $my_window ]]
+        then
+            # use xprop to get the window's type and only close "normal" windows
+            # this is to avoid disrupting windowmanager/compositor (e.g. kwin) functionaliy
+            if xprop -id $win | grep -q "_NET_WM_WINDOW_TYPE_NORMAL" ; then
+                echo -e -n " (${BGon}Normal${Boff})"
+                xdotool windowclose $win 2>/dev/null && echo " closed" || \
+                    echo "tried, but failed to close"
+            else
+                echo -e " (${BMon}Special, ${BRon}NOT Normal${Boff} window, ${BYon}skipping${Boff})"
+            fi
+        else
+            echo -e " (${BYon}My${Boff} window, ${BYon}skipping${Boff})"
+        fi
+        sleep $sleepWait
+    done
+    return 0
+}
+
+#-----[ main script ]-----------------------------------------------
 
 exec 6>&1 2>/dev/null           # Link file descriptor #6 with stdout. Saves stdout.
 exec > $logFile  2>/dev/null    # stdout replaced with file.
@@ -28,55 +117,20 @@ exec > $logFile  2>/dev/null    # stdout replaced with file.
 # All output from commands in this block sent to file $logFile
 separator "${PN}-${BUILD}" "(closing)"
 message "Exterminating any rogue xdotool_xxx process..."
-pids=($(ps -aef | grep xdotool_ | grep -v 'color=auto' | grep -v $! | awk '{print $2}'))
-message "Found ${#pids[@]} xdotool_xxx processes..."
-for x in ${pids}
-do
-  message "killing process x=${x}"
-  kill -9 $x 2>/dev/null
-done
-x=""
-
-my_window=$(xdotool getactivewindow)
-message "my_window: ${my_window}"
 num_desktops=$(xdotool get_num_desktops)
 message "num_desktops: $num_desktops"
 
-window_list=()
-window_list=($(xdotool search --any lxterminal 2>/dev/null))
-window_list+=($(xdotool search --any Konsole))
-window_list+=($(xdotool search --any xterm 2>/dev/null))
-message "Current window list:"
-echo ${window_list[@]}
-echo
-message "Now closing all terminal windows except my_window [${my_window}] ..."
+# kill any existing xdotoo_xxx processes
+filter="grep 'xdotool_' | grep -v 'color=auto' | grep -v $!"
+kill_pids || die "failed to kill_pids for filter [${filter}]"
 
-
-for win in ${window_list[@]}
-do
-    desktop=$(xdotool get_desktop_for_window $win 2>/dev/null)
-    message_n "Examining window [ $win ] on desktop [ $desktop ] ... "
-    if [[ $win -ne $my_window ]]
-    then
-        xdotool windowclose $win 2>/dev/null && echo "closed" || \
-            echo "tried, but failed to close"
-    else
-        echo "my_window; skipping"
-    fi
-    sleep $sleepWait
-done
+# close all terminal windows except the control_window (that activated this program)
+close_windows || die "failed to close_windows"
 
 # now kill any residual ssh sessions
 message "Exterminating any rogue ssh processes ..."
-filter="grep -v 'ssh-agent' | grep -v 'sshd' | grep -v 'grep'"
-pids=($(eval "ps -aef | grep ssh | ${filter} | awk '{print \$2}'"))
-message "Found ${#pids[@]} ssh processes..."
-for x in ${pids}
-do
-  message "killing process x=${x}"
-  kill -9 $x 2>/dev/null
-done
-x=""
+filter="grep 'ssh' | grep -v 'ssh-agent' | grep -v 'sshd' | grep -v 'grep'"
+kill_pids || die "failed to kill_pids"
 
 # move the active window to desktop 0, if it isn't already there
 my_window=$(xdotool getactivewindow)
diff --git a/dev-util/xdotool_open_windows/xdotool_open_windows b/dev-util/xdotool_open_windows/xdotool_open_windows
--- a/dev-util/xdotool_open_windows/xdotool_open_windows
+++ b/dev-util/xdotool_open_windows/xdotool_open_windows
@@ -37,8 +37,12 @@ SCREEN_HEIGHT=$(echo $SCREEN_DIMENSIONS | cut -dx -f2)
 
 silent=">/dev/null 2>&1"  # append this to a command to silence it
 
-sleepWait=0.5      # default - set in .conf
-longWait=2         # default - set in .conf
+# customized timing and detailed output (increase for debugging)
+#sleepWait=0.5    # default - set in .conf
+sleepWait=0.15    # default - set in .conf
+#longWait=2       # default - set in .conf
+longWait=1.1      # default - set in .conf
+timeout=10        # seconds to wait while trying to close a window or identify a new one
 
 new_window_timeout=10 # seconds to wait while trying to identify the newly launched window
 
@@ -275,7 +279,6 @@ open_windows() {
 
     # use xdotool_sizemove_this_window (alias mw) l|L|r|R [<width>%] [<height>%]
     log_message_n "resizing control_window"
-#    mw "R" "$WINDOW_WIDTH" "$WINDOW_HEIGHT" ${silent}; result=$?
     eval "mw L $WINDOW_WIDTH $WINDOW_HEIGHT ${silent}"; result=$?
     if [ $result -eq 0 ] ; then
         right_status $TRUE
@@ -361,40 +364,43 @@ setup_terminal() {
     d_log_message "in ${FUNCNAME[0]} with arg(s) [$@]" 5
     local t="$1"  # terminal number
     ssh_target="${ssh_session_list[$t]}"
-    log_message "openning terminal and ssh to [${ssh_target}]"
-    # take a baseline for comparison so we can find the new window for certain
-    terminal_class="$(basename ${terminal_program})"
-    before=($(xdotool search --class "${terminal_class}"))
-    # launch a new terminal with an ssh session as needed
-    "${terminal_program}" -e ssh "${ssh_target}" &
-    sleep $longWait
-    # newterm=$(xdotool getactivewindow 2>/dev/null) ## <-- unreliable
-    newterm=$(poll_for_new_window)
-    if  [ ! -z "$newterm" ] ; then
-        xdotool set_window --name "$(hostname) $(basename ${terminal_program})_${i}.${t}" "${newterm}"
-        log_message "opened new terminal for ${ssh_target} on desktop [$i]"
-        # sizemove this windw
-        if [ $(($t % 2)) -eq 0 ] ; then
-            # even (Left)
-            log_message_n "resizing window [$t]"
-#            mw "L" "$WINDOW_WIDTH" "$WINDOW_HEIGHT" ${silent}; result=$?
-            eval "mw L $WINDOW_WIDTH $WINDOW_HEIGHT ${silent}"; result=$?
+    # if the ssh_target name begins "x_" we ignore it - it is intended to be blank (no window)
+    if [[ ! "${ssh_target}" == "x_"* ]] ; then
+        log_message "openning terminal and ssh to [${ssh_target}]"
+        # take a baseline for comparison so we can find the new window for certain
+        terminal_class="$(basename ${terminal_program})"
+        before=($(xdotool search --class "${terminal_class}"))
+        # launch a new terminal with an ssh session as needed
+        "${terminal_program}" -e ssh "${ssh_target}" &
+        sleep $longWait
+        # newterm=$(xdotool getactivewindow 2>/dev/null) ## <-- unreliable
+        newterm=$(poll_for_new_window)
+        if  [ ! -z "$newterm" ] ; then
+            xdotool set_window --name "$(hostname) $(basename ${terminal_program})_${i}.${t}" "${newterm}"
+            log_message "opened new terminal for ${ssh_target} on desktop [$i]"
+            # sizemove this windw
+            if [ $(($t % 2)) -eq 0 ] ; then
+                # even (Left)
+                log_message_n "resizing window [$t]"
+                eval "mw L $WINDOW_WIDTH $WINDOW_HEIGHT ${silent}"; result=$?
+            else
+                # odd (Right)
+                log_message_n "resizing window [$t]"
+                eval "mw R $WINDOW_WIDTH $WINDOW_HEIGHT ${silent}"; result=$?
+            fi # even/odd
+            if [ $result -eq 0 ] ; then
+                right_status $TRUE
+            else
+                log_E_message "failed to resize window [$t]"
+                right_status 1
+                return 1
+            fi # 0 result
         else
-            # odd (Right)
-            log_message_n "resizing window [$t]"
-#            mw "R" "$WINDOW_WIDTH" "$WINDOW_HEIGHT" ${silent}; result=$?
-            eval "mw R $WINDOW_WIDTH $WINDOW_HEIGHT ${silent}"; result=$?
-        fi # even/odd
-        if [ $result -eq 0 ] ; then
-            right_status $TRUE
-        else
-            log_E_message "failed to resize window [$t]"
-            right_status 1
-            return 1
-        fi # 0 result
+            log_E_message "failed to get new window ID within time limit"
+        fi # nonzero newterm
     else
-        log_E_message "failed to get new window ID within time limit"
-    fi # nonzero newterm
+        log_message "not openning a terminal for (blank) [${ssh_target}]"
+    fi # non x_ (blank) ssh_target
     return 0
 }
 
