joetoobuild-tools-0.0.16.tbz2 - update finalize-chroot-sys to not set TARGET_ARCH
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-build/joetoobuild-tools/finalize-chroot-sys b/dev-build/joetoobuild-tools/finalize-chroot-sys
--- a/dev-build/joetoobuild-tools/finalize-chroot-sys
+++ b/dev-build/joetoobuild-tools/finalize-chroot-sys
@@ -71,7 +71,7 @@ emerge_trail_opts=""
 ## set these static here for $PN; they would be set by validate_target() in crossbuild-tools
 export BOARD=generic_amd64
 export TARGET=x86_64-pc-linux-gnu
-export TARGET_ARCH=amd64
+#export TARGET_ARCH=amd64
 export QEMU_ARCH=x86_64
 #STAGE3_SELECTOR="stage3-amd64-openrc-[0-9]"   # go with hardened below and change to hardened desktop >
 #default_profile="default/linux/amd64/23.0"
@@ -277,24 +277,26 @@ get-check-config() {
     configvarlist+=" STAGE3_SELECTOR default_profile LLVM_TARGET"
 #    for x in ${configvarlist}; do varname="cb_${x}" ; eval $x=${!varname}; done
 # replace unsafe eval method
-    j_msg "-${notice}" -p -n "performing indirect variable assigments"
-    for x in ${configvarlist}; do
-        varname="cb_${x}"
-        # Use printf -v for safe, indirect assignment
-        # This assigns the value of ${!varname} to the variable named by $x
-        printf -v "$x" "%s" "${!varname}" || die "failed indirect variable assignment for $x"
-        j_msg "-${notice}" -mp -n " ."
-    done
+#    j_msg "-${notice}" -p -n "performing indirect variable assigments"
+#    for x in ${configvarlist}; do
+#        varname="cb_${x}"
+#        # Use printf -v for safe, indirect assignment
+#        # This assigns the value of ${!varname} to the variable named by $x
+#        printf -v "$x" "%s" "${!varname}" || die "failed indirect variable assignment for $x"
+#        j_msg "-${notice}" -mp -n " ."
+#    done
     right_status 0 "${notice}"
 
     j_msg "-${notice}" -p "${BYon}tentatively assigned these globals${Boff} --"
-    j_msg "-${notice}" -p "  ${LBon}BOARD ............: ${Mon}${BOARD}${Boff}"
-    j_msg "-${notice}" -p "  ${LBon}TARGET ...........: ${Mon}${TARGET}${Boff}"
-    j_msg "-${notice}" -p "  ${LBon}TARGET_ARCH ......: ${Mon}${TARGET_ARCH}${Boff}"
-    j_msg "-${notice}" -p "  ${LBon}QEMU_ARCH ........: ${Mon}${QEMU_ARCH}${Boff}"
-    j_msg "-${notice}" -p "  ${LBon}STAGE3_SELECTOR ..: ${Mon}${STAGE3_SELECTOR}${Boff}"
-    j_msg "-${notice}" -p "  ${LBon}default_profile ..: ${Mon}${default_profile}${Boff}"
-    j_msg "-${notice}" -p "  ${LBon}LLVM_TARGET ......: ${Mon}${LLVM_TARGET}${Boff}"
+    j_msg "-${notice}" -p "  ${BCon}BOARD ............: ${Mon}${BOARD}${Boff}"
+    j_msg "-${notice}" -p "  ${BCon}TARGET ...........: ${Mon}${TARGET}${Boff}"
+    j_msg "-${notice}" -p "  ${BCon}TARGET_ARCH ......: ${Mon}${TARGET_ARCH}${Boff}"
+    j_msg "-${notice}" -p "  ${BCon}QEMU_ARCH ........: ${Mon}${QEMU_ARCH}${Boff}"
+    j_msg "-${notice}" -p "  ${BCon}STAGE3_SELECTOR ..: ${Mon}${STAGE3_SELECTOR}${Boff}"
+    j_msg "-${notice}" -p "  ${BCon}default_profile ..: ${Mon}${default_profile}${Boff}"
+    j_msg "-${notice}" -p "  ${BCon}LLVM_TARGET ......: ${Mon}${LLVM_TARGET}${Boff}"
+    j_msg "-${notice}" -mp ""
+    j_msg "-${notice}" -p "  ${BYon}To Do ............: ${BRon}Refactor this stuff!${Boff}"
 
     return 0
 }
