fix sourcing of BUILD, BPN
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-build/joetoobuild-tools/finalize-chroot-joetoo b/dev-build/joetoobuild-tools/finalize-chroot-joetoo
--- a/dev-build/joetoobuild-tools/finalize-chroot-joetoo
+++ b/dev-build/joetoobuild-tools/finalize-chroot-joetoo
@@ -26,11 +26,11 @@ PN="$(basename $0)" || die "failed to assign PN"
 d_right_status $TRUE 3
 
 d_message_n "sourcing BUILD ..." 3
-source /etc/${PN}/BUILD || die "failed to source BUILD"
+source /etc/joetoobuild-tools/BUILD || die "failed to source BUILD"
 d_right_status $TRUE 3
 
 d_message_n "sourcing BPN ..." 3
-source /etc/${PN}/BPN || die "failed to source BPN"
+source /etc/joetoobuild-tools/BPN || die "failed to source BPN"
 d_right_status $TRUE 3
 
 d_message_n "sourcing script_header_joetoo_extended ..." 3
@@ -132,9 +132,9 @@ initialize_variables() {
     # set default values
     FLAGGED=$FALSE
     d_message_n "sourcing BUILD ..." 2
-    source /etc/${PN}/BUILD ; result=$?; d_right_status $result 2 ; [ $result -ne 0 ] && FLAGGED=$TRUE
+    source /etc/joetoobuild-tools/BUILD ; result=$?; d_right_status $result 2 ; [ $result -ne 0 ] && FLAGGED=$TRUE
     d_message_n "sourcing BPN ..." 2
-    source /etc/${PN}/BPN ; result=$?; d_right_status $result 2 ; [ $result -ne 0 ] && FLAGGED=$TRUE
+    source /etc/joetoobuild-tools/BPN ; result=$?; d_right_status $result 2 ; [ $result -ne 0 ] && FLAGGED=$TRUE
 
     d_message_n "setting default starting_step = 0" 2
     export starting_step=0 ; result=$?; d_right_status $result 2 ; [ $result -ne 0 ] && FLAGGED=$TRUE
@@ -170,7 +170,7 @@ initialize_variables() {
 
 display_configuration()  {
     # will pick up PN, BUILD, varlist from the environment of whatever script sources cb-common-functions
-    separator "configuration" "${PN}-${BUILD}"
+    separator "${PN}-${BUILD}" "(configuration)"
     longest=$(get_longest ${varlist})
     display_vars ${longest} ${varlist}
     return 0
@@ -601,7 +601,7 @@ display-next-steps() {
 
 #-----[ main script ]-------------------------------------------------------------------
 checkroot
-separator "(starting)" "${PN}"
+separator "${PN}-${BUILD}" "(starting)"
 
 initialize_variables     # set defaults
 
@@ -639,4 +639,4 @@ right_status $result
 message "chroot firstlogin configuration completed successfully" || \
 E_message "chroot firstlogin configuration completed with errors; check red flags in output above"
 echo
-separator "(complete)" "${PN}"
+separator "${PN}-${BUILD}" "(complete)"
