joetoobuild-tools-0.0.18.tbz2 - patch jb-mksys ; update finalize-chroot-sys to validate resolv.conf; update content_for_mkenv_generic_amd64
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-build/joetoobuild-tools/finalize-chroot-sys b/dev-build/joetoobuild-tools/finalize-chroot-sys
--- a/dev-build/joetoobuild-tools/finalize-chroot-sys
+++ b/dev-build/joetoobuild-tools/finalize-chroot-sys
@@ -416,7 +416,7 @@ emerge-me() {
 emerge-git-eselect-repo() {
     local result=0
     # format: emerge-me "quoted payload" "quoted extra args"
-    emerge-me "dev-vcs/git eselect-repository" "-1"; result=$?
+    emerge-me "dev-vcs/git ifcoeselect-repository" "-1"; result=$?
 #    # use an array to construct the emerge command
 #    local -a emerge_command=( "${chroot_emerge}" -av1 )
 #    # before sync-repo joetoo, we need git (and eselect-repo for form)
@@ -1298,6 +1298,29 @@ edit-package-accept-keywords() {
     return $?
 }
 
+validate-resolv-conf() {
+    local result=0
+    # to-do make this a choice - static or dynamic; for now set up for dynamic
+    j_msg "-${notice}" -p -n "maybe creating /run/resolvconf ..."
+    mkdir -p "/run/resolvconf"
+    handle_result $? '' '' "$notice" || return 1
+    j_msg "-${notice}" -p -n "maybe copying content to /run/resolvconf/resolv.conf ..."
+    [ -f "/run/resolvconf/resolv.conf" ]
+    handle_result $? "exists" "creating" "$notice"
+    if [ ! $? -eq 0 ]; then
+        cat << 'EOF' > /run/resolvconf/resolv.conf
+# Generated by joetoobuild-tools based on what resolvconf would do
+search brendler
+domain brendler
+nameserver 192.168.62.17
+nameserver fd62:6262:6262::17
+EOF
+        result=$?
+        j_msg "-${notice}" -p -n "done copying content; result:"
+        handle_result $result "" "" "$notice" || result=1
+    fi
+    return $result
+}
 
 #-----[ main script ]-------------------------------------------------------------------
 checkroot
@@ -1317,6 +1340,9 @@ validate_root_file "${status_file}"
 # get-target will need to run "portageq envvar CHOST" which needs a the
 # chroots own repo to be syncd first, and that needs chroot_emerge variable defined
 build-chroot_emerge-command || die "failed to build-chroot_emerge-command"
+
+# validate resolv.conf
+validate-resolv-conf || die "failed to validate-resolv-conf"
 
 # get dev-vcs/git and eselect-repository so sync-type = git will work for next step
 get-git-and-eselect-repository || die "failed to get-git-and-eselect-repository"
