mkinitramfs-7.1.9999.tbz2

diff --git a/mkinitramfs.bak/mkinitramfs b/mkinitramfs.bak/mkinitramfs
--- a/mkinitramfs.bak/mkinitramfs
+++ b/mkinitramfs.bak/mkinitramfs
@@ -12,8 +12,14 @@
 # output for the user.  This script will not have access to the BUILD
 # value until after make_sources is run; here it is used only in the
 # final visual output
+
+#-----[ initialize variables ]-------------------------------------------------
+echo -n "Sourcing globals... "
 source GLOBALS
+[[ $? ]] && echo "ok" || ( echo "Error: sourcing globals failed. Possibly no kernel sources at /usr/src/linux?" && exit 1 )
+
 source ${SCRIPT_HEADER_DIR}/script_header_brendlefly
+
 old_dir=$(pwd)
 
 # set defaults
@@ -31,6 +37,8 @@ then
   pre_existing=$(set $(find $(dirname $SOURCES_DIR) -maxdepth 1 -mindepth 1 -type d -iname 'initramfs*' -print); echo $#)
   mv ${SOURCES_DIR} ${SOURCES_DIR}.bak.$((${pre_existing} - 1))
 fi
+
+#-----[ main script ]----------------------------------------------------------
 
 # (re-)create and (re-)load the ${SOURCES_DIR}
 ${MAKE_DIR}/make_sources.sh
