joetoo-platform-meta-0.1.18.tbz2 - bugfix make.conf
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/joetoo-base/joetoo-platform-meta/tools/assemble-make-conf b/joetoo-base/joetoo-platform-meta/tools/assemble-make-conf
--- a/joetoo-base/joetoo-platform-meta/tools/assemble-make-conf
+++ b/joetoo-base/joetoo-platform-meta/tools/assemble-make-conf
@@ -6,6 +6,8 @@
 script_header_installed_dir=/usr/sbin   # this is where it should be installed
 source "${script_header_installed_dir%/}/script_header_joetoo"
 
+#user="joe"  # supplied by config file
+
 package_source_dir=/home/joe/myUtilities/joetoo-base/joetoo-platform-meta
 tool_dir="${package_source_dir%/}/tools"
 
@@ -62,7 +64,7 @@ initialize_variables() {
 
     FLAGGED=$FALSE
     # assign initial values
-    j_msg -${notice} -p -n "Re-assigning PN = $(basename $0) ..."
+    j_msg -${notice} -p -n "Re-assigning PN = \$(basename $0) ..."
     PN=${0##*/} ; result=$? ; right_status $result ${notice}
     [ ! $result -eq 0 ] && FLAGGED=$TRUE
 
@@ -577,9 +579,9 @@ post-file() {
         if [ -d "${z}" ] ; then
             j_msg -${notice} -mp -n " (dir ${BGon}exists${Boff})"
         else
-            mkdir -p "${z}" ; result=$?
+            mkdir -p "${z}" && chown -f -R "${user}:${user}" "${z}"; result=$?
             if [ "$result" -eq 0 ] ; then
-                j_msg -${notice} -mp -n " (dir ${BMon}created${Boff})"
+                j_msg -${notice} -mp -n " (dir ${BMon}created for ${user}${Boff})"
             else
                 die "failed to mkdir -p ${z}"
            fi  # mkdir result
@@ -591,6 +593,13 @@ post-file() {
     right_status $? ${notice} ; return $?
 }
 
+set-ownership() {
+    j_msg -${debug} -p "inside ${FUNCNAME[0]}"
+    j_msg -${notice} -p -n "setting ownership of \${OUT_FILE}"
+    chown -f "${user}:${user}"  "${OUT_FILE}"
+    handle_result $? "" "" ${notice}
+    return $?
+}
 
 #-----[ main script ]----------------------------------------------------
 checkroot
@@ -657,6 +666,7 @@ add-USE || die "failed to add-USE"
 add-GRUB_PLATFORMS || die "failed to add-GRUB_PLATFORMS"
 add-MIRRORS || die "failed to add-MIRRORS"
 post-file || die "failed to post-file"
+set-ownership || die "failed to set-ownership"
 
 j_msg -${notice} -p "${PN} Complete"
 j_msg -${notice} -mp ""   # severity-aware newline
