mkinitramfs-10.0.4.tbz2 - refactored for j_msg and new script_header_joetoo
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-util/mkinitramfs/ckinitramfs b/dev-util/mkinitramfs/ckinitramfs
--- a/dev-util/mkinitramfs/ckinitramfs
+++ b/dev-util/mkinitramfs/ckinitramfs
@@ -6,45 +6,50 @@
 
 source /usr/sbin/script_header_joetoo
 
+mk_dir=/usr/src/mkinitramfs
+
 #-----[ variables ]------------------------------------------
 # see configure()
 
 # set default verbosity if not set externally
-[ -z "$verbosity" ] && verbosity = 2
+[ -z "$verbosity" ] && verbosity=${notice}
 
 #-----[ functions ]------------------------------------------
 
 usage() {
-  error_msg "usage: ckinitramfs [-][v|q]"
-  notice_msg   "  v - increase verbosity"
-  notice_msg   "  q - decrease verbosity"
+  j_msg -${err} "usage: ckinitramfs [-][v|q]"
+  j_msg -${notice} -p   "  v - increase verbosity"
+  j_msg -${notice} -p   "  q - decrease verbosity"
   exit 1
 }
 
 configure() {
-  notice_msg "configuring ..."
-  SOURCES_DIR="/usr/src/initramfs"
-  MAKE_DIR="/usr/src/mkinitramfs"
+  j_msg -${notice} -p "configuring ..."
+  j_msg -${notice} -p -n "sourcing GLOBALS ..."
+  source "${mk_dir}/GLOBALS"; right_status $? ${notice}
+
+#  SOURCES_DIR="/usr/src/initramfs"
+#  MAKE_DIR="/usr/src/mkinitramfs"
 
   # set ckinitramfs BUILD; not the kernel's BUILD used by mkinitramfs for init
   # PKG_PVR is populated by make_sources.sh in /usr/src/mkinitramfs
   # it is NOT found in development directory
   BUILD="$(cat ${MAKE_DIR%/}/PKG_PVR)"
-  PN=$(basename "$0")
-  debug_msg "MAKE_DIR: $MAKE_DIR"
-  debug_msg "BUILD: $BUILD"
-  debug_msg "PN: $PN"
+  PN=${0##*/}   # like =$(basename "$0") but w/o subshell and function call
+  j_msg -${debug} -p "MAKE_DIR: $MAKE_DIR"
+  j_msg -${debug} -p "PN: $PN"
+  j_msg -${debug} -p "BUILD: $BUILD"
   # source the list of executables used by the init script (from init_structure)
   executables=()
-  notice_msg_n "sourcing ${MAKE_DIR%/}/init_structure ..."
-  source "${MAKE_DIR%/}/init_structure"; right_status $?
+  j_msg -${notice} -p -n "sourcing ${MAKE_DIR%/}/init_structure ..."
+  source "${MAKE_DIR%/}/init_structure"; right_status $? ${notice}
   # source header for load_ list_ dump_executables
-  notice_msg_n "sourcing ${MAKE_DIR%/}/common_bash_functions_header ..."
-  source "${MAKE_DIR%/}/common_bash_functions_header"; right_status $?
+  j_msg -${notice} -p -n "sourcing ${MAKE_DIR%/}/common_bash_functions_header ..."
+  source "${MAKE_DIR%/}/common_bash_functions_header"; right_status $? ${notice}
 
   # source header for display_config, echo_long_string
-  notice_msg_n "sourcing ${MAKE_DIR%/}/common_ash_functions_header ..."
-  source "${MAKE_DIR%/}/common_ash_functions_header"; right_status $?
+  j_msg -${notice} -p -n "sourcing ${MAKE_DIR%/}/common_ash_functions_header ..."
+  source "${MAKE_DIR%/}/common_ash_functions_header"; right_status $? ${notice}
   load_executables
 
   # initialize verbosity by sourcing mkinitramfs.conf
@@ -53,11 +58,11 @@ configure() {
   elif [[ -e "/etc/mkinitramfs/mkinitramfs.conf" ]] ; then
     config_file="/etc/mkinitramfs/mkinitramfs.conf"
   else
-    error_msg "${BRon}Error: no mkinitramfs.conf found"
+    j_msg -${err} "${BRon}Error: no mkinitramfs.conf found"
     exit
   fi
-  notice_msg_n "sourcing config file ${config_file} ..."
-  source "${config_file}"; right_status $?
+  j_msg -${notice} -p -n "sourcing config file ${config_file} ..."
+  source "${config_file}"; right_status $? ${notice}
 
   # convert executables array into string variable we can display
   cki_executables=$(list_executables)
@@ -65,11 +70,11 @@ configure() {
 }
 
 process_cmdline() {  # tiny alternative to using the whole cli in script_header_joetoo
-  notice_msg "processsing commandline ..."
+  j_msg -${notice} -p "processsing commandline ..."
   # this is a macro for use by external helper _pc_action_verbosity (in script_header_joetoo)
   _pc_adjust_verbosity="verbosity=\$(( verbosity \${_pc_operator} 1 ))";
   if [ $# -gt 1 ] ; then
-    error_msg "invalid arguments: $@"
+    j_msg -${err} "invalid arguments: $@"
     usage
   elif [ $# -eq 1 ] ; then
     arg="$1"
@@ -79,7 +84,7 @@ process_cmdline() {  # tiny alternative to using the whole cli in script_header_
         "-"* ) echo_msg "ignoring \"-\"";;
         "v"* ) _pc_operator="+"; _pc_action_verbosity ;;
         "q"* ) _pc_operator="-"; _pc_action_verbosity ;;
-         *  ) error_msg "invalid argument [ $arg ]"; usage;;
+         *  ) j_msg -${err} "invalid argument [ $arg ]"; usage;;
       esac
       arg="${arg:1}"   # drop first char (left shift)
     done
@@ -88,41 +93,41 @@ process_cmdline() {  # tiny alternative to using the whole cli in script_header_
 
 check_executables() {
   local _ce_w _ce_x _ce_y _ce_z _ce_find=()
-  notice_msg "checking initramfs executables ..."
+  j_msg -${notice} -p "checking initramfs executables ..."
   # compare current system executables (identified by the which command) with those installed in intramfs
   for _ce_w in "${executables[@]}"
   do
     # this will evaluate null (false) for files; and non-null (true) for links
     if [[ -L  $_ce_w ]] ; then
       # this is a link; skip it
-      info_msg "$_ce_w is a symbolic link; skipping ..."
+      j_msg -${info} -m "$_ce_w is a symbolic link; skipping ..."
       continue
     else
-      info_msg "$_ce_w is a file; checking ..."
-      debug_msg "_ce_w: $_ce_w"
+      j_msg -${info} -m "$_ce_w is a file; checking ..."
+      j_msg -${debug} -p "_ce_w: $_ce_w"
       _ce_x="$(basename $_ce_w)"
-      debug_msg "  _ce_x = basename _ce_w: $_ce_x"
+      j_msg -${debug} -p "  _ce_x = basename _ce_w: $_ce_x"
       # find the one running on the host system
       _ce_y="$(which $_ce_w)"
-      debug_msg "  _ce_y = which _ce_w: $_ce_y"
-      [ ! "$QUIET"] && d_do 'verbosity=7 _ce_ysize=$(stat -c %s "$_ce_y");  verbosigy=7 debug_msg "  _ce_y size: $_ce_ysize"' "$debug"
+      j_msg -${debug} -p "  _ce_y = which _ce_w: $_ce_y"
+      [ ! "$QUIET"] && d_do 'verbosity=7 _ce_ysize=$(stat -c %s "$_ce_y");  verbosity=7 j_msg -${debug} -p "  _ce_y size: $_ce_ysize"' "$debug"
       # find the one in a *bin folder in initramfs
       # some, e.g. fsck might be links on initramfs - skip those
       readarray -d '' _ce_find < <(find ${SOURCES_DIR%/}/ -wholename '*bin*'  -and -name "$_ce_x" -print0)
       if [[ ${#_ce_find[@]} -eq 0 ]]; then
-        error_msg "Component: ${LBon}$_ce_x ${BRon}NOT FOUND in initramfs"
+        j_msg -${err} "Component: ${LBon}$_ce_x ${BRon}NOT FOUND in initramfs"
         continue
       fi
       for _ce_z in "${_ce_find[@]}"; do  # this loop is just debugging output
         if [[ -L  $_ce_z ]] ; then
-          info_msg "$_ce_z is a symbolic link in initramfs; skipping ..."
+          j_msg -${info} -m "$_ce_z is a symbolic link in initramfs; skipping ..."
           continue
         else
-          debug_msg "  _ce_z = find ${SOURCES_DIR%/}/ -type f -name $_ce_x | grep bin: $_ce_z"
-          [ ! "$QUIET"] && d_do 'verbosity=7 _ce_zsize=$(stat -c %s "$_ce_z"); verbosity=7 debug_msg "  _ce_z size: $_ce_zsize"' "$debug"
+          j_msg -${debug} -p "  _ce_z = find ${SOURCES_DIR%/}/ -type f -name $_ce_x | grep bin: $_ce_z"
+          [ ! "$QUIET"] && d_do 'verbosity=7 _ce_zsize=$(stat -c %s "$_ce_z"); verbosity=7 j_msg -${debug} -p "  _ce_z size: $_ce_zsize"' "$debug"
           #--- this is the main output of this program ---
-          debug_msg "  abount to run cmp"
-          notice_msg_n "Component: ${LBon}$_ce_x"
+          j_msg -${debug} -p "  abount to run cmp"
+          j_msg -${notice} -p -n "Component: ${LBon}$_ce_x"
           cmp --silent $_ce_z $_ce_y
           handle_result $? "has not changed" "${BRon}has changed --> ${BMon}Rebuild your initramfs${Boff}"
         fi
diff --git a/dev-util/mkinitramfs/init b/dev-util/mkinitramfs/init
--- a/dev-util/mkinitramfs/init
+++ b/dev-util/mkinitramfs/init
@@ -20,13 +20,13 @@ printf '%s' "sourcing /script_header_joetoo ..."
 . "${script_header_installed_path_fixed%/}/script_header_joetoo"
 printf '%s' "Checking for header commands (toc, run_sequence) to confirm sourcing"
 if command -v toc >/dev/null 2>&1 && command -v run_sequence >/dev/null 2>&1 ; then
-handle_result $? ; else printf '%s\n' "Failed; header not sourced; cannot continue"; exit 1; fi
+handle_result $? '' '' ${notice}; else printf '%s\n' "Failed; header not sourced; cannot continue"; exit 1; fi
 sleep .5
 
 # source the BUILD number generated by the make_sources.sh script,
-notice_msg "sourcing /BUILD ..."
+j_msg -${notice} -p "sourcing /BUILD ..."
 . "${init_ROOT%/}/BUILD"
-handle_result $? || die "failed to source /BUILD"
+handle_result $? '' '' ${notice} || die "failed to source /BUILD"
 sleep .5
 
 PN="initramfs: $(basename "$0")"
@@ -62,15 +62,15 @@ initialize_vars
 #----[ reassign variables with values from config files ]----------------------------------
 
 # source variables assigned in init.conf. Note cmdline may override root=, usr=, verbosity=
-notice_msg "sourcing /init.conf ..."
+j_msg -${notice} -p "sourcing /init.conf ..."
 . "${init_ROOT%/}/init.conf"
-right_status $? || die "failed to source /init.conf"
+right_status $? ${notice} || die "failed to source /init.conf"
 sleep .5
 [ ! -z "${init_root_volume}" ] && root_volume="${init_root_volume}"
 [ ! -z "${init_usr_volume}" ]  && usr_volume="${init_usr_volume}"
 ! isint "${init_wait}" && init_wait=1  # hard code default 1 second
 ! isint "${init_mdev_wait}" && init_wait=3  # hard code default 3 seconds
-echo_msg   # newline
+j_msg -${notice} -mp ""  # severity-aware newline
 
 #----[ display separator to mark start of script ]-----------------------------------------------
 separator "${PN}-${BUILD}" "(Running /init)"
@@ -78,17 +78,17 @@ separator "${PN}-${BUILD}" "(Running /init)"
 #----[ source functions local to initramfs ]-----------------------------------------------------
 
 ### ***** for testing source this second ***** ---
-notice_msg "sourcing /testing_functions_header ..."
+j_msg -${notice} -p "sourcing /testing_functions_header ..."
 . "${init_ROOT%/}/testing_functions_header"
-right_status $? || die "failed to source /testing_functions_header"
+right_status $? ${notice} || die "failed to source /testing_functions_header"
 
 ### ***** for testing -- change oder of these two sourcing blocks ***** ---
 # note: in the real init script, we MUST source validated_functions_header second, in order to
 #   override testing-only-modified functions also present in testing_functions_header
 #   (in the testing init script (ash.temp) it is the other way around)
-notice_msg "sourcing /validated_functions_header ..."
+j_msg -${notice} -p "sourcing /validated_functions_header ..."
 . "${init_ROOT%/}/validated_functions_header"
-right_status $? || die "failed to source /validated_functions_header"
+right_status $? ${notice} || die "failed to source /validated_functions_header"
 
 # construct a wrappable string to represent PATH (translate : to ' ')
 PATH_str=$(printf '%s' "$PATH" | tr ':' ' ')
@@ -113,7 +113,7 @@ varlist="
 #usr_fs \
 #CMDLINE \
 # PATH -- display, don't initialize
-notice_msg "Initial Configuration follows ..."
+j_msg -${notice} -p "Initial Configuration follows ..."
 show_config
 
 #----[ Define functions local to initramfs ]-----------------------------------------------------
@@ -155,17 +155,17 @@ mini_udev() {
     mu_ret=0
 
     # the kernel needs these virtual file systems to report hardware status
-    notice_msg_n "mounting /proc"
+    j_msg -${notice} -p -n "mounting /proc"
     mount -t proc proc /proc
-    right_status $? || die "failed to mount /proc"
+    right_status $? ${notice} || die "failed to mount /proc"
 
-    notice_msg_n "mounting devtmpfs"
+    j_msg -${notice} -p -n "mounting devtmpfs"
     mount -t devtmpfs none /dev
-    right_status $? || die "failed to mount devtmpfs"
+    right_status $? ${notice} || die "failed to mount devtmpfs"
 
-    notice_msg_n "mounting sysfs"
+    j_msg -${notice} -p -n "mounting sysfs"
     mount -t sysfs sysfs /sys
-    right_status $? || die "failed to mount sysfs"
+    right_status $? ${notice} || die "failed to mount sysfs"
 
     # with mounts above in place, immediately instruct kernel to execute mdev
     #   whenever a device is added or removed --
@@ -177,24 +177,24 @@ mini_udev() {
     # kernel.hotplug has evidently been deprecated for a while -- if keeping the code, write to gracefully
     # move on to other options (and not hard fail) if id doesn't return a clean exit status
     #
-    notice_msg "checking if hotplug is supported"
+    j_msg -${notice} -p "checking if hotplug is supported"
     if [ -w /proc/sys/kernel/hotplug ]; then
       echo "$(which mdev)" > /proc/sys/kernel/hotplug
-      handle_result $? "" "" || mu_ret=1
+      handle_result $? "" "" ${notice} || mu_ret=1
     else
-      notice_msg "kernel.hotplug not available; relying on netlink uevents"
+      j_msg -${notice} -p "kernel.hotplug not available; relying on netlink uevents"
     fi
 
     # seed /dev/ with all the device nodes that were created --
     #   mdev -s is called a "coldplug" scan (handles devices discovered via past events),
     #   whereas the "kernel.hotplug" line above is instructions for future events
-    notice_msg "starting coldplug (mdev -s)"
+    j_msg -${notice} -p "starting coldplug (mdev -s)"
     mdev -s ; _mu_result=$?
-    notice_msg_n "result:"; handle_result $_mu_result "" "" || mu_ret=2
+    j_msg -${notice} -p -n "result:"; handle_result $_mu_result "" "" ${notice} || mu_ret=2
 
     # I used to just pause so kernel could finish identifying devices
     echo_msg  # newline
-    notice_msg "${BYon}NOTE: ${BRon}if using removable keying device, ensure it is inserted and active...${Boff}"
+    j_msg -${notice} -p "${BYon}NOTE: ${BRon}if using removable keying device, ensure it is inserted and active...${Boff}"
     # sh_countdown $(( ${init_wait} * 3 ))
     # instead of sleeping for "magic" amount of time, use a
     # system-agnostic wait for block device population to settle down
@@ -217,19 +217,19 @@ mini_udev() {
     #   (we will do that later)
 
     # secondary mounts occur after main dev population
-    notice_msg_n "looking for /dev/pts"
+    j_msg -${notice} -p -n "looking for /dev/pts"
     [ -d /dev/pts ]; _mu_result=$?
     if [ ! "$_mu_result" -eq 0 ]; then
         notice_echo_msg " (${BYon}not found${Boff})"
-        notice_msg_n "making /dev/pts"
+        j_msg -${notice} -p -n "making /dev/pts"
         mkdir /dev/pts
-        handle_result $? "created" "failed" || die "failed to mkdir /dev/pts"
+        handle_result $? "created" "failed" ${notice} || die "failed to mkdir /dev/pts"
     else
         notice_echo_msg " (${BGon}found${Boff})"
     fi
-    notice_msg_n "mounting /dev/pts"
+    j_msg -${notice} -p -n "mounting /dev/pts"
     mount -t devpts devpts /dev/pts
-    handle_result $? "mounted" "failed" || die "failed to mount devpts"
+    handle_result $? "mounted" "failed" ${notice} || die "failed to mount devpts"
 
     unset -v _mu_min_count _mu_last_count _mu_curr_count _mu_retry _mu_max_retry _mu_result
     return $mu_ret
@@ -238,17 +238,17 @@ mini_udev() {
 #---[ Main script ]----------------------------------------------------------------------------------------
 
 # wait for normal trailing kernel output
-#notice_msg "Waiting for normal trailing kernel output ..."
+#j_msg -${notice} -p "Waiting for normal trailing kernel output ..."
 #sh_countdown $((${init_wait} * 5))
 # above should no longer be needed, with agnositc wait in mini_udev function
 
 # start mini-udev (mdev) and wait long enough for devices to be recognized
-notice_msg "Starting mini udev ..."
+j_msg -${notice} -p "Starting mini udev ..."
 ### ***** for testing comment out the line below ***** ---
 mini_udev
 result=$?
-notice_msg_n "mini_udev result: "
-handle_result "$result" "complete" "mdev failed with exit status [$result]" || die "mini_udev failed"
+j_msg -${notice} -p -n "mini_udev result: "
+handle_result "$result" "complete" "mdev failed with exit status [$result]" ${notice} || die "mini_udev failed"
 
 # now converting this dumb wait to a targeted wait (if needed) when getting keying dev
 #&& sh_countdown $(($init_mdev_wait))
@@ -264,12 +264,12 @@ else
     CMDLINE=""     # Fallback or error for non-Linux systems (BSD, macOS, etc.)
 fi
 
-notice_msg "Calling process_cmdline"
+j_msg -${notice} -p "Calling process_cmdline"
 process_cmdline ; result=$?
-notice_msg_n "Done calling process_cmdline; result:"
-handle_result $result "assigned CMDLINE below" "" || die "failed to assign CMDLINE"
-notice_msg_n "${BWon}CMDLINE:${Boff} ${CMDLINE}"   # can smart-wrap if long
-notice_echo_msg   # newline
+j_msg -${notice} -p -n "Done calling process_cmdline; result:"
+handle_result $result "assigned CMDLINE below" "" ${notice} || die "failed to assign CMDLINE"
+j_msg -${notice} -p -n "${BWon}CMDLINE:${Boff} ${CMDLINE}"   # can smart-wrap if long
+j_msg -${notice} -mp ""  # severity-aware newline
 
 # if init.conf indicates there is a non-zero-lenght keyfile name to be looked for on a non-empty list of
 # devices, then see if we can select one that will work, otherwise use passphrase method
@@ -278,32 +278,32 @@ notice_echo_msg   # newline
 
 # translate from init.conf to script_header_joetoo luks management suite
 crypt_keydev_list="$init_passdevice_list"
-notice_msg "Translated init.conf init_passdevice_list -> crypt_keydev_list: $crypt_keydev_list"
+j_msg -${notice} -p "Translated init.conf init_passdevice_list -> crypt_keydev_list: $crypt_keydev_list"
 crypt_keydev_mountpoint="$init_passdevice_mount_point"
-notice_msg "Translated init.conf init_passdevice_mount_point -> crypt_keydev_mountpoint: $crypt_keydev_mountpoint"
+j_msg -${notice} -p "Translated init.conf init_passdevice_mount_point -> crypt_keydev_mountpoint: $crypt_keydev_mountpoint"
 crypt_keyfile="$init_keyfile"
-notice_msg "Translated init.conf init_keyfile -> crypt_keyfile: $crypt_keyfile"
+j_msg -${notice} -p "Translated init.conf init_keyfile -> crypt_keyfile: $crypt_keyfile"
 
 luks_partition_device_list=$( blkid | grep -i luks | cut -d':' -f1 )
 ### ***** substitute below for testing only ***** --- ***** ALSO CHANGE HERE in init not init.test for qemu test ***** ---
 #luks_partition_device_list=$(blkid | grep -i luks | grep 'UUID="b3c2b95f-1477-4433-b653-310e03dbffc2"' |cut -d':' -f1 )
 
-notice_msg "Calling unlock_devices $luks_partition_device_list"
+j_msg -${notice} -p "Calling unlock_devices $luks_partition_device_list"
 unlock_luks_devices $luks_partition_device_list ; result=$?
-notice_msg_n "Done calling unlock_devices; result:"
-handle_result $result "complete" "failed" || die "failed to unlock_devices"
+j_msg -${notice} -p -n "Done calling unlock_devices; result:"
+handle_result $result "complete" "failed" ${notice} || die "failed to unlock_devices"
 
 # done with all luks devices; ok to un-mount keying device now
 if [ -b "${init_passdevice_mount_point}" ]; then
-    notice_msg_n "Un-mounting keying device (no longre needed) ..."
+    j_msg -${notice} -p -n "Un-mounting keying device (no longre needed) ..."
     umount "${init_passdevice_mount_point}" 2>/dev/null
-    handle_result $? "unmounted" "failed" || warn_msg "Warning: keying passdevice is still mounted"
+    handle_result $? "unmounted" "failed" ${notice} || j_msg -${warn} "Warning: keying passdevice is still mounted"
 fi
 
 # make lvm logical volumes available
-notice_msg "running vgscan"
+j_msg -${notice} -p "running vgscan"
 vgscan
-notice_msg "running vgchange -a y"
+j_msg -${notice} -p "running vgchange -a y"
 vgchange -a y
 
 # assign root and usr volume names (if not already done)
@@ -312,7 +312,7 @@ vgchange -a y
 #  and create the rest of the /dev/ structure needed)
 separator "${PN}-${BUILD}" "(assign/validate root, usr vols)"
 TIMEOUT=20 # Max wait of 10 seconds total (20 * 0.5s checks)
-notice_msg "Trying to confirm lvm has started and assign root volume"
+j_msg -${notice} -p "Trying to confirm lvm has started and assign root volume"
 while [ "$TIMEOUT" -gt 0 ]; do
     # Try to assign the volume name - redirect output for cleaner waiting dots
     if assign_volume "root_volume" ; then
@@ -323,27 +323,27 @@ while [ "$TIMEOUT" -gt 0 ]; do
     TIMEOUT=$((TIMEOUT - 1))
 done
 # check if it completed or timed out
-notice_msg_n "checking status"
+j_msg -${notice} -p -n "checking status"
 [ -b "$root_volume" ]
-handle_result $? "complete. root: $root_volume" "failed" || \
+handle_result $? "complete. root: $root_volume" "failed" ${notice} || \
     die "timed out waiting for LVM root_volume [$root_volume]; cannot proceed"
-notice_msg "Assigning usr volume"
+j_msg -${notice} -p "Assigning usr volume"
 assign_volume "usr_volume"
-notice_msg_n "checking status"
+j_msg -${notice} -p -n "checking status"
 [ -b "$usr_volume" ]
-handle_result $? "complete. usr: $usr_volume" "failed" || \
+handle_result $? "complete. usr: $usr_volume" "failed" ${notice} || \
     warn_msg "Failed to assign usr volume. Proceeding without it"
 
 # validate root and usr device and assign fs
 #  cannot do this until after the volume is unlocked and the volume is assigned
 #  need to pass string name arg so function can make fs assignment
-notice_msg "Calling validate_volume_and_assign_fs for root_volume"
+j_msg -${notice} -p "Calling validate_volume_and_assign_fs for root_volume"
 validate_volume_and_assign_fs "root_volume"
-notice_msg_n "root_fs:" ; handle_result $? "$root_fs" ""
+j_msg -${notice} -p -n "root_fs:" ; handle_result $? "$root_fs" "" ${notice}
 
-notice_msg "Calling validate_volume_and_assign_fs for usr_volume"
+j_msg -${notice} -p "Calling validate_volume_and_assign_fs for usr_volume"
 validate_volume_and_assign_fs "usr_volume"
-notice_msg_n "usr_fs:" ; handle_result $? "$usr_fs" ""
+j_msg -${notice} -p -n "usr_fs:" ; handle_result $? "$usr_fs" "" ${notice}
 
 # display config - after volumes uinlocked and root/usr fs obtained
 varlist="
@@ -365,13 +365,13 @@ varlist="
   lv.PATH_str
 "
 # PATH -- display, don't initialize
-notice_msg "Mature Configuration follows ..."
+j_msg -${notice} -p "Mature Configuration follows ..."
 show_config
 
 if [ ! "$QUIET" ] && [ "$verbosity" -ge "$debug" ]; then sh_countdown $(( $init_wait * 3 )); fi
 
 # access the root and usr logical volumes (among others), and show what we unlocke
-display_logical_volumes || error_msg "error running display_logical_volumes"
+display_logical_volumes || j_msg -${err} "error running display_logical_volumes"
 
 # mount new_root and prepareto switch_root
 mount_new_root_and_prepare_to_switch_root || die "failed to mount_new_root_and_prepare_to_switch_root"
@@ -379,16 +379,16 @@ mount_new_root_and_prepare_to_switch_root || die "failed to mount_new_root_and_p
 #mount_and_test_new_root || die "failed to mount_and_test_new_root"
 
 separator "${PN}-${BUILD}" "(Switching to /newroot, mounted on encrypted volume [${root_volume}])"
-notice_msg "  -  Will continue with /sbin/init"
-[ ! -z "${CMDLINE}" ] && notice_msg "  -  using cmdline: ${CMDLINE}"
+j_msg -${notice} -p "  -  Will continue with /sbin/init"
+[ ! -z "${CMDLINE}" ] && j_msg -${notice} -p "  -  using cmdline: ${CMDLINE}"
 echo
 
 ### ***** for testing comment out EVERYTHING below ***** ---
 
 # boot the real thing or exit to rescue shell if not locked down
 exec $(which busybox) switch_root /newroot /sbin/init ${CMDLINE} || \
-    { error_msg "failed to mount root volume" ; [ ! "${init_lock_down}" ] && rescue_shell "Failed to pivot root" ; }
+    { j_msg -${err} "failed to mount root volume" ; [ ! "${init_lock_down}" ] && rescue_shell "Failed to pivot root" ; }
 
-notice_msg "General failure, shutting down for security reasons"
+j_msg -${notice} -p "General failure, shutting down for security reasons"
 sh_countdown $(($init_wait * 3))
 shutdown -hP now
diff --git a/dev-util/mkinitramfs/mkinitramfs b/dev-util/mkinitramfs/mkinitramfs
--- a/dev-util/mkinitramfs/mkinitramfs
+++ b/dev-util/mkinitramfs/mkinitramfs
@@ -46,10 +46,10 @@ if [[ -d "${SOURCES_DIR}" ]]; then
   # readarray with find ... -print0 is the safer way to do this
   readarray -d '' bak_dirs < <(find $(dirname "$SOURCES_DIR") -maxdepth 1 -mindepth 1 -type d -iname 'initramfs*' -print0)
   pre_existing=${#bak_dirs[@]}
-  notice_msg_n "backing up pre-existing initramfs directory"
+  j_msg -${notice} -p -n "backing up pre-existing initramfs directory"
   mv "${SOURCES_DIR}" "${SOURCES_DIR}.bak.${pre_existing}"
-  handle_result $? "initramfs.bak.${pre_existing}" "failed" || \
-    error_msg "failed to mv ${SOURCES_DIR} ${SOURCES_DIR}.bak.${pre_existing}"
+  handle_result $? "initramfs.bak.${pre_existing}" "failed" ${notice} || \
+    j_msg -${err} "failed to mv ${SOURCES_DIR} ${SOURCES_DIR}.bak.${pre_existing}"
 fi
 
 #-----[ main script ]----------------------------------------------------------
@@ -59,14 +59,14 @@ fi
 
 # unless testing, mount the boot device if it wasn't already
 if ! -z "$suffix"; then
-  notice_msg_n "checking if /boot is mounted"
+  j_msg -${notice} -p -n "checking if /boot is mounted"
   checkboot >/dev/null
   result=$?
-  handle_result $result "mounted" "not mounted"
+  handle_result $result "mounted" "not mounted" ${notice}
   if [ ! $result -eq 0 ]; then
-    notice_msg_n "Mounting /boot..."
+    j_msg -${notice} -p -n "Mounting /boot..."
     mount -o rw /boot
-    handle_result $? || die "failed to mount -o rw /boot"
+    handle_result $? "" "" ${notice} || die "failed to mount -o rw /boot"
   fi  # checkboot result
 fi  # testing?
 
@@ -85,4 +85,4 @@ separator "Please verify the results, below)" "initramfs-${BUILD} installed"
 # list files in /boot/ with names containing "initramfs"
 find "${img_ROOT%/}/boot/" -maxdepth 1 -type f -iname 'initramfs*' -print
 separator "${PN}-${BUILD}" "(Done)"
-echo_msg    # newline
+printf '\n'    # unconditional newline
diff --git a/dev-util/mkinitramfs/validated_functions_header b/dev-util/mkinitramfs/validated_functions_header
--- a/dev-util/mkinitramfs/validated_functions_header
+++ b/dev-util/mkinitramfs/validated_functions_header
@@ -16,18 +16,18 @@ assign_volume() {
     _av_prefix="${_av_volume_name%_volume}"     # e.g. assign root, from root_volume (POSIX strip from end)
     eval "_av_volume=\"\$${_av_volume_name}\""
     if [ -z "${_av_volume}" ] ; then
-        info_msg "about to evaluate ${_av_prefix}_volume=/dev/mapper/$(lvs | grep ${_av_prefix} | awk '{print $2"-"$1}')"
-        info_msg_n "${_av_prefix} _av_volume_name not assigned, scanning ..."
+        j_msg -${info} -m "about to evaluate ${_av_prefix}_volume=/dev/mapper/$(lvs | grep ${_av_prefix} | awk '{print $2"-"$1}')"
+        j_msg -${info} -m -n "${_av_prefix} _av_volume_name not assigned, scanning ..."
         _av_volume="/dev/mapper/$(lvs | grep ${_av_prefix} | awk '{print $2"-"$1}')"
 ### substitute for testing only (ver 10.0+ changed from deselecting gmki91 to SELECTING test device)
-#        info_msg "about to evaluate ${_av_prefix}_volume=/dev/mapper/$(lvs | grep 'rock5bplus6401' | grep ${_av_prefix} | awk '{print $2"-"$1}')"
-#        info_msg_n "${_av_prefix} _av_volume_name not assigned, scanning ..."
+#        j_msg -${info} -m "about to evaluate ${_av_prefix}_volume=/dev/mapper/$(lvs | grep 'rock5bplus6401' | grep ${_av_prefix} | awk '{print $2"-"$1}')"
+#        j_msg -${info} -m -n "${_av_prefix} _av_volume_name not assigned, scanning ..."
 #        _av_volume="/dev/mapper/$(lvs | grep 'rock5bplus6401' | grep $_av_prefix | awk '{print $2"-"$1}')"
         eval "${_av_prefix}_volume=$_av_volume"
         ret=$?
-        info_handle_result $ret "$_av_volume" "failed to assign _av_volume"
+        handle_result $ret "$_av_volume" "failed to assign _av_volume" ${info}
     else
-        info_msg "No action. ${_av_prefix} volume already assigned [$_av_volume]"
+        j_msg -${info} -m "No action. ${_av_prefix} volume already assigned [$_av_volume]"
     fi
     unset -v _av_prefix _av_volume_name _av_volume
     return $ret
@@ -42,7 +42,7 @@ display_logical_volumes() {
     vgs || ret=1
     separator "${PN}-${BUILD}" "(available logical volumes)"
     lvs || ret=1
-    [ ! "$QUIET" ] && d_do verbosity=7 sh_countdown '$init_wait' "$debug"
+    [ ! "$QUIET" ] && d_do sh_countdown "$init_wait" "$debug"
     return $ret
 }
 
@@ -52,30 +52,30 @@ mount_new_root_and_prepare_to_switch_root() {
     # previous version re-scanned here, but that now occurs after unlock
     # note: script_header_joetoo v0.2.0+ changed arg sequence for color()
     # color() - $1: FG code (30-37, 39); $2: Bold (0/1); $3: BG code (40-47, 49
-    info_msg "$(color ${RED} ${BOLD} ${BBACK})running fsck -t ${root_fs} on $root_volume${Boff}"
+    j_msg -${info} -m "$(color ${RED} ${BOLD} ${BBACK})running fsck -t ${root_fs} on $root_volume${Boff}"
     fsck -t "${root_fs}" -p "$root_volume" 2>/dev/null
     result=$?
-    info_handle_result $result '' "failed with exit code [$result]"
+    handle_result $result '' "failed with exit code [$result]" ${info}
     [ $result -ge 4 ] && die "fsck failure ($result); cannot continue"
-    info_msg "$(color ${RED} ${BOLD} ${BBACK})running fsck -t ${usr_fs} on $usr_volume${Boff}"
+    j_msg -${info} -m "$(color ${RED} ${BOLD} ${BBACK})running fsck -t ${usr_fs} on $usr_volume${Boff}"
     fsck -t "${usr_fs}" -p "$usr_volume" 2>/dev/null
     result=$?
-    info_handle_result $result '' "failed with exit code [$result]"
+    handle_result $result '' "failed with exit code [$result]" ${info}
     [ $result -ge 4 ] && die "fsck failure ($result); cannot continue"
     # give more time to read display if debugging
-    [ ! "$QUIET" ] && d_do verbosity=7 sh_countdown '$init_wait' "$debug"
-    [ ! "$QUIET" ] && d_do verbosity=7 'tree -d' "$debug"
+    [ ! "$QUIET" ] && d_do sh_countdown "$init_wait" "$debug"
+    [ ! "$QUIET" ] && d_do tree -d "$debug"
     # mount root - drop to shell if not locked down
-    info_msg_n "Mounting new root volume ..."
+    j_msg -${info} -m -n "Mounting new root volume ..."
     mount -r -t "${root_fs}" "${root_volume}" /newroot 2>/dev/null ; _mnr_result=$?
-    info_handle_result "$_mnr_result" '' "failed to mount root volume"
+    handle_result "$_mnr_result" '' "failed to mount root volume" ${info}
     if  [ ! "$_mnr_result" -eq 0 ] && [ "$init_lock_down" = "no" ]; then
         ret=1
         rescue_shell "Failed to mount root volume"
     fi
-    info_msg_n "Mounting new usr volume ..."
+    j_msg -${info} -m -n "Mounting new usr volume ..."
     mount -t "${usr_fs}" -o defaults,noatime "$usr_volume" /newroot/usr ; _mnr_result=$?
-    info_handle_result "$_mnr_result" '' "failed to mount usr volume"
+    handle_result "$_mnr_result" '' "failed to mount usr volume" ${info}
     if  [ ! "$_mnr_result" -eq 0 ] && [ "$init_lock_down" = "no" ]; then
         ret=1
         rescue_shell "Failed to mount usr volume"
@@ -86,18 +86,18 @@ mount_new_root_and_prepare_to_switch_root() {
 
     # clean up in preparation to actually switch root - with retry if needed
     for _mnr_fs in /dev/pts /dev /sys /proc; do
-        info_msg_n "umount ${_mnr_fs} ..."
+        j_msg -${info} -m -n "umount ${_mnr_fs} ..."
         # Try standard unmount
         umount "${_mnr_fs}"
         _mnr_result=$?
         # if standard umount fails, try a "lazy" unmount (-l)
         # This is often necessary if a process has a lingering handle
         if [ $_mnr_result -ne 0 ]; then
-            info_msg " (retrying lazy umount...)"
+            j_msg -${info} -m " (retrying lazy umount...)"
             umount -l "${_mnr_fs}"
             _mnr_result=$?
         fi
-        info_handle_result "$_mnr_result" '' "Critical error: Could not unmount ${_mnr_fs}"
+        handle_result "$_mnr_result" '' "Critical error: Could not unmount ${_mnr_fs}" ${info}
 
         # fatal exit -- if it's still mounted, switch_root WILL fail.
         if [ $_mnr_result -ne 0 ]; then
@@ -110,7 +110,7 @@ mount_new_root_and_prepare_to_switch_root() {
     done
 
     # give more time to read display if debugging
-    [ ! "$QUIET" ] && d_do verbosity=7 sh_countdown "$init_wait" "$debug"
+    [ ! "$QUIET" ] && d_do sh_countdown "$init_wait" "$debug"
     unset -v _mnr_result _mnr_fs
     return $ret
 }
@@ -127,12 +127,12 @@ validate_volume_and_assign_fs() {
     #   (2) begins with a numeral are invalid variable names in a POSIX shell
     case "$_vva_volume_name" in
         *[![:alnum:]_]* | [0-9]*)
-            error_msg "volume_name [$_vva_volume_name] is not a valid POSIX variable name"
+            j_msg -${err} "volume_name [$_vva_volume_name] is not a valid POSIX variable name"
             unset -v _vva_volume_name ; return 1 ;;
     esac
     # POSIX indirect variable assignment
     eval "_vva_volume=\"\$${_vva_volume_name}\""
-    info_msg "validating volume ${_vva_volume_name} [${_vva_volume}]"
+    j_msg -${info} -m "validating volume ${_vva_volume_name} [${_vva_volume}]"
 
     # caution - an unassigned volume_name (null $my_volume) will evaluate true for [ -b ${my_volume} ]
     if [ -b "${_vva_volume}" ]; then
@@ -141,16 +141,16 @@ validate_volume_and_assign_fs() {
         # e.g. if _vva_volume_name = root_volume then _vva_fs_name = root_fs
         _vva_fs_name=$( printf '%s' "$_vva_volume_name" | sed 's|volume|fs|')
         # get only the filesystem type and assign it directly to a variable
-        info_msg_n "looking up fs type for ${_vva_volume}"
+        j_msg -${info} -m -n "looking up fs type for ${_vva_volume}"
         # capture raw blkid output (since BusyBox -o value may fail)
         _vva_raw_info=$(blkid "${_vva_volume}")
         # use awk to find the field starting with TYPE= and strip the quotes
         _vva_fs_type=$(printf '%s' "$_vva_raw_info" | awk -F'TYPE="' '{print $2}' | awk -F'"' '{print $1}')
-        info_handle_result $? "$_vva_fs_type" "failed"
+        handle_result $? "$_vva_fs_type" "failed" ${info}
         # now assign the type to the fs name e.g. root_fs=ext4
-        info_msg_n "performing indirect assignment ${_vva_fs_name}=\"${_vva_fs_type}\""
+        j_msg -${info} -m -n "performing indirect assignment ${_vva_fs_name}=\"${_vva_fs_type}\""
         eval "${_vva_fs_name}=\"${_vva_fs_type}\""
-        info_handle_result $? '' ''
+        handle_result $? '' '' ${info}
     else
         _vva_EXISTS=$FALSE
         printf '%s' " (${BRon}not a blockdev${Boff})"
@@ -158,13 +158,13 @@ validate_volume_and_assign_fs() {
     fi
     # keep this check/message outside the if-then-else above, so it can return clean status on the same line
     if [ $_vva_EXISTS ];    then
-        info_msg "    ${BGon}Valid device${Boff} [${_vva_volume}] type [${TYPE}] ${BGon}Exists${Boff}"
+        j_msg -${info} -m "    ${BGon}Valid device${Boff} [${_vva_volume}] type [${TYPE}] ${BGon}Exists${Boff}"
     else
-        error_msg "    ${BRon}invalid device [${_vva_volume}]${Boff}"
+        j_msg -${err} "    ${BRon}invalid device [${_vva_volume}]${Boff}"
         _vva_volcase="$(printf '%s' ${_vva_volume_name} | sed 's|_volume||')"
         case "${_vva_volcase}" in
-            "root"|"usr" ) info_msg "     -- will scan for ${_vva_volcase} volume later, in unlocked volumes" ;;
-            * ) info_msg "    -- invalid case [$_vva_volcase]" ;;
+            "root"|"usr" ) j_msg -${info} -m "     -- will scan for ${_vva_volcase} volume later, in unlocked volumes" ;;
+            * ) j_msg -${info} -m "    -- invalid case [$_vva_volcase]" ;;
         esac
     fi
     unset -v _vva_volume_name _vva_fs_name _vva_volume _vva_fs_type _vva_answer _vva_EXISTS
@@ -174,7 +174,7 @@ validate_volume_and_assign_fs() {
 
 process_cmdline() {
   ret=0
-  notice_msg "Processing cmdline ..."
+  j_msg -${notice} -p "Processing cmdline ..."
   _pc_line_out=""
   set -- ${CMDLINE}
   while [ $# -gt 0 ]; do
@@ -188,19 +188,19 @@ process_cmdline() {
     case "$_pc_var" in
       "verbosity" )
         export "${_pc_entry}" || die "failed to export verbosity"
-        info_msg "cmdline override: [${_pc_entry}]]"
+        j_msg -${info} -m "cmdline override: [${_pc_entry}]]"
       ;;
       "root" )
         export root_volume="${_pc_val}" || die "failed to export root_volume"
-        info_msg "cmdline override: [root_volume=${_pc_val}]"
+        j_msg -${info} -m "cmdline override: [root_volume=${_pc_val}]"
         _pc_line_out="${_pc_line_out} ${_pc_entry}"
       ;;
       "usr" )
         export usr_volume="${_pc_val}" || die "failed to export usr_volume"
-        info_msg "cmdline override: [usr_volume=${_pc_val}]"
+        j_msg -${info} -m "cmdline override: [usr_volume=${_pc_val}]"
       ;;
       * )
-        info_msg "cmdline entry [${_pc_entry}] ignored by initramfs"
+        j_msg -${info} -m "cmdline entry [${_pc_entry}] ignored by initramfs"
         _pc_line_out="${_pc_line_out} ${_pc_entry}"
       ;;
     esac
@@ -209,8 +209,8 @@ process_cmdline() {
   # reset the CMDLINE without the initramfs-peculiar entries
   export CMDLINE="${_pc_line_out}"
   # if not dead from a die command above, then success
-  notice_msg_n "Done processing cmdline; result:"
-  handle_result 0 "exported \$CMDLINE" ""
+  j_msg -${notice} -p -n "Done processing cmdline; result:"
+  handle_result 0 "exported \$CMDLINE" "" ${notice}
   unset -v _pc_line_out _pc_entry _pc_var _pc_val
   return $ret
 }
