major upgrade POSIX header integration
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-util/mkinitramfs/init b/dev-util/mkinitramfs/init
--- a/dev-util/mkinitramfs/init
+++ b/dev-util/mkinitramfs/init
@@ -11,14 +11,17 @@
 ###----******************************************************************************************************
 
 # make my usual functions and formatting utilities available
+init_ROOT="/"   # real system
+#init_ROOT="/home/joe/myUtilities/dev-util/mkinitramfs/scratch/initramfs/"   # substitute for testing only
+
 printf '%s' "sourcing /script_header_joetoo ..."
-. /script_header_joetoo
+. "${init_ROOT%/}/script_header_joetoo"
 handle_result $? || die "failed to source /script_header_joetoo"
 sleep .5
 
 # source the BUILD number generated by the make_sources.sh script,
 d_message_n "sourcing /BUILD ..." 1
-. /BUILD
+. "${init_ROOT%/}/BUILD"
 d_handle_result $? 1 || die "failed to source /BUILD"
 sleep .5
 
@@ -36,8 +39,6 @@ varlist="
   unlock_method
   lv.init_passdevice_list
   init_passdevice_mount_point
-  init_passdevice_volume
-  init_passdevice_fs
   bool.init_lock_down
   root_volume
   root_fs
@@ -50,15 +51,15 @@ varlist="
 # PATH -- display, don't initialize
 
 initialize_vars
-# set default verbosity - b/c we must have it assigned,
+# set default verbosity if it is not externally set
 #  just in case neither in init.conf nor cmdline does it
-verbosity=2
+[ -z "$verbosity" ] && verbosity=2
 
 #----[ reassign variables with values from config files ]----------------------------------
 
 # source variables assigned in init.conf. Note cmdline may override root=, usr=, verbosity=
 d_message_n "sourcing /init.conf ..." 1
-. /init.conf
+. "${init_ROOT%/}/init.conf"
 d_handle_result $? 1 || die "failed to source /init.conf"
 sleep .5
 [ ! -z "${init_root_volume}" ] && root_volume="${init_root_volume}"
@@ -74,16 +75,18 @@ separator "${PN}-${BUILD}" "(Running /init)"
 
 ### *** for testing, when ready, move still-testing functions to validated_functions_header **---
 d_message_n "sourcing /testing_functions_header ..." 1
-. /testing_functions_header
+. "${init_ROOT%/}/testing_functions_header"
 d_handle_result $? 1 || die "failed to source /testing_functions_header"
 
 # note: in the real init script, we MUST source validated_functions_header second, in order to
 #   override testing-only-modified functions also present in testing_functions_header
 #   (in the testing init script (ash.temp) it is the other way around)
 d_message_n "sourcing /validated_functions_header ..." 1
-. /validated_functions_header
+. "${init_ROOT%/}/validated_functions_header"
 d_handle_result $? 1 || die "failed to source /validated_functions_header"
 
+# construct a wrappable string to represent PATH (translate : to ' ')
+PATH_str=$(printf '%s' "$PATH" | tr ':' ' ')
 # display initial config of variables available
 # (must source display_config function first)
 varlist="
@@ -97,12 +100,10 @@ varlist="
   usr_volume
   verbosity
   lv.init_passdevice_list
-  lv.PATH
+  lv.PATH_str
 "
 # these below are not available yet
 #unlock_method \
-#init_passdevice_volume \
-#init_passdevice_fs \
 #root_fs \
 #usr_fs \
 #CMDLINE \
@@ -261,6 +262,10 @@ maybe_redirect_output
 # safely assing CMDLINE
 if [ -f /proc/cmdline ]; then
     CMDLINE="$(cat /proc/cmdline)"
+# substitute below for testing only
+#    CMDLINE="BOOT_IMAGE=/vmlinuz-6.12.63-gentoo-dist-hardened-joetoo"
+#    CMDLINE+=" root=/dev/mapper/vg_rock5bplus6401-root ro verbosity=5"
+#    CMDLINE+=" usr=/dev/mapper/vg_rock5bplus6401-usr net.ifnames=0"
 else
     CMDLINE=""     # Fallback or error for non-Linux systems (BSD, macOS, etc.)
 fi
@@ -270,12 +275,13 @@ process_cmdline
 # if init.conf indicates there is a non-zero-lenght keyfile name to be looked for on a non-empty list of
 # devices, then see if we can select one that will work, otherwise use passphrase method
 
-# call select_keying_device_and_unlock_method to assign unlock_method and init_passdevice_volume
-select_keying_device_and_unlock_method || die "failed to select_keying_device_and_unlock_method"
+# call get_keyfile_and_unlock_method to assign unlock_method and keyfile
+get_keyfile_and_unlock_method || die "failed to get_keyfile_and_unlock_method"
 
 # echo to console to confirm attempt to unlock HDs
 separator "${PN}-${BUILD}" "(Unlocking encrypted Drive(s))"
 # call function to unlock HD(s)
+d_message "calling unlock_devices \"${unlock_method}\"" 3
 unlock_devices "${unlock_method}" || die "failed to unlock_devices"
 
 # done with all luks devices; ok to un-mount keying device now
@@ -288,11 +294,29 @@ fi
 # make lvm logical volumes available
 vgscan
 vgchange -a y
-sh_countdown $(( $init_wait * 3 ))
 
 # assign root and usr volume names (if not already done)
+# (build in safe wait-loop to ensure lvm device mapper
+#  populates the nodes and mdev has time to recognize
+#  and create the rest of the /dev/ structure needed)
 separator "${PN}-${BUILD}" "(assign/validate root, usr vols)"
-assign_volume "root_volume"
+TIMEOUT=20 # Max wait of 10 seconds total (20 * 0.5s checks)
+while [ "$TIMEOUT" -gt 0 ]; do
+    # Try to assign the volume name - redirect output for cleaner waiting dots
+#    if assign_volume "root_volume" >/dev/null ; then
+    if assign_volume "root_volume" ; then
+      # if assignment succeeded, and it is a real blockdev, we are done!
+      if [ -b "$root_volume" ]; then break; fi
+    fi
+#    printf '%s' "."
+    sleep 0.5
+    TIMEOUT=$((TIMEOUT - 1))
+done
+printf '\n' # add newline to the line of dots
+# check if it completed or timed out
+if [ ! -b "$root_volume" ]; then
+    die "timed out waiting for LVM root_volume [$root_volume]; cannot proceed"
+fi
 assign_volume "usr_volume"
 
 # validate root and usr device and assign fs
@@ -306,12 +330,11 @@ varlist="
   BUILD
   init_mdev_wait
   init_wait
-  init_passdevice_volume
-  init_passdevice_fs
   unlock_method
   init_keyfile
   init_passdevice_mount_point
   init_lock_down
+  luks_partition_device
   root_volume
   root_fs
   usr_volume
@@ -332,6 +355,8 @@ display_logical_volumes || E_message "error running display_logical_volumes"
 
 # mount_new_root_and_prepare_to_switch_root
 mount_new_root_and_prepare_to_switch_root || die "failed to mount_new_root_and_prepare_to_switch_root"
+# substitute below for testing only
+#mount_and_test_new_root || die "failed to mount_and_test_new_root"
 
 separator "${PN}-${BUILD}" "(Switching to /newroot, mounted on encrypted volume [${root_volume}])"
 d_message "  -  Will continue with /sbin/init" 1
diff --git a/dev-util/mkinitramfs/make_sources_functions_header b/dev-util/mkinitramfs/make_sources_functions_header
--- a/dev-util/mkinitramfs/make_sources_functions_header
+++ b/dev-util/mkinitramfs/make_sources_functions_header
@@ -46,14 +46,15 @@ create_links()
   for ((i=0; i<${#other_link_name[@]}; i++)); do
     d_message_n "moving to ${SOURCES_DIR%/}/${other_link_dir[i]#/}" 1
     cd "${SOURCES_DIR%/}/${other_link_dir[i]#/}"
-    handle_result $? "ok" "failed" 1 || die "failed to cd ${SOURCES_DIR%/}/${other_link_dir[i]#/}"
-    _cl_msg+"Linking:   ${BBon}[${other_link_dir[i]}] ${LBon}${other_link_name[i]}${Boff}"
+    d_handle_result $? "ok" "failed" 1 || die "failed to cd ${SOURCES_DIR%/}/${other_link_dir[i]#/}"
+    _cl_msg+="Linking:   ${BBon}[${other_link_dir[i]}] ${LBon}${other_link_name[i]}${Boff}"
     _cl_msg+=" --> ${BGon}${other_link_target[i]}${Boff} ..."
     d_message_n "$_cl_msg" 2
-    ln -sf "${other_link_target[i]}"  "${other_link_name[i]}" ;
-    d_right_status $? 2;
+    ln -sf "${other_link_target[i]}"  "${other_link_name[i]}"
+    d_handle_result $? "ok" "failed" 2|| die "failed to ln -sf ${other_link_target[i]} ${other_link_name[i]}" 
+
   done
-  d_message_n "moving to $_cl_old_pwd"
+  d_message_n "moving to $_cl_old_pwd" 1
   cd "$_cl_old_pwd"
   handle_result $? "ok" "failed" 1 || die "failed to cd $_cl_old_pwd"
 
@@ -196,7 +197,7 @@ build_other_devices()
   # @note mdev handles block devices; this creates the essential static console node
   local _bod_old_pwd="$PWD"
   d_message_n "Moving to SOURCES_DIR/dev: ${SOURCES_DIR%/}/dev/" 2
-  cd "${SOURCES_DIR%/}/dev/" 2?dev/null
+  cd "${SOURCES_DIR%/}/dev/" 2>/dev/null
   handle_result $?  || die "Could not cd to SOURCES_DIR/dev"
   # build console character device
   message_n "making console device node in ${SOURCES_DIR%/}/dev/"
diff --git a/dev-util/mkinitramfs/testing_functions_header b/dev-util/mkinitramfs/testing_functions_header
--- a/dev-util/mkinitramfs/testing_functions_header
+++ b/dev-util/mkinitramfs/testing_functions_header
@@ -17,14 +17,13 @@ assign_volume() {
 #        d_message "about to evaluate ${_av_prefix}_volume=/dev/mapper/$(lvs | grep ${_av_prefix} | awk '{print $2"-"$1}')" 3
 #        d_message_n "${_av_prefix} _av_volume_name not assigned, scanning ..." 1
 #        _av_volume="/dev/mapper/$(lvs | grep ${_av_prefix} | awk '{print $2"-"$1}')"
-# substitute for testing only -
-        d_message "about to evaluate ${_av_prefix}_volume=/dev/mapper/$(lvs | grep -v 'gmki91' | grep ${_av_prefix} | awk '{print $2"-"$1}')" 3
+### substitute for testing only (ver 10.0+ changed from deselecting gmki91 to SELECTING test device)
+        d_message "about to evaluate ${_av_prefix}_volume=/dev/mapper/$(lvs | grep 'rock5bplus6401' | grep ${_av_prefix} | awk '{print $2"-"$1}')" 3
         d_message_n "${_av_prefix} _av_volume_name not assigned, scanning ..." 1
-        _av_volume="/dev/mapper/$(lvs | grep -v 'gmki91' | grep $_av_prefix | awk '{print $2"-"$1}')"
+        _av_volume="/dev/mapper/$(lvs | grep 'rock5bplus6401' | grep $_av_prefix | awk '{print $2"-"$1}')"
         eval "${_av_prefix}_volume=$_av_volume"
         ret=$?
-        d_handle_result $ret 1
-        d_message "_av_volume: [$_av_volume]" 3
+        d_handle_result $ret "$_av_volume" "failed to assign _av_volume" 1
     else
         message "No action. ${_av_prefix} volume already assigned [$_av_volume]"
     fi
@@ -34,32 +33,36 @@ assign_volume() {
 
 unlock_devices() {
     ret=0
-    # for version 4.x and beyond, this is a complete re-write of the unlocking procedure.
+    # for version 4.x+, this is a complete re-write of the unlocking procedure.
     # The unlock method has already been determined, and the script will now "scan" for LUKS
     # devices and automatically use the selected method (key vs prompt) to unlock all of them
+    # for version 10.0+, get_luks_edev_name is in script_header_joetoo and uses global $luks_partition_device
+    [ -z "$1" ] && die "error: no arg; unlock_device requires \$1 unlock_method"
     _ud_method=$1;
-    _ud_device="";
+    luks_partition_device="";
 
     # securely read the passphrase with POSIX ask_pass function if needed
     if [ "$_ud_method" = "prompt" ]; then _ud_pass=$(ask_pass "Enter LUKS passphrase: "); fi
 
-### substitute for testing only
-    for _ud_device in $(blkid | grep -i luks | grep -v 'UUID="ef4195f0-6c4a-4116-86dd-fc469ddb6e21"' |cut -d':' -f1 )
-###    for _ud_device in $(blkid | grep -i luks | cut -d':' -f1)
+### substitute for testing only (ver 10.0+ changed from deselecting gmki91 to SELECTING test device)
+      for luks_partition_device in $(blkid | grep -i luks | grep 'UUID="b3c2b95f-1477-4433-b653-310e03dbffc2"' |cut -d':' -f1 )
+#    for luks_partition_device in $(blkid | grep -i luks | cut -d':' -f1)
     do
-        # use get_luks_edev_name in script_header_joetoo to id each _ud_device /dev/sdxn with corresponding name edxn
-        get_luks_edev_name "$_ud_device"
+        d_message "calling get_luks_edev_name \"$luks_partition_device\"" 3
+        d_message "edev: $edev" 3
+        # use get_luks_edev_name in script_header_joetoo to id each luks_partition_device /dev/sdxn with corresponding name edxn
+        get_luks_edev_name "$luks_partition_device"
         case "$_ud_method" in
             "prompt")
                 # this is no longer a f-ing "indented" heredoc '-' tells it to ignore leading TABs (not spaces)
                 # so the next two lines MUS begin with tabs
-                message "About to run cryptsetup luksOpen ${_ud_device} ${edev} with passphrase provided ..."
-#               cryptsetup luksOpen "${_ud_device}" "${edev}" <<-EOF
-cryptsetup luksOpen "${_ud_device}" "${edev}" <<EOF
+                message "About to run cryptsetup luksOpen ${luks_partition_device} ${edev} with passphrase provided ..."
+#               cryptsetup luksOpen "${luks_partition_device}" "${edev}" <<-EOF
+cryptsetup luksOpen "${luks_partition_device}" "${edev}" <<EOF
 $_ud_pass
 EOF
                 _ud_result=$?
-                handle_result "$_ud_result" "Unlocked ${_ud_device} ${edev} with passphrase provided" "mycmd failed. Dropping to a shell ..."
+                handle_result "$_ud_result" "Unlocked ${luks_partition_device} ${edev} with passphrase provided" "mycmd failed. Dropping to a shell ..."
                 if [ ! "$_ud_result" -eq 0 ]; then
                     ret=1
                     d_do sh_countdown $(( $init_wait * 5 )) 4
@@ -71,15 +74,15 @@ EOF
                 # Use cryptsetup option for key file -d <mount_point><keyfile> and -S <key slot #>
                 # unmount the passdevice when we are done with it
                 _ud_keyfile="${init_passdevice_mount_point%/}/${init_keyfile}"
-                message "About to execute command [ cryptsetup -d ${_ud_keyfile} -S 1 luksOpen ${_ud_device} ${edev} ]"
-                cryptsetup -d $(echo "${_ud_keyfile}") -S 1 luksOpen "${_ud_device}" "${edev}"
+                message "About to execute command [ cryptsetup -d ${_ud_keyfile} -S 1 luksOpen ${luks_partition_device} ${edev} ]"
+                cryptsetup -d $(echo "${_ud_keyfile}") -S 1 luksOpen "${luks_partition_device}" "${edev}"
                 _ud_result=$?
                 handle_result "$_ud_result"
                 if [ "$_ud_result" -eq 0 ]; then
-                    message "Unlocked ${_ud_device} ${edev} with key found at $(echo ${init_passdevice_mount_point}${init_keyfile})"
+                    message "Unlocked ${luks_partition_device} ${edev} with key found at $(echo ${init_passdevice_mount_point}${init_keyfile})"
                 else  # cryptsetup luksOpen with key failed
                     ret=1
-                    _ud_msg="${BRon}Error: Could not unlock ${BYon}${_ud_device} ${edev}"
+                    _ud_msg="${BRon}Error: Could not unlock ${BYon}${luks_partition_device} ${edev}"
                     _ud_msg="${_ud_msg} ${BRon}with key found at ${BMon}${_ud_keyfile}${Boff}"
                     E_message "${_ud_msg}"
                     if [ ! "${init_lock_down}" ]; then
@@ -91,12 +94,38 @@ EOF
                 ;;
         esac
     done
-    unset -v _ud_method _ud_device _ud_pass _ud_keyfile
+    unset -v _ud_method _ud_pass _ud_keyfile
     return $ret
 }
 
-
 ### ----[ end duplicated functions ]--------------------------------------------------------------------------------------------------------------
+
+mount_and_test_new_root() {
+    ret=0
+    separator "${PN}-${BUILD}" "(Mounting new root for testing ...)"
+    # previous version re-scanned here, but that now occurs after unlock
+    # note: script_header_joetoo v0.2.0+ changed arg sequence for color()
+    # color() - $1: FG code (30-37, 39); $2: Bold (0/1); $3: BG code (40-47, 49
+    d_message "$(color ${RED} ${BOLD} ${BBACK})running fsck.${root_fs} on $root_volume${Boff}" 1
+    "fsck.${root_fs}" -p "$root_volume"
+    d_message "$(color ${RED} ${BOLD} ${BBACK})running fsck.${usr_fs} on $usr_volume${Boff}" 1
+    "fsck.${usr_fs}" -p "$usr_volume"
+    # give more time to read display if debugging
+    d_do sh_countdown $init_wait 4
+    # mount root - drop to shell if not locked down
+    d_message_n "Mounting new root volume ..." 1
+    mount -r -t "${root_fs}" "${root_volume}" "${init_ROOT%/}/newroot" 2>/dev/null ; _mnr_result=$?
+    d_handle_result "$_mnr_result" '' "failed to mount root volume" 1
+    d_message_n "Mounting new usr volume ..." 1
+    mount -t "${usr_fs}" -o defaults,noatime "$usr_volume" "${init_ROOT%/}/newroot/usr" ; _mnr_result=$?
+    d_handle_result "$_mnr_result" '' "failed to mount usr volume" 1
+
+    separator "${PN}-${BUILD}" "(Mounts)"
+    mount | sed 's|^|    |'
+
+    unset -v _mnr_result 
+    return $ret
+}
 
 test() {
         verbosity=2
