initiate synchronized deprecation strategy for  variable (redundant to any verbosity -gt 0)
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-util/mkinitramfs/init b/dev-util/mkinitramfs/init
--- a/dev-util/mkinitramfs/init
+++ b/dev-util/mkinitramfs/init
@@ -12,13 +12,13 @@
 
 # make my usual functions and formatting utilities available
 printf '%s' "sourcing /script_header_joetoo ..."
-source /script_header_joetoo
+. /script_header_joetoo
 handle_result $? || die "failed to source /script_header_joetoo"
 sleep .5
 
 # source the BUILD number generated by the make_sources.sh script,
 d_message_n "sourcing /BUILD ..." 1
-source /BUILD
+. /BUILD
 d_handle_result $? 1 || die "failed to source /BUILD"
 sleep .5
 
@@ -59,14 +59,14 @@ VERBOSE=$TRUE; verbosity=2
 
 # source variables assigned in init.conf. Note cmdline may override root=, usr=, verbosity=
 d_message_n "sourcing /init.conf ..." 1
-source /init.conf
+. /init.conf
 d_handle_result $? 1 || die "failed to source /init.conf"
 sleep .5
 if [ "$verbosity" -gt 0 ]; then VERBOSE=$TRUE; else VERBOSE=$FALSE; fi
 [ ! -z "${init_root_volume}" ] && root_volume="${init_root_volume}"
 [ ! -z "${init_usr_volume}" ]  && usr_volume="${init_usr_volume}"
-if ! isint "${init_wait}" && init_wait=1  # hard code default 1 second
-if ! isint "${init_mdev_wait}" && init_wait=3  # hard code default 3 seconds 
+! isint "${init_wait}" && init_wait=1  # hard code default 1 second
+! isint "${init_mdev_wait}" && init_wait=3  # hard code default 3 seconds
 printf "\n"
 
 #----[ display separator to mark start of script ]-----------------------------------------------
@@ -75,19 +75,19 @@ separator "${PN}-${BUILD}" "(Running /init)"
 #----[ source functions local to initramfs ]-----------------------------------------------------
 # common ash functions used by several scripts (display_config, echo_long_string)
 d_message_n "sourcing /common_ash_functions_header ..." 1
-source /common_ash_functions_header
+. /common_ash_functions_header
 d_handle_result $? 1 || die "failed to source /common_ash_functions_header"
 
 ### *** for testing, when ready, move still-testing functions to validated_functions_header **---
 d_message_n "sourcing /testing_functions_header ..." 1
-source /testing_functions_header
+. /testing_functions_header
 d_handle_result $? 1 || die "failed to source /testing_functions_header"
 
 # note: in the real init script, we MUST source validated_functions_header second, in order to
 #   override testing-only-modified functions also present in testing_functions_header
 #   (in the testing init script (ash.temp) it is the other way around)
 d_message_n "sourcing /validated_functions_header ..." 1
-source /validated_functions_header
+. /validated_functions_header
 d_handle_result $? 1 || die "failed to source /validated_functions_header"
 
 # display initial config of variables available
@@ -218,6 +218,33 @@ mini_udev() {
 
 }
 
+maybe_redirect_output() # if /dev/console is writable, deliberately redirect output there
+{
+  # (1) /dev/console is created by mksources ( mknod -m 600 console c 5 1 ), and even if not,
+  # then now that /dev is populated by mini_udev, the device node should exist [ -c test ].
+  # However - that doesn't guarantee that the kernel will have loaded drivers capable of using it
+  # (serial/VGA for example), so we need to check the devices "writability" [ -w test ], to be sure
+  # implement a bounded wait here, incase it hasn't happened "yet"
+  # note: -w implies -c so don't need to check both
+  ret=0
+  _init_shortwait="0.1"
+  _init_console_retry=0; _init_max_retry=20    # max wait 2 seconds total
+  while [ ! -w /dev/console ] && [ "$_init_console_retry" -lt "$_init_max_retry" ]; do
+    sleep "$_init_shortwait"
+    _init_console_retry=$((_init_console_retry + 1))
+  done
+  if [ -w /dev/console ]; then
+    exec > /dev/console 2>&1
+    # Subsequent messages now appear on the actual boot console
+    message "Standard and Error output redirected to /dev/console"
+  else
+    # if -c passes but -w fails, the node exists but the device is not ready for output
+    echo "Warning: /dev/console exists but is not writable. Redirection skipped." >&2
+  fi
+  unset -v _init_console_retry _init_shortwait _init_max_retry
+  return $ret
+}
+
 #---[ Main script ]----------------------------------------------------------------------------------------
 
 # wait for normal trailing kernel output
@@ -230,7 +257,10 @@ message "Starting mini udev ..."
 mini_udev
 result=$?
 message_n "mini_udev result: "
-handle_result "$result" "mdev started" "mdev failed to start"
+handle_result "$result" "mini_udev hotplug and coldplug started" "mdev failed to start" || die "mini_udev failed"
+
+# if /dev/console is writable, deliberately redirect output there
+maybe_redirect_output
 
 # now converting this dumb wait to a targeted wait (if needed) when getting keying dev
 #&& sh_countdown $(($init_mdev_wait))
