stabilized scripts, consolidated rollback into rotate with direction
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-util/mkinitramfs/mkinitramfs b/dev-util/mkinitramfs/mkinitramfs
--- a/dev-util/mkinitramfs/mkinitramfs
+++ b/dev-util/mkinitramfs/mkinitramfs
@@ -12,17 +12,26 @@
 # output for the user.  This script will not have access to the BUILD
 # value until after make_sources is run; here it is used only in the
 # final visual output
+# NOTE: if in testing mode, substitute three lines below
 
 #-----[ initialize variables ]-------------------------------------------------
 echo -n "Sourcing globals... "
 source GLOBALS
-[[ $? ]] && echo "ok" || ( echo "Error: sourcing globals failed. Possibly no kernel sources at /usr/src/linux?" && exit 1 )
+# subsititure below for testing only
+#source GLOBALS.scratch_test
+
+if [[ $? -eq 0 ]]; then echo "ok"; else echo "Error: failed to source GLOBALS"; exit 1; fi
+
+img_ROOT="/"; suffix=""; prefix=""
+# subsititure below for testing only
+#img_ROOT="${MAKE_DIR%/}/scratch/"; suffix=".test"; prefix="scratch/"
 
 source "${SCRIPT_HEADER_DIR}/script_header_joetoo"
 
 old_dir=$(pwd)
 
-# set defaults
+# set defaults (ROTATE, like globally defined TRUE=0; FALSE="" is a pseudo-boolean;
+#   only ever assigned ROTATE=$TRUE or =$FALSE, [ $ROTATE ] will always evaluate as expected
 ROTATE=$FALSE
 
 # load customized configuration parameters - subsequent assignments supercede defaults
@@ -38,28 +47,35 @@ if [[ -d "${SOURCES_DIR}" ]]; then
   readarray -d '' bak_dirs < <(find $(dirname "$SOURCES_DIR") -maxdepth 1 -mindepth 1 -type d -iname 'initramfs*' -print0)
   pre_existing=${#bak_dirs[@]}
   message_n "backing up pre-existing initramfs directory"
-  mv "${SOURCES_DIR}" "${SOURCES_DIR}.bak.$((${pre_existing} - 1))"
-  handle_result $? "initramfs.bak.$((${pre_existing} - 1))" "failed" || \
-    E_message "failed to mv ${SOURCES_DIR} ${SOURCES_DIR}.bak.$((${pre_existing} - 1))"
+  mv "${SOURCES_DIR}" "${SOURCES_DIR}.bak.${pre_existing}"
+  handle_result $? "initramfs.bak.${pre_existing}" "failed" || \
+    E_message "failed to mv ${SOURCES_DIR} ${SOURCES_DIR}.bak.${pre_existing}"
 fi
 
 #-----[ main script ]----------------------------------------------------------
 
 # (re-)create and (re-)load the ${SOURCES_DIR}
-"${MAKE_DIR}/make_sources.sh"
+"${MAKE_DIR}/${prefix}make_sources.sh${suffix}"
 
-# mount the boot device if it wasn't already
-if ! checkboot >/dev/null; then
-  message_n "Mounting /boot..."
-  mount -o rw /boot
-  handle_result $? || die "failed to mount -o rw /boot"
-fi
+# unless testing, mount the boot device if it wasn't already
+if ! -z "$suffix"; then
+  message_n "checking if /boot is mounted"
+  checkboot >/dev/null
+  result=$?
+  handle_result $result "mounted" "not mounted"
+  if [ ! $result -eq 0 ]; then
+    message_n "Mounting /boot..."
+    mount -o rw /boot
+    handle_result $? || die "failed to mount -o rw /boot"
+  fi  # checkboot result
+fi  # testing?
+
 # generate and install the acutal image (cpio.gz archive of the sources)
-"${MAKE_DIR}/make_image.sh"
+"${MAKE_DIR}/${prefix}make_image.sh${suffix}"
 
 # (Optionally) auto-rotate initramfs images, if called for in .conf
 
-[[ $ROTATE ]] && "${MAKE_DIR}/rotate_initramfs.sh"
+[[ $ROTATE ]] && "${MAKE_DIR}/${prefix}rotate_initramfs.sh${suffix}"
 
 # get the BUILD number generated by make_sources.sh
 source "${SOURCES_DIR}/BUILD"
@@ -67,5 +83,6 @@ source "${SOURCES_DIR}/BUILD"
 # show the results
 separator "Please verify the results, below)" "initramfs-${BUILD} installed"
 # list files in /boot/ with names containing "initramfs"
-find /boot/ -maxdepth 1 -type f -iname 'initramfs*' -print
-separator "Done"  "mkinitramfs-${BUILD}"
+find "${img_ROOT%/}/boot/" -maxdepth 1 -type f -iname 'initramfs*' -print
+separator "${PN}-${BUILD}" "(Done)"
+echo
