update to both mkinitramfs and script_header_joetoo with all luks management in the latter now
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-util/script_header_joetoo/archive/script_header_joetoo_archive b/dev-util/script_header_joetoo/archive/script_header_joetoo_archive
--- a/dev-util/script_header_joetoo/archive/script_header_joetoo_archive
+++ b/dev-util/script_header_joetoo/archive/script_header_joetoo_archive
@@ -1992,3 +1992,381 @@ varlist="${varlist} bool.INTERACTIVE bool.RESUME bool.LOGGING bool.QUIET bool.DE
 varlist="${varlist} bool.handle_local_arg_EXISTS bool.handle_local_compound_arg_EXISTS"
 varlist="${varlist} bool.handle_local_usage_EXISTS"
 varlist="${varlist} app_customization_root local_cmdline_arg_handler"
+
+# old validated functions header
+
+#!/bin/sh
+#
+#  20260126 - changed from #!/bin/ash after revising all contained functions to be fully POSIX compliant
+
+### -----[ duplicated functions ]--------------------------------------------------------------
+### These scripts exist in both "validated_" and "testing_" headers but have been modified in each
+### In the live init script, source the "testing_" header first and "validated_" header second
+### In the testing script, source "validated_" header first and the "testing_" header second
+### The later-sourced will override, and this avoid having the "testing" script mess with
+###    non-testing luks devices on a testing host system
+assign_volume() {
+    ret=0
+    # given string volume name (root_ usr_volume), scan lvs and make volume pathname assignment
+    _av_volume_name=$1
+#    _av_prefix="${_av_volume_name/_volume}"     # e.g. assign root, from root_volume (bash substitution)
+    _av_prefix="${_av_volume_name%_volume}"     # e.g. assign root, from root_volume (POSIX strip from end)
+    eval "_av_volume=\"\$${_av_volume_name}\""
+    if [ -z "${_av_volume}" ] ; then
+        info_msg "about to evaluate ${_av_prefix}_volume=/dev/mapper/$(lvs | grep ${_av_prefix} | awk '{print $2"-"$1}')"
+        info_msg_n "${_av_prefix} _av_volume_name not assigned, scanning ..."
+        _av_volume="/dev/mapper/$(lvs | grep ${_av_prefix} | awk '{print $2"-"$1}')"
+### substitute for testing only (ver 10.0+ changed from deselecting gmki91 to SELECTING test device)
+#        info_msg "about to evaluate ${_av_prefix}_volume=/dev/mapper/$(lvs | grep 'rock5bplus6401' | grep ${_av_prefix} | awk '{print $2"-"$1}')"
+#        info_msg_n "${_av_prefix} _av_volume_name not assigned, scanning ..."
+#        _av_volume="/dev/mapper/$(lvs | grep 'rock5bplus6401' | grep $_av_prefix | awk '{print $2"-"$1}')"
+        eval "${_av_prefix}_volume=$_av_volume"
+        ret=$?
+        info_handle_result $ret "$_av_volume" "failed to assign _av_volume"
+    else
+        info_msg "No action. ${_av_prefix} volume already assigned [$_av_volume]"
+    fi
+    unset -v _av_prefix _av_volume_name _av_volume
+    return $ret
+}
+
+unlock_devices() {
+    ud_ret=0
+    # for version 4.x+, this is a complete re-write of the unlocking procedure.
+    # The unlock method has already been determined, and the script will now "scan" for LUKS
+    # devices and automatically use the selected method (key vs prompt) to unlock all of them
+    # for version 10.0+, get_luks_edev_name is in script_header_joetoo and uses global $luks_partition_device
+    [ -z "$1" ] && die "error: no arg; unlock_device requires \$1 unlock_method"
+    _ud_method=$1;
+    luks_partition_device="";
+
+    # securely read the passphrase with POSIX ask_pass function if needed
+    if [ "$_ud_method" = "prompt" ]; then _ud_pass=$(ask_pass "Enter LUKS passphrase: "); fi
+
+### substitute for testing only (ver 10.0+ changed from deselecting gmki91 to SELECTING test device)
+#      for luks_partition_device in $(blkid | grep -i luks | grep 'UUID="b3c2b95f-1477-4433-b653-310e03dbffc2"' |cut -d':' -f1 )
+    for luks_partition_device in $(blkid | grep -i luks | cut -d':' -f1)
+    do
+        info_msg "calling get_luks_edev_name \"$luks_partition_device\""
+        # use get_luks_edev_name in script_header_joetoo to id each luks_partition_device /dev/sdxn with corresponding name edxn
+        get_luks_edev_name "$luks_partition_device"
+        case "$_ud_method" in
+            "prompt")
+                # this is no longer a f-ing "indented" heredoc '-' tells it to ignore leading TABs (not spaces)
+                # so the next two lines MUS begin with tabs
+                info_msg "About to run cryptsetup luksOpen ${luks_partition_device} ${edev} with passphrase provided ..."
+#		cryptsetup luksOpen "${luks_partition_device}" "${edev}" <<-EOF
+cryptsetup luksOpen "${luks_partition_device}" "${edev}" <<EOF
+$_ud_pass
+EOF
+                _ud_result=$?
+                info_handle_result "$_ud_result" "Unlocked ${luks_partition_device} ${edev} with passphrase provided" "mycmd failed. Dropping to a shell ..."
+                if [ ! "$_ud_result" -eq 0 ]; then
+                    ud_ret=1
+                    [ ! "$QUIET" ] && d_do verbosity=7 sh_countdown $(( $init_wait * 5 )) "$debug"
+                    [ ! "${init_lock_down}" ] && rescue_shell
+                fi;
+                ;;
+            "key")
+                # passdevice already mounted,
+                # Use cryptsetup option for key file -d <mount_point><keyfile> and -S <key slot #>
+                # unmount the passdevice when we are done with it
+                _ud_keyfile="${init_passdevice_mount_point%/}/${init_keyfile}"
+                info_msg "About to run cryptsetup -d ${_ud_keyfile} -S 1 luksOpen ${luks_partition_device} ${edev} "
+                cryptsetup -d $(printf '%s' "${_ud_keyfile}") -S 1 luksOpen "${luks_partition_device}" "${edev}"
+                _ud_result=$?
+                info_msg_n "unlock result:"
+                info_handle_result $_ud_result "" ""
+                if [ "$_ud_result" -eq 0 ]; then
+                    info_msg "Unlocked ${luks_partition_device} ${edev} with key found at ${init_passdevice_mount_point}${init_keyfile}"
+                else  # cryptsetup luksOpen with key failed
+                    ud_ret=1
+                    _ud_msg="${BRon}Error: Could not unlock ${BYon}${luks_partition_device} ${edev}"
+                    _ud_msg="${_ud_msg} ${BRon}with key found at ${BMon}${_ud_keyfile}${Boff}"
+                    error_msg "${_ud_msg}"
+                    if [ ! "${init_lock_down}" ]; then
+                        error_msg "${BRon}Dropping to a shell${Boff}"
+                        sh_countdown $(( $init_wait * 5 ))
+                        rescue_shell
+                    fi
+                fi
+                ;;
+        esac
+    done
+    unset -v _ud_method _ud_pass _ud_keyfile
+    return $ud_ret
+}
+
+### ----[ end duplicated functions ]--------------------------------------------------------------------------------------------------------------
+
+display_logical_volumes() {
+    ret=0
+    # show what we've found...
+    separator "${PN}-${BUILD}" "(available volume groups)"
+    vgs || ret=1
+    separator "${PN}-${BUILD}" "(available logical volumes)"
+    lvs || ret=1
+    [ ! "$QUIET" ] && d_do verbosity=7 sh_countdown '$init_wait' "$debug"
+    return $ret
+}
+
+mount_new_root_and_prepare_to_switch_root() {
+    ret=0
+    separator "${PN}-${BUILD}" "(Attempting to mount new root ...)"
+    # previous version re-scanned here, but that now occurs after unlock
+    # note: script_header_joetoo v0.2.0+ changed arg sequence for color()
+    # color() - $1: FG code (30-37, 39); $2: Bold (0/1); $3: BG code (40-47, 49
+    info_msg "$(color ${RED} ${BOLD} ${BBACK})running fsck -t ${root_fs} on $root_volume${Boff}"
+    fsck -t "${root_fs}" -p "$root_volume" 2>/dev/null
+    result=$?
+    info_handle_result $result '' "failed with exit code [$result]"
+    [ $result -ge 4 ] && die "fsck failure ($result); cannot continue"
+    info_msg "$(color ${RED} ${BOLD} ${BBACK})running fsck -t ${usr_fs} on $usr_volume${Boff}"
+    fsck -t "${usr_fs}" -p "$usr_volume" 2>/dev/null
+    result=$?
+    info_handle_result $result '' "failed with exit code [$result]"
+    [ $result -ge 4 ] && die "fsck failure ($result); cannot continue"
+    # give more time to read display if debugging
+    [ ! "$QUIET" ] && d_do verbosity=7 sh_countdown '$init_wait' "$debug"
+    [ ! "$QUIET" ] && d_do verbosity=7 'tree -d' "$debug"
+    # mount root - drop to shell if not locked down
+    info_msg_n "Mounting new root volume ..."
+    mount -r -t "${root_fs}" "${root_volume}" /newroot 2>/dev/null ; _mnr_result=$?
+    info_handle_result "$_mnr_result" '' "failed to mount root volume"
+    if  [ ! "$_mnr_result" -eq 0 ] && [ "$init_lock_down" = "no" ]; then
+        ret=1
+        rescue_shell "Failed to mount root volume"
+    fi
+    info_msg_n "Mounting new usr volume ..."
+    mount -t "${usr_fs}" -o defaults,noatime "$usr_volume" /newroot/usr ; _mnr_result=$?
+    info_handle_result "$_mnr_result" '' "failed to mount usr volume"
+    if  [ ! "$_mnr_result" -eq 0 ] && [ "$init_lock_down" = "no" ]; then
+        ret=1
+        rescue_shell "Failed to mount usr volume"
+    fi
+
+    separator "${PN}-${BUILD}" "(Mounts)"
+    mount | sed 's|^|    |'
+
+    # clean up in preparation to actually switch root - with retry if needed
+    for _mnr_fs in /dev/pts /dev /sys /proc; do
+        info_msg_n "umount ${_mnr_fs} ..."
+        # Try standard unmount
+        umount "${_mnr_fs}"
+        _mnr_result=$?
+        # if standard umount fails, try a "lazy" unmount (-l)
+        # This is often necessary if a process has a lingering handle
+        if [ $_mnr_result -ne 0 ]; then
+            info_msg " (retrying lazy umount...)"
+            umount -l "${_mnr_fs}"
+            _mnr_result=$?
+        fi
+        info_handle_result "$_mnr_result" '' "Critical error: Could not unmount ${_mnr_fs}"
+
+        # fatal exit -- if it's still mounted, switch_root WILL fail.
+        if [ $_mnr_result -ne 0 ]; then
+            if [ "$init_lock_down" = "no" ]; then
+                rescue_shell "Manual intervention required: ${_mnr_fs} is busy."
+            else
+                die "Panic: Critical filesystem ${_mnr_fs} busy during lockdown."
+            fi
+        fi
+    done
+
+    # give more time to read display if debugging
+    [ ! "$QUIET" ] && d_do verbosity=7 sh_countdown "$init_wait" "$debug"
+    unset -v _mnr_result _mnr_fs
+    return $ret
+}
+
+
+validate_volume_and_assign_fs() {
+    ret=0
+    # given the string name of the volume, validate its existence and assign fs type
+    # sets select_keying_device() _vva_EXISTS ("global" here) and
+    # assigns global variable named by $_vva_fs_name (e.g. root_fs, by indirect reference
+    _vva_volume_name=$1
+    # guard - reject invalid variable names, which either
+    #   (1) include chars other than members of [:alnum:] or _, OR
+    #   (2) begins with a numeral are invalid variable names in a POSIX shell
+    case "$_vva_volume_name" in
+        *[![:alnum:]_]* | [0-9]*)
+            error_msg "volume_name [$_vva_volume_name] is not a valid POSIX variable name"
+            unset -v _vva_volume_name ; return 1 ;;
+    esac
+    # POSIX indirect variable assignment
+    eval "_vva_volume=\"\$${_vva_volume_name}\""
+    info_msg "validating volume ${_vva_volume_name} [${_vva_volume}]"
+
+    # caution - an unassigned volume_name (null $my_volume) will evaluate true for [ -b ${my_volume} ]
+    if [ -b "${_vva_volume}" ]; then
+        _vva_EXISTS=$TRUE
+        # use eval to assign the fs type; identify the variable name from the volume name
+        # e.g. if _vva_volume_name = root_volume then _vva_fs_name = root_fs
+        _vva_fs_name=$( printf '%s' "$_vva_volume_name" | sed 's|volume|fs|')
+        # get only the filesystem type and assign it directly to a variable
+        info_msg_n "looking up fs type for ${_vva_volume}"
+        # capture raw blkid output (since BusyBox -o value may fail)
+        _vva_raw_info=$(blkid "${_vva_volume}")
+        # use awk to find the field starting with TYPE= and strip the quotes
+        _vva_fs_type=$(printf '%s' "$_vva_raw_info" | awk -F'TYPE="' '{print $2}' | awk -F'"' '{print $1}')
+        info_handle_result $? "$_vva_fs_type" "failed"
+        # now assign the type to the fs name e.g. root_fs=ext4
+        info_msg_n "performing indirect assignment ${_vva_fs_name}=\"${_vva_fs_type}\""
+        eval "${_vva_fs_name}=\"${_vva_fs_type}\""
+        info_handle_result $? '' ''
+    else
+        _vva_EXISTS=$FALSE
+        printf '%s' " (${BRon}not a blockdev${Boff})"
+        right_status 1
+    fi
+    # keep this check/message outside the if-then-else above, so it can return clean status on the same line
+    if [ $_vva_EXISTS ];    then
+        info_msg "    ${BGon}Valid device${Boff} [${_vva_volume}] type [${TYPE}] ${BGon}Exists${Boff}"
+    else
+        error_msg "    ${BRon}invalid device [${_vva_volume}]${Boff}"
+        _vva_volcase="$(printf '%s' ${_vva_volume_name} | sed 's|_volume||')"
+        case "${_vva_volcase}" in
+            "root"|"usr" ) info_msg "     -- will scan for ${_vva_volcase} volume later, in unlocked volumes" ;;
+            * ) info_msg "    -- invalid case [$_vva_volcase]" ;;
+        esac
+    fi
+    unset -v _vva_volume_name _vva_fs_name _vva_volume _vva_fs_type _vva_answer _vva_EXISTS
+    unset -v  _vva_volcase
+    return $ret
+}
+
+process_cmdline() {
+  ret=0
+  notice_msg "Processing cmdline ..."
+  _pc_line_out=""
+  set -- ${CMDLINE}
+  while [ $# -gt 0 ]; do
+    _pc_entry=$1
+    # strip the longest match for =* from the end; i.e. evrything from the first = onward
+    #  (e.g. keep only 'root' in root=UUID=8234baac-f344-42ac-b08a-5e256d89fd07)
+    _pc_var="${_pc_entry%%=*}"  # equiv $(echo ${_pc_entry} | cut -d'=' -f1) but more efficient
+    # strip the shortest match for *= from front; i.e. from first = and to the left
+    #  (e.g. keep 'UUID=8234baac-...' in root=UUID=8234baac-f344-42ac-b08a-5e256d89fd07)
+    _pc_val="${_pc_entry#*=}"  # equiv $(echo ${_pc_entry} | cut -d'=' -f2-) but more efficient
+    case "$_pc_var" in
+      "verbosity" )
+        export "${_pc_entry}" || die "failed to export verbosity"
+        info_msg "cmdline override: [${_pc_entry}]]"
+      ;;
+      "root" )
+        export root_volume="${_pc_val}" || die "failed to export root_volume"
+        info_msg "cmdline override: [root_volume=${_pc_val}]"
+        _pc_line_out="${_pc_line_out} ${_pc_entry}"
+      ;;
+      "usr" )
+        export usr_volume="${_pc_val}" || die "failed to export usr_volume"
+        info_msg "cmdline override: [usr_volume=${_pc_val}]"
+      ;;
+      * )
+        info_msg "cmdline entry [${_pc_entry}] ignored by initramfs"
+        _pc_line_out="${_pc_line_out} ${_pc_entry}"
+      ;;
+    esac
+    shift  # get next entry from CMDLINE
+  done
+  # reset the CMDLINE without the initramfs-peculiar entries
+  export CMDLINE="${_pc_line_out}"
+  # if not dead from a die command above, then success
+  notice_msg_n "Done processing cmdline; result:"
+  handle_result 0 "exported \$CMDLINE" ""
+  unset -v _pc_line_out _pc_entry _pc_var _pc_val
+  return $ret
+}
+
+select_keying_device() {
+    # go through the list of devices presented as argv -- select the first one that
+    #   has a valid type, actually exists, mounts successfully, and contains a key,
+    #   else fail upon exhaustion of the list
+    # If select_keying_device successfully validates a keying device and keyfile,
+    #   it effectively transitions the system from a "searching" state
+    #   to an "authorized" state for LUKS decryption
+    # assign global unlock_method
+    #
+    ret=0
+    _skd_HAS_KEY=$FALSE
+    # set the input string (list of candidate keying devices) so we can loop thru them safely
+    set -- "$@"
+    _skd_candidate_key_device=""
+
+    # careful: this loop runs for every candidate in the list - it can take a long time with several second delays in each pass
+    _skd_count=1
+    while [ $# -gt 0 ]; do
+        _skd_candidate_key_device="$1"
+        # use get_luks_keyfile to find and mount the device if possible
+        # it returns 0: success; 1: invalid; 2: mount failed; 3: has key failed
+        # it reads global crypt_keydev_mountpoint and exports keyfile
+
+        info_msg_n "assigning crypt_keydev_mountpoint = $init_passdevice_mount_point"
+        crypt_keydev_mountpoint="$init_passdevice_mount_point"
+        info_handle_result $? "assigned" "failed" || die "failed to assign crypt_keydev_mountpoint = \$init_passdevice_mount_point"
+
+        info_msg "calling get_luks_keyfile ${_skd_candidate_key_device}"
+        get_luks_keyfile "${_skd_candidate_key_device}"
+        _skd_result=$?
+        info_handle_result $_skd_result "" "failed with exit code [$_skd_result]"
+        # check for the actual keyfile
+        if [ $_skd_result -eq 0 ]; then
+          _skd_HAS_KEY=$TRUE
+          break # done - we have what we came for
+        else
+          # un-mount if it got mounted
+          if [ "$_skd_result" -eq 3 ]; then
+            info_msg_n "un-mounting candidate that did not have keyfile"
+            umount "${crypt_keydev_mountpoint}" >/dev/null 2>&1
+            info_handle_result $? "un-mounted" "failed" || die "failed to umount ${crypt_keydev_mountpoint}"
+            shift  # go to next candidate device in list
+          fi  # mounted but no key
+        fi  # get_luks_keyfile result
+    done
+    # to leave the loop above, we either --
+    #    (a) found a valid extant device, mounted it and confirmed it contains a key (_skd_HAS_KEY is now "true"), or
+    #    (b) exhausted the init_passdevice_list of devices authorized to be used and found none of them
+    #        on this system (in which case _skd_HAS_KEY is still "false")
+    if [ $_skd_HAS_KEY ]; then
+        unlock_method="key"
+        info_msg "Keystore: [$keyfile] exists - using automatic keying method..."
+        ret=0
+    else
+        unlock_method="prompt"
+        error_msg "${BRon}Keystore: [$keyfile] does not exist - reverting to prompt method...${Boff}"
+        ret=1
+    fi
+    unset -v _skd_HAS_KEY _skd_candidate_key_device _skd_result
+    return $ret
+}
+
+get_keyfile_and_unlock_method() {
+    ret=0
+    separator "${PN}-${BUILD}" "(get keyfile and unlock method)"
+    info_msg_n "Checking if keyfile was specified ..."
+    if [ ! -z "$init_keyfile" ]; then _sku_KF=$TRUE; else _sku_KF=$FALSE; fi
+    [ $_sku_KF ] ; info_handle_result "$?" "yes" "no"
+
+    info_msg_n "Checking if passdevice list was specified ..."
+    if [ ! -z "${init_passdevice_list}" ]; then _sku_PDL=$TRUE; else _sku_PDL=$FALSE; fi
+    [ $_sku_PDL ] ; info_handle_result "$?" "yes" "no"
+
+    if { [ $_sku_KF ] && [ $_sku_PDL ] ; }  ; then
+        # pause to give mdev a chance to recognize devices
+        info_msg "Waiting ${init_mdev_wait} more seconds, per init.conf, to give mdev a chance to recognize hardware..."
+        sh_countdown $init_mdev_wait
+        # this function is the meat of this
+        select_keying_device ${init_passdevice_list}
+        # note that if this succeded, it will have set unlock_method="key"
+        # and it will have assigned the global config variable "init_passdevice"
+    else
+        unlock_method="prompt"
+    fi
+    info_msg "${BWon}Result: ${LBon}keyfile = ${Mon}[ $keyfile ]${Boff}"
+    info_msg "${BWon}Result: ${LBon}unlock_method = ${Mon}[ $unlock_method ]${Boff}"
+    unset -v _sku_KF _sku_PDL
+    return $ret
+}
+
+
diff --git a/dev-util/script_header_joetoo/script_header_joetoo b/dev-util/script_header_joetoo/script_header_joetoo
--- a/dev-util/script_header_joetoo/script_header_joetoo
+++ b/dev-util/script_header_joetoo/script_header_joetoo
@@ -3307,7 +3307,19 @@ _get_luks_keyfile() # (POSIX) find and mount keydev and confirm it has key
   # handle all cases as valid until examined further below
   debug_handle_result 0 "${Boff}${Mon}${_glk_crypt_keydev_type}" ""
 
-  # if _glk_crypt_keydev is not mounted, try to mount it
+  # check if there actually is such a device in the system
+  case "$_glk_crypt_keydev_type" in
+    "devicename" ) [ -b "$_glk_crypt_keydev" ] ; _glk_result=$? ;;
+    "UUID"       ) blkid | grep -q "UUID=\"$_glk_crypt_keydev\"" ; _glk_result=$? ;;
+    "LABEL"      ) blkid | grep -q "LABEL=\"$_glk_crypt_keydev\""; _glk_result=$? ;;
+  esac
+  if [ "$_glk_result" -eq 0 ]; then
+    debug_msg "crypt_keydev [$_glk_crypt_keydev] is of type [$_glk_crypt_keydev_type] and exists"
+  else
+    debug_msg "crypt_keydev [$_glk_crypt_keydev] is of type [$_glk_crypt_keydev_type] but there is no such device"
+    return 2
+  fi
+  # if we got here, it does exist in the system, so if _glk_crypt_keydev is not mounted, try to mount it
   # safe grep: match space-padded " /path " exactly to avoid partial directory false-matches
   # check /proc/mounts directly as the source of truth
   debug_msg_n "checking if ${_glk_crypt_keydev} is mounted"
@@ -3320,12 +3332,6 @@ _get_luks_keyfile() # (POSIX) find and mount keydev and confirm it has key
       "devicename" ) mount "${_glk_crypt_keydev}" "${_glk_mnt_fixed}"; _glk_result=$? ;;
       "UUID"       ) mount UUID="${_glk_crypt_keydev}" "${_glk_mnt_fixed}"; _glk_result=$? ;;
       "LABEL"      ) mount LABEL="${_glk_crypt_keydev}" "${_glk_mnt_fixed}"; _glk_result=$? ;;
-      * )
-        debug_echo_msg " (${BRon}failed${Boff})"
-        error_msg "invalid _glk_crypt_keydev"
-        unset -v _glk_mnt_fixed _glk_crypt_keydev _glk_crypt_keydev_type _glk_result
-        return 1  # invalid type
-        ;;
     esac
     case "$_glk_result" in
       0 ) debug_handle_result 0 "mounted" "" ;;
@@ -3336,12 +3342,12 @@ _get_luks_keyfile() # (POSIX) find and mount keydev and confirm it has key
     esac
     if [ ! "$_glk_result" -eq 0 ]; then
         unset -v _glk_mnt_fixed _glk_crypt_keydev _glk_crypt_keydev_type _glk_result
-        return 2    # mount failure
+        return 3    # mount failure
     fi  # mount failure
   fi  # mounted ?
   debug_msg_n "looking for keyfile"
   [ -f "${_glk_mnt_fixed}/crypt/dat" ]
-  debug_handle_result $? "found" "not found" || return 3    # has key check failure
+  debug_handle_result $? "found" "not found" || return 4    # has key check failure
   # set keyfile pathname
   export keyfile="${_glk_mnt_fixed}/crypt/dat"
   unset -v _glk_mnt_fixed _glk_crypt_keydev _glk_crypt_keydev_type _glk_result
@@ -3391,19 +3397,29 @@ _maybe_select_keying_device() {
         _mskd_result=$?
         debug_msg_n "Done with _get_luks_keyfile; result:"
         debug_handle_result $_mskd_result "keyfile: $keyfile" "failed with exit code [$_mskd_result]"
+        d_do '
+          case "$_mskd_result" in
+            0 ) debug_msg "(debug) exit code [$_mskd_result] means \"success\"" ;;
+            1 ) debug_msg "(debug) exit code [$_mskd_result] means \"no device identified in call\"" ;;
+            2 ) debug_msg "(debug) exit code [$_mskd_result] means \"device does not exist in the system\"" ;;
+            3 ) debug_msg "(debug) exit code [$_mskd_result] means \"device exists, but mount failed\"" ;;
+            4 ) debug_msg "(debug) exit code [$_mskd_result] means \"device exists, mounted, but did not have key\"" ;;
+            * ) debug_msg "(debug) exit code [$_mskd_result] means \"invalid exit code\"" ;;
+          esac
+        ' "$debug"
         # check for the actual keyfile
         if [ $_mskd_result -eq 0 ]; then
           _mskd_HAS_KEY=$TRUE
           break # done - we have what we came for
         else
-          # un-mount if it got mounted
-          if [ "$_mskd_result" -eq 3 ]; then
+          # un-mount if it got mounted but did not have the key
+          if [ "$_mskd_result" -eq 4 ]; then
             debug_msg_n "un-mounting candidate that did not have keyfile"
             umount "${crypt_keydev_mountpoint}" >/dev/null 2>&1
             debug_handle_result $? "un-mounted" "failed" || die "failed to umount ${crypt_keydev_mountpoint}"
-            shift  # go to next candidate device in list
           fi  # mounted but no key
         fi  # get_luks_keyfile result
+        shift  # go to next candidate device in list
     done
     # to leave the loop above, we either --
     #    (a) found a valid extant device, mounted it and confirmed it contains a key (_mskd_HAS_KEY is now "true"), or
@@ -3477,8 +3493,10 @@ unlock_luks_devices()
     [ $# -eq 0 ] && \
         { error_msg "unlock_luks_devices requires a non-emply device list"; return 1; }
 
+    debug_msg "(debug) in unlock_luks_devices with \$2: [$@]"
+
     # determine unlock_method
-    notice_msg "Determining unlock method"    
+    notice_msg "Determining unlock method"
     _get_unlock_method
     notice_msg_n "Done determining unlock method:"
     handle_result $? "method: $unlock_method" ""
@@ -3494,6 +3512,8 @@ unlock_luks_devices()
     while [ $# -gt 0 ]; do
         _ulds_device="$1"
         notice_msg "Unlocking device: $_ulds_device"
+        debug_msg "(debug) unlock_method: $unlock_method"
+        debug_msg "(debug) _ulds_device: $_ulds_device"
         _unlock_device "$unlock_method" "$_ulds_device" ; _ulds_result=$?
         notice_msg_n "Done unlocking device; result:"
         handle_result $_ulds_result "" ""
