fixed some bug
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-util/script_header_joetoo/archive/script_header_joetoo_archive b/dev-util/script_header_joetoo/archive/script_header_joetoo_archive
--- a/dev-util/script_header_joetoo/archive/script_header_joetoo_archive
+++ b/dev-util/script_header_joetoo/archive/script_header_joetoo_archive
@@ -1831,3 +1831,37 @@ box_msg_bash() # (LINUX BASH) $1=msg, $2=width, $3=center, $4=color
     printf "%b" "$OFF"
 
 }
+---------------------------------------
+this is an old initramfs function to try to get console working right
+
+maybe_redirect_output() # if /dev/console is writable, deliberately redirect output there
+{
+  # (1) /dev/console is created by mksources ( mknod -m 600 console c 5 1 ), and even if not,
+  # then now that /dev is populated by mini_udev, the device node should exist [ -c test ].
+  # However - that doesn't guarantee that the kernel will have loaded drivers capable of using it
+  # (serial/VGA for example), so we need to check the devices "writability" [ -w test ], to be sure
+  # implement a bounded wait here, incase it hasn't happened "yet"
+  # note: -w implies -c so don't need to check both
+  mro_ret=0
+  _mro_init_shortwait="0.1"
+  _mro_init_console_retry=0; _mro_init_max_retry=30    # max wait 3 seconds total
+  while [ ! -w /dev/console ] && [ "$_mro_init_console_retry" -lt "$_mro_init_max_retry" ]; do
+    sleep "$_mro_init_shortwait"
+    mro_ret=1
+    _mro_init_console_retry=$((_mro_init_console_retry + 1))
+  done
+  if [ -w /dev/console ]; then
+    exec > /dev/console 2>&1
+    # Subsequent messages now appear on the actual boot console 
+    notice_msg "Standard and Error output redirected to /dev/console"
+    mro_ret=0
+  else
+    # if -c passes but -w fails, the node exists but the device is not ready for output 
+    warn_msg "Warning: /dev/console exists but is not writable. Redirection skipped." >&2
+    mro_ret=1
+  fi
+  unset -v _mro_init_console_retry _mro_init_shortwait _mro_init_max_retry
+  return $mro_ret
+}
+
+
diff --git a/dev-util/script_header_joetoo/script_header_joetoo b/dev-util/script_header_joetoo/script_header_joetoo
--- a/dev-util/script_header_joetoo/script_header_joetoo
+++ b/dev-util/script_header_joetoo/script_header_joetoo
@@ -3121,27 +3121,37 @@ get_luks_keyfile() # (POSIX) find and mount keydev and confirm it has key
   # check /proc/mounts directly as the source of truth
   notice_msg_n "checking if ${_glk_crypt_keydev} is mounted"
   if grep -q " ${_glk_mnt_fixed} " /proc/mounts; then
-    handle_result $TRUE "mounted" "not mounted"
+    handle_result 0 "mounted" ""
   else
+    handle_result 1 "" "not mounted"
     notice_msg_n "trying to mount (${_glk_crypt_keydev_type}) [${_glk_crypt_keydev}] ..."
-    case $_glk_crypt_keydev_type in
-       "devicename" ) mount "${_glk_crypt_keydev}" "${_glk_mnt_fixed}" ;;
-       "UUID"       ) mount UUID="${_glk_crypt_keydev}" "${_glk_mnt_fixed}" ;;
-       "LABEL"      ) mount LABEL="${_glk_crypt_keydev}" "${_glk_mnt_fixed}" ;;
-       * )
+    case "$_glk_crypt_keydev_type" in
+      "devicename" ) mount "${_glk_crypt_keydev}" "${_glk_mnt_fixed}"; _glk_result=$? ;;
+      "UUID"       ) mount UUID="${_glk_crypt_keydev}" "${_glk_mnt_fixed}"; _glk_result=$? ;;
+      "LABEL"      ) mount LABEL="${_glk_crypt_keydev}" "${_glk_mnt_fixed}"; _glk_result=$? ;;
+      * )
         printf '%b' " (${BRon}failed${Boff}) ..."
         right_status 1
         error_msg "invalid _glk_crypt_keydev"
         unset -v _glk_mnt_fixed _glk_crypt_keydev _glk_crypt_keydev_type _glk_result
-        return 1
+        return 1  # invalid type
         ;;
     esac
-    handle_result $? "mounted" "could not mount _glk_crypt_keydev ($_glk_crypt_keydev_type)" || \
-      { unset -v _glk_mnt_fixed _glk_crypt_keydev _glk_crypt_keydev_type _glk_result; return 2 ; }
-  fi
+    case "$_glk_result" in
+      0 ) handle_result 0 "mounted" "" ;;
+      1 ) handle_result 1 "" "mount failure (device missing, wrong FS, permission, etc)" ;;
+      2 ) handle_result 2 "" "mount usage/syntax error" ;;
+      32 ) handle_result 32 "" "filesystem helper error (only for helper-based FS types)" ;;
+      * ) handle_result 99 "" "mount failure of unknown type" ;;
+    esac
+    if [ ! "$_glk_result" -eq 0 ]; then
+        unset -v _glk_mnt_fixed _glk_crypt_keydev _glk_crypt_keydev_type _glk_result
+        return 2    # mount failure
+    fi  # mount failure
+  fi  # mounted ?
   notice_msg_n "looking for keyfile"
   [ -f "${_glk_mnt_fixed}/crypt/dat" ]
-  handle_result $? "found" "not found" || return 3
+  handle_result $? "found" "not found" || return 3    # has key check failure
   # set keyfile pathname
   export keyfile="${_glk_mnt_fixed}/crypt/dat"
   unset -v _glk_mnt_fixed _glk_crypt_keydev _glk_crypt_keydev_type _glk_result
@@ -3153,7 +3163,7 @@ get_luks_keyfile() # (POSIX) find and mount keydev and confirm it has key
 # @deps mount grep right_status notice_msg_n die
 # @rule identifies device type (dev/UUID/LABEL) using POSIX case patterns
 # @rule verifies mount status via /proc/mounts with space-padding to prevent false matches
-# @ret 0: success; 1: invalid; 2: mount fail; 3: has key fail
+# @ret 0: success; 1: invalid type; 2: mount fail; 3: has key fail
 # @note Note: crypt_keydev_mountpoint must be globally defined by the calling script
 # @note exports the $keyfile variable for use by cryptsetup or other LUKS tools
 
@@ -3162,7 +3172,7 @@ get_luks_edev_name()  # (POSIX) determine an edev name to use with this device
   [ -z "${luks_partition_device}" ] && die "luks_partition_device not defined"
   # ( e.g. sda2->eda2 nvme0n1p2->ev012 mmcblk0p2->em02 )
   _glen_bn="${luks_partition_device##*/}" # equivalent to $(basename ${luks_partition_device})
-  notice_msg_n "determining edev name ..."
+  info_msg_n "determining edev name ..."
   case ${_glen_bn} in
       "sd"* ) # scsi device (sda2 -> eda2)
         # strip s w/ parameter expansion, and replace w/ e
@@ -3178,12 +3188,12 @@ get_luks_edev_name()  # (POSIX) determine an edev name to use with this device
         _glen_tmp="${_glen_bn#mmcblk}"
         _glen_myedev="em$(printf '%s' "$_glen_tmp" | tr -d 'p')"
         ;;
-      *    ) # tbd
-        echo_msg "" ; die "bad luks device name [${_glen_bn}]"
+      *    ) # tbd (newline; error die)
+        echo_msg; error_msg "" ; die "bad luks device name [${_glen_bn}]"
         ;;
     esac
     _glen_result=$?
-    echo_msg_n " (${_glen_myedev})" ; right_status 0
+    info_echo_msg_n " (${Con}${_glen_myedev}${Boff})" ; right_status 0
     export edev=${_glen_myedev}
     unset -v _glen_bn _glen_myedev _glen_tmp _glen_result
     return 0
