kernelupdate-0.11.11.tbz2 bugfix cd _old_dir
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/sys-kernel/kernelupdate/kernelupdate b/sys-kernel/kernelupdate/kernelupdate
--- a/sys-kernel/kernelupdate/kernelupdate
+++ b/sys-kernel/kernelupdate/kernelupdate
@@ -273,9 +273,9 @@ kernelupdate_configure()
   if [[ ! -e "${sources_dir}" ]] ; then
       version_number="<TBD>"
   else
-      notice_msg "Old pwd: $PWD - moving to sources_dir"
-      cd "${sources_dir%/}" ; handle_result $? "PWD" "" || die "failed to cd sources_dir for kernelversion"
-      notice_msg "gettig kernel version"
+      notice_msg_n "Old pwd: [$PWD]; moving to sources_dir"
+      cd "${sources_dir%/}" ; handle_result $? "$PWD" "" || die "failed to cd sources_dir for kernelversion"
+      notice_msg_n "gettig kernel version"
       version_number=$("${make_me[@]}" -s kernelversion)
       handle_result $? "$version_number" "" || die "failed to get kernelversion"
       # domU using gentoo-sources, will get version line "X.Y.Z-gentoo"
@@ -306,7 +306,7 @@ kernelupdate_configure()
   publish_ebuild_cmd_file="${build_dir%/}/publish_ebuild_${kernel_image_name}"
   debug_handle_result $? "$publish_ebuild_cmd_file" "" || die "failed to assign publish_ebuild_cmd_file"
 
-  notice_msg "returning to _old_dir"
+  notice_msg_n "returning to _old_dir"
   cd "$_old_dir"; handle_result $? "$PWD" "" || die "fained to cd $_old_dir"
   notice_msg "done setup and auto-configure"
 
@@ -318,7 +318,6 @@ display_config()
     local longest=$(get_longest ${varlist})
     local _msg0 _msg1 _msg2
     notice_msg "${BMon}Current Configuration:${Boff}"
-    display_vars ${longest} "config_dir"
     separator "$(hostname) $PN-$BUILD" "(joetoo header configuration)"
     display_vars ${longest} ${header_varlist}
     echo
@@ -371,7 +370,7 @@ run_make_me()
   cd "$sources_dir"; handle_result $? "$PWD" "" || die "failed to cd sources_dir for run_make_me"
   "${make_me[@]}" "$@" ; _result=$?
   notice_msg_n "returning to _old_dir"
-  cd "$old_dir" ; handle_result $? "$PWD" "" || die "failed to cd _old_dir for run_make_me"
+  cd "$_old_dir" ; handle_result $? "$PWD" "" || die "failed to cd _old_dir for run_make_me"
   return $_result
 }
 # @usage run_make_me <make_target>
@@ -410,7 +409,7 @@ warn_oldconfig() {
         notice_msg_n "done running \"\${make_me[@]}\" olddefconfig; result:"
         handle_result $_result "" "" || return 1
         notice_msg_n "returning to _old_dir"
-        cd "$old_dir" ; handle_result $? "$PWD" "" || die "failed to cd _old_dir for warn_oldconfig"
+        cd "$_old_dir" ; handle_result $? "$PWD" "" || die "failed to cd _old_dir for warn_oldconfig"
         ;;
     [sS]* ) notice_msg "skipping as instructed" ; return 0 ;;
     [nN]* ) error_msg "negative answer; aborting" ; return 1 ;;
@@ -473,7 +472,7 @@ make_mrproper() {
     fi
 
     notice_msg_n "returning to _old_dir"
-    cd "$old_dir" ; handle_result $? "$PWD" "" || die "failed to cd _old_dir for make_mrproper"
+    cd "$_old_dir" ; handle_result $? "$PWD" "" || die "failed to cd _old_dir for make_mrproper"
 
     return 0
 }
@@ -524,7 +523,7 @@ make_dtbs() {
     [[ ! "${model}" == dom* ]] && "${make_me[@]}" dtbs
     result=$? ; return $result
     notice_msg_n "returning to _old_dir"
-    cd "$old_dir" ; handle_result $? "$PWD" "" || die "failed to cd _old_dir for make_dtbs"
+    cd "$_old_dir" ; handle_result $? "$PWD" "" || die "failed to cd _old_dir for make_dtbs"
 
 }
 
@@ -614,7 +613,7 @@ install_kernel()
     fi
 
     notice_msg_n "returning to _old_dir"
-    cd "$old_dir" ; handle_result $? "$PWD" "" || die "failed to cd _old_dir for install_kernel"
+    cd "$_old_dir" ; handle_result $? "$PWD" "" || die "failed to cd _old_dir for install_kernel"
 
     [ "$_ik_FLAGGED" ] && error_msg "exiting ${FUNCNAME[0]} with error, exit status [$_result]"
     return $_result
@@ -667,7 +666,7 @@ install_modules()
   handle_result $_result "" ""
 
   notice_msg_n "returning to _old_dir"
-  cd "$old_dir" ; handle_result $? "$PWD" "" || die "failed to cd _old_dir for install_modules"
+  cd "$_old_dir" ; handle_result $? "$PWD" "" || die "failed to cd _old_dir for install_modules"
   return 0
 }
 
@@ -732,7 +731,7 @@ install_dtbs()
 #    mkdir -p ${boot_dir%/}/entire_source_dts
 #    cp -av ${model_dir%/}/arch/${arch}/boot/dts ${boot_dir%/}/entire_source_dts/
     notice_msg_n "returning to _old_dir"
-    cd "$old_dir" ; handle_result $? "$PWD" "" || die "failed to cd _old_dir for install_dtbs"
+    cd "$_old_dir" ; handle_result $? "$PWD" "" || die "failed to cd _old_dir for install_dtbs"
 
     return 0
 }
@@ -792,7 +791,7 @@ make_tarball()
     right_status $?
 
     notice_msg_n "returning to _old_dir"
-    cd "$old_dir" ; handle_result $? "$PWD" "" || die "failed to cd _old_dir for make_tarball"
+    cd "$_old_dir" ; handle_result $? "$PWD" "" || die "failed to cd _old_dir for make_tarball"
     return 0
 }
 
@@ -857,7 +856,7 @@ publish_tarball() {
     sudo -u "${_user}" "${publish_tarball_cmd_file}"
 
     notice_msg_n "returning to _old_dir"
-    cd "$old_dir" ; handle_result $? "$PWD" "" || die "failed to cd _old_dir for publish_tarball"
+    cd "$_old_dir" ; handle_result $? "$PWD" "" || die "failed to cd _old_dir for publish_tarball"
 
     _result=$? ; return $_result
 }
@@ -1046,7 +1045,7 @@ publish_ebuild() {
     sudo -u "${_user}" "${publish_ebuild_cmd_file}"
 
     notice_msg_n "returning to _old_dir"
-    cd "$old_dir" ; handle_result $? "$PWD" "" || die "failed to cd _old_dir for publish_ebuild"
+    cd "$_old_dir" ; handle_result $? "$PWD" "" || die "failed to cd _old_dir for publish_ebuild"
 
     _result=$? ; return $_result
 }
