bugfix
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/sys-kernel/kernelupdate/kernelupdate b/sys-kernel/kernelupdate/kernelupdate
--- a/sys-kernel/kernelupdate/kernelupdate
+++ b/sys-kernel/kernelupdate/kernelupdate
@@ -122,8 +122,6 @@ copypaste_parmlist="lv.make_model lv.manual_prefix lv.make_me"
 
 varlist="${config_parmlist} ${auto_parmlist} ${output_parmlist} ${copypaste_parmlist}"
 
-
-
 # append "/" to dtb_folder and overlay_folder if missing and not null
 #( [[ ${#dtb_folder} -gt 0 ]] && [[ ! "${dtb_folder: -1}" == "/" ]] ) && dtb_folder+="/"
 #( [[ ${#overlay_folder} -gt 0 ]] && [[ ! "${overlay_folder: -1}" == "/" ]] ) && overlay_folder+="/"
@@ -319,29 +317,29 @@ warn_oldconfig() {
 }
 
 make_mrproper() {
-  # clean up both the sources and build directories
-  message "Now working in $PWD (should be sources directory)"
-  clean_make_me="MAKEOPTS=\"${makeopts}\" FEATURES=\"${features}\" "
-  clean_make_me+="make ARCH=${arch} CROSS_COMPILE=${cross_compile} "
-  d_message "Cleaning sources directory [ ${sources_dir} ] ..." 1
-  eval ${clean_make_me} mrproper || die "failed to clean_make_me mrproper"
-  d_message "Cleaning ${model} build directory [ ${model_dir} ] ..." 1
-  eval ${make_me} mrproper || die "failed to make_me mrproper"
-  d_message "*Completely* cleaning ${model} build directory ..." 1
-  # CAUTION: this will destroy your system if KBUILD_OUTPUT is unassigned
-  if [ ! -z "${KBUILD_OUTPUT" ] ; then
-    answer=""
-    message "${BYon}Caution: About to remove KBUILD_OUTPUT filestructure with ${BRon}rm -r ${KBUILD_OUTPUT}/* ${KBUILD_OUTPUT}/*${Boff} "
-    prompt "${BWon}(Y: Ok to continue ; N: No, abort)"
-    if [[ "${answer}" == [yY] ]] ; then
-      rm -r ${KBUILD_OUTPUT}/* ${KBUILD_OUTPUT}/* || die "failed while trying to delete KBUILD_OUTPUT filestructure"
+    # clean up both the sources and build directories
+    message "Now working in $PWD (should be sources directory)"
+    clean_make_me="MAKEOPTS=\"${makeopts}\" FEATURES=\"${features}\" "
+    clean_make_me+="make ARCH=${arch} CROSS_COMPILE=${cross_compile} "
+    d_message "Cleaning sources directory [ ${sources_dir} ] ..." 1
+    eval ${clean_make_me} mrproper || die "failed to clean_make_me mrproper"
+    d_message "Cleaning ${model} build directory [ ${model_dir} ] ..." 1
+    eval ${make_me} mrproper || die "failed to make_me mrproper"
+    d_message "*Completely* cleaning ${model} build directory ..." 1
+    # CAUTION: this will destroy your system if KBUILD_OUTPUT is unassigned
+    if [ ! -z "${KBUILD_OUTPUT}" ] ; then
+        answer=""
+        message "${BYon}Caution: About to remove KBUILD_OUTPUT filestructure with ${BRon}rm -r ${KBUILD_OUTPUT}/* ${KBUILD_OUTPUT}/*${Boff} "
+        prompt "${BWon}(Y: Ok to continue ; N: No, abort)"
+        if [[ "${answer}" == [yY] ]] ; then
+            rm -r ${KBUILD_OUTPUT}/* ${KBUILD_OUTPUT}/* || die "failed while trying to delete KBUILD_OUTPUT filestructure"
+        else
+            die "aborting, as instructed"
+        fi
     else
-      die "aborting, as instructed"
+        die "KBUILD_OUTPUT [${KBUILD_OUTPUT}] appears to be null; not running rm command; exiting"
     fi
-  else
-    die "KBUILD_OUTPUT [${KBUILD_OUTPUT}] appears to be null; not running rm command; exiting"
-  fi
-  return 0
+    return 0
 }
 
 backup_config() {
@@ -594,7 +592,8 @@ publish_ebuild() {
     #   (so I'm going back to an ebuild for the kernel for each model)
 
     publish_ebuild_command_sequence=()
-    publish_ebuild_command_sequence=('#!/bin/bash' \
+    publish_ebuild_command_sequence=( \
+        '#!/bin/bash' \
         'export SSH_AUTH_SOCK="'"${SSH_AUTH_SOCK}"'"' \
         "ssh-add -l 2>/dev/null >/dev/null" \
         '[ $? -ge 2 ] && ssh-agent -a ${SSH_AUTH_SOCK} >/dev/null' \
@@ -604,7 +603,8 @@ publish_ebuild() {
         "echo" \
         "cd ${ebuild_dir%/}/" \
         "echo new PWD: \${PWD}" \
-        "git pull" )
+        "git pull" \
+        )
 
     # if the ebuild_dir does not exist, create it
     if [[ ! -d "${ebuild_dir}" ]] ; then
@@ -704,9 +704,7 @@ publish_ebuild() {
     message "old ebuild full pathname: ${ebuild_dir%/}/${kernel_basename}-${old_version}.ebuild"
     message "new ebuild full pathname: ${ebuild_dir%/}/${kernel_image_name}.ebuild"
     cp ${ebuild_dir%/}/${kernel_basename}-${old_version}.ebuild ${ebuild_dir%/}/${kernel_image_name}.ebuild
-    # don't chown -R ${variable}/ -- if variable is null, it will dork up your filesystem
-#    chown -R ${user}:${user} ${ebuild_dir%/}/
-    chown -R ${user}:${user} ${ebuild_dir%/}
+    chown -R ${user}:${user} ${ebuild_dir%/}/
     # remove the old Manifest file
     rm ${ebuild_dir%/}/Manifest 2>/dev/null
 
@@ -884,3 +882,6 @@ final_msg="${BMon}Components, including kernel image [ ${image} ], modules, over
 final_msg+="and dtb files, as appropriate for model [ ${model} ], successfully staged in "
 final_msg+="${build_dir%/}/${model} and published in ${kernel_image_name}.ebuild${Boff}"
 message "${final_msg}"
+
+#message "${BMon}Debug Marker${Boff}"  ; exit
+
