bugfix use of rm command for cleanup
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/sys-kernel/kernelupdate/kernelupdate b/sys-kernel/kernelupdate/kernelupdate
--- a/sys-kernel/kernelupdate/kernelupdate
+++ b/sys-kernel/kernelupdate/kernelupdate
@@ -330,10 +330,10 @@ make_mrproper() {
     # CAUTION: this will destroy your system if model_dir%/ is unassigned
     if [ ! -z "${model_dir%/}" ] ; then
         answer=""
-        message "${BYon}Caution: About to remove ${model_dir%/} filestructure with ${BRon}rm -r ${model_dir%/}/* ${model_dir%/}/*${Boff} "
+        message "${BYon}Caution: About to remove ${model_dir%/} filestructure with ${BRon}rm -r -f ${model_dir%/}/* ${model_dir%/}/.*${Boff} "
         prompt "${BWon}(Y: Ok to continue ; N: No, abort)"
         if [[ "${answer}" == [yY] ]] ; then
-            rm -r ${model_dir%/}/* ${model_dir%/}/* || die "failed while trying to delete ${model_dir%/} filestructure"
+            rm -r -f ${model_dir%/}/* ${model_dir%/}/.* || die "failed while trying to delete ${model_dir%/} filestructure"
         else
             die "aborting, as instructed"
         fi
