bugfix kernelupdate to prevent destruction of users filesystem by malformed rm command
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/sys-kernel/kernelupdate/kernelupdate b/sys-kernel/kernelupdate/kernelupdate
--- a/sys-kernel/kernelupdate/kernelupdate
+++ b/sys-kernel/kernelupdate/kernelupdate
@@ -153,7 +153,8 @@ module_dir="<TBD>"  # to be set after make modules_install
 [[ "${model}" == "domU" ]] && \
 [[ ! -d "${host_dir}" ]]    && mkdir -pv -m 755 "${host_dir}"    && chown ${user}:${user} "${host_dir}"
 
-# set up the parts of the make command
+# set up the parts of the make command 
+# NOTE: this does not set the environment variables directly, it creates a string that will do so when evaluated as (part of) a command
 make_prefix="MAKEOPTS="
 make_prefix+="\"${makeopts}\" "
 make_prefix+=" FEATURES="
@@ -326,18 +327,18 @@ make_mrproper() {
     d_message "Cleaning ${model} build directory [ ${model_dir} ] ..." 1
     eval ${make_me} mrproper || die "failed to make_me mrproper"
     d_message "*Completely* cleaning ${model} build directory ..." 1
-    # CAUTION: this will destroy your system if KBUILD_OUTPUT is unassigned
-    if [ ! -z "${KBUILD_OUTPUT}" ] ; then
+    # CAUTION: this will destroy your system if model_dir%/ is unassigned
+    if [ ! -z "${model_dir%/}" ] ; then
         answer=""
-        message "${BYon}Caution: About to remove KBUILD_OUTPUT filestructure with ${BRon}rm -r ${KBUILD_OUTPUT}/* ${KBUILD_OUTPUT}/*${Boff} "
+        message "${BYon}Caution: About to remove ${model_dir%/} filestructure with ${BRon}rm -r ${model_dir%/}/* ${model_dir%/}/*${Boff} "
         prompt "${BWon}(Y: Ok to continue ; N: No, abort)"
         if [[ "${answer}" == [yY] ]] ; then
-            rm -r ${KBUILD_OUTPUT}/* ${KBUILD_OUTPUT}/* || die "failed while trying to delete KBUILD_OUTPUT filestructure"
+            rm -r ${model_dir%/}/* ${model_dir%/}/* || die "failed while trying to delete ${model_dir%/} filestructure"
         else
             die "aborting, as instructed"
         fi
     else
-        die "KBUILD_OUTPUT [${KBUILD_OUTPUT}] appears to be null; not running rm command; exiting"
+        die "model_dir [${model_dir%/}] appears to be null; not running rm command; exiting"
     fi
     return 0
 }
