kernelupdate and 80joetoo_common package.use updates
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/sys-kernel/kernelupdate/kernelupdate b/sys-kernel/kernelupdate/kernelupdate
--- a/sys-kernel/kernelupdate/kernelupdate
+++ b/sys-kernel/kernelupdate/kernelupdate
@@ -286,9 +286,25 @@ warn_oldconfig() {
   message "  ${LBon}run ${BBon}${sources_dir%/}/ # ${Gon}eval \${make_me} olddefconfig${Boff}"
   message "  ${BYon}and then restart this program with e.g. ${Gon}${PN} -r${Boff}"
   echo
-  newanswer=""
-  new_prompt "${BYon}Do you want to just go ahead and run ${Gon}eval \${make_me} olddefconfig ${BYon} now? ${Boff}(YyNnSs) "
-  expr "${newanswer:0:1}" : [yY] >/dev/null && eval ${make_me} olddefconfig
+  response=""
+  msg="${BYon}Do you want run ${Gon}eval \${make_me} olddefconfig ${BYon} now? ${Boff}\n"
+  msg+="${BWon}   (Y: yes, run it; N: no, abort; S: skip, to next step) ${Boff}"
+  new_prompt "${msg}"
+  d_message "response: $response" 5
+  case ${response:0:1} in
+    [yY] ) eval ${make_me} olddefconfig ; result=$?;
+      if [ $result -eq 0 ] ; then
+        d_message "make olddefconfig succeeded" 1
+      else
+        E_message "make olddefconfig failed"
+        return 1
+      fi
+      ;;
+    [sS] ) d_message "skipping as instructed" 2 ; return 0 ;;
+    [nN] ) E_message "negative answer; aborting" ; return 1 ;;
+    *    ) die "invalid newanser (should never happen)" ;;
+  esac
+  return 0
 }
 
 make_mrproper() {
@@ -768,15 +784,16 @@ then
   else
     # confirm the current configuration before executing main script
     prompt "${BYon}Starting ${PN}.\n Please confirm configuration above.\n${LBon}Continue? ${Boff}?"
-    [[ ! $answer == [Yy] ]] && exit
+    [[ ! $answer == [Yy] ]] && return 1
   fi
 else
   # resume operation at some step other than 0
   do_first_prompt="${BMon}Resuming at step [ ${BWon}$starting_step${BMon} ] --[ ${BGon}${command_sequence[${starting_step}]}${BMon} ]--${Boff}\n"
   do_first_prompt+="${BYon}Please verify configuration above.${Boff}"
   prompt "${do_first_prompt}\n${LBon} Continue? ${Boff}?"
-  [[ ! $answer == [yY] ]] && exit
+  [[ ! $answer == [yY] ]] && return 1
 fi
+return 0
 }
 
 #-----[ main script ]------------------------------------------------
