crossbuild-tools-0.10.2.tbz2
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-sbc/crossbuild-tools/cb-chroot-target b/dev-sbc/crossbuild-tools/cb-chroot-target
--- a/dev-sbc/crossbuild-tools/cb-chroot-target
+++ b/dev-sbc/crossbuild-tools/cb-chroot-target
@@ -18,6 +18,9 @@ PN=$(basename $0)
 message_n "sourcing cb-common-functions ..."
 source /usr/sbin/cb-common-functions ; right_status $?
 
+message_n "assigning user = joe (used to find/mount /home/<user>/xxx-sources)"
+user="joe" && right_status $? || die "failed to assign user"
+
 TARGET=""
 
 usage() {
@@ -87,51 +90,37 @@ validate-repo-mountpoints() {
     return 0
 }
 
-validate-dirlist() {
-    separator "${PN}" "(${FUNCNAME[0]})"
-    dirlist="proc dev usr/src/linux lib/modules sys tmp dev/pts"
-
-    # ensure all the needed filesystem structures are present
-    for x in ${dirlist}
-    do
-        message_n "examining $x"
-        if [ ! -d $x ] ; then
-          echo -en " (does not exist)"
-          mkdir -p $x >/dev/null 2>/dev/null && echo -en " (${BGon}created${Boff})" || die "failed to mkdir -pv $x"
-        else
-          echo -en " (${BGon}exists${Boff})"
-        fi
-        right_status $TRUE
-    done
-    return 0
-}
+# moved validate-dirlist to cb-common-functions
 
 mount-everything() {
     separator "${PN}" "(${FUNCNAME[0]})"
-    message_n "mounting proc for chroot target ..."
-    mount -t proc none /usr/${TARGET}/proc >/dev/null 2>&1 && \
-        right_status $? || die "failed to mount /proc"
-    message_n "mounting dev for chroot target ..."
-    mount -o bind /dev /usr/${TARGET}/dev >/dev/null 2>&1 && \
-        right_status $? || die "failed to mount /dev"
-    message_n "mounting var/db/repos/joetoo for chroot target ..."
-    mount -o bind /var/db/repos/joetoo /usr/${TARGET}/var/db/repos/joetoo >/dev/null 2>&1 && \
-        right_status $? || die "failed to mount host repo joetoo"
-    message_n "mounting var/db/repos/gentoo for chroot target ..."
-    mount -o bind /var/db/repos/gentoo /usr/${TARGET}/var/db/repos/gentoo >/dev/null 2>&1 && \
-        right_status $? || die "failed to mount host repo gentoo"
-    message_n "mounting usr/src/linux for chroot target ..."
-    mount -o bind /home/joe/raspi-sources/linux /usr/${TARGET}/usr/src/linux >/dev/null 2>&1 && \
-        right_status $? || die "failed to mount host kernel sources"
-    message_n "mounting lib/modules for chroot target ..."
-    mount -o bind /lib/modules /usr/${TARGET}/lib/modules >/dev/null 2>&1 && \
-        right_status $? || die "failed to mount host modules"
-    message_n "mounting sys for chroot target ..."
-    mount -o bind /sys /usr/${TARGET}/sys >/dev/null 2>&1 && \
-        right_status $? || die "failed to mount /sys"
+
+    # copy resolv.conf
     message_n "copying /etc/resolv.conf for chroot target ..."
     cp /etc/resolv.conf /usr/${TARGET}/etc/resolv.conf >/dev/null 2>&1 && \
         right_status $? || die "failed to copy resolv.conf"
+
+    # mount chroot-prep stuff
+    mount_list="proc dev sys lib/modules "
+    # and repos
+    mount_list+="var/db/repos/gentoo var/db/repos/joetoo"
+    mount-chroot-prep || die "failed mount-chroot-prep for ${PN}"
+
+    # mount kernel sources
+    message_n "looking for kernel sources"
+    case ${BOARD:0:2} in
+        "bc" ) SOURCES="raspi-sources" ;;
+        "rk" ) SOURCES="rockchip-sources" ;;
+        "fs" ) SOURCES="nxp-sources" ;;
+        "me" ) SOURCES="amlogic-sources" ;;
+        *    ) die "sources for board [$BOARD] not supported (yet)"
+    esac
+    [ ! -d /home/${user}/${SOURCES}/linux ] && echo && die "could not find kernel sources [/home/${user}/${SOURCES}/linux]"
+    right_status $TRUE
+    message_n "mounting usr/src/linux for chroot target ..."
+    mount -o bind /home/${user}/${SOURCES}/linux /usr/${TARGET}/usr/src/chroot-sources-mountpoint >/dev/null 2>&1 && \
+        right_status $? || die "failed to mount host kernel sources"
+
     #mount -o bind /tmp tmp
     #mount -o bind /dev/pts dev/pts #only for X
     return 0
@@ -142,20 +131,14 @@ umount-everything() {
     #umount /usr/${TARGET}/dev/pts
     #umount /usr/${TARGET}/tmp
     FLAGGED=$FALSE
-    message_n "un-mounting sys from chroot target ..."
-    umount /usr/${TARGET}/sys && right_status $? || ( right_status $? && FLAGGED=$TRUE )
-    message_n "un-mounting lib/modules from chroot target ..."
-    umount /usr/${TARGET}/lib/modules && right_status $? || ( right_status $? && FLAGGED=$TRUE )
-    message_n "un-mounting usr/src/linux from chroot target ..."
-    umount /usr/${TARGET}/usr/src/linux && right_status $? || ( right_status $? && FLAGGED=$TRUE )
-    message_n "un-mounting var/db/repos/gentoo from chroot target ..."
-    umount /usr/${TARGET}/var/db/repos/gentoo && right_status $? || ( right_status $? && FLAGGED=$TRUE )
-    message_n "un-mounting var/db/repos/joetoo from chroot target ..."
-    umount /usr/${TARGET}/var/db/repos/joetoo && right_status $? || ( right_status $? && FLAGGED=$TRUE )
-    message_n "un-mounting dev from chroot target ..."
-    umount /usr/${TARGET}/dev && right_status $? || ( right_status $? && FLAGGED=$TRUE )
-    message_n "un-mounting proc from chroot target ..."
-    umount /usr/${TARGET}/proc && right_status $? || ( right_status $? && FLAGGED=$TRUE )
+    # chroot-prep stuff
+    mount_list="proc dev sys lib/modules "
+    # and repos (but not crossdev)
+    mount_list+=" var/db/repos/gentoo var/db/repos/joetoo"
+    # and kernel sources
+    mount_list+=" usr/src/chroot-sources-mountpoint"
+    umount-chroot-prep || FLAGGED=$TRUE
+
     [ $FLAGGED ] && return 1 || return 0
 }
 
@@ -180,7 +163,11 @@ message "now working in crossbuild target directory: [${Mon}$(pwd)${Boff}]"
 
 validate-repo-mountpoints || die "failed to validate-repo-mountpoints"
 
-validate-dirlist || die "failed to validate-dirlist"
+# set dirlist for cb-chroot-target
+dirlist="proc dev sys tmp dev/pts"
+dirlist+=" chroot_sources_mountpoint lib/modules"
+#    dirlist+=" var/db/repos/gentoo var/db/repos/joetoo var/db/repos/crossdev"
+validate-chroot-mountpoint-dirlist || die "failed validate-chroot-mountpoint-dirlist for ${PN}"
 
 mount-everything || die "failed to mount-everything"
  
diff --git a/dev-sbc/crossbuild-tools/cb-chroot-target-image b/dev-sbc/crossbuild-tools/cb-chroot-target-image
--- a/dev-sbc/crossbuild-tools/cb-chroot-target-image
+++ b/dev-sbc/crossbuild-tools/cb-chroot-target-image
@@ -45,47 +45,34 @@ message_n "restarting qemu-binfmt ..."
 #echo '-1' > /proc/sys/fs/binfmt_misc/arm #deregister wrong arm
 #echo ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\x00\xff\xfe\xff\xff\xff:/usr/local/bin/qemu-wrapper:' > /proc/sys/fs/binfmt_misc/register
 
-dirlist="proc dev var/db/repos/gentoo var/db/repos/joetoo \
-  var/db/repos/crossdev usr/src/linux lib/modules sys tmp dev/pts"
-
-for x in ${dirlist}
-do
-  if [ ! -d $x ] ; then
-    E_message_n "directory $x does not exist; creating it ..."
-    mkdir -pv $x && right_status $? || ( right_status $? && exit 1 )
-  else
-    echo "directory $x already exists; skipping mkdir"
-  fi
-done
-
-# for image chroot, don't mount repos - populate them if empty
-message_n "mounting proc for chroot target ..."
-mount -t proc none proc && right_status $? || ( right_status $? && exit 1 )
-message_n "mounting dev for chroot target ..."
-mount -o bind /dev dev && right_status $? || ( right_status $? && exit 1 )
-message_n "mounting sys for chroot target ..."
-mount -o bind /sys sys && right_status $? || ( right_status $? && exit 1 )
 message_n "copying /etc/resolv.conf for chroot target ..."
 cp /etc/resolv.conf etc/resolv.conf && right_status $? || ( right_status $? && exit 1 )
-# not chrooted yet, use rel addresses for repos
+
+# moved "validate dirlist" to cb-common-functions
+# set dirlist for cb-chroot-target-image
+dirlist="proc dev sys tmp dev/pts"
+dirlist+=" chroot_sources_mountpoint lib/modules"
+dirlist+=" var/db/repos/gentoo var/db/repos/joetoo var/db/repos/crossdev"
+validate-chroot-mountpoint-dirlist || die "failed validate-chroot-mountpoint-dirlist for ${PN}"
+
+# moved to mounts for chroot cb-common-functions
+# for cb-chroot-target-image, don't mount tmp (it will have its own)
+mount_list="proc dev sys"
+mount-chroot-prep || die "failed mount-chroot-prep for ${PN}"
+
+# for cb-chroot-target-image, don't mount repos - populate them if empty
+
+# not chrooted yet, use rel addresses for repos (note cd /usr/${TARGET} above)
 [[ -z $(find var/db/repos/gentoo/ -mindepth 1) ]] && E_message "Note: var/db/repos/gentoo/ is empty; first login will attempt to sync it ..."
 [[ -z $(find var/db/repos/joetoo/ -mindepth 1) ]] && E_message "Note: var/db/repos/joetoo/ is empty; first login will attempt to sync it ..."
 [[ -z $(find usr/src/linux/ -mindepth 1) ]] && E_message "/usr/src/linux/ is empty; consider installing a kernel sources package ..."
 [[ -z $(find lib/modules/ -mindepth 1) ]] && E_message "/lib/modules/ s empty; consider installing a boot-firmware package ..."
-#mount -o bind /tmp tmp
-#mount -o bind /dev/pts dev/pts #only for X
  
 chroot . /bin/bash --login
  
-#umount dev/pts
-#umount tmp
 FLAGGED=$FALSE
-message_n "un-mounting sys from chroot target ..."
-umount sys && right_status $? && right_status $? || ( right_status $? && FLAGGED=$TRUE )
-message_n "un-mounting dev from chroot target ..."
-umount dev && right_status $? && right_status $? || ( right_status $? && FLAGGED=$TRUE )
-message_n "un-mounting proc from chroot target ..."
-umount proc && right_status $? && right_status $? || ( right_status $? && FLAGGED=$TRUE )
+umount-chroot-prep
+
 [[ "$FLAGGED" == "$TRUE" ]] && ( E_message "failed clean exit; note red flags above" && exit 1 )
 
 echo
diff --git a/dev-sbc/crossbuild-tools/cb-common-functions b/dev-sbc/crossbuild-tools/cb-common-functions
--- a/dev-sbc/crossbuild-tools/cb-common-functions
+++ b/dev-sbc/crossbuild-tools/cb-common-functions
@@ -504,6 +504,88 @@ TARGET-emerge-world() {
     return 0
 }
 
+validate-chroot-mountpoint-dirlist() {
+    d_message "now in ${FUNCNAME[0]}" 3
+    # used by both cb-chroot-target and cb-chroot-target-image
+    # *** calling function must cd to new sysroot before calling this ***
+    # check for (and if needed, create) directories needed for chroot mountpoints
+
+    # dirlist must be set by the calling function
+    dirlist="proc dev sys tmp dev/pts"
+    dirlist+=" var/db/repos/gentoo var/db/repos/joetoo var/db/repos/crossdev"
+    dirlist+=" chroot_sources_mountpoint lib/modules"
+
+    d_message "looking for chroot mountpoints ..." 2
+    for x in ${dirlist} ; do
+        d_message_n "looking for $x" 3
+        if [ ! -d $x ] ; then
+            debug_do 'echo -e -n " (${BRon}not found${Boff)"' 3
+            mkdir -pv $x >/dev/null 2>/dev/null || die "failed to mkdir -pv $x"
+            debug_do 'echo -e -n " (${BGon}created${Boff})"' 3
+        else
+            debug_do 'echo -e -n " (${BGon}exists${Boff})"' 3
+        fi
+        d_right_status $TRUE 3
+    done
+    # now link the sources directory if it isn't
+    d_message_n "(re)building link to kernel sources usr/src/linux" 2
+    # if a directory by this name exists, remove it
+    if [ -d usr/src/linux ] ; then
+        rm -r usr/src/linux
+        debug_do 'echo -e -n " (removed dir)"' 3
+    fi
+    if [ -d usr/src/chroot-sources-mountpoint ] ; then
+        debug_do 'echo -e -n " (mountpoint exists)"' 3
+    else
+        mkdir usr/src/chroot-sources-mountpoint || die "failed to mkdir usr/src/chroot-sources-mountpoint"
+        debug_do 'echo -e -n " (mountpoint created)"' 3
+    fi
+    ln -snf chroot-sources-mountpoint usr/src/linux || die "failed to create link for usr/src/linux for ${PN}"
+    debug_do 'echo -e -n " (${BGon}created${Boff})"' 3
+    d_right_status $TRUE 2
+
+    d_message "done validating chroot mountpoint directories" 2
+    return 0
+}
+
+mount-chroot-prep() {
+    d_message "now in ${FUNCNAME[0]}" 3
+    # used by both cb-chroot-target and cb-chroot-target-image
+    # *** calling function must cd to new sysroot before calling this ***
+    # mount_list must be set by calling function
+
+    for tgt in ${mount_list}; do
+        case $tgt in
+            "proc" ) src="-t proc none" ;;
+            "dev"  ) src="-o bind /dev" ;;
+            "sys"  ) src="-o bind /sys" ;;
+            "tmp"  ) src="-o bind /tmp" ;;
+            "lib/modules" ) src="-o bind /lib/modules" ;; # not sure why we have to do this... seems like these (host's) modules would be wrong for target
+            "dev/pts"     ) src="-o bind /dev/pts" ;;   # only for X
+            "var/db/repos/joetoo"   ) src="-o bind /${tgt}" ;;
+            "var/db/repos/gentoo"   ) src="-o bind /${tgt}" ;;
+            "var/db/repos/crossdev" ) src="-o bind /${tgt}" ;;
+        esac
+        message_n "mounting $src on $tgt for ${PN} ..."
+        mount $src $tgt >/dev/null 2>&1 || die "failed to mount $src on $tgt for ${PN}"
+        right_status $TRUE
+    done
+    return 0
+}
+
+umount-chroot-prep() {
+    d_message "now in ${FUNCNAME[0]}" 3
+    # used by both cb-chroot-target and cb-chroot-target-image
+    # *** calling function must cd to new sysroot before calling this ***
+    # mount_list must be set by calling function
+    for tgt in ${mount_list}; do
+        message_n "un-mounting $tgt from chroot target for ${PN} ..."
+        umount $tgt ; result=$? ; right_status $result
+        [ $result -eq 0 ] || FLAGGED=$TRUE
+    done
+    [ $FLAGGED ] && return 1 || return 0
+}
+
 sanity_check() {
     # sanity check configuration
     FLAGGED=$FALSE
