add check to create rust-src package.use file if needed
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-sbc/crossbuild-tools/cb-common-functions b/dev-sbc/crossbuild-tools/cb-common-functions
--- a/dev-sbc/crossbuild-tools/cb-common-functions
+++ b/dev-sbc/crossbuild-tools/cb-common-functions
@@ -1032,14 +1032,24 @@ prepare-cross-rust() {
     # (1) rust-src USE flag on rust and rust-bin in CHOST's package.use
     # verify USE flag "dev-lang/rust rust-src"
     host_package_use="/etc/portage/package.use/99rust"
-    # verify that USE flag "dev-lang/rust rust-src" is in CHOST's package.use
-    message_n "looking for \"dev-lang/rust rust-src\" in ${host_package_use}"
-    if grep -qF -- "dev-lang/rust rust-src" "${host_package_use}" ; then
-        echo -en " (${BGon}found${Boff}))"
+    message_n "looking for ${host_package_use}"
+    # verify the package.use file exists; create if not
+    if [ -f "{$host_package_use}" ]; then
+        echo -e -n " (${BGon}found${Boff}))"
     else
-        echo -en " (${BRon}not found${Boff}))"
+        echo -e -n " (${BRon}not found${Boff}))"
+        touch "${host_package_use}" || die "failed to touch ${host_package_use}"
+        echo -e -n " (${BGon}created${Boff}))"
+        export RUST_LLVM_CHANGE_FLAG=$TRUE
+    fi
+    # verify that USE flag "dev-lang/rust rust-src" is in CHOST's package.use
+    if grep -qF -- "dev-lang/rust rust-src" "${host_package_use}" ; then
+        echo -e -n " (${BGon}found${Boff}))"
+    else
+        echo -e -n " (${BRon}not found${Boff}))"
         echo -e "\ndev-lang/rust rust-src" >> "${host_package_use}" || \
             die "failed to append rust-src use flag"
+        echo -e -n " (${BGon}appended{Boff}))"
         export RUST_LLVM_CHANGE_FLAG=$TRUE
     fi
     right_status $TRUE
@@ -1048,11 +1058,12 @@ prepare-cross-rust() {
     #  on dev-lang/rust rather than rust-bin, but lets keep it for compatibility)
     message_n "looking for \"dev-lang/rust-bin rust-src\" in ${host_package_use}"
     if grep -qF -- "dev-lang/rust-bin rust-src" "${host_package_use}" ; then
-        echo -en " (${BGon}found${Boff}))"
+        echo -e -n " (${BGon}found${Boff}))"
     else
-        echo -en " (${BRon}not found${Boff}))"
+        echo -e -n " (${BRon}not found${Boff})"
         echo -e "\ndev-lang/rust-bin rust-src" >> "${host_package_use}" || \
             die "failed to append rust-src use flag"
+        echo -e -n " (${BGon}appended{Boff}))"
         export RUST_LLVM_CHANGE_FLAG=$TRUE
     fi
     right_status $TRUE
