first round of rewrite to updated coding standard, with full set of tools in suite
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-sbc/crossbuild-tools/cb-chroot-target b/dev-sbc/crossbuild-tools/cb-chroot-target
--- a/dev-sbc/crossbuild-tools/cb-chroot-target
+++ b/dev-sbc/crossbuild-tools/cb-chroot-target
@@ -4,6 +4,7 @@
 #
 
 source /usr/sbin/script_header_joetoo
+source /usr/sbin/script_header_joetoo_unicode
 message_n "sourcing BUILD ..."
 source /etc/crossbuild-tools/BUILD ; right_status $?
 message_n "sourcing BPN ..."
@@ -48,7 +49,8 @@ validate-repo-mountpoints() {
                 echo -en " (${BRon}link${Boff}"
                 rm ${repo%/} && echo -en " ${BGon}removed${Boff})" || die "failed to remove link"
                 # replace with empty directory (valid mountpoint)
-                mkdir ${repo} >/dev/null 2>/dev/null && echo -en "(${BGon}dir created${Boff})" || die "failed to create mountpoint"
+                mkdir ${repo} >/dev/null 2>/dev/null || die "failed to create mountpoint"
+                echo -e -n "(${BGon}dir created${Boff})"
                 VALID_MOUNTPOINT=$TRUE
                 right_status $TRUE
             elif [ -d ${repo} ] ; then
@@ -63,7 +65,7 @@ validate-repo-mountpoints() {
                     echo -en " ${BMon}not${Boff} empty)"
                     # die here so we don't have to use rm -r to remove blindly below
                     # what might be an invalid link pointing to something important
-                    die "repo $x is a non-empty directory; please resolve this before resuming ${PN}"
+                    die "repo $x is a non-empty directory; use cb-chroot-update instead, or fix before resuming ${PN}"
                 fi
                 # if we got here, repo was either (or now is) and empty directory (valid mount point)
                 right_status $TRUE
@@ -76,7 +78,8 @@ validate-repo-mountpoints() {
         else
             # repo does not exist - create empty directory (valid mountpoint)
             echo -en " (does not exist)"
-            mkdir ${repo} >/dev/null 2>/dev/null && echo -en " (${BGon}dir created${Boff})" || die "failed to create mountpoint"
+            mkdir ${repo} >/dev/null 2>/dev/null || die "failed to create mountpoint"
+            echo -e -n " (${BGon}dir created${Boff})"
             VALID_MOUNTPOINT=$TRUE
             right_status $TRUE
         fi
@@ -98,8 +101,8 @@ mount-everything() {
 
     # copy resolv.conf
     message_n "copying /etc/resolv.conf for chroot target ..."
-    cp /etc/resolv.conf /usr/${TARGET}/etc/resolv.conf >/dev/null 2>&1 && \
-        right_status $? || die "failed to copy resolv.conf"
+    cp /etc/resolv.conf /usr/${TARGET}/etc/resolv.conf >/dev/null 2>&1 || die "failed to copy resolv.conf"
+    right_status $TRUE
 
     # mount chroot-prep stuff
     mount_list="proc dev sys lib/modules "
@@ -119,8 +122,9 @@ mount-everything() {
     [ ! -d /home/${user}/${SOURCES}/linux ] && echo && die "could not find kernel sources [/home/${user}/${SOURCES}/linux]"
     right_status $TRUE
     message_n "mounting usr/src/linux for chroot target ..."
-    mount -o bind /home/${user}/${SOURCES}/linux /usr/${TARGET}/usr/src/chroot-sources-mountpoint >/dev/null 2>&1 && \
-        right_status $? || die "failed to mount host kernel sources"
+    mount -o bind /home/${user}/${SOURCES}/linux /usr/${TARGET}/usr/src/chroot-sources-mountpoint >/dev/null 2>&1 || \
+        die "failed to mount host kernel sources"
+    right_status $TRUE
 
     #mount -o bind /tmp tmp
     #mount -o bind /dev/pts dev/pts #only for X
@@ -140,7 +144,8 @@ umount-everything() {
     mount_list+=" usr/src/chroot-sources-mountpoint"
     umount-chroot-prep || FLAGGED=$TRUE
 
-    [ $FLAGGED ] && return 1 || return 0
+    [ $FLAGGED ] && return 1
+    return 0
 }
 
 #-----[ main script ]---------------------------------------------
diff --git a/dev-sbc/crossbuild-tools/cb-common-functions b/dev-sbc/crossbuild-tools/cb-common-functions
--- a/dev-sbc/crossbuild-tools/cb-common-functions
+++ b/dev-sbc/crossbuild-tools/cb-common-functions
@@ -775,3 +775,347 @@ buildtarget-qemu() {
     message "now working in previous directory: [${Mon}$(pwd)${Boff}]"
     return 0
 }
+
+copy-to-stockpile(){
+    source_file="$1"   # full path to source file
+    dest_file="$2"     # full path to destination file (in STOCKPILE)
+    # copy ${source_file} to ${STOCKPILE}/${dest_file}
+    # create STOCKPILE directory if it doesn't exist
+    # assumes STOCKPILE to be assigned in the environment
+
+    # check for existence of STOCKPILE directory (create if needed)
+    message_n "examining STOCKPILE"
+    if [ ! -d ${STOCKPILE} ] ; then
+        echo -en " (${BRon}not found${Boff})"
+        mkdir -p ${STOCKPILE} && \
+            echo -en " (${BGon}created${Boff})" || die "failed to create STOCKPILE"
+    else
+        echo -en " (${BGon}found${Boff})"
+    fi
+    right_status $TRUE
+
+    # Check for existing file and handle immutability
+    message_n "looking for backing file"
+    if [ -f "${dest_file}" ] ; then
+        # If it's already there, we must UNSET immutable flag to allow backup/overwrite
+        echo -e -n " (${BGon}found${Boff})"
+        chattr -i "${dest_file}" 2>/dev/null || die "failed to unset immutability"
+        echo -e -n " (${BGon}unset immutable attribute${Boff})"
+        right_status $TRUE
+
+        response=""
+        msg="${BYon}${dest_file} already exists. ${BRon}Create backup?\n${Boff}"
+        msg+="${BWon}(y|Y: backup; n|N: abort; s|S: skip/overwrite)${Boff}"
+        new_prompt "${msg}"
+        case ${response:0:1} in
+            [yY] )
+                message_n "backing up image file"
+                cp "${dest_file}" "${dest_file}.bak" || die "failed to create backup"
+                echo -e -n " (${BGon}backed-up${Boff})"
+                right_status $TRUE
+                ;;
+            [sS] ) message_n "will overwrite image file"
+                right_status $TRUE
+                ;;
+            * ) die "aborting as instructed [$response]" ;;
+        esac
+    fi
+    # copy /usr/${BOARD}.img to ${STOCKPILE}/${UPDATEIMAGE}
+    message_n "stockpiling ${source_file} as $(basename ${dest_file})"
+    cp "${source_file}" "${dest_file}" >/dev/null 2>&1 || die "failed to cp ${source_file} ${dest_file}"
+    echo -en " (${BGon}copied${Boff})"
+    right_status $TRUE
+
+    # make the stockpiled image file immutable
+    message_n "protecting production image (chattr +i)"
+    chattr +i "${dest_file}" || die "failed to set immutable flag"
+    echo -e -n " (${BGon}immutable${Boff})"
+    right_status $TRUE
+
+    return 0
+
+}
+
+emerge-host-world() {
+    options="--update --verbose --deep --newuse --getbinpkg --usepkg --keep-going"
+    [ $INTERACTIVE ] && options+=" --ask"
+    emerge @world ${options} ; result=$?
+    return $result
+}
+
+configure-make-conf-for-crossbuilding() {
+    # remove any pending version of make.conf and accept delivery of chroot and crossbuild versions
+    message_n "accepting pending ._cfgxxxx_make.conf installs ..."
+    for x in /etc/portage/._cfg*make.conf; do rm $x ; done
+    for x in /etc/portage/._cfg*make.conf.crossbuild; do 
+        mv $x make.conf.crossbuild
+    done
+    for x in /etc/portage/._cfg*make.conf.chroot; do
+        mv $x make.conf.chroot
+    done
+    right_status $TRUE
+    # change to the chroot version of make.conf installed by joetoo-platform-meta
+    message_n "configuring make.conf for crossbuilding ..."  
+    newfile="/usr/${TARGET}/etc/portage/make.conf.crossbuild"
+    oldfile="/usr/${TARGET}/etc/portage/make.conf"
+    cp "${newfile}" "${oldfile}" || die "failed to cp ${newfile} ${oldfile}"
+    right_status $TRUE
+    return 0
+}
+
+configure-make-conf-for-chroot() {
+    # change to the chroot version of make.conf installed by joetoo-platform-meta
+    newfile="/usr/${TARGET}/etc/portage/make.conf.chroot"
+    oldfile="/usr/${TARGET}/etc/portage/make.conf"
+    message_n "configuring make.conf for chroot ..."
+    cp "${newfile}" "${oldfile}" || die "failed to cp ${newfile} ${oldfile}"
+    right_status $TRUE
+    return 0
+}
+
+emerge-cross-rust-std() {
+    # build cross-${TARGET}/rust-std
+    options="--verbose --getbinpkg --usepkg"
+    [ $INTERACTIVE ] && options+=" --ask"
+    emerge cross-${TARGET}/rust-std ${options} ; result=$?
+    return $result
+}
+
+rebuild-rust-and-llvm() {
+    # rebuild rust and llvm with the new configuration, if it changed
+    if [ $RUST_LLVM_CHANGE_FLAG ] ; then
+        # configuration changed - rebuild
+        message "${BYon}rust/llvm configuration ${BMon}changed -- rebuilding${Boff}"
+        options="--update --verbose --deep --newuse --getbinpkg --usepkg"
+        [ $INTERACTIVE ] && options+=" --ask"
+        emerge @world ${options} ; result=$?
+    else
+        # configuration unchanged - just continue
+        message "${BYon}rust/llvm configuration ${BGon}unchanged -- continuing${Boff}"
+        right_status $TRUE
+        result=0
+    fi
+    return $result
+}
+
+prepare-cross-rust() {
+    # Some packages (such as gnome-base/librsvg) depend on a rust cross toolchain
+    # so build the rust cross toolchain
+
+    # change this if we have to modify the system
+    export RUST_LLVM_CHANGE_FLAG=$FALSE
+
+    host_package_use="/etc/portage/package.use/joetoo"
+    # verify that USE flag "dev-lang/rust rust-src" is in CHOST's package.use
+    message_n "looking for \"dev-lang/rust rust-src\" in ${host_package_use}"
+    if grep -qF -- "dev-lang/rust rust-src" "${host_package_use}" ; then
+        echo -en " (${BGon}found${Boff}))"
+    else
+        echo -en " (${BRon}not found${Boff}))"
+        echo -e "\ndev-lang/rust rust-src" >> "${host_package_use}" || die "failed to append rust-src use fl>
+        export RUST_LLVM_CHANGE_FLAG=$TRUE
+    fi
+    right_status $TRUE
+
+    # verify that USE flag "dev-lang/rust-bin rust-src" is in CHOST's package.use
+    message_n "looking for \"dev-lang/rust-bin rust-src\" in ${host_package_use}"
+    if grep -qF -- "dev-lang/rust-bin rust-src" "${host_package_use}" ; then
+        echo -en " (${BGon}found${Boff}))"
+    else
+        echo -en " (${BRon}not found${Boff}))"
+        echo -e "\ndev-lang/rust-bin rust-src" >> "${host_package_use}" || die "failed to append rust-src us>
+        export RUST_LLVM_CHANGE_FLAG=$TRUE
+    fi
+    right_status $TRUE
+
+    # verify or correct LLVM_TARGETS in CHOST's make.conf
+    # not sure this is really necessary -- all targets may be unconditionally enabled in llvm-core/llvm(?)
+    # Gentoo forum administrator Hu noted on Fri Sep 16, 2022 -- news regarding adjustment of profiles' pack>
+        # Micha ^b G  rny <mgorny@gentoo.org> (2021-11-04)
+        # Enable all LLVM targets unconditionally.  Unfortunately, disabling
+        # targets tend to break reverse dependencies (e.g. Rust) and we are yet
+        # to find a clean way of resolving that.  Compared to the damage
+        # potential, the increase of build time is a minor problem.  Users who
+        # really insist of building a smaller system can un-force the flags
+        # at their own responsibility.
+    # see more in footnote at the bottom of this file
+    # anyway, do this for now
+    # if make.conf doesn't contain LLVM_TARGETS, then add them
+    host_make_conf="/etc/portage/make.conf"
+    message "examining LLVM_TARGETS in ${host_make_conf}"
+    message_n "looking for ${LLVM_TARGET}"
+    if grep -qF "LLVM_TARGETS=" "${host_make_conf}" ; then
+        # make.conf contains an assigment for LLVM_TARGETS - is this board's target in it?
+        source "${host_make_conf}"  # activate the current assignemt so we can check it
+        if [[ "${LLVM_TARGETS}" == *"${LLVM_TARGET}"* ]] ; then
+            # our target is already included
+            echo -en " (${BGon}found${Boff})"
+        else
+            echo -en " (${BRon}not found${Boff})"
+            echo -e "\nLLVM_TARGETS=\"AArch64 AMDGPU ARM AVR BPF Hexagon Lanai LoongArch MSP430 Mips NVPTX P>
+                echo -en "(${BGon}appended${Boff})" || die "failed to append LLVM_TARGETS to CHOSTs make.con>
+            export RUST_LLVM_CHANGE_FLAG=$TRUE
+        fi
+    else
+        # make.conf does not contain an assignment for LLVM_TARGETS -- append one
+        echo -en " (${BRon}not found${Boff})"
+        echo -e "\nLLVM_TARGETS=\"AArch64 AMDGPU ARM AVR BPF Hexagon Lanai LoongArch MSP430 Mips NVPTX Power>
+            echo -en "(${BGon}appended${Boff})" || die "failed to append LLVM_TARGETS to CHOSTs make.conf"
+        export RUST_LLVM_CHANGE_FLAG=$TRUE
+    fi
+    right_status $TRUE
+
+    # now set up cross-rust in CHOSTs crossdev repo
+    VALID_LINK=$FALSE
+    message "creating rust-std link in crossdev repo (to CHOSTs rust-std ebuilds) ..."
+    old_dir="$(pwd)"
+    cd /var/db/repos/crossdev/cross-${TARGET} && \
+    message "now working in crossdev repo: [${Mon}$(pwd)${Boff}]"
+    message_n "looking for link"
+    if [ -L rust-std ] ; then
+        echo -en " (found, "
+        # link forund - right target?
+        target_path=$(readlink -f rust-std)
+#        olv_verbosity=$verbosity ; verbosity=5
+#        d_message "target_path: [${target_path}]" 4
+#        verbosity=$old_verbosity
+        if [[ "${target_path}" == "/var/db/repos/gentoo/sys-devel/rust-std" ]] ; then
+            # link points to correct target
+            echo -en "${BGon}valid${Boff})"
+            VALID_LINK=$TRUE
+        else
+            # link does not point to correct target -- remove it
+            echo -en "${BRon}invalid${Boff})"
+            rm rust-std && echo -en "(removed)" || die "failed to remove invalid rust-std link"
+        fi
+    else
+        echo -en " (not found)"
+        # no link found
+    fi
+    if [ ! $VALID_LINK ] ; then
+        # valid link does not yet exist or invalid one was removed -- create it
+        ln -s /var/db/repos/gentoo/sys-devel/rust-std && \
+            echo -en "(${BGon}created${Boff})" || die "failed to create link for rust-std"
+    fi
+    # if we got here (didn't die above) close action as OK
+    right_status $TRUE
+    echo
+    cd $old_dir
+    message "now working in previous directory: [${Mon}$(pwd)${Boff}]"
+
+    # now unmask rust-std in CHOSTs package.accept_keywords
+    message_n "unmasking rust-std in CHOSTs package.accept_keywords ..."
+    echo "cross-${TARGET}/rust-std **" >> /etc/portage/package.accept_keywords/cross-target-rust-std && \
+        right_status $? || die "failed to unmasking rust-std in CHOSTs package.accept_keywords"
+
+    # now validate or create /etc/portage/env/dev-lang/rust per-package env setting
+    # (should be installed by this package's ebuild)
+    message_n "examining /etc/portage/env/dev-lang/rust"
+    if [ -e /etc/portage/env/dev-lang/rust ] ; then
+        echo -en " (${BGon}found${Boff})"
+    else
+        # not found - create
+        echo -en " (${BRon}not found${Boff})"
+        CONTENT="RUST_CROSS_TARGETS=(\n"
+        CONTENT+=" \"ARM:arm-unknown-linux-gnueabihf:armv6j-unknown-linux-gnueabihf\"\n"
+        CONTENT+=" \"ARM:armv7-unknown-linux-gnueabihf:armv7a-unknown-linux-gnueabihf\"\n"
+        CONTENT+=" \"AArch64:aarch64-unknown-linux-gnu:aarch64-unknown-linux-gnu\"\n"
+        CONTENT+=" )"
+        echo -e "${CONTENT}" > /etc/portage/env/dev-lang/rust && \
+            echo -en "(${BGon}created${Boff})" || die "failed to create /etc/portage/env/dev-lang/rust"
+        export RUST_LLVM_CHANGE_FLAG=$TRUE
+    fi
+    right_status $TRUE
+    return 0
+}
+
+run-dispatch-conf() {
+    # run dispatch-conf to activate newly installed configs
+    ROOT="/usr/${TARGET}/" dispatch-conf
+    return $?
+}
+
+edit-make-conf() {
+    # use system editor to edit config file
+    ${EDITOR} /usr/${TARGET}/etc/portage/make.conf
+    return $?
+}
+
+edit-package-use-platform() {
+    # use system editor to edit config file (it's numbered, so use find to id it)
+    configfile=$(find /usr/${TARGET}/etc/portage/package.use/ -iname "*joetoo_${BOARD}")
+    ${EDITOR} ${configfile}
+    return $?
+}
+
+edit-package-use-common() {
+    # use system editor to edit config file (it's numbered, so use find to id it)
+    configfile=$(find /usr/${TARGET}/etc/portage/package.use/ -iname "*joetoo_common")
+    ${EDITOR} ${configfile}
+    return $?
+}
+
+edit-package-accept-keywords() {
+    # use system editor to edit config file (it's numbered, so use find to id it)
+    configfile=$(find /usr/${TARGET}/etc/portage/package.accept_keywords/ -iname "*joetoo")
+    ${EDITOR} ${configfile}
+    return $?
+}
+
+create-new-cross-compiler() {
+    message "creating new crossdev cross compiler. Done after stage3 extraction"
+    message "because crossdev may produce split-usr layout, and I prefer the"
+    message "merged-usr layout that modern stage3 provides ..."
+    echo
+    FLAGGED=$FALSE
+    for x in profiles metadata; do
+        target_dir="/var/db/repos/crossdev/${x}"
+        message_n "validating ${target_dir} ..."
+        if [ ! -d ${target_dir} ] ; then
+            echo -en " (${BYon}creating${Boff})"
+            mkdir -p ${target_dir} && right_status $? || ( right_status $? && FLAGGED=$TRUE )
+        else
+            echo -en " (${BGon}valid${Boff})"
+            right_status $TRUE
+        fi
+    done
+
+    # validate or populate /var/db/repos/crossdev/metadata/layout.conf
+    message_n "validating /var/db/repos/crossdev/metadata/layout.conf ..."
+    if [ ! -f /var/db/repos/crossdev/metadata/layout.conf ] || \
+       [ -z "$(grep 'masters = gentoo' /var/db/repos/crossdev/metadata/layout.conf 2>/dev/null)" ] ; then
+        echo -en " ${BYon}(populating)${Boff} ..."
+        echo 'masters = gentoo' > /var/db/repos/crossdev/metadata/layout.conf && \
+        right_status $? || ( right_status $? && FLAGGED=$TRUE )
+    else
+        echo -en " (${BGon}valid${Boff})"
+        right_status $TRUE
+    fi
+
+    # validate or populate /var/db/repos/crossdev/profiles/repo_name
+    message_n "validating /var/db/repos/crossdev/profiles/repo_name ..."
+    if [ ! -f /var/db/repos/crossdev/profiles/repo_name ] || \
+       [ -z "$(grep 'crossdev' /var/db/repos/crossdev/profiles/repo_name)" ] ; then
+        echo -en " ${BYon}(populating)${Boff} ..."
+        echo 'crossdev' > /var/db/repos/crossdev/profiles/repo_name && \
+        right_status $? || ( right_status $? && FLAGGED=$TRUE )
+    else
+        echo -en " (${BGon}valid${Boff})"
+        right_status $TRUE
+    fi
+
+    # set permissions
+    message_n "setting permission for portage on /var/db/repos/crossdev ..."
+    chown -R portage:portage /var/db/repos/crossdev && \
+    right_status $? || ( right_status $? && FLAGGED=$TRUE )
+
+    # now actually build the new cross-compiler
+    message "building new cross-compiler ..."
+    crossdev -S -t ${TARGET} && \
+    right_status $? || ( right_status $? && FLAGGED=$TRUE )
+    if [[ $FLAGGED ]] ; then
+        E_message "failed clean exit; note red flags above" ; return 1
+    else
+        message "cross-compiler creation complete" ; return 0
+    fi
+}
diff --git a/dev-sbc/crossbuild-tools/cb-layout-device b/dev-sbc/crossbuild-tools/cb-layout-device
--- a/dev-sbc/crossbuild-tools/cb-layout-device
+++ b/dev-sbc/crossbuild-tools/cb-layout-device
@@ -11,6 +11,7 @@
 #   rather than load the BPN file created by the parent package which uses BPN= its own PN
 
 source /usr/sbin/script_header_joetoo
+source /usr/sbin/script_header_joetoo_unicode
 export LC_NUMERIC="en_US.UTF-8"
 declare -A lv_size  # user later, for size of LVs (root, usr, var, opt, home, tmp, srv, extra, swap)
 
@@ -280,21 +281,30 @@ source_templates() {
     d_message "sfdisk_template: $sfdisk_template" 5
     # (1) ingest sfdisk_template
     message_n "checking sfdisk_template ..."
-    [ -f "${config_dir%/}/${sfdisk_template_dir%/}/${sfdisk_template}" ] && \
-        right_status $? || die "sfdisk_template does not exist"
-        ingest_sfdisk_template || die "failed to ingest_sfdisk_template"
+    if [ -f "${config_dir%/}/${sfdisk_template_dir%/}/${sfdisk_template}" ] ; then
+        right_status $TRUE
+    else
+        die "sfdisk_template does not exist"
+    fi
+    ingest_sfdisk_template || die "failed to ingest_sfdisk_template"
 
     # (2) ingest blkid_template
     message_n "checking blkid_template ..."
-    [ -f "${config_dir%/}/${blkid_template_dir%/}/${blkid_template}" ] && \
-        right_status $? || die "blkid_template does not exist"
-        ingest_blkid_template || die "failed to ingest_blkid_template"
+    if [ -f "${config_dir%/}/${blkid_template_dir%/}/${blkid_template}" ] ; then
+        right_status $TRUE
+    else
+        die "blkid_template does not exist"
+    fi
+    ingest_blkid_template || die "failed to ingest_blkid_template"
 
     # (3) ingest lsblk_template
     message_n "checking lsblk_template ..."
-    [ -f "${config_dir%/}/${lsblk_template_dir%/}/${lsblk_template}" ] && \
-        right_status $? || die "lsblk_template does not exist"
-        ingest_lsblk_template || die "failed to ingest_lsblk_template"
+    if [ -f "${config_dir%/}/${lsblk_template_dir%/}/${lsblk_template}" ] ; then
+        right_status $TRUE
+    else
+        die "lsblk_template does not exist"
+    fi
+    ingest_lsblk_template || die "failed to ingest_lsblk_template"
 
     # (4) set luks_partition_device (so it can be used and displayed in config)
     # luks_partition_device= (last on OUTPUTDEVICE)
@@ -303,12 +313,12 @@ source_templates() {
     message_n "assigning luks_partition_device = ${OUTPUTDEVICE}${p_prefix}${partition_count}"
     luks_partition_device="${OUTPUTDEVICE}${p_prefix}${partition_count}" || \
         die "failed to set luks_partition_device"
-    right_status $?
+    right_status $TRUE
 
     # (5) set luks container name - get_luks_edev_name operates on luks_partition_device and sets edev
     message_n "assigning luks container name (edev ="
     get_luks_edev_name || die "failed to get_luks_edev_name"
-    echo -n " ${edev})" ; right_status $?
+    echo -n " ${edev})" ; right_status $TRUE
 
     return 0
 }
@@ -1038,17 +1048,27 @@ write_mount_the_rest_script() {
     # populate the mount-the-rest.<hostname> script, to mount other LVs and/or partitions
     # initialize script file by writing header line with ">"
     message_n "creating ${mount_the_rest_script} ..."
-    echo "#!/bin/bash" > ${root_dev_mountpoint%/}/${mount_the_rest_script} && \
-    right_status $? || (right_status $?; ERROR=$TRUE)
+    echo "#!/bin/bash" > ${root_dev_mountpoint%/}/${mount_the_rest_script} ; result=$?
+    case $result in
+        0 ) right_status $TRUE ;;
+        * ) right_status 1; ERROR=$TRUE ;;
+    esac
     # append mountpoint line
     message_n "appending mountpoint=${root_dev_mountpoint} to ${mount_the_rest_script}"
-    echo "mountpoint=${root_dev_mountpoint}" >> ${root_dev_mountpoint%/}/${mount_the_rest_script} && \
-    right_status $? || (right_status $?; ERROR=$TRUE)
+    echo "mountpoint=${root_dev_mountpoint}" >> ${root_dev_mountpoint%/}/${mount_the_rest_script} ; result=$?
+    case $result in
+        0 ) right_status $TRUE ;;
+        * ) right_status 1; ERROR=$TRUE ;;
+    esac
+
     # if LUKS, append a root_vg line to identify the VG parent of all LVs
     if [ $LUKS ] ; then
         message_n "appending root_vg line to identify the VG parent of all LVs"
-        echo "root_vg=vg_${DEV_HOSTNAME}" >> ${root_dev_mountpoint%/}/${mount_the_rest_script} && \
-        right_status $? || (right_status $?; ERROR=$TRUE)
+        echo "root_vg=vg_${DEV_HOSTNAME}" >> ${root_dev_mountpoint%/}/${mount_the_rest_script} ; result=$?
+        case $result in
+            0 ) right_status $TRUE ;;
+            * ) right_status 1; ERROR=$TRUE ;;
+        esac
     fi
     # append a partition_list line and look up uuid while we're at it
     # (use live blkid data to get var/val pairs for LABEL, TYPE, UUID)
@@ -1088,15 +1108,24 @@ write_mount_the_rest_script() {
 #    d_message "recap partition_uuids[@]: ${partition_uuids[@]}" 5
     debug_do 'echo -e "${BMon} * ${Boff}recap partition_uuids[@]: ${partition_uuids[@]}"' 5
     message_n "appending partition_list assignment line"
-    echo "partition_list=\"${pnames}\"" >> ${root_dev_mountpoint%/}/${mount_the_rest_script} && \
-    right_status $? || (right_status $?; ERROR=$TRUE)
+    echo "partition_list=\"${pnames}\"" >> ${root_dev_mountpoint%/}/${mount_the_rest_script}  ; result=$?
+    case $result in
+        0 ) right_status $TRUE ;;
+        * ) right_status 1; ERROR=$TRUE ;;
+    esac
+
     # now append uuid assignments for all partitions, using partition_uuids already saved
     for selector in ${pnames} ; do
         uuid_assignment="${selector}_uuid=${partition_uuids[${selector}]}"
         message_n "appending uuid assignment: [${uuid_assignment}]"
-        echo "${uuid_assignment}" >> ${root_dev_mountpoint%/}/${mount_the_rest_script} && \
+        echo "${uuid_assignment}" >> ${root_dev_mountpoint%/}/${mount_the_rest_script}  ; result=$?
+        case $result in
+            0 ) right_status $TRUE ;;
+            * ) right_status 1; ERROR=$TRUE ;;
+        esac
         non_stty_right_status $? || (non_stty_right_status $?; ERROR=$TRUE)
     done
+
     # now append mountpoint assignments for all partitions
     # (use blkid to get partitions again, lsblk template to get mountpoins)
     for selector in ${pnames} ; do
@@ -1115,58 +1144,97 @@ write_mount_the_rest_script() {
         fi
         mp_assignment="${selector}_mountpoint=${mp}"
         message_n "appending mountpoint assignment: [${mp_assignment}]"
-        echo "${mp_assignment}" >> ${root_dev_mountpoint%/}/${mount_the_rest_script} && \
-        non_stty_right_status $? || (non_stty_right_status $?; ERROR=$TRUE)
+        echo "${mp_assignment}" >> ${root_dev_mountpoint%/}/${mount_the_rest_script}  ; result=$?
+        case $result in
+            0 ) non_stty_right_status $TRUE ;;
+            * ) non_stty_right_status 1; ERROR=$TRUE ;;
+        esac
     done
     # append a blank line, for format clarity
     message_n "appending a blank line, for format clarity"
-    echo "" >> ${root_dev_mountpoint%/}/${mount_the_rest_script} && \
-    right_status $? || (right_status $?; ERROR=$TRUE)
+    echo "" >> ${root_dev_mountpoint%/}/${mount_the_rest_script} ; result=$?
+    case $result in
+        0 ) right_status $TRUE ;;
+        * ) right_status 1; ERROR=$TRUE ;;
+    esac
+
     # now append (concatenate) a standard script to mount partitions
     message_n "concatenating standard script to mount partitions"
-    cat ${config_dir%/}/mkdev-files/mount-PARTs_template >> ${root_dev_mountpoint%/}/${mount_the_rest_script} && \
-    right_status $? || (right_status $?; ERROR=$TRUE)
+    cat ${config_dir%/}/mkdev-files/mount-PARTs_template >> ${root_dev_mountpoint%/}/${mount_the_rest_script} ; result=$? 
+    case $result in
+        0 ) right_status $TRUE ;;
+        * ) right_status 1; ERROR=$TRUE ;;
+    esac
+
     # append a blank line, for format clarity
     message_n "appending a blank line, for format clarity"
-    echo "" >> ${root_dev_mountpoint%/}/${mount_the_rest_script} && \
-    right_status $? || (right_status $?; ERROR=$TRUE)
+    echo "" >> ${root_dev_mountpoint%/}/${mount_the_rest_script}  ; result=$?
+    case $result in
+        0 ) right_status $TRUE ;;
+        * ) right_status 1; ERROR=$TRUE ;;
+    esac
+
     # if LUKS, append (concatenate) a standard script to mount LVs
     if [ $LUKS ] ; then
         message_n "concatenating standard script to mount LVs"
-        cat ${config_dir%/}/mkdev-files/mount-LVs_template.luks >> ${root_dev_mountpoint%/}/${mount_the_rest_script} && \
-        right_status $? || (right_status $?; ERROR=$TRUE)
+        cat ${config_dir%/}/mkdev-files/mount-LVs_template.luks >> ${root_dev_mountpoint%/}/${mount_the_rest_script}  ; result=$?
+        case $result in
+            0 ) right_status $TRUE ;;
+            * ) right_status 1; ERROR=$TRUE ;;
+        esac
     fi
     # append a blank line, for format clarity
     message_n "appending a blank line, for format clarity"
-    echo "" >> ${root_dev_mountpoint%/}/${mount_the_rest_script} && \
-    right_status $? || (right_status $?; ERROR=$TRUE)
+    echo "" >> ${root_dev_mountpoint%/}/${mount_the_rest_script}  ; result=$?
+    case $result in
+        0 ) right_status $TRUE ;;
+        * ) right_status 1; ERROR=$TRUE ;;
+    esac
+
     # append a line that will generate a blank line in output, for format clarity
     message_n "appending a line to generate a blank line, for format clarity"
-    echo "echo" >> ${root_dev_mountpoint%/}/${mount_the_rest_script} && \
-    right_status $? || (right_status $?; ERROR=$TRUE)
+    echo "echo" >> ${root_dev_mountpoint%/}/${mount_the_rest_script}  ; result=$?
+    case $result in
+        0 ) right_status $TRUE ;;
+        * ) right_status 1; ERROR=$TRUE ;;
+    esac
+
     # append lines that will display what was mounted
     message_n "appending lines to display what was mounted (indented)"
     echo "echo 'here is what was mounted --'" >> ${root_dev_mountpoint%/}/${mount_the_rest_script} && \
-    echo "mount | grep ${root_dev_mountpoint} | sed 's|^|    |'" >> ${root_dev_mountpoint%/}/${mount_the_rest_script} && \
-    right_status $? || (right_status $?; ERROR=$TRUE)
+    echo "mount | grep ${root_dev_mountpoint} | sed 's|^|    |'" >> ${root_dev_mountpoint%/}/${mount_the_rest_script}  ; result=$?
+    case $result in
+        0 ) right_status $TRUE ;;
+        * ) right_status 1; ERROR=$TRUE ;;
+    esac
 
     # capture and append the blkid data for each partition
     # (prefix each line with # to comment it out)
     # append a blank line, for format clarity
     message_n "appending a blank line, for format clarity"
-    echo "" >> ${root_dev_mountpoint%/}/${mount_the_rest_script} && \
-    right_status $? || (right_status $?; ERROR=$TRUE)
+    echo "" >> ${root_dev_mountpoint%/}/${mount_the_rest_script}  ; result=$?
+    case $result in
+        0 ) right_status $TRUE ;;
+        * ) right_status 1; ERROR=$TRUE ;;
+    esac
+
     for selector in ${pnames} ; do
         # get blkid data to append to file
         message_n "capturing blkid data for ${selector} ..."
         blkid_data="$(blkid | grep ${partition_uuids[${selector}]} | sed 's|^|#|')" && \
-        echo "# ${blkid_data}" >> ${root_dev_mountpoint%/}/${mount_the_rest_script} && \
-        right_status $? || (right_status $?; ERROR=$TRUE)
+        echo "# ${blkid_data}" >> ${root_dev_mountpoint%/}/${mount_the_rest_script}  ; result=$?
+        case $result in
+            0 ) right_status $TRUE ;;
+            * ) right_status 1; ERROR=$TRUE ;;
+        esac
     done
     # make the script executable
     message_n "making ${root_dev_mountpoint%/}/${mount_the_rest_script} executable"
-    chmod +x ${root_dev_mountpoint%/}/${mount_the_rest_script} && \
-    right_status $? || (right_status $?; ERROR=$TRUE)
+    chmod +x ${root_dev_mountpoint%/}/${mount_the_rest_script}  ; result=$?
+        case $result in
+            0 ) right_status $TRUE ;;
+            * ) right_status 1; ERROR=$TRUE ;;
+        esac
     return 0
 }
 
diff --git a/dev-sbc/crossbuild-tools/cb-mkimg b/dev-sbc/crossbuild-tools/cb-mkimg
--- a/dev-sbc/crossbuild-tools/cb-mkimg
+++ b/dev-sbc/crossbuild-tools/cb-mkimg
@@ -46,7 +46,7 @@ response=""
 
 varlist="PN BPN BUILD BOARD TARGET TARGET_ARCH QEMU_ARCH"
 varlist+=" LLVM_TARGET default_profile"
-varlist+=" BREAK starting_step stopping_step mkimgstatusfile"
+varlist+=" BREAK starting_step stopping_step mkimgstatusfile user STOCKPILE"
 varlist+=" bool.RESUME bool.INTERACTIVE"
 varlist+=" BREAK bool.VERBOSE verbosity old_dir"
 
@@ -64,17 +64,17 @@ command_sequence=(
 msg1_sequence=(
 'repopulate image additional content'
 'cb-chroot into target image ${BOARD}'
-'save hostname for use in stockpile image name'
+'save hostname for use in STOCKPILE image name'
 'un-mount BOARD image'
-'add image to deployable image stockpile'
+'add image to deployable image STOCKPILE'
 )
 
 msg2_sequence=(
 'repopulating image additional content'
 'cb-chrooting into target image ${BOARD}'
-'saving hostname for use in stockpile image name'
+'saving hostname for use in STOCKPILE image name'
 'un-mounting BOARD image'
-'adding image to deployable image stockpile'
+'adding image to deployable image STOCKPILE'
 )
 
 #-----[ functions ]-----------------------------------------------------
@@ -95,25 +95,53 @@ initialize_variables() {
     # set default values
     FLAGGED=$FALSE
     d_message_n "sourcing BUILD ..." 2
-    source /etc/crossbuild-tools/BUILD && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    source /etc/crossbuild-tools/BUILD ; result=$?
+    if [ $result -eq 0 ] ; then d_right_status $TRUE 2; else FLAGGED=$TRUE; d_right_status 1 2; fi
+
     d_message_n "setting PN = $(basename $0)" 2
-    PN=$(basename $0) && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    PN=$(basename $0) ; result=$?
+    if [ $result -eq 0 ] ; then d_right_status $TRUE 2; else FLAGGED=$TRUE; d_right_status 1 2; fi
+
     d_message_n "sourcing BPN ..." 2
-    source /etc/crossbuild-tools/BPN && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    source /etc/crossbuild-tools/BPN ; result=$?
+    if [ $result -eq 0 ] ; then d_right_status $TRUE 2; else FLAGGED=$TRUE; d_right_status 1 2; fi
+
     d_message_n "setting old_dir = $(pwd)" 2
-    export old_dir=$(pwd) && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    export old_dir=$(pwd) ; result=$?
+    if [ $result -eq 0 ] ; then d_right_status $TRUE 2; else FLAGGED=$TRUE; d_right_status 1 2; fi
+
+    d_message_n "setting user = joe" 2
+    export user="joe" ; result=$?
+    if [ $result -eq 0 ] ; then d_right_status $TRUE 2; else FLAGGED=$TRUE; d_right_status 1 2; fi
+
+    d_message_n "setting STOCKPILE = /home/${user}/sbc-stockpile" 2
+    export STOCKPILE="/home/${user}/sbc-stockpile" ; result=$?
+    if [ $result -eq 0 ] ; then d_right_status $TRUE 2; else FLAGGED=$TRUE; d_right_status 1 2; fi
+
     d_message_n "setting default starting_step = 0" 2
-    export starting_step=0 && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    export starting_step=0 ; result=$?
+    if [ $result -eq 0 ] ; then d_right_status $TRUE 2; else FLAGGED=$TRUE; d_right_status 1 2; fi
+
     d_message_n "setting default stopping_step = $(( ${#command_sequence[@]} - 1 ))" 2
-    export stopping_step=$(( ${#command_sequence[@]} - 1 )) && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    export stopping_step=$(( ${#command_sequence[@]} - 1 )) ; result=$?
+    if [ $result -eq 0 ] ; then d_right_status $TRUE 2; else FLAGGED=$TRUE; d_right_status 1 2; fi
+
     d_message_n "setting default mkimgstatusfile = /root/bin/mkcrossbuildimg_status" 2
-    export mkimgstatusfile="/root/bin/mkcrossbuildimg_status" && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    export mkimgstatusfile="/root/bin/mkcrossbuildimg_status" ; result=$?
+    if [ $result -eq 0 ] ; then d_right_status $TRUE 2; else FLAGGED=$TRUE; d_right_status 1 2; fi
+
     d_message_n "setting default INTERACTIVE true" 2
-    export INTERACTIVE=$TRUE && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    export INTERACTIVE=$TRUE ; result=$?
+    if [ $result -eq 0 ] ; then d_right_status $TRUE 2; else FLAGGED=$TRUE; d_right_status 1 2; fi
+
     d_message_n "setting default VERBOSE = $(TrueFalse $oldVERBOSE)" 2
-    export VERBOSE=$oldVERBOSE && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    export VERBOSE=$oldVERBOSE ; result=$?
+    if [ $result -eq 0 ] ; then d_right_status $TRUE 2; else FLAGGED=$TRUE; d_right_status 1 2; fi
+
     d_message_n "setting default verbosity = $oldverbosity" 2
-    export verbosity=$oldverbosity && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    export verbosity=$oldverbosity ; result=$?
+    if [ $result -eq 0 ] ; then d_right_status $TRUE 2; else FLAGGED=$TRUE; d_right_status 1 2; fi
+
     if [[ $FLAGGED ]] ; then
         E_message "failed clean exit; note red flags above"
         return 1
@@ -145,7 +173,10 @@ validate-image() {
     fi
     # verify the loop device is mounted on the target
     mountpoint=$(mount | grep "${loop_dev}p2" | awk '{print $3}')
-    [[ ! "${mountpoint}" == "/usr/${TARGET}" ]] && E_message "no rootfs (loop_dev p2) is mounted on target /usr/${TARGET}" && FLAGGED=$TRUE
+    if [[ ! "${mountpoint}" == "/usr/${TARGET}" ]] ; then
+        E_message "no rootfs (loop_dev p2) is mounted on target /usr/${TARGET}"
+        FLAGGED=$TRUE
+    fi
     mountpoint=$(mount | grep "${loop_dev}p1" | awk '{print $3}')
     if [[ ! "${mountpoint}" == "/usr/${TARGET}/boot" ]] ; then
         E_message "no bootfs (loop_dev p1) is mounted on target /usr/${TARGET}/boot"
@@ -201,30 +232,14 @@ stockpile-img() {
     # start point for development of the scpecific system for which it was created
     # receive hostname as $1
 
-    stockpile=/home/joe/sbc-stockpile
-
     # use my_hostname to create output filename
-    message_n "assigning stockpile output filename"
-    outfile="${BOARD}_${my_hostname}.img" && \
-        echo -en " (${BGon}ok${Boff})" || die "failed to assign stockpile filename"
+    message_n "assigning STOCKPILE output filename"
+    outfile="${BOARD}_${my_hostname}.img" || die "failed to assign STOCKPILE filename"
+    echo -en " (${BGon}ok${Boff})"
     right_status $TRUE
 
-    # create stockpile directory if it doesn't exist
-    message_n "examining stockpile"
-    if [ ! -d ${stockpile} ] ; then
-        echo -en " (${BRon}not found${Boff})"
-        mkdir -p ${stockpile} && \
-            echo -en " (${BGon}created${Boff})" || die "failed to create stockpile"
-    else
-        echo -en " (${BGon}found${Boff})"
-    fi
-    right_status $TRUE
+    copy-to-stockpile "/usr/${BOARD}.img" "${STOCKPILE%/}/${outfile}"
 
-    # copy /usr/${BOARD}.img to ${stockpile}/${BOARD}.env
-    message_n "stockpiling as ${outfile}"
-    cp /usr/${BOARD}.img ${stockpile%/}/${outfile} && \
-        echo -en " (${BGon}copied${Boff})" || die "failed copy to stockpile"
-    right_status $TRUE
     return 0
 }
 
diff --git a/dev-sbc/crossbuild-tools/cb-mktemplateimage b/dev-sbc/crossbuild-tools/cb-mktemplateimage
--- a/dev-sbc/crossbuild-tools/cb-mktemplateimage
+++ b/dev-sbc/crossbuild-tools/cb-mktemplateimage
@@ -41,7 +41,7 @@ usage() {
 
 initialize_variables() {
     d_message "in ${FUNCNAME[0]}" 5
-    [ $verbosity -lt 2 ] && message_n "initializing ..." || message "initializing ..."
+    if [ $verbosity -lt 2 ] ; then message_n "initializing ..." ; else message "initializing ..."; fi
     # save variables we have in varlist but dont want to lose
     oldVERBOSE=$VERBOSE; oldverbosity=$verbosity
     initialize_vars ${varlist}
@@ -49,28 +49,45 @@ initialize_variables() {
     # set default values
     FLAGGED=$FALSE
     d_message_n "sourcing BUILD ..." 2
-    source /etc/crossbuild-tools/BUILD && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    source /etc/crossbuild-tools/BUILD ; result=$?
+    if [ $result -eq 0 ] ; then d_right_status $TRUE 2; else FLAGGED=$TRUE; d_right_status 1 2; fi
+
     d_message_n "setting PN = $(basename $0)" 2
-    PN=$(basename $0) && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    PN=$(basename $0) ; result=$?
+    if [ $result -eq 0 ] ; then d_right_status $TRUE 2; else FLAGGED=$TRUE; d_right_status 1 2; fi
+
     d_message_n "sourcing BPN ..." 2
-    source /etc/crossbuild-tools/BPN && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    source /etc/crossbuild-tools/BPN ; result=$?
+    if [ $result -eq 0 ] ; then d_right_status $TRUE 2; else FLAGGED=$TRUE; d_right_status 1 2; fi
 
     d_message_n "re-setting IMAGE_TYPE = ${myIMAGE_TYPE}" 2
-    IMAGE_TYPE="${myIMAGE_TYPE}" && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    IMAGE_TYPE="${myIMAGE_TYPE}" ; result=$?
+    if [ $result -eq 0 ] ; then d_right_status $TRUE 2; else FLAGGED=$TRUE; d_right_status 1 2; fi
+
     d_message_n "setting default imagefile = /etc/crossbuild-tools/admin_files/TEMPLATE_SBC_IMAGE_FILE.img" 2
-    imagefile=/etc/crossbuild-tools/admin_files/TEMPLATE_SBC_IMAGE_FILE.img && \
-        d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    imagefile=/etc/crossbuild-tools/admin_files/TEMPLATE_SBC_IMAGE_FILE.img ; result=$?
+    if [ $result -eq 0 ] ; then d_right_status $TRUE 2; else FLAGGED=$TRUE; d_right_status 1 2; fi
+
     d_message_n "setting default image_size_mb = 20480" 2
-    image_size_mb=20480 && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    image_size_mb=20480 ; result=$?
+    if [ $result -eq 0 ] ; then d_right_status $TRUE 2; else FLAGGED=$TRUE; d_right_status 1 2; fi
+
     d_message_n "setting default partition1_size_mb = 512" 2
-    partition1_size_mb=512 && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    partition1_size_mb=512 ; result=$?
+    if [ $result -eq 0 ] ; then d_right_status $TRUE 2; else FLAGGED=$TRUE; d_right_status 1 2; fi
+
     d_message_n "setting default partition2_size_mb = $((image_size_mb - partition1_size_mb))" 2
-    partition2_size_mb=$((image_size_mb - partition1_size_mb)) && \
-        d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    partition2_size_mb=$((image_size_mb - partition1_size_mb)) ; result=$?
+    if [ $result -eq 0 ] ; then d_right_status $TRUE 2; else FLAGGED=$TRUE; d_right_status 1 2; fi
+
     d_message_n "re-setting VERBOSE to $(TrueFalse $oldVERBOSE)" 2
-    export VERBOSE=$oldVERBOSE && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    export VERBOSE=$oldVERBOSE ; result=$?
+    if [ $result -eq 0 ] ; then d_right_status $TRUE 2; else FLAGGED=$TRUE; d_right_status 1 2; fi
+
     d_message_n "re-setting verbosity = $oldverbosity" 2
-    export verbosity=$oldverbosity && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    export verbosity=$oldverbosity ; result=$?
+    if [ $result -eq 0 ] ; then d_right_status $TRUE 2; else FLAGGED=$TRUE; d_right_status 1 2; fi
+
     if [[ $FLAGGED ]] ; then
         E_message "failed clean exit; note red flags above"
         return 1
@@ -88,7 +105,10 @@ prepare() {
     # there may be other checks to do, so save the FLAGGED structure for now
 
     # shouldn't have been called if it already exists, but in case invoked manually, check this
-    [ -f "${imagefile}" ] && E_message "imagefile ${imagefile} already exists" && FLAGGED=$TRUE
+    if [ -f "${imagefile}" ] ; then
+        E_message "imagefile ${imagefile} already exists"
+        FLAGGED=$TRUE
+    fi
     if [[ $FLAGGED ]] ; then
         E_message "Note red flags above. Please clean up before continuing"
         exit 1
@@ -100,63 +120,103 @@ mksparseimagetemplate() {
     d_message "in ${FUNCNAME[0]}" 5
     # Create empty image file
     message_n "creating sparse image file [ ${imagefile} ] ..."
-    dd if=/dev/zero of=${imagefile} bs=1 count=0 seek=${image_size_mb}M && right_status $? && \
-    mktemplate-common || ( right_status $? && exit 1 )
+    dd if=/dev/zero of=${imagefile} bs=1 count=0 seek=${image_size_mb}M || \
+        die "failed to create sparse image file [ ${imagefile} ]"
+    right_status $TRUE
+    mktemplate-common ; result=$?
+    case $result in
+        0 ) right_status $TRUE ;;
+        * ) die "mktemplate-common failed!${Boff} exit status: [${Mon}$result${Boff}]" ;;
+    esac
+    return $result
 }
 
 mkimagetemplate() {
     d_message "in ${FUNCNAME[0]}" 5
     # Create empty image file
     message_n "creating fixed-size image file [ ${imagefile} ] ..."
-    dd if=/dev/zero of=${imagefile} bs=1M count=${image_size_mb} && right_status $? || ( right_status $? && exit 1 )
-    mktemplate-common && right_status $? || ( right_status $? && exit 1 )
+    dd if=/dev/zero of=${imagefile} bs=1M count=${image_size_mb}|| \
+        die "failed to fixed-size image file [ ${imagefile} ]"
+    right_status $TRUE
+    mktemplate-common ; result=$?
+    case $result in
+        0 ) right_status $TRUE ;;
+        * ) die "mktemplate-common failed!${Boff} exit status: [${Mon}$result${Boff}]" ;;
+    esac
+    return $result
 }
 
 mktemplate-common() {
     d_message "in ${FUNCNAME[0]}" 5
     # Set up loop device
     message_n "setting up loop device"
-    loop_device="$(losetup --find --show ${imagefile})" && result=$? && \
-    echo -n " ( ${loop_device} )" && \
-    right_status ${result} || ( right_status $? && exit 1 )
+    loop_device="$(losetup --find --show ${imagefile})" || die "failed to setup loop device"
+    echo -n " (${loop_device})"
+    right_status $TRUE
+
     # Create partition table
     message_n "making dos disk label ..."
-    parted -s "$loop_device" mklabel msdos && right_status $? || ( right_status $? && exit 1 )
+    parted -s "$loop_device" mklabel msdos || die "failed to create dos disk label"
+    right_status $TRUE
+
     # Create partitions
     message_n "creating partition 1 ..."
     # create partition 1 starting at 0 and going until designated size
-    parted -s "$loop_device" mkpart primary 0% ${partition1_size_mb}MiB && right_status $? || ( right_status $? && exit 1 )
+    parted -s "$loop_device" mkpart primary 0% ${partition1_size_mb}MiB || die "failed to create partition 1"
+    right_status $TRUE
+
     message_n "creating partition 2 ..."
     # create partition 2 starting at the end of partition 1 and using the rest of the device
-    parted -s "$loop_device" mkpart primary ${partition1_size_mb}MiB 100% && right_status $? || ( right_status $? && exit 1 )
-    # Get partition device names
-    message_n "getting device name for partition 1 ..."
-    partition1_device="${loop_device}p1" && result=$? && \
-    echo -n " ( ${partition1_device} )" && \
-    right_status ${result} || ( right_status $? && exit 1 )
-    message_n "getting device name for partition 1 ..."
-    partition2_device="${loop_device}p2" && result=$? && \
-    echo -n " ( ${partition2_device} )" && \
-    right_status ${result} || ( right_status $? && exit 1 )
+    parted -s "$loop_device" mkpart primary ${partition1_size_mb}MiB 100% || die "failed to create partition 2"
+    right_status $TRUE
+
+    # assign partition device names
+    message_n "assigning device name for partition 1 ..."
+    partition1_device="${loop_device}p1" || die "failed to assign device name for partition 1"
+    echo -n " (${partition1_device})"
+    right_status $TRUE
+    message_n "assigning device name for partition 2 ..."
+    partition2_device="${loop_device}p2" || die "failed to assign device name for partition 2"
+    echo -n " (${partition2_device})"
+    right_status $TRUE
+
+    # ensures loopXp1 and loopXp2 actually appear in /dev
+    message_n "triggering kernel partition re-scan ..."
+    partx -u "$loop_device" || partprobe "$loop_device"
+    udevadm settle  --timeout=5 # Wait for /dev nodes to be created, but not too long
+    right_status $?
+
     # Format partitions
     message "formatting partition 1 ..."
-    mkfs.vfat -F 32 -n bootfs "$partition1_device" && right_status $? || ( right_status $? && exit 1 )
+    mkfs.vfat -F 32 -n bootfs "$partition1_device" || die "failed to format partition 1"
+    right_status $TRUE
     message "formatting partition 2 ..."
-    mkfs.ext4 -L rootfs "$partition2_device" && right_status $? || ( right_status $? && exit 1 )
+    mkfs.ext4 -L rootfs "$partition2_device" || die "failed to format partition 2"
+    right_status $TRUE
+
     # mount rootfs, mkdir boot
     if [ ! -d /mnt/image ] ; then
         message_n "creating mountpoint /mnt/image ..."
-        mkdir /mnt/image && right_status $? || ( right_status $? && exit 1 )
+        mkdir /mnt/image || die "failed to mkdir /mnt/image"
+        right_status $TRUE
     fi
     message_n "mounting rootfs ..."
-    mount "${partition2_device}" /mnt/image && right_status $? || ( right_status $? && exit 1 )
+    mount "${partition2_device}" /mnt/image || die "failed to mount ${partition2_device} /mnt/image"
+    right_status $TRUE
+
     message_n "creating boot directory ..."
-    mkdir /mnt/image/boot && right_status $? || ( right_status $? && exit 1 )
+    mkdir /mnt/image/boot || die "failed to create boot directory"
+    right_status $TRUE
+
     message "un-mounting rootfs ..."
-    umount /mnt/image && right_status $? || ( right_status $? && exit 1 )
+    umount /mnt/image || die "failed to umount /mnt/image"
+    right_status $TRUE
+
     # Clean up loop device
     message_n "cleaning up loop device [ ${loop_device} ]"
-    losetup -d "$loop_device" && right_status $? || ( right_status $? && exit 1 )
+    losetup -d "$loop_device" || die "failed to detach loop device"
+    right_status $TRUE
+
     echo "Image ${imagefile} created with two partitions:"
     echo "Partition 1: $partition1_size_mb MB, formatted as vfat"
     echo "Partition 2: $partition2_size_mb MB, formatted as ext4"
@@ -170,7 +230,10 @@ d_message "in main script with verbosity [$verbosity] and args [$@]" 5
 [ $# -ne 1 ] && usage
 
 myIMAGE_TYPE="$1"
-[[ "${myIMAGE_TYPE:0:1}" != [sSfF] ]] && E_message "Invalid argument [ ${myIMAGE_TYPE} ]" && usage
+if [[ "${myIMAGE_TYPE:0:1}" != [sSfF] ]] ; then
+    E_message "Invalid argument [ ${myIMAGE_TYPE} ]"
+    usage
+fi
 
 # initialize variables and set default values
 initialize_variables || die "Failed to initialize_variables"
diff --git a/dev-sbc/crossbuild-tools/cb-mount b/dev-sbc/crossbuild-tools/cb-mount
--- a/dev-sbc/crossbuild-tools/cb-mount
+++ b/dev-sbc/crossbuild-tools/cb-mount
@@ -46,23 +46,43 @@ mount-board() {
     else
         message "no loop device is yet attached to /usr/${BOARD}.img; continuing"
     fi
+
+    # attach loop device (read-write)
     message_n "attaching loop device"
-    img_loop_dev=$(losetup --find --show --partscan /usr/${BOARD}.img) && \
-        ( echo -n " (${img_loop_dev})" && right_status $? ) || ( right_status $? && exit 1 )
-    # Get partition device names
-    message_n "getting device name for partition 1 ..."
-    img_partition1_dev="${img_loop_dev}p1" && result=$? && \
-    echo -n " ( ${img_partition1_dev} )" && \
-    right_status ${result} || ( right_status $? && exit 1 )
-    message_n "getting device name for partition 2 ..."
-    img_partition2_dev="${img_loop_dev}p2" && result=$? && \
-    echo -n " ( ${img_partition2_dev} )" && \
-    right_status ${result} || ( right_status $? && exit 1 )
+    img_loop_dev=$(losetup --find --show --partscan /usr/${BOARD}.img) || die "failed to attach loop device"
+    echo -n " (${img_loop_dev})"
+    right_status $TRUE
+
+    # assign partition device names
+    message_n "assigning device name for partition 1 ..."
+    img_partition1_dev="${img_loop_dev}p1" || die "failed to assign img_partition1_dev"
+    echo -n " ( ${img_partition1_dev} )"
+    right_status $TRUE
+    message_n "assigning device name for partition 2 ..."
+    img_partition2_dev="${img_loop_dev}p2" || die "failed to assign img_partition2_dev"
+    echo -n " ( ${img_partition2_dev} )"
+    right_status $TRUE
+
+    # use fsck to preen bootfs (vfat)
+    message_n "preening bootfs (vfat) ..."
+    fsck.vfat -a ${img_partition1_dev} >/dev/null 2>&1
+    right_status $?
+
+    # use fsck to preen rootfs (ext4)
+    message_n "preening rootfs (ext4) ..."
+    e2fsck -p ${img_partition2_dev} >/dev/null 2>&1 ; result=$?
+    case $result in
+        0|1|2 ) right_status $TRUE ;; # 0: clear; 1: fixed; 2: fixed->reboot (N/A for .img)
+        *     ) die "${BRon}e2fsck failed!${Boff} exit code: [${Mon}$result${Boff}]. Fix before continuing"
+    esac
+
     # now mount the partitions
     message_n "mounting rootfs (${img_partition2_dev}) on /usr/${TARGET}/ ..."
-    mount ${img_partition2_dev} /usr/${TARGET}/ && right_status $? || ( right_status $? && exit 1 )
+    mount ${img_partition2_dev} /usr/${TARGET}/ || die "failed to mount img_partition2_dev"
+    right_status $TRUE
     message_n "mounting bootfs (${img_partition1_dev}) on /usr/${TARGET}/boot/ ..."
-    mount ${img_partition1_dev} /usr/${TARGET}/boot/ && right_status $? || ( right_status $? && exit 1 )
+    mount ${img_partition1_dev} /usr/${TARGET}/boot/ || die "failed to mount img_partition1_dev"
+    right_status $TRUE
     return 0
 }
 
diff --git a/dev-sbc/crossbuild-tools/cb-mount-binhost b/dev-sbc/crossbuild-tools/cb-mount-binhost
--- a/dev-sbc/crossbuild-tools/cb-mount-binhost
+++ b/dev-sbc/crossbuild-tools/cb-mount-binhost
@@ -100,7 +100,7 @@ mount-board-image-as-read-only-binhost() {
     else
         message "no loop device is yet attached to ${stockpile_dir%/}/${BACKING_FILE}; continuing"
     fi
-    # mount the binhost backing file with kernel-level read-only protection
+    # attach the binhost backing file with kernel-level read-only protection
     message_n "attaching loop device (read-only)"
 #    img_loop_dev=$(losetup --find --show --partscan ${stockpile_dir%/}/${BACKING_FILE}) && \
 #        ( echo -n " (${img_loop_dev})" && right_status $? ) || ( right_status $? && exit 1 )
@@ -115,13 +115,28 @@ mount-board-image-as-read-only-binhost() {
     img_partition2_dev="${img_loop_dev}p2" && result=$? && \
     echo -n " ( ${img_partition2_dev} )" && \
     right_status ${result} || ( right_status $? && exit 1 )
+
+    # Run a non-destructive fsck (-n opens fs RO and assumes 'no' to all repairs - ok for RO images)
+    message_n "checking filesystem integrity (RO check)..."
+    e2fsck -n ${img_partition2_dev} >/dev/null 2>&1
+    result=$?
+    case $result in
+        0   ) echo -e -n " (${BGon}clean${Boff})"; mount_opts="ro" ;;
+        1|2 ) echo -e -n " (${BYon}recoverable dirty journal${Boff})"; mount_opts="ro,noload" ;;
+        *   ) die "${BRon}e2fsck detected corruption on ${img_partition2_dev}!${Boff} Fix before continuing"
+    esac
+    right_status $TRUE
+
     # now mount the partitions with mount-layer (filesystem) read-only protection
     message_n "mounting rootfs (${img_partition2_dev}) on ${MOUNTPOINT}/ (read-only) ..."
 #    mount ${img_partition2_dev} ${MOUNTPOINT}/ && right_status $? || ( right_status $? && exit 1 )
-    mount -o ro ${img_partition2_dev} ${MOUNTPOINT}/ && right_status $? || ( right_status $? && exit 1 )
+    mount -o ${mount_opts} ${img_partition2_dev} ${MOUNTPOINT}/ || die "failed to mount -o ro ${img_partition2_dev} ${MOUNTPOINT}/"
+    right_status $TRUE
     message_n "mounting bootfs (${img_partition1_dev}) on ${MOUNTPOINT}/boot/ (read-only) ..."
 #    mount ${img_partition1_dev} ${MOUNTPOINT}/boot/ && right_status $? || ( right_status $? && exit 1 )
-    mount -o ro ${img_partition1_dev} ${MOUNTPOINT}/boot/ && right_status $? || ( right_status $? && exit 1 )
+    mount -o ro ${img_partition1_dev} ${MOUNTPOINT}/boot/ || die "failed to mount -o ro ${img_partition1_dev} ${MOUNTPOINT}/boot/"
+    right_status $TRUE
+
     return 0
 }
 
diff --git a/dev-sbc/crossbuild-tools/cb-populate-target b/dev-sbc/crossbuild-tools/cb-populate-target
--- a/dev-sbc/crossbuild-tools/cb-populate-target
+++ b/dev-sbc/crossbuild-tools/cb-populate-target
@@ -5,6 +5,7 @@
 #
 
 source /usr/sbin/script_header_joetoo
+source /usr/sbin/script_header_joetoo_unicode
 message_n "sourcing BUILD ..."
 source /etc/crossbuild-tools/BUILD ; right_status $?
 message_n "sourcing BPN ..."
@@ -34,27 +35,35 @@ save_config() {
     FLAGGED=$FALSE
     # first write creates/overwrites file; others append
     message_n "saving BOARD to /usr/${TARGET}${IMAGE_CONFIG_FILE} ..."
-    echo "export cb_BOARD=${BOARD}" > /usr/${TARGET}${IMAGE_CONFIG_FILE} && \
-        right_status $? || ( right_status $? && FLAGGED=$TRUE )
+    echo "export cb_BOARD=${BOARD}" > /usr/${TARGET}${IMAGE_CONFIG_FILE}  ; result=$?
+    if [ $result -eq 0 ] ; then right_status $TRUE; else FLAGGED=$TRUE; right_status 1; fi
+
     message_n "saving TARGET to /usr/${TARGET}${IMAGE_CONFIG_FILE} ..."
-    echo "export cb_TARGET=${TARGET}" >> /usr/${TARGET}${IMAGE_CONFIG_FILE}  && \
-        right_status $? || ( right_status $? && FLAGGED=$TRUE )
+    echo "export cb_TARGET=${TARGET}" >> /usr/${TARGET}${IMAGE_CONFIG_FILE}  ; result=$?
+    if [ $result -eq 0 ] ; then right_status $TRUE; else FLAGGED=$TRUE; right_status 1; fi
+
     message_n "saving TARGET_ARCH to /usr/${TARGET}${IMAGE_CONFIG_FILE} ..."
-    echo "export cb_TARGET_ARCH=${TARGET_ARCH}" >> /usr/${TARGET}${IMAGE_CONFIG_FILE} && \
-        right_status $? || ( right_status $? && FLAGGED=$TRUE )
+    echo "export cb_TARGET_ARCH=${TARGET_ARCH}" >> /usr/${TARGET}${IMAGE_CONFIG_FILE} ; result=$?
+    if [ $result -eq 0 ] ; then right_status $TRUE; else FLAGGED=$TRUE; right_status 1; fi
+
     message_n "saving QEMU_ARCH to /usr/${TARGET}${IMAGE_CONFIG_FILE} ..."
-    echo "export cb_QEMU_ARCH=${QEMU_ARCH}" >> /usr/${TARGET}${IMAGE_CONFIG_FILE}
-        right_status $? || ( right_status $? && FLAGGED=$TRUE )
+    echo "export cb_QEMU_ARCH=${QEMU_ARCH}" >> /usr/${TARGET}${IMAGE_CONFIG_FILE} ; result=$?
+    if [ $result -eq 0 ] ; then right_status $TRUE; else FLAGGED=$TRUE; right_status 1; fi
+
     message_n "saving STAGE3_SELECTOR to /usr/${TARGET}${IMAGE_CONFIG_FILE} ..."
-    echo "export cb_STAGE3_SELECTOR=${STAGE3_SELECTOR}" >> /usr/${TARGET}${IMAGE_CONFIG_FILE}
-        right_status $? || ( right_status $? && FLAGGED=$TRUE )
+    echo "export cb_STAGE3_SELECTOR=${STAGE3_SELECTOR}" >> /usr/${TARGET}${IMAGE_CONFIG_FILE}; result=$?
+    if [ $result -eq 0 ] ; then right_status $TRUE; else FLAGGED=$TRUE; right_status 1; fi
+
     message_n "saving default_profile to /usr/${TARGET}${IMAGE_CONFIG_FILE} ..."
-    echo "export cb_default_profile=${default_profile}" >> /usr/${TARGET}${IMAGE_CONFIG_FILE}
-        right_status $? || ( right_status $? && FLAGGED=$TRUE )
+    echo "export cb_default_profile=${default_profile}" >> /usr/${TARGET}${IMAGE_CONFIG_FILE}; result=$?
+    if [ $result -eq 0 ] ; then right_status $TRUE; else FLAGGED=$TRUE; right_status 1; fi
+
     message_n "saving LLVM_TARGET to /usr/${TARGET}${IMAGE_CONFIG_FILE} ..."
-    echo "export cb_LLVM_TARGET=${LLVM_TARGET}" >> /usr/${TARGET}${IMAGE_CONFIG_FILE}
-        right_status $? || ( right_status $? && FLAGGED=$TRUE )
-    [ $FLAGGED ] && return 1 || return 0
+    echo "export cb_LLVM_TARGET=${LLVM_TARGET}" >> /usr/${TARGET}${IMAGE_CONFIG_FILE}; result=$?
+    if [ $result -eq 0 ] ; then right_status $TRUE; else FLAGGED=$TRUE; right_status 1; fi
+
+    [ $FLAGGED ] && return 1
+    return 0
 }
 
 #-----[ main script ]---------------------------------------------
@@ -96,11 +105,11 @@ install_files_from_source "${SOURCE_DIR%/}/common/" || \
 
 # make scripts executable in chroot (joetoo-meta should have deployed them with emerge-world)
 DESTINATION="/usr/${TARGET}/usr/sbin"
-message_n "setting permissions on scripts in ${DESTINATION} ..."
-chmod +x ${DESTINATION}/script_header_joetoo* && \
-chmod +x ${DESTINATION}/finalize-chroot && \
-chmod +x ${DESTINATION}/install_my_local_ca_certificates && \
-right_status $? || ( right_status $? && exit 1 )
+for x in "script_header_joetoo*" "finalize-chroot" "install_my_local_ca_certificates"; do
+    message_n "setting permissions on ${DESTINATION}/$x ..."
+    eval "chmod +x ${DESTINATION}/$x" || die "failed to chmod +x ${DESTINATION}/$x"
+    right_status $TRUE
+done
 
 # save basic confguration data in /usr/${TARGET}${IMAGE_CONFIG_FILE}
 save_config || die "Failed to save_config"
diff --git a/dev-sbc/crossbuild-tools/cb-setup b/dev-sbc/crossbuild-tools/cb-setup
--- a/dev-sbc/crossbuild-tools/cb-setup
+++ b/dev-sbc/crossbuild-tools/cb-setup
@@ -5,6 +5,7 @@
 #
 
 source /usr/sbin/script_header_joetoo
+source /usr/sbin/script_header_joetoo_unicode
 message_n "sourcing BUILD ..."
 source /etc/crossbuild-tools/BUILD ; right_status $?
 message_n "sourcing BPN ..."
@@ -67,9 +68,11 @@ setup-board-image() {
             response="n"  # take the safe course (to NOT non-interactively destroy stuff)
         fi
         case ${response:0:1} in
-            [yY] ) message "re-running cleanup" ; cb-cleanup ${BOARD} && \
-                   ( right_status $? && message "cb-cleanup succeeded" ) || \
-                   ( right_status $? && exit 1 ) ;;
+            [yY] ) message "re-running cleanup"
+                   cb-cleanup ${BOARD} || die "failed cb-cleanup"
+                   right_status $TRUE
+                   message "cb-cleanup succeeded"
+                ;;
             [sS] ) message "OK; no action; continuing" ;;
             [nN] ) E_message "Exiting as instructed [ ${response} ]" ; exit 1 ;;
             * ) E_message "Invalid response; exiting" ; exit 1 ;;
@@ -85,7 +88,8 @@ setup-board-image() {
         message "target directory /usr/${TARGET} already exists - using"
     else
         message_n "making target /usr/${TARGET} ...."
-        mkdir /usr/${TARGET} && right_status $? || ( right_status $? && exit 1 )
+        mkdir /usr/${TARGET} || die "failed to mkdir /usr/${TARGET}"
+        right_status $TRUE
     fi
     # use or create board image file
     if [ -f /usr/${BOARD}.img ] ; then
@@ -93,8 +97,9 @@ setup-board-image() {
         message "image file /usr/${BOARD}.img already exists - using"
     else
         message_n "generating /usr/${BOARD}.img from template ...."
-        cp /etc/crossbuild-tools/admin_files/TEMPLATE_SBC_IMAGE_FILE.img /usr/${BOARD}.img && \
-        right_status $? || ( right_status $? && exit 1 )
+        cp /etc/crossbuild-tools/admin_files/TEMPLATE_SBC_IMAGE_FILE.img /usr/${BOARD}.img || \
+            die "failed to generate /usr/${BOARD}.img from template"
+        right_status $TRUE
     fi
     # loopmount board image file on target directory
     # (moved to cb-mount, called by cb-mkenv)
diff --git a/dev-sbc/crossbuild-tools/cb-umount b/dev-sbc/crossbuild-tools/cb-umount
--- a/dev-sbc/crossbuild-tools/cb-umount
+++ b/dev-sbc/crossbuild-tools/cb-umount
@@ -28,26 +28,59 @@ usage() {
 }
 
 umount-board() {
+    # zero-fill and remove empty space to facilitate "resparsification" of sparse image
+    message "zero-filling empty space"
+    # zero-fill and ignore "No space left on device" ...
+    dd if=/dev/zero of=/usr/${TARGET}/ZERO_FILL bs=1M status=progress 2>&1 | grep -v "No space left"
+    true # reset error code and continue
+    sync; echo -e "${BGon}done${Boff}" ; right_status $TRUE
+    message_n "removing zero-fill"
+    rm /usr/${TARGET}/ZERO_FILL 2>/dev/null || die "failed to remove zero-fill"
+    sync; echo -e -n " (${BGon}done${Boff})" ; right_status $TRUE
+    # note: complete "resparsification" with fallocate after detaching
+
     # inspect target (mount point) - is anything mounted? (un-mount)
     if [ ! -z "$(findmnt -n -M /usr/${TARGET})" ] ; then
         # something is mounted - un-mount it
         E_message "${BYon}the following devices are mounted on /usr/${TARGET} --${Boff}"
         mount | grep "on /usr/${TARGET}" | sed 's|^|    |'
         message_n "recursively umounting /usr/${TARGET} ..."
-	umount -l /usr/${TARGET}/dev{/shm,/pts,} 2>/dev/null
-        umount -R /usr/${TARGET} && right_status $? || die "failed to umount -R /usr/${TARGET}"
+	umount -l /usr/${TARGET}/dev{/shm,/pts,} 2>/dev/null || E_message "failed to umount -l /usr/${TARGET}/dev{/shm,/pts,}"
+        umount -R /usr/${TARGET} || die "failed to umount -R /usr/${TARGET}"
+        right_status $TRUE
     else
         message "nothing is mounted on /usr/${TARGET} ; continuing"
     fi
-    # inspect for loop devices attached to BOARD image file
+
+    # run fsck with optimization
+    message_n "optimizing directory indexes..."
+    # -f forces check, -D optimizes/reindexes, -y assumes yes to all
+    e2fsck -fD /dev/loop0p2 -y >/dev/null 2>&1
+    result=$?
+    case $result in
+        0|1|2 ) right_status $TRUE ;;  # 0: clean; 1: fixed; 2: fixed->reboot (N/A for .img)
+        * ) die "${BRon}e2fsck failed!${Boff} exit code: [${Mon}${result}${Boff}]" ;;
+    esac
+
+    # inspect for loop devices attached to BOARD image file and detach them
     message "looking for loop device attached to /usr/${BOARD}.img ..."
     loop_dev=$(losetup -a | grep "/usr/${BOARD}.img" | cut -d':' -f1)
-    if [ -n "${loop_dev}" ] ; then
+    if [ -b "${loop_dev}" ] ; then
         message_n "detaching ${loop_dev} ..."
-        losetup -d ${loop_dev} && right_status $? || die "failed to losetup -d ${loop_dev}"
+        losetup -d ${loop_dev} || die "failed to detach ${loop_dev}"
+        right_status $TRUE
     else
         message "no loop device is attached to /usr/${BOARD}.img ; continuing"
     fi
+
+    # use fallocate to resparsify the image file
+    message_n "using ${BBon}fallocate ${BMon}-d${Boff} to resparsify /usr/${BOARD}.img"
+    fallocate -d /usr/${BOARD}.img  || die "failed to resparsify /usr/${BOARD}.img"
+    right_status $TRUE
+    apparent_size=$(du -h --apparent-size /usr/${BOARD}.img | awk '{print $1}')
+    actual_size=$(du -h /usr/${BOARD}.img | awk '{print $1}')
+    message "${BYon}/usr/${BOARD}.img${Boff} apparent: ${Mon}${apparent_size}${Boff} actual: ${Gon}${actual_size}${Boff}"
+
     return 0
 }
 
