bugfix and enhancement
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-sbc/crossbuild-tools/cb-common-functions b/dev-sbc/crossbuild-tools/cb-common-functions
--- a/dev-sbc/crossbuild-tools/cb-common-functions
+++ b/dev-sbc/crossbuild-tools/cb-common-functions
@@ -953,6 +953,7 @@ edit-package-accept-keywords() {
 }
 
 create-new-cross-compiler() {
+    local target_dir=""
     message "creating new crossdev cross compiler. Done after stage3 extraction"
     message "because crossdev may produce split-usr layout, and I prefer the"
     message "merged-usr layout that modern stage3 provides ..."
@@ -1031,10 +1032,23 @@ prepare-cross-rust() {
 
     # (1) rust-src USE flag on rust and rust-bin in CHOST's package.use
     # verify USE flag "dev-lang/rust rust-src"
-    host_package_use="/etc/portage/package.use/99rust"
-    message_n "looking for ${host_package_use}"
+    local host_package_use="/etc/portage/package.use/99rust"
+    local target_dir=$(dirname "${host_package_use}")
+
+    # verify the package.use directory exists; create if not
+    message_n "looking for directory: $(dirname "${host_package_use}")"
+    if [ -d "${target_dir}" ]; then
+        echo -e -n " (${BGon}found${Boff})"
+    else
+        echo -e -n " (${BRon}not found${Boff})"
+        mkdir -p "${target_dir}" || die "failed to  mkdir -p ${target_dir}"
+        echo -e -n " (${BGon}created${Boff})"
+        export RUST_LLVM_CHANGE_FLAG=$TRUE
+    fi
+    right_status $TRUE
     # verify the package.use file exists; create if not
-    if [ -f "{$host_package_use}" ]; then
+    message_n "looking for file: ${host_package_use}"
+    if [ -f "${host_package_use}" ]; then
         echo -e -n " (${BGon}found${Boff})"
     else
         echo -e -n " (${BRon}not found${Boff})"
