add verbosity to crossbuild use of per-package cb-perl-wrapper
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-sbc/crossbuild-tools/cb-common-functions b/dev-sbc/crossbuild-tools/cb-common-functions
--- a/dev-sbc/crossbuild-tools/cb-common-functions
+++ b/dev-sbc/crossbuild-tools/cb-common-functions
@@ -581,11 +581,22 @@ TARGET-emerge-perl-fix() {
     local target_package_env_file="${target_conf_dir}/package.env/package.env"
 
     # Setup temporary cross-build scaffolding (on target)
-    mkdir -p "${target_conf_dir}/env"
-    echo 'CC="/usr/sbin/cb-perl-wrapper"' > "${env_perl_wrapper_conf}"
-    echo 'CPP="/usr/sbin/cb-perl-wrapper"' >> "${env_perl_wrapper_conf}"
-    echo 'CXX="/usr/sbin/cb-perl-wrapper"' >> "${env_perl_wrapper_conf}"
-    echo "dev-perl/* perl-wrapper.conf" >> "${target_package_env_file}"
+    message "setting up temporary per-package crossbuild config for perl ..."
+    message_n "creating ${target_conf_dir}/env"
+    mkdir -p "${target_conf_dir}/env" || die "failed to mkdir -p ${target_conf_dir}/env"
+    right_status $TRUE
+    message_n "generating temporary perl-wrapper.conf"
+    echo 'CC="/usr/sbin/cb-perl-wrapper"' > "${env_perl_wrapper_conf}" || die "failed to write line 1 to perl-wrapper.conf"
+    echo -e -n " (${Mon}1${Boff})"
+    echo 'CPP="/usr/sbin/cb-perl-wrapper"' >> "${env_perl_wrapper_conf}" || die "failed to write line 2 to perl-wrapper.conf"
+    echo -e -n "(${Yon}2${Boff})"
+    echo 'CXX="/usr/sbin/cb-perl-wrapper"' >> "${env_perl_wrapper_conf}" || die "failed to write line 3 to perl-wrapper.conf"
+    echo -e -n "(${Gon}3${Boff})"
+    right_status $TRUE
+    message_n "appending dev-perl/* perl-wrapper.conf to target package.env"
+    echo "dev-perl/* perl-wrapper.conf" >> "${target_package_env_file}" || die "failed to append dev-perl/* perl-wrapper.conf to target package.env"
+    right_status $TRUE
+
 
     # explicitly set options and features
     # (use option -g/--getbinpkg vs feature b/c it triggers refresh of remote metadata where latter does not)
@@ -597,10 +608,14 @@ TARGET-emerge-perl-fix() {
 
     # Remove the temporary cross-build scaffolding (would be incorrect for chroot or normal ops)
     #   remove the wrapper conf file that set CC= etc.
-    rm -f "${env_perl_wrapper_conf}"
+    message_n "removing temporary perl-wrapper.conf"
+    rm -f "${env_perl_wrapper_conf}" || die "failed to rm -f ${env_perl_wrapper_conf}"
+    right_status $TRUE
     # Remove ONLY the specific line we added to package.env
-    sed -i '/dev-perl\/\* perl-wrapper.conf/d' "${target_package_env_file}"
-
+    message_n "removing just dev-perl/* perl-wrapper.conf from target package.env"
+    sed -i '/dev-perl\/\* perl-wrapper.conf/d' "${target_package_env_file}" || \
+        die "failed to remove dev-perl/* perl-wrapper.conf from target package.env"
+    right_status $TRUE
 
     echo
     message "Do not worry if some @system packages fail to build (e.g. gcc, above)"
