change from procedure of Gentoo crossbuild-environment wiki to Embedded wiki
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-sbc/crossbuild-tools/cb-common-functions b/dev-sbc/crossbuild-tools/cb-common-functions
--- a/dev-sbc/crossbuild-tools/cb-common-functions
+++ b/dev-sbc/crossbuild-tools/cb-common-functions
@@ -748,3 +748,30 @@ smaller_script_common_usage_message() {
     message "${BMon}  find additional information at ${LBon}/etc/crossbuild-tools/README${Boff}"
     echo
 }
+
+buildtarget-qemu() {
+    # this used to be a separate script cb-buildtarget-qemu
+    old_dir="$(pwd)"
+    cd /usr/${TARGET}
+    message "now working in crossbuild target directory: [${Mon}$(pwd)${Boff}]"
+
+    [[ $INTERACTIVE ]] && emerge_options="-av1" || emerge_options="-v1"
+
+    message "building qemu for ${TARGET} ..."
+    FEATURES="-getbinpkg" QEMU_USER_TARGETS="${QEMU_ARCH}" QEMU_SOFTMMU_TARGETS="${QEMU_ARCH}" \
+        USE="static-user -plugins static-libs" emerge ${emerge_options} --buildpkg qemu || \
+            die "failed to build qemu for ${TARGET}"
+    right_status $TRUE
+
+    message_n "installing qemu binary in ${TARGET} ..."
+    # 20251218 - swithced from procedure of Gentoo's "crossbuild environment" to "Embedded" wiki
+    cp "/usr/bin/qemu-$(QEMU_ARCH)" "/usr/${TARGET}/" || die "failed to install qemu binary in ${TARGET}"
+    right_status $TRUE
+
+    # cross-rust setup has been relocated to step 16 in cb-mkenv
+
+    echo
+    cd $old_dir
+    message "now working in previous directory: [${Mon}$(pwd)${Boff}]"
+    return 0
+}
