switched from rust-std to rust-bin for cross-rust and  rust
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-sbc/crossbuild-tools/cb-common-functions b/dev-sbc/crossbuild-tools/cb-common-functions
--- a/dev-sbc/crossbuild-tools/cb-common-functions
+++ b/dev-sbc/crossbuild-tools/cb-common-functions
@@ -882,7 +882,7 @@ configure-make-conf-for-chroot() {
     return 0
 }
 
-emerge-cross-rust-std() {
+DEPRECATED_emerge-cross-rust-std() {
     # build cross-${TARGET}/rust-std
     options="--verbose --getbinpkg --usepkg"
     [ $INTERACTIVE ] && options+=" --ask"
@@ -891,7 +891,7 @@ emerge-cross-rust-std() {
 }
 
 rebuild-rust-and-llvm() {
-    # rebuild rust and llvm with the new configuration, if it changed
+    # rebuild @world to update rust and llvm with the new configuration, if it changed
     if [ $RUST_LLVM_CHANGE_FLAG ] ; then
         # configuration changed - rebuild
         message "${BYon}rust/llvm configuration ${BMon}changed -- rebuilding${Boff}"
@@ -999,12 +999,26 @@ create-new-cross-compiler() {
 }
 
 prepare-cross-rust() {
-    # Some packages (such as gnome-base/librsvg) depend on a rust cross toolchain
-    # so build the rust cross toolchain
+    # Some packages depend on a rust cross toolchain, so --
+    # update configs to use rust-bin as cross-compiler and
+    #  set RUST_LLVM_CHANGE_FLAG=$TRUE in order to make rebuild-rust-and-llvm()
+    #  update rust-bin [which is a dependency of crossbuild-tools], if needed)
+    # (rebuild-rust-and-llvm() is the next step in cb-mkenv command sequence
+    #  and in cb-mkupd's validate-prerequisites()
 
-    # change this if we have to modify the system
+    # change this if we modify the configuration and need to rebuild rust-bin, llvm etc.
     export RUST_LLVM_CHANGE_FLAG=$FALSE
 
+    # three (not five) things required to prepare cross-rust
+    # (1) rust-src USE flag on rust and rust-bin in CHOST's package.use
+    # (2) RUST_CROSS_TARGETS=() array set-up in /etc/portage/env/dev-lang/rust
+    # (3) LLVM_TARGETS use-expand set-up in CHOST's make.conf
+    # DEPRECATED (4) symlink for cross-${TARGET}/rust-std set up cross-rust in CHOSTs crossdev repo(s)
+    # DEPRECATED (5) unmask cross-${TARGET}/rust-std in CHOSTs package.accept_keywords
+    # 4 & 5 are residue of legacy gentoo crossbuild-environment wiki procedure
+
+    # (1) rust-src USE flag on rust and rust-bin in CHOST's package.use
+    # verify USE flag "dev-lang/rust rust-src"
     host_package_use="/etc/portage/package.use/joetoo"
     # verify that USE flag "dev-lang/rust rust-src" is in CHOST's package.use
     message_n "looking for \"dev-lang/rust rust-src\" in ${host_package_use}"
@@ -1017,8 +1031,7 @@ prepare-cross-rust() {
         export RUST_LLVM_CHANGE_FLAG=$TRUE
     fi
     right_status $TRUE
-
-    # verify that USE flag "dev-lang/rust-bin rust-src" is in CHOST's package.use
+    # verify USE flag "dev-lang/rust-bin rust-src"
     # (this should be unnecessary b/c I changed crossbuild-tools ebuild to depend
     #  on dev-lang/rust rather than rust-bin, but lets keep it for compatibility)
     message_n "looking for \"dev-lang/rust-bin rust-src\" in ${host_package_use}"
@@ -1032,7 +1045,27 @@ prepare-cross-rust() {
     fi
     right_status $TRUE
 
-    # verify or correct LLVM_TARGETS in CHOST's make.conf
+    # (2) RUST_CROSS_TARGETS=() array set-up in /etc/portage/env/dev-lang/rust
+    # validate or create /etc/portage/env/dev-lang/rust per-package env setting
+    # (should be installed by this package's ebuild)
+    message_n "examining /etc/portage/env/dev-lang/rust"
+    if [ -e /etc/portage/env/dev-lang/rust ] ; then
+        echo -en " (${BGon}found${Boff})"
+    else
+        # not found - create
+        echo -en " (${BRon}not found${Boff})"
+        CONTENT="RUST_CROSS_TARGETS=(\n"
+        CONTENT+=" \"ARM:arm-unknown-linux-gnueabihf:armv6j-unknown-linux-gnueabihf\"\n"
+        CONTENT+=" \"ARM:armv7-unknown-linux-gnueabihf:armv7a-unknown-linux-gnueabihf\"\n"
+        CONTENT+=" \"AArch64:aarch64-unknown-linux-gnu:aarch64-unknown-linux-gnu\"\n"
+        CONTENT+=" )"
+        echo -e "${CONTENT}" > /etc/portage/env/dev-lang/rust || die "failed to create /etc/portage/env/dev-lang/rust"
+        echo -en "(${BGon}created${Boff})"
+        export RUST_LLVM_CHANGE_FLAG=$TRUE
+    fi
+    right_status $TRUE
+
+    # (3) LLVM_TARGETS use-expand set-up in CHOST's make.conf
     # not sure this is really necessary --
     #   all targets may be unconditionally enabled in llvm-core/llvm(?)
     # Gentoo forum administrator Hu noted on Fri Sep 16, 2022 --
@@ -1073,69 +1106,49 @@ prepare-cross-rust() {
     fi
     right_status $TRUE
 
-    # now set up cross-rust in CHOSTs crossdev repo
+# DEPRECATED (4) symlink for cross-${TARGET}/rust-std set up cross-rust in CHOSTs crossdev repo(s)
+#    VALID_LINK=$FALSE
+#    message "creating rust-std link in crossdev repo (to CHOSTs rust-std ebuilds) ..."
+#    old_dir="$(pwd)"
+#    cd /var/db/repos/crossdev/cross-${TARGET} && \
+#    message "now working in crossdev repo: [${Mon}$(pwd)${Boff}]"
+#    message_n "looking for link"
+#    if [ -L rust-std ] ; then
+#        echo -en " (found, "
+#        # link forund - right target?
+#        target_path=$(readlink -f rust-std)
+##        olv_verbosity=$verbosity ; verbosity=5
+##        d_message "target_path: [${target_path}]" 4
+##        verbosity=$old_verbosity
+#        if [[ "${target_path}" == "/var/db/repos/gentoo/sys-devel/rust-std" ]] ; then
+#            # link points to correct target
+#            echo -en "${BGon}valid${Boff})"
+#            VALID_LINK=$TRUE
+#        else
+#            # link does not point to correct target -- remove it
+#            echo -en "${BRon}invalid${Boff})"
+#            rm rust-std && echo -en "(removed)" || die "failed to remove invalid rust-std link"
+#        fi
+#    else
+#        echo -en " (not found)"
+#        # no link found
+#    fi
+#    if [ ! $VALID_LINK ] ; then
+#        # valid link does not yet exist or invalid one was removed -- create it
+#        ln -s /var/db/repos/gentoo/sys-devel/rust-std || die "failed to create link for rust-std"
+#        echo -en "(${BGon}created${Boff})"
+#    fi
 
-    VALID_LINK=$FALSE
-    message "creating rust-std link in crossdev repo (to CHOSTs rust-std ebuilds) ..."
-    old_dir="$(pwd)"
-    cd /var/db/repos/crossdev/cross-${TARGET} && \
-    message "now working in crossdev repo: [${Mon}$(pwd)${Boff}]"
-    message_n "looking for link"
-    if [ -L rust-std ] ; then
-        echo -en " (found, "
-        # link forund - right target?
-        target_path=$(readlink -f rust-std)
-#        olv_verbosity=$verbosity ; verbosity=5
-#        d_message "target_path: [${target_path}]" 4
-#        verbosity=$old_verbosity
-        if [[ "${target_path}" == "/var/db/repos/gentoo/sys-devel/rust-std" ]] ; then
-            # link points to correct target
-            echo -en "${BGon}valid${Boff})"
-            VALID_LINK=$TRUE
-        else
-            # link does not point to correct target -- remove it
-            echo -en "${BRon}invalid${Boff})"
-            rm rust-std && echo -en "(removed)" || die "failed to remove invalid rust-std link"
-        fi
-    else
-        echo -en " (not found)"
-        # no link found
-    fi
-    if [ ! $VALID_LINK ] ; then
-        # valid link does not yet exist or invalid one was removed -- create it
-        ln -s /var/db/repos/gentoo/sys-devel/rust-std || die "failed to create link for rust-std"
-        echo -en "(${BGon}created${Boff})"
-    fi
-    # if we got here (didn't die above) close action as OK
+# DEPRECATED (5) unmask cross-${TARGET}/rust-std in CHOSTs package.accept_keywords
+#    message_n "unmasking rust-std in CHOSTs package.accept_keywords ..."
+#    echo "cross-${TARGET}/rust-std **" >> /etc/portage/package.accept_keywords/cross-target-rust-std || \
+#         die "failed to unmasking rust-std in CHOSTs package.accept_keywords"
+#    right_status $TRUE
+
+    # if we got here (didn't die above) close action as OK and return exit status 0
     right_status $TRUE
     echo
     cd $old_dir
     message "now working in previous directory: [${Mon}$(pwd)${Boff}]"
-
-    # now unmask rust-std in CHOSTs package.accept_keywords
-    message_n "unmasking rust-std in CHOSTs package.accept_keywords ..."
-    echo "cross-${TARGET}/rust-std **" >> /etc/portage/package.accept_keywords/cross-target-rust-std || \
-         die "failed to unmasking rust-std in CHOSTs package.accept_keywords"
-    right_status $TRUE
-
-    # now validate or create /etc/portage/env/dev-lang/rust per-package env setting
-    # (should be installed by this package's ebuild)
-    message_n "examining /etc/portage/env/dev-lang/rust"
-    if [ -e /etc/portage/env/dev-lang/rust ] ; then
-        echo -en " (${BGon}found${Boff})"
-    else
-        # not found - create
-        echo -en " (${BRon}not found${Boff})"
-        CONTENT="RUST_CROSS_TARGETS=(\n"
-        CONTENT+=" \"ARM:arm-unknown-linux-gnueabihf:armv6j-unknown-linux-gnueabihf\"\n"
-        CONTENT+=" \"ARM:armv7-unknown-linux-gnueabihf:armv7a-unknown-linux-gnueabihf\"\n"
-        CONTENT+=" \"AArch64:aarch64-unknown-linux-gnu:aarch64-unknown-linux-gnu\"\n"
-        CONTENT+=" )"
-        echo -e "${CONTENT}" > /etc/portage/env/dev-lang/rust || die "failed to create /etc/portage/env/dev-lang/rust"
-        echo -en "(${BGon}created${Boff})"
-        export RUST_LLVM_CHANGE_FLAG=$TRUE
-    fi
-    right_status $TRUE
     return 0
 }
-
diff --git a/dev-sbc/crossbuild-tools/cb-mkupd b/dev-sbc/crossbuild-tools/cb-mkupd
--- a/dev-sbc/crossbuild-tools/cb-mkupd
+++ b/dev-sbc/crossbuild-tools/cb-mkupd
@@ -25,6 +25,13 @@
 # edit-package-accept-keywords()
 # create-new-cross-compiler()
 
+# 20260107 - switched from rust-std (legacy Gentoo Crossbuild-Environment wiki)
+#    to rust-bin as cross-compiler for rust, with RUST_CROSS_TARGETS array
+#    defined at /etc/portage/env/dev-lang/rust
+#    (updated prepare-cross-rust() and deprecated emerge-cross-rust-std in cb-common-functions)
+#    (*for cb-mkupd*) moved prepare-cross-rust to include as part of validate-prerequisites()
+#     which runs BEFORE run-sequence
+
 # ToDo: - consolidate other functions cb-mkimg to cb-common-functions
 
 source /usr/sbin/script_header_joetoo
@@ -78,9 +85,6 @@ command_sequence=(
 'run-dispatch-conf'
 'buildtarget-qemu'
 'emerge-host-world'
-'prepare-cross-rust'
-'rebuild-rust-and-llvm'
-'emerge-cross-rust-std'
 'configure-make-conf-for-chroot'
 'edit-make-conf'
 'cb-chroot-update'
@@ -211,41 +215,21 @@ stockpile-img() {
     return 0
 }
 
-# moved out to cb-chroot-update script
-DISABLED_chroot-update() {
-    separator "${PN}" "(${FUNCNAME[0]})"
-
-    # possible validate dirlist
-    # set old dir; cd mountpoint
-    old_dir="$(pwd)"
-    cd /usr/${TARGET}
-    message "now working in crossbuild target directory: [${Mon}$(pwd)${Boff}]"
-
-    mount_list="proc dev sys "
-    # equivalent to "mount-everything" function in cb-chroot-env (calls mount-chroot-prep)
-    # tmp optional, and /dev/pts only for X
-    mount-chroot-prep || die "failed mount-chroot-prep for ${PN}"
-
-    # actual chroot
-    chroot . /bin/bash --login
-
-    echo
-    cd old_dir
-    message "now working in previous directory: [${Mon}$(pwd)${Boff}]"
-
-    # equivalent to "umount-everything" function in cb-chroot-env (calls mount-chroot-prep)
-    #umount /usr/${TARGET}/dev/pts
-    #umount /usr/${TARGET}/tmp
-    umount-chroot-prep || FLAGGED=$TRUE
-
-    [ $FLAGGED ] && return 1
-    return 0
-}
-
 validate_prerequisites() {
     separator "${PN}" "(${FUNCNAME[o]})"
 
-    # Verify that the STOCKPILE UPDATEIMAGE exists
+    # must do ____ things before we can start or resume run-sequence
+    # (1) Verify that the STOCKPILE UPDATEIMAGE exists
+    # (2) make sure there isn't already something mounted on this TARGET mountpoint
+    # (3) make sure there isn't a ${BOARD}.img file already active for this board
+    # (4) check if a /usr/BOARD.img file is already in use (and remove it if so)
+    # (5) validate the crossdev repository and cross-rust for TARGET
+    # (6) verify the TARGET crossdevelopment mountpoint still exists
+    # (7) copy the STOCKPILE UPDATEIMAGE file to /usr/
+    # (8) mount the new /usr/${BOARD}.img file on the crossdev $TARGET
+
+
+    # (1) Verify that the STOCKPILE UPDATEIMAGE exists
     # do this first so we can assign BOARD and run validate_target to assign TARGET
     message "verifying <UPDATEIMAGE> ..."
     if [ -f "${STOCKPILE%/}/${UPDATEIMAGE}" ] ; then
@@ -267,7 +251,7 @@ validate_prerequisites() {
     # now use BOARD to validate TARGET
     validate_target ${BOARD} || usage
 
-    # make sure there isn't already something mounted on this TARGET mountpoint
+    # (2) make sure there isn't already something mounted on this TARGET mountpoint
     MOUNTPOINT_BUSY=$FALSE
     LOOPDEV_BUSY=$FALSE
     message_n "checking for other active crossbuilding on TARGET mountpoint"
@@ -283,7 +267,7 @@ validate_prerequisites() {
         right_status $TRUE
     fi  # something else mounted for crossbuilding
 
-    # make sure there isn't a ${BOARD}.img file already active for this board
+    # (3) make sure there isn't a ${BOARD}.img file already active for this board
     loop_dev=$(losetup -a -O NAME,BACK-FILE | grep "/usr/${BOARD}.img" | cut -d' ' -f1 | head -n1)
     if [ ! -z "${loop_dev}" ] ; then
         right_status 1
@@ -300,11 +284,11 @@ validate_prerequisites() {
         cb-umount "${BOARD}" || die "failed cb-umount ${BOARD}"
     fi
 
-    # now check if a /usr/BOARD.img file is already in use (and remove it if so)
+    # (4) check if a /usr/BOARD.img file is already in use (and remove it if so)
     message "checking for pre-existing $BOARD.img"
     cb-cleanup "${BOARD}"
 
-    # now verify the crossdev repository for TARGET
+    # (5) validate the crossdev repository and cross-rust for TARGET
     message_n "looking for /var/db/repos/crossdev/"
     if [ ! -d "/var/db/repos/crossdev" ] ; then
         echo -e -n " (${BRon}not found${Boff})"
@@ -323,21 +307,23 @@ validate_prerequisites() {
             echo -e -n " (${BGon}found${Boff})"
             right_status $TRUE
             message "TARGET sub-repo exists and will be updated (Ok to continue)"
-            # now verify that the rust-std symlink is present in the crossdev repository for TARGET
-            message_n "looking for /var/db/repos/crossdev/cross-${TARGET}/rust-std"
-            if [ ! -L /var/db/repos/crossdev/cross-${TARGET}/rust-std ] ; then
-                echo -e -n " (${BRon}not found${Boff})"
-                right_status 1
-                E_message "running prepare-cross-rust()"
-                prepare-cross-rust || die "failed to prepare-cross-rust"
-            else
-                echo -e -n " (${BGon}found${Boff})"
-                right_status $TRUE
-            fi  # rust-std symlink existence
+            # as of crossbuild-tools-0.12.15 and prior used rust-std for cross-rust
+            # based on legacy Gentoo Crossbuild-Environment wiki procedure
+            # starting with 0.12.16 we use rust-bin instead and drop code previously found here to validate
+            # the crossdev repos cross-${TARGET}/rust-std symlinks. Now we just
+            # run prepare-cross-rust() and rebuild-rust-and-llvm() from cb-common-functions
+            # (i.e. these are pre-requisite in cb-mkupd whereas they are part of run-sequence in cb-mkenv)
+            message "(re)validating cross-rust ..."
+            # update configs to use rust-bin as cross-compiler and
+            #  set RUST_LLVM_CHANGE_FLAG=$TRUE in order to make rebuild-rust-and-llvm()
+            #  update rust-bin [which is a dependency of crossbuild-tools], if needed)
+            prepare-cross-rust || die "failed to prepare-cross-rust"
+            # rebuild @world to update rust and llvm with the new configuration, if it changed
+            rebuild-rust-and-llvm || die "failed to rebuild-rust-and-llvm"
         fi # sub-repo existence
     fi  # repo existence
 
-    # now verify the TARGET crossdevelopment mountpoint still exists
+    # (6) verify the TARGET crossdevelopment mountpoint still exists
     message_n "looking for /usr/${TARGET}"
     if [ ! -d "/usr/${TARGET}" ] ; then
         echo -e -n " (${BRon}not found${Boff})"
@@ -350,7 +336,7 @@ validate_prerequisites() {
         right_status $TRUE
     fi  # mountpoint existence
 
-    # now copy the STOCKPILE UPDATEIMAGE file to /usr/
+    # (7) copy the STOCKPILE UPDATEIMAGE file to /usr/
     msg="${BYon}copy ${UPDATEIMAGE} from STOCKPILE to /usr/ as ${BMon}${BOARD}.img${Boff}\n"
     msg+="(if you copied it manually, you can safely skip this)"
     new_prompt "${msg}"
@@ -370,7 +356,7 @@ validate_prerequisites() {
         * ) die "Please correct this before continuing" ;;
     esac
 
-    # now mount the new /usr/${BOARD}.img file on the crossdev $TARGET
+    # (8) mount the new /usr/${BOARD}.img file on the crossdev $TARGET
     cb-mount "${BOARD}" || die "failed to cb-mount ${BOARD}"
 
     return 0
