update cb-dashboard
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-sbc/crossbuild-tools/cb-dashboard b/dev-sbc/crossbuild-tools/cb-dashboard
--- a/dev-sbc/crossbuild-tools/cb-dashboard
+++ b/dev-sbc/crossbuild-tools/cb-dashboard
@@ -24,13 +24,14 @@ stockpile_dir="/home/${user}/sbc-stockpile/"
 PN=$(basename $0)
 
 # specify cross-build targets to look for
-#TARGETS="aarch64-unknown-linux-gnu\|armv7a-unknown-linux-gnueabihf\|armv6j-unknown-linux-gnueabihf"
-#TARGETS="aarch64-unknown-linux-gnu armv7a-unknown-linux-gnueabihf armv6j-unknown-linux-gnueabihf"
-# detect crossdev build targets actually installed (in repo)
-#TARGETS=( $(find /var/db/repos/crossdev/ -mindepth 1 -maxdepth 1 -type d -name 'cross*' -printf '%f\n' | sed 's|^cross-||') )
-#readarray -d'' TARGETS < <(find /var/db/repos/crossdev/ -mindepth 1 -maxdepth 1 -type d -name 'cross*' -print0)
-# NOTE: use -d $'\0' /// NOT -d '' /// also provide final null terminator with ; printf '\0'
-readarray -d $'\0' -t TARGETS < <(find /var/db/repos/crossdev/ -mindepth 1 -maxdepth 1 -type d -name 'cross*' -print0; printf '\0')
+declare -a TARGETS
+# load TARGETS array with selected directory names (starting "cross") output by find command
+# use -print0 to safely pass filenames potentially containing whitespace
+# use readarray -d $'\0' /// NOT -d '' 
+#/// also provide final null terminator with ; printf '\0'
+#readarray -d $'\0' -t TARGETS < <(find /var/db/repos/crossdev/ -mindepth 1 -maxdepth 1 -type d -name 'cross*' -print0; printf '\0')
+# apparently don't need the final \0 terminator - it creates a blank element
+readarray -d $'\0' -t TARGETS < <(find /var/db/repos/crossdev/ -mindepth 1 -maxdepth 1 -type d -name 'cross*' -print0)
 
 #-----[ functions ]--------------------------------------------------------------------------
 
@@ -45,6 +46,8 @@ usage() {
 }
 
 show-dashboard() {
+    local selector=""  # string used to target various function calls
+
     echo
     separator "${PN}-${BUILD}" "( crossdev TARGETs in /var/db/repos/crossdev/ )"
     for TARGET in ${TARGETS[@]}; do echo -e "    ${LBon}${TARGET}${Boff}"; done
@@ -53,12 +56,13 @@ show-dashboard() {
     # for each active loopdevice, show backing file and mounts
     separator "${PN}-${BUILD}" "(active crossbuild loop devices)"
     show-loopdev-backfile-and-mounts "/usr/"
+    [ $? -eq 0 ] && echo   ## echo only if something was presented in output (don't waste space if not)
 
     # now display anything else mounted on one of our TARGETs (e.g. proc, dev, sys for chroot...)
     separator "${PN}-${BUILD}" "(other mounts - e.g. for chroot)"
     for TARGET in ${TARGETS[@]}; do
         selector="${TARGET}"
-        show-mounts "${TARGET}" | grep -v "loop"
+        show-mounts "${selector}" | grep -v "loop"
     done
 
     # now show any other mounts on /dev/sd devices
@@ -79,8 +83,8 @@ show-dashboard() {
     # now do binhosts (selected by 'stockpile')
     separator "${PN}-${BUILD}" "(active binhost loop devices)"
     show-loopdev-backfile-and-mounts "stockpile"
+    [ $? -eq 0 ] && echo   ## echo only if something was presented in output
 
-    echo
     # now show links at webroot/packages/ and their targets
     separator "${PN}-${BUILD}" "(linked binhost web services)"
     show-binary-package-services
@@ -94,6 +98,9 @@ show-dashboard() {
 }
 
 show-stockpile-contents() {
+    local selector=""
+    local category=""
+
     for selector in "env" "img" "qcow2" ; do
         d_message "selector: [${selector}]" 5
         case $selector in
@@ -102,28 +109,41 @@ show-stockpile-contents() {
             *     ) category="other developed images" ;;
         esac
         message "${BMon}crossbuild ${category} (*.${selector})${Boff}"
-        show-stockpile-category "*.${selector}"
+        show-stockpile-filesizes "*.${selector}"
     done
 
 }
 
-show-stockpile-category() {
-    filter="$1"
-    readarray -t backers < <(find ${stockpile_dir} -maxdepth 1 -type f -name "${filter}" -printf '%f\n' | sort -h)
+show-stockpile-filesizes() {
+    local APPARENT_SIZE_BYTES=""
+    local apparent_gibs=""
+    local ACTUAL_SIZE_BYTES=""
+    local actual_gibs=""
+    local filter="$1"    # filename(s) used to filger find command output
 
-    for ((i=0; i<${#backers[@]}; i++)) ; do
-#        echo; echo ${backers[$i]}; echo $(repeat '-' ${#backers[$i]}) ;
-        APPARENT_SIZE_BYTES=$(stat -c%s "${stockpile_dir%/}/${backers[$i]}") ;
+    local -a filenames   # array of filenames found by find command
+
+    readarray -t filenames < <(find ${stockpile_dir} -maxdepth 1 -type f -name "${filter}" -printf '%f\n' | sort -h)
+
+    for ((i=0; i<${#filenames[@]}; i++)) ; do
+#        echo; echo ${filenames[$i]}; echo $(repeat '-' ${#filenames[$i]}) ;
+        APPARENT_SIZE_BYTES=$(stat -c%s "${stockpile_dir%/}/${filenames[$i]}") ;
         apparent_gibs=$(echo "scale=1; (($APPARENT_SIZE_BYTES / 1000 / 1000 / 1000))" | bc) ;
-        ACTUAL_SIZE_BYTES=$(du -B 1 "${stockpile_dir%/}/${backers[$i]}" | awk '{print $1}') ;
+        ACTUAL_SIZE_BYTES=$(du -B 1 "${stockpile_dir%/}/${filenames[$i]}" | awk '{print $1}') ;
         actual_gibs=$(echo "scale=1; (($ACTUAL_SIZE_BYTES / 1000 / 1000 / 1000))" | bc) ;
-        echo -e "    ${BYon}${backers[$i]}${Boff} ( apparent size: ${apparent_gibs}GiB ; actual size: ${actual_gibs}GiB )" ;
+        echo -e "    ${BYon}${filenames[$i]}${Boff} ( apparent size: ${Mon}${apparent_gibs}GiB${Boff} ; actual size: ${Gon}${actual_gibs}GiB${Boff} )" ;
     done
 }
-
-
 
 show-mounts() {
+    local src=""    # mountpoint source found in findmnt output
+    local tgt=""    # mountpoint target found in findmnt output
+    local fstype="" # filesystem type found in findmnt output
+    local opts=""   # mount options found in findmnt output
+    local ro_rw=""  # string to represent read-only/read-write option if present in opts
+
+    local -a mounts_found  # array of lines of output from findmnt command
+
     # display anything mounted on /dev/sd devices (possible outputdevice)
     d_message "  in ${FUNCNAME[0]} with selector: ${selector}" 5
     # -S /dev/sd*: filters for devices originating from /dev/sd*.
@@ -131,66 +151,145 @@ show-mounts() {
     # -l: provides a list format.
     # -o SOURCE,TARGET,FSTYPE: specifies the exact output columns.
     # -r: provides raw output, disabling special formatting.
-    readarray -t mounts_found < <(findmnt -lno SOURCE,TARGET,FSTYPE | grep -E "^${selector}")
+    readarray -t mounts_found < <(findmnt -lno SOURCE,TARGET,FSTYPE,OPTIONS | grep -E "^${selector}")
     d_message "mounts_found[@]: ${mounts_found[@]}" 5
     if [ ! ${#mounts_found[@]} -eq 0 ] ; then
         d_message "#: ${#mounts_found[@]}" 6
         for ((i=0; i<${#mounts_found[@]}; i++)) ; do
             echo ${mounts_found[$i]}
-            eval $(echo ${mounts_found[$i]} | awk '{print "src="$1"; tgt="$2"; fstype="$3}')
-            d_message "src: $src   tgt: $tgt   fstype: $fstype" 5
-            echo -e "        ${BYon}${src}${Boff} is mounted at ${LBon}${tgt}${Boff} with fs_type ${BMon}${fstype}${Boff}"
+            eval $(echo ${mounts_found[$i]} | awk '{print "src="$1"; tgt="$2"; fstype="$3"; opts="$4}')
+            d_message "src: $src   tgt: $tgt   fstype: $fstype   opts: $opts" 5
+            # check mount options for ro/rw (read-only/read-write)
+            if scan_for_mount_option "${mount_options}" "ro" ; then
+                ro_rw="(${BGon}ro${Boff})"
+            elif scan_for_mount_option "${mount_options}" "rw" ; then
+                ro_rw="(${BRon}rw${Boff})"
+            else
+                ro_rw="(${BYon}no ro/rw${Boff})"
+            fi
+            echo -e "        ${BYon}${src}${Boff} is mounted ${ro_rw} at ${LBon}${tgt}${Boff} with fs_type ${BMon}${fstype}${Boff}"
         done
     fi
 }
 
 show-target-repositories-status() {
+    # display the status of (gentoo and joetoo) repositories if anything is mounted at /usr/${TARGET}/
+    local TARGET_DIR="" # path to target repository (element of TARGETS array)
+    local TARGET=""     # one of the tuples (crossdev targets/repository directory names) in global array TARGETS
+    local repo_list=""  # list of repositories
+    local repo=""       # one repository selected
+    local repo_path=""  # path to the one repo selected
+    local repo_info=""  # info returned by file command
+
    # display status of repositories in various /usr/${TARGET} directories
 #    for TARGET in $(echo $TARGETS | sed 's:\\|: :g'); do
-    for TARGET in ${TARGETS} ; do
+    for TARGET_DIR in "${TARGETS[@]}" ; do
+        # extract just <tuple> from /var/db/repos/crossdev/"cross-<tuple>"
+        TARGET="$(basename ${TARGET_DIR} | sed 's|cross-||')"
         repo_list="gentoo joetoo"
-        for repo in ${repo_list} ; do
-            if [ -d /usr/${TARGET}/var/db/repos ] ; then
-                repo_path="/usr/${TARGET}/var/db/repos/${repo}"
-                if [ -e ${repo_path} ] ; then
-                    repo_info=$(file ${repo_path} | cut -d':' -f2)
-                    echo -e "    ${LBon}${repo_path}${Boff} is a ${BWon}${repo_info}${Boff}"
+        if [ -d /usr/${TARGET}/var/db/repos ] ; then
+            # this target has content; list it and look for repos
+            echo -e "    ${BMon}/usr/${TARGET}/var/db/repos${Boff}"
+            for repo in ${repo_list} ; do
+                if [ -d /usr/${TARGET}/var/db/repos/${repo} ] ; then
+                    repo_path="/usr/${TARGET}/var/db/repos/${repo}"
+                    if [ -e ${repo_path} ] ; then
+                        repo_info=$(file "${repo_path}" | awk '{print $2}')
+                        echo -e "        ${BYon}${repo_path}${Boff} is a ${BWon}${repo_info}${Boff}"
+                    else
+                        echo -e "        ${BYon}${repo_path} ${BRon}does not exist${Boff}"
+                    fi  # full repo path
                 else
-                    echo -e "    ${LBon}${repo_path} ${BRon}does not exist${Boff}"
-                fi  # full repo path
-            fi  # /var/db/repos
-        done # repo_list
+                    dE_message "no directory found for [/usr/${TARGET}/var/db/repos/${repo}]" 5
+                fi  # /var/db/repos/${repo}
+            done # repo_list
+        else
+                dE_message "no directory found for [/usr/${TARGET}/var/db/repos]" 5
+        fi  # /var/db/repos
     done # TARGETS
 }
 
 show-loopdev-backfile-and-mounts() {
+    # output info about loop devices and backing files found using selector $1
+    # return 0 if successful; 1 if no results found; 2 if error
     [ ! $# -eq 1 ] && E_message "argument null; ${FUNCNAME[0]} requires selector" && exit 1
-    selector="$1"
+    local selector="$1"     # selector for matching output of losetup
+    local loop_dev=""       # loop device
+    local backing_file=""   # backing file attached to loop device
+    local loop_dev_part=""  # partition within loop device (backing file image)
+    local mountpoint=""     # mountpoint at which loop device partition is mounted
+    local fstype=""         # file system type
+    local mount_options=""  # string containing all mount options for a line of findmnt output
+    local ro_rw=""          # string to return within informative program output
+
+    local -a loop_devices
+    local -a mounts_found
+
     readarray -t loop_devices < <(losetup -lnO NAME,BACK-FILE | grep "${selector}" | sort -h)
-    for ((i=0; i<${#loop_devices[@]}; i++)) ; do
-        # identify the loop_dev name and its backing_file
-        loop_dev="$(echo ${loop_devices[$i]} | cut -d' ' -f1)"
-        backing_file="$(echo ${loop_devices[$i]} | cut -d' ' -f2)"
-        if [ ! -z "${loop_dev}" ] ; then
-            echo -e "    ${BMon}${loop_dev}${Boff} is backed by file: ${BWon}${backing_file}${Boff}"
-            # identify this loop_dev's mounts
-            readarray -t mounts_found < <(findmnt -lno SOURCE,TARGET,FSTYPE | grep -E "^${loop_dev}")
-            for ((j=0; j<${#mounts_found[@]}; j++)) ; do
-                loop_dev_part="$(echo ${mounts_found[$j]} | cut -d' ' -f1)"
-                mountpoint="$(echo ${mounts_found[$j]} | cut -d' ' -f2)"
-                echo -e "        ${BYon}${loop_dev_part}${Boff} is mounted at ${LBon}${mountpoint}${Boff}"
-            done # mounts found for loop_dev
-        fi
-    done # loop_devices
+    if [ ${#loop_devices[@]} -gt 0 ] ; then
+        for ((i=0; i<${#loop_devices[@]}; i++)) ; do
+            # identify the loop_dev name and its backing_file
+            loop_dev="$(echo ${loop_devices[$i]} | cut -d' ' -f1)"
+            backing_file="$(echo ${loop_devices[$i]} | cut -d' ' -f2)"
+            if [ ! -z "${loop_dev}" ] ; then
+                echo -e "    ${BMon}${loop_dev}${Boff} is backed by file: ${BWon}${backing_file}${Boff}"
+                # identify this loop_dev's mounts
+                readarray -t mounts_found < <(findmnt -lno SOURCE,TARGET,FSTYPE,OPTIONS | grep -E "^${loop_dev}")
+                for ((j=0; j<${#mounts_found[@]}; j++)) ; do
+                    loop_dev_part="$(echo ${mounts_found[$j]} | cut -d' ' -f1)"
+                    mountpoint="$(echo ${mounts_found[$j]} | cut -d' ' -f2)"
+                    fstype="$(echo ${mounts_found[$j]} | cut -d' ' -f3)"
+                    mount_options="$(echo ${mounts_found[$j]} | cut -d' ' -f4)"
+                    d_message "mount_options: [$mount_options]" 5
+                    # check mount options for ro/rw (read-only/read-write)
+                    if scan_for_mount_option "${mount_options}" "ro" ; then
+                        ro_rw="(${BGon}ro${Boff})"
+                    elif scan_for_mount_option "${mount_options}" "rw" ; then
+                        ro_rw="(${BRon}rw${Boff})"
+                    else
+                        ro_rw="(${BYon}no ro/rw${Boff})"
+                    fi
+                    echo -e "        ${BYon}${loop_dev_part}${Boff} is mounted ${ro_rw} at ${LBon}${mountpoint}${Boff}"
+                done # mounts found for loop_dev
+            else
+                # no loop device on this line of output (error)
+                die "something wrong here - no loop device on this entry of non-zero array"
+            fi
+        done # loop_devices
+    else
+        # no loop devices found by losetupp command
+        return 1
+    fi  # no loop devices
+}
+
+scan_for_mount_option() {
+    # return 0 if the options string $1 contains the queried option $2; 1 if not found, 2 if error
+    if [ ! $# -eq 2 ] ; then
+        E_message "Usage: ${FUNCNAME[0]} \"<full_options_string>\" \"<search_option>\""
+        return 2
+    fi
+
+    local full_options_string="$1"                 # the string with all mount options returned by findmnt command (externally)
+    local search_option="$2"                       # the mount option to check for in full options string
+    local padded_options=",$full_options_string,"  # Pad the string with commas to reliably check for options at the start/end.
+
+    if [[ "$padded_options" == *",$search_option,"* ]]; then
+        return 0 # Success (option found)
+    else
+        return 1 # Failure (option not found)
+    fi
 }
 
 show-binary-package-services() {
     # display links in webroot and their link_targets
     d_message "  in ${FUNCNAME[0]}" 5
-    website="${webroot%/}/packages"
-    echo; message "${BWon}binhost website: ${BMon}${website}${Boff}"
+    local website="${webroot%/}/packages"  # binary package repository website
+    local link=""                          # link name found by find command
+    local link_target=""                   # target of link extracted from output of file command
+
+    echo; message "${BWon}links at binhost website: ${BMon}${website}${Boff}"
     for link in $(find ${website} -maxdepth 1 -mindepth 1 -type l -printf '%f\n'); do
-        message_n ${BYon}${link}
+        echo -e -n "    ${BYon}${link}"
         link_target=$(echo $(file ${website%/}/${link}) | awk '{print $NF}');
         echo -e "${BWon} --> ${LBon}${link_target}${Boff}"
     done
diff --git a/dev-sbc/crossbuild-tools/cb-mount-binhost b/dev-sbc/crossbuild-tools/cb-mount-binhost
--- a/dev-sbc/crossbuild-tools/cb-mount-binhost
+++ b/dev-sbc/crossbuild-tools/cb-mount-binhost
@@ -77,14 +77,16 @@ validate_mountpoint() {
     return 0
 }
 
-mount-board-image-as-crossbuild-binhost() {
+mount-board-image-as-read-only-binhost() {
     d_message "in ${FUNCNAME[0]}" 5
     # inspect target (mount point) - is anything mounted? (un-mount)
     d_message "MOUNTPOINT ......: ${MOUNTPOINT}" 1
     d_echo 1
     if [ ! -z "$(findmnt -n -M ${MOUNTPOINT})" ] ; then
-        E_message "${BYon}the following devices are already mounted on ${MOUNTPOINT} --${Boff}"
-        mount | grep "on ${MOUNTPOINT}" | sed 's|^|    |'
+#        E_message "${BYon}the following devices are already mounted on ${MOUNTPOINT} --${Boff}"
+#        mount | grep "on ${MOUNTPOINT}" | sed 's|^|    |'
+        E_message "${BYon}the following device is already mounted on ${MOUNTPOINT} --${Boff}"
+        findmnt -n -M ${MOUNTPOINT} | sed 's|^|    |'
         exit 1
     else
         message "nothing is mounted on ${MOUNTPOINT} ; continuing"
@@ -98,8 +100,11 @@ mount-board-image-as-crossbuild-binhost() {
     else
         message "no loop device is yet attached to ${stockpile_dir%/}/${BACKING_FILE}; continuing"
     fi
-    message_n "attaching loop device"
-    img_loop_dev=$(losetup --find --show --partscan ${stockpile_dir%/}/${BACKING_FILE}) && \
+    # mount the binhost backing file with kernel-level read-only protection
+    message_n "attaching loop device (read-only)"
+#    img_loop_dev=$(losetup --find --show --partscan ${stockpile_dir%/}/${BACKING_FILE}) && \
+#        ( echo -n " (${img_loop_dev})" && right_status $? ) || ( right_status $? && exit 1 )
+    img_loop_dev=$(losetup --find --show --partscan --read-only ${stockpile_dir%/}/${BACKING_FILE}) && \
         ( echo -n " (${img_loop_dev})" && right_status $? ) || ( right_status $? && exit 1 )
     # Get partition device names
     message_n "getting device name for partition 1 ..."
@@ -110,11 +115,13 @@ mount-board-image-as-crossbuild-binhost() {
     img_partition2_dev="${img_loop_dev}p2" && result=$? && \
     echo -n " ( ${img_partition2_dev} )" && \
     right_status ${result} || ( right_status $? && exit 1 )
-    # now mount the partitions
-    message_n "mounting rootfs (${img_partition2_dev}) on ${MOUNTPOINT}/ ..."
-    mount ${img_partition2_dev} ${MOUNTPOINT}/ && right_status $? || ( right_status $? && exit 1 )
-    message_n "mounting bootfs (${img_partition1_dev}) on ${MOUNTPOINT}/boot/ ..."
-    mount ${img_partition1_dev} ${MOUNTPOINT}/boot/ && right_status $? || ( right_status $? && exit 1 )
+    # now mount the partitions with mount-layer (filesystem) read-only protection
+    message_n "mounting rootfs (${img_partition2_dev}) on ${MOUNTPOINT}/ (read-only) ..."
+#    mount ${img_partition2_dev} ${MOUNTPOINT}/ && right_status $? || ( right_status $? && exit 1 )
+    mount -o ro ${img_partition2_dev} ${MOUNTPOINT}/ && right_status $? || ( right_status $? && exit 1 )
+    message_n "mounting bootfs (${img_partition1_dev}) on ${MOUNTPOINT}/boot/ (read-only) ..."
+#    mount ${img_partition1_dev} ${MOUNTPOINT}/boot/ && right_status $? || ( right_status $? && exit 1 )
+    mount -o ro ${img_partition1_dev} ${MOUNTPOINT}/boot/ && right_status $? || ( right_status $? && exit 1 )
     return 0
 }
 
@@ -148,7 +155,8 @@ old_dir="$(pwd)"
 cd $(dirname ${MOUNTPOINT}) || die "Failed to change director to parent of mountpoint [${MOUNTPOINT}]"
 message "now working in parent of crossbuild binhost MOUNTPOINT directory: [${Mon}$(pwd)${Boff}]"
 
-mount-board-image-as-crossbuild-binhost || die "failed to mount-board-image-as-crossbuild-binhost"
+#mount-board-image-as-crossbuild-binhost || die "failed to mount-board-image-as-crossbuild-binhost"
+mount-board-image-as-read-only-binhost || die "failed to mount-board-image-as-read-only-binhost"
 
 echo
 cd $old_dir
diff --git a/dev-util/joetoolkit/joetoolkit/tarup b/dev-util/joetoolkit/joetoolkit/tarup
--- a/dev-util/joetoolkit/joetoolkit/tarup
+++ b/dev-util/joetoolkit/joetoolkit/tarup
@@ -5,18 +5,27 @@
 source /usr/sbin/script_header_joetoo
 
 VERBOSE=$TRUE
-verbosity=3
+[ -z $verbosity ] && verbosity=3  # assign default if null; allow calling program to dictate
 
 PN=$(basename $0)
 
 separator ${PN} $(hostname)
 
-taroptions="-cvjpf"
-current_version_numbers=( 0 0 0 )
-new_version_numbers=()
-latest_tarball_version=""
-new_tarball_version=""
-output_tarball_filename=""
+user="joe"
+archived_tarballs_dir="/home/${user}/archived_tarballs"
+
+#-----[ variables ]--------------------------------------------------
+
+taroptions="-cvjpf"                # options for tar command
+to_be_archived_tarball_version=""  # oldest (to-be-archived) version string (to be determined)
+latest_tarball_version=""          # latest version string (to be determined)
+new_tarball_version=""             # new version string (to be calculated)
+output_tarball_filename=""         # filename for the new version's tarball
+
+declare -a tarball_versions        # array of version strings
+
+current_version_numbers=( 0 0 0 )  # array of digits constituting the parts (major minor patch) of current version number
+new_version_numbers=()             # array to hold new version's digits, when calculated
 
 #-----[ functions ]--------------------------------------------------
 usage() {
@@ -32,12 +41,24 @@ usage() {
     exit 1
 }
 
+load-tarball_versions() {
+    # load the tarball_versions array
+    # load array of version numbers for tarballs matching the name of SOURCE_DIR
+    # use \0 as newline delimter for whitespace-safe handling of filenames
+    # subsititutions strip the package name and .tbz2 extension to leave just the version number
+    # sort -rV puts them in reverse version order , -z tells sort to use the \0 delimiter
+    readarray -d $'\0' tarball_versions < <(
+        find ./ -name "${SOURCE_DIR}*.tbz2" -printf '%f\0' |
+        sed -z "s|${SOURCE_DIR}-||g" |
+        sed -z "s|.tbz2$||g" |
+        sort -rVz
+    )
+    return $?
+}
+
 get-current-version() {
-    # find tarballs matching the name of SOURCE_DIR
-    tarball_versions=( $(find ./ -name "${SOURCE_DIR}*.tbz2" -printf '%f\n' | \
-        sed "s|^${SOURCE_DIR}-||" | \
-        sed "s|.tbz2$||" | \
-        sort -rV) )    # reverse-order version sort
+    # put the latest version number string into latest_tarball_version variable
+    local result=""
     d_message "tarball_versions #: ${#tarball_versions[@]}" 2
     # identify the latest version
     if [ ${#tarball_versions[@]} -eq 0 ] ; then
@@ -47,20 +68,41 @@ get-current-version() {
         message " so current tarball version = 0.0.0 [i.e. none]"
     else
         latest_tarball_version="${tarball_versions[0]}"
-        message "current version: ${latest_tarball_version}"
+        message "current version: [${latest_tarball_version}]"
         # split version into ( major minor patch )
         IFS='.' read -ra current_version_numbers <<< $latest_tarball_version
+        result=$?
         # Reset IFS to its default value
         IFS=$' \t\n'
     fi
     message "  current major: ${current_version_numbers[0]}"
     message "  current minor: ${current_version_numbers[1]}"
     message "  current patch: ${current_version_numbers[2]}"
+    return $result
 }
 
-get-new-version() {
+get-archive-version() {
+    # put the oldest (to-be-archived) version number string into to_be_archived_tarball_version variable
+    d_message "tarball_versions #: ${#tarball_versions[@]}" 2
+    # identify the latest version
+    if [ ${#tarball_versions[@]} -eq 0 ] ; then
+        # there are no tarballs matching SOURCE_DIR,
+        # so archive tarball version = 0.0.0 [i.e. none]
+        message "no tarballs matching SOURCE_DIR [${SOURCE_DIR}] found"
+        message "  (so there is nothing to archive)"
+        to_be_archived_tarball_version="none"
+    else
+        to_be_archived_tarball_version="${tarball_versions[ -1 ]}" || die "failed to assign to_be_archived_tarball_version="
+        message "archive version: [${to_be_archived_tarball_version}]"
+    fi
+    return 0
+}
+
+calculate-new-version() {
     # increment the version number appropriately
-    case ${UPGRADE} in
+    local result=""
+    local UPGR="$1"
+    case ${UPGR} in
         "major" )
             # increment major number and reset minor patch number to 0
             new_version_numbers[0]="$(( ${current_version_numbers[0]} + 1 ))"
@@ -79,15 +121,52 @@ get-new-version() {
             new_version_numbers[1]="${current_version_numbers[1]}"
             new_version_numbers[2]="$(( ${current_version_numbers[2]} + 1 ))"
             ;;
-        * )  E_message "invalid UPGRADE type [${UPGRADE}]" && exit ;;
+        * )  E_message "invalid UPGRADE type [${UPGR}]" && exit ;;
     esac
     message "  new major: ${new_version_numbers[0]}"
     message "  new minor: ${new_version_numbers[1]}"
     message "  new patch: ${new_version_numbers[2]}"
     new_tarball_version="${new_version_numbers[0]}.${new_version_numbers[1]}.${new_version_numbers[2]}"
+    result=$?
     message "new version: ${new_tarball_version}"
+    return $result
 }
 
+archive-old-version() {
+    # move the oldest version to the archived_tarballs_dir
+    archive_tarball_filename="${SOURCE_DIR}-${to_be_archived_tarball_version}.tbz2"
+    if [[ "${archive_tarball_filename}" == "none" ]] ; then
+        d_message "no tarball to archive" 3
+    elif [ -f "${archive_tarball_filename}" ] ; then
+        response=""
+        msg="${BYon}About to run command:\n${Boff}"
+        msg+="    ${BGon}mv  ${archive_tarball_filename} ${archived_tarballs_dir%/}/${Boff}\n"
+        msg+="    ${BYon}Please confirm ( ${BWon}y|Y[es]: yes; s|S[kip]: skip; n|N[o]: No (abort program)${Boff} )"
+        new_prompt "${msg}"
+        case ${response:0:1} in
+            [yY] )
+                 mv "${archive_tarball_filename}" "${archived_tarballs_dir%/}/" || die "failed to archive old tarball" ;;
+            [sS] ) message "${BMon}Skipping archive as instructed${Boff}" ;;
+            [nN] ) E_message "Aborting as instructed" ; return 1;;
+            *    ) E_message "Invalid response [$response]" ; return 1;;
+        esac
+    else
+        E_message "Error: tarball [${archive_tarball_filename}] not found"
+        return 1
+    fi
+    return 0
+}
+
+create-new-tarball() {
+    output_tarball_filename="${SOURCE_DIR}-${new_tarball_version}.tbz2"
+
+    msg="${BYon}About to run command:\n${Boff}"
+    msg+="    ${BGon}tar ${taroptions} ${output_tarball_filename} ${SOURCE_DIR}${Boff}"
+    message "${msg}"
+    confirm_continue_or_exit
+    tar "${taroptions}" "${output_tarball_filename}" "${SOURCE_DIR}"
+    return $?
+}
 
 #-----[ main script ]------------------------------------------------
 checknotroot
@@ -108,13 +187,14 @@ else
     UPGRADE="patch"; message "initiating patch upgrade (as default) ..."
 fi
 
-get-current-version
-get-new-version
+load-tarball_versions || die "failed to load-tarball_versions"
+get-current-version || die "failed to get-current-version"
+get-archive-version || die "failed to get-archive-version"
 
-output_tarball_filename="${SOURCE_DIR}-${new_tarball_version}.tbz2"
+archive-old-version || die "failed to archive-old-version"
 
-msg="${BYon}About to run command:\n${Boff}"
-msg+="    ${BGon}tar ${taroptions} ${output_tarball_filename} ${SOURCE_DIR}${Boff}"
-message "${msg}"
-confirm_continue_or_exit
-tar "${taroptions}" "${output_tarball_filename}" "${SOURCE_DIR}"
+calculate-new-version "${UPGRADE}" || die "failed to calculate-new-version ${UPGRADE}"
+
+create-new-tarball || die "failed to create-new-tarball"
+
+message "${BGon}Done${Boff}"
