version minor bump with working cb-mkenv, cb-mkimg, cb-mkdev
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-sbc/crossbuild-tools/cb-flash-device b/dev-sbc/crossbuild-tools/cb-flash-device
--- a/dev-sbc/crossbuild-tools/cb-flash-device
+++ b/dev-sbc/crossbuild-tools/cb-flash-device
@@ -97,7 +97,9 @@ usage() {
 }
 
 check-target-board-loopmount() {
-    separator "(check-target-board-loopmount)" ${PN}
+    separator ${PN} "(${FUNCNAME[0]})"
+    d_message "in ${FUNCNAME[0]}" 5
+
     FLAGGED=$FALSE
     # inspect target (mount point) - verify that BOARD is mounted and get its loop_dev
     if [[ ! -z $(findmnt -ln | grep "/usr/${TARGET}") ]] ; then
@@ -139,8 +141,9 @@ check-target-board-loopmount() {
 }
 
 prep-newroot() {
-    separator "(prep-newroot)" ${PN}
-    d_message "in prep-newroot" 4
+    separator ${PN} "(${FUNCNAME[0]})"
+    d_message "in ${FUNCNAME[0]}" 5
+
     # examine OUTPUTDEVICE expected to be o(if luks, pen and) ready for mounting
     message_n "is newroot mounted?"
     if [[ -z "$(findmnt -ln | grep ${newroot_mountpoint})" ]] ; then
@@ -186,15 +189,16 @@ prep-newroot() {
             echo -en " ${BMon}${root_dev}"${Boff}
             mount ${root_dev} ${newroot_mountpoint} && right_status $? || \
                 die "failed to mount /dev/mapper/${root_lv}"
-        # otherwise, if there's a LABEL=root_fs device, mount it on newroot_mountpoint
-        elif [[ ! -z "$(blkid ${OUTPUTDEVICE}* | grep -i root_fs)" ]] ;  then
-            # use blkid data to idendify root_fs device (e.g. /dev/sdb)
-            root_dev=$(blkid ${OUTPUTDEVICE}* | grep boot_fs | cut -d' ' -f1 | sed 's|\:$||')
-            echo -en " ${LBon}${root_dev}${Boff}"
-            mount ${root_dev} ${newroot_mountpoint} && right_status $? || \
-                die "failed to mount /dev/mapper/${root_lv}"
+        # otherwise, identify the rootdev and mount it on newroot_mountpoint
         else
-            die "no root luks or regular block device found"
+            # identify the name and UUID of the root device (LV if LUKS, part if not)
+           identify_root_device || die "failed to identify_root_device for ${PN}"
+           d_message "(${PN}) ROOT_DEVICE: $ROOT_DEVICE   ROOT_UUID: $ROOT_UUID" 5
+
+            # use blkid data to idendify root_fs device (e.g. /dev/sdb)
+            echo -en " ${LBon}${ROOT_DEVICE}${Boff}"
+            mount ${ROOT_DEVICE} ${newroot_mountpoint} || die "failed to mount ${ROOT_DEVICE} ${newroot_mountpoint}"
+            right_status $TRUE
         fi
         # if we get here, it should be successfully mounted
         right_status $TRUE
@@ -205,30 +209,32 @@ prep-newroot() {
         echo -e " ${BGon}yes${Boff}" ; right_status $TRUE
     fi
     # whether already mounted or just mounted, we can now go to newroot_mountpoint
-    #   and if there is a mount-the-rest script, run it ( mount-newroot() )
+    #   and if there is a mount-the-rest script, run it ( mount-the-rest-on-newroot() )
     return 0
 }
 
-mount-newroot() {
-    separator "(mount-newroot)" ${PN}
-    d_message "in mount-newroot" 5
+mount-the-rest-on-newroot() {
+    separator ${PN} "(${FUNCNAME[0]})"
+    d_message "in ${FUNCNAME[0]}" 5
+
     old_dir=$(pwd)
     message_n "moving from $(pwd) to ${newroot_mountpoint} ..."
     cd ${newroot_mountpoint} && right_status $? || die "failed to cd ${newroot_mountpoint}"
     message "now working in $(pwd)"
     message_n "looking for mount-the-rest script"
-    mounttherestscript="$(find ./ -iname 'mount-the-rest*' -type f -executable)" && right_status $? || \
+    mount_the_rest_script="$(find ./ -iname 'mount-the-rest*' -type f -executable)" && right_status $? || \
         die "failed to find ./ -iname 'mount-the-rest*' -type f -executable"
 
     # "DANGER Will Robinson" - check the resulting script builds reliably, before sourcing it
-#    exec ${mounttherestscript}
-    source ${mounttherestscript}
+#    exec ${mount_the_rest_script}
+    source ${mount_the_rest_script}
     return 0
 }
 
 copy-content() {
-    separator "(copy-content)" ${PN}
-    d_message "in copy-content" 4
+    separator ${PN} "(${FUNCNAME[0]})"
+    d_message "in ${FUNCNAME[0]}" 5
+
     # ok - now copy content
     msg="about to run cp -av /usr/${TARGET}/* ${newroot_mountpoint}/ \n"
     msg+="are you sure you want to continue"
@@ -278,7 +284,12 @@ display_configuration || die "failed to display_configuration"
 echo
 format_warning || die "failed format warning somehow, oddly"
 
-mount-newroot || die "failed to mount-newroot"
+if [ ${partition_count} -gt 1 ] ; then
+    mount-the-rest-on-newroot || die "failed to mount-the-rest-on-newroot"
+else
+    message "partition_count is [${partition_count}] so mount-the-rest is N/A; skipping"
+fi
+
 copy-content || die "failed to copy-content"
 
 separator "(wrapping up)" ${PN}
diff --git a/dev-sbc/crossbuild-tools/cb-layout-device b/dev-sbc/crossbuild-tools/cb-layout-device
--- a/dev-sbc/crossbuild-tools/cb-layout-device
+++ b/dev-sbc/crossbuild-tools/cb-layout-device
@@ -41,6 +41,10 @@ hidden_varlist="crypt_passphrase"
 
 #-----[ functions ]-------------------------------------------------------------------------
 
+# non-stty-separator() ...... moved to /usr/sbin/script_header_joetoo_extended
+# non-stty-right_status () .. moved to /usr/sbin/script_header_joetoo_extended
+# list_unused_disks(() ...... moved to /usr/sbin/script_header_joetoo_extended
+
 usage() {
     E_message "${BRon}usage: ${BGon}${PN} <BOARD> <OUTPUTDEVICE>${Boff}"
     echo
@@ -55,10 +59,6 @@ usage() {
     echo
     exit 1
 }
-
-# non-stty-separator() ...... moved to /usr/sbin/script_header_joetoo_extended
-# non-stty-right_status () .. moved to /usr/sbin/script_header_joetoo_extended
-# list_unused_disks(() ...... moved to TBD
 
 initialize_variables() {
 
@@ -768,12 +768,12 @@ format_partitions() {
     d_message "in ${FUNCNAME[0]}" 4
 
     # use blkid template data (already ingested) to format partitions
-    for ((i=1; i<${partition_count}; i++)) ; do
-        # determine the partition name on the new device
-        # use TYPE in formatted lablk -o output to filter on partition (ignore disk) lines with grep 'part'
-        # use PARTN to identify THIS partition number in column 3 of formated -o output with awk
-#        p_name="$(lsblk -nlo NAME,TYPE,PARTN ${OUTPUTDEVICE} | grep 'part' | awk -v var="${i}" '$3 == var {print}' | cut -d' ' -f1)"
-#        p_dev_name="/dev/${p_name}"
+    for ((i=1; i<=${partition_count}; i++)) ; do
+        # if this is the last partition in a LUKS setup, don't format it; be done now
+        [ $i -eq ${partition_count} ] && [ $LUKS ] && return 0
+        # otherwise, determine the partition name on the new device
+        #   use TYPE in formatted lablk -o output to filter on partition (ignore disk) lines with grep 'part'
+        #   use PARTN to identify THIS partition number in column 3 of formated -o output with awk
         p_dev_name="${OUTPUTDEVICE}${p_prefix}${i}"
         d_message "i: $i" 4
         d_message "p_dev_name: $p_dev_name" 4
@@ -960,16 +960,8 @@ mount_and_populate() {
     d_message "in ${FUNCNAME[0]}" 4
 
     # identify the name and UUID of the root device (LV if LUKS, part if not)
-    # lsblk doesn't know fs labels for lvm LVs, so we have to use blkid to get this
-    message_n "identifying root device"
-    [ $LUKS ] && rootdev_prefix="/dev/mapper/vg_${DEV_HOSTNAME}" || rootdev_prefix=${OUTPUTDEVICE}
-    LINE=$(blkid ${rootdev_prefix}*  | grep 'root_fs')
-    ROOT_DEVICE=$(echo $LINE | cut -d':' -f1)
-    remainder=$(echo $LINE | cut -d':' -f2-) ; eval ${remainder}  #assigns LABEL, UUID, TYPE, etc
-    ROOT_UUID="${UUID}"
-    echo -en " ( $ROOT_DEVICE | $ROOT_UUID )"
-    right_status $TRUE
-    d_message "ROOT_DEVICE: $ROOT_DEVICE   ROOT_UUID: $ROOT_UUID" 4
+    identify_root_device || die "failed to identify_root_device for ${PN}"
+    d_message "(${PN}) ROOT_DEVICE: $ROOT_DEVICE   ROOT_UUID: $ROOT_UUID" 5
 
     message_n "mounting new root dev [ /dev/mapper/vg_${DEV_HOSTNAME}-root ] ..."
     mount ${ROOT_DEVICE} ${root_dev_mountpoint} 2>/dev/null || die "failed to mount ${ROOT_DEVICE} ${root_dev_mountpoint} "
@@ -987,6 +979,19 @@ mount_and_populate() {
         die "failed to copy chroot-commands text file to ${root_dev_mountpoint%/}/"
     right_status $TRUE
 
+    # if there is not more than one partition, then this is not applicable
+    if [ ${partition_count} -gt 1 ] ; then
+        # populate the mount-the-rest.<hostname> script, to mount other LVs and/or partitions
+        write_mount_the_rest_script || die "failed to write_mount_the_rest_script"
+    else
+        message "partition_count is [${partition_count}]; mount-the-rest script is N/A; skipping"
+    fi
+
+    [ $ERROR ] && return 1
+    return 0
+}
+
+write_mount_the_rest_script() {
     # populate the mount-the-rest.<hostname> script, to mount other LVs and/or partitions
     # initialize script file by writing header line with ">"
     message_n "creating ${mount_the_rest_script} ..."
@@ -1108,8 +1113,6 @@ mount_and_populate() {
     message_n "making ${root_dev_mountpoint%/}/${mount_the_rest_script} executable"
     chmod +x ${root_dev_mountpoint%/}/${mount_the_rest_script} && \
     right_status $? || (right_status $?; ERROR=$TRUE)
-
-    [ $ERROR ] && return 1
     return 0
 }
 
