major rewrite of dev-sbc/crossbuild-tools to consolidate functions to script_header_joetoo and _extended (cli processing, useage, etc) and to fix some bugs, refine/add features

diff --git a/dev-sbc/crossbuild-tools/cb-flash-device b/dev-sbc/crossbuild-tools/cb-flash-device
--- a/dev-sbc/crossbuild-tools/cb-flash-device
+++ b/dev-sbc/crossbuild-tools/cb-flash-device
@@ -5,6 +5,12 @@
 #
 
 source /usr/sbin/script_header_joetoo
+message_n "sourcing BUILD ..."
+source /etc/crossbuild-tools/BUILD ; right_status $?
+message_n "sourcing BPN ..."
+source /etc/crossbuild-tools/BPN ; right_status $?
+source /usr/sbin/script_header_joetoo_extended
+
 VERBOSE=$TRUE
 #verbosity=2
 verbosity=3
@@ -32,14 +38,17 @@ hidden_varlist="crypt_passphrase luks_partition_device"
 
 initialize_variables() {
 
-    message_n "sourcing BUILD ..."
-    source /etc/crossbuild-tools/BUILD ; right_status $?
-
     message_n "sourcing cb-common-functions ..."
     source /usr/sbin/cb-common-functions ; right_status $?
 
     initialize_vars ${varlist}
     initialize_vars ${hidden_varlist}
+
+    message_n "sourcing BUILD ..."
+    source /etc/crossbuild-tools/BUILD ; right_status $?
+
+    message_n "sourcing BPN ..."
+    source /etc/crossbuild-tools/BPN ; right_status $?
 
     message_n "re-initializing VERBOSE = TRUE ..."
     VERBOSE=$TRUE ; right_status $?
@@ -81,23 +90,10 @@ initialize_variables() {
     return 0
 }
 
-usage() {
-    E_message "${BRon}usage: ${BGon}${PN} <OUTPUTDEVICE> <BOARD>${Boff}"
-    echo
-    message "${PN} requires a valid (already formatted) OUTPUTDEVCE, and it also requires"
-    message "  a valid (already cross-built and mounted) BOARD as its second argument"
-    echo
-    message "${BYon}Notess:${Boff}"
-    message " ${LBon}(1) Crossbuild TARGET, BOARD, which function as de facto SOURCES here, ${Boff}"
-    message " ${LBon}    are expected to be set up prior to running ${PN}${Boff}"
-    message " ${LBon}(2) OUTPUTDEVICE functions as a defacto output target here, and it is${Boff}"
-    message " ${LBon}    expected to already be formatted, (if luks, unlocked) and${Boff}"
-    message " ${LBon}    ready to be mounted for flashing${Boff}"
-    message " ${LBon}(3) OUTPUTDEVICE's bootloader (grub menu, config.txt, joetooEnv.txt, etc)${Boff}"
-    message " ${LBon}    and /etc/fstab will need to be updated after the image is flashed to${Boff}"
-    message " ${LBon}    this new block device${Boff}"
-    usage-common-message
-    exit 1
+myusage() {
+    message "${BRon}usage: ${BGon}${PN} <OUTPUTDEVICE>${Boff}"
+    source /etc/${BPN}/local.usage
+    exit
 }
 
 check-target-board-loopmount() {
@@ -203,7 +199,7 @@ prep-newroot() {
         # if we get here, it should be successfully mounted
         right_status $TRUE
     else
-        # use lsblk data to set root_dev
+        # use findmnt data to set root_dev
         eval $(findmnt -o TARGET,SOURCE -P | grep ${newroot_mountpoint})
         root_dev=${SOURCE}
         echo -e " ${BGon}yes${Boff}" ; right_status $TRUE
@@ -224,7 +220,7 @@ mount-newroot() {
     mounttherestscript="$(find ./ -iname 'mount-the-rest*' -type f -executable)" && right_status $? || \
         die "failed to find ./ -iname 'mount-the-rest*' -type f -executable"
 
-    # DANGER Will Robinson - check this first
+    # "DANGER Will Robinson" - check the resulting script builds reliably, before sourcing it
 #    exec ${mounttherestscript}
     source ${mounttherestscript}
     return 0
@@ -253,13 +249,13 @@ copy-content() {
 checkroot
 separator "$(hostname)" "${PN}"
 initialize_variables || die "failed to initialize variables"
-[ $# -ne 2 ] && usage
+[ $# -ne 2 ] && myusage
 OUTPUTDEVICE=$1
 BOARD=$2
 # board must be set in environment by calling script or manually
 d_message "about to run validate_target ${BOARD}" 3
-validate_target ${BOARD}
-validate_device ${OUTPUTDEVICE}
+validate_target ${BOARD} || die "failed to validate_target [${BOARD}]"
+validate_device ${OUTPUTDEVICE} || die "failed to validate_device [${OUTPUTDEVICE}]"
 
 message "confirming BOARD is mounted on crossbuild TARGET ..."
 check-target-board-loopmount ; result=$?
@@ -278,7 +274,7 @@ varlist+=" BREAK bool.VERBOSE verbosity bool.FLAGGED bool.ERROR"
 # it can't get edev until it creates one, be we can get both now
 prep-newroot || die "failed to prep-newroot"
 
-display_configuration
+display_configuration || die "failed to display_configuration"
 echo
 format_warning || die "failed format warning somehow, oddly"
 
diff --git a/dev-sbc/crossbuild-tools/cb-layout-device b/dev-sbc/crossbuild-tools/cb-layout-device
--- a/dev-sbc/crossbuild-tools/cb-layout-device
+++ b/dev-sbc/crossbuild-tools/cb-layout-device
@@ -5,6 +5,12 @@
 #
 
 source /usr/sbin/script_header_joetoo
+message_n "sourcing BUILD ..."
+source /etc/crossbuild-tools/BUILD ; right_status $?
+message_n "sourcing BPN ..."
+source /etc/crossbuild-tools/BPN ; right_status $?
+source /usr/sbin/script_header_joetoo_extended
+
 VERBOSE=$TRUE
 #verbosity=2
 verbosity=3
@@ -25,14 +31,17 @@ hidden_varlist="crypt_passphrase partition_device luks_partition_device"
 
 initialize_variables() {
 
-    message_n "sourcing BUILD ..."
-    source /etc/crossbuild-tools/BUILD ; right_status $?
-
     message_n "sourcing cb-common-functions ..."
     source /usr/sbin/cb-common-functions ; right_status $?
 
     initialize_vars ${varlist}
     initialize_vars ${hidden_varlist}
+
+    message_n "sourcing BUILD ..."
+    source /etc/crossbuild-tools/BUILD ; right_status $?
+
+    message_n "sourcing BPN ..."
+    source /etc/crossbuild-tools/BPN ; right_status $?
 
     message_n "re-initializing VERBOSE = TRUE ..."
     VERBOSE=$TRUE ; right_status $?
@@ -85,7 +94,7 @@ initialize_variables() {
     return 0
 }
 
-usage() {
+myusage() {
     E_message "${BRon}usage: ${BGon}${PN} <OUTPUTDEVICE>${Boff}"
     echo
     message "${PN} requires exactly one valid device name as its only argument"
@@ -93,24 +102,12 @@ usage() {
     echo
     list_unused_disks
     echo
-    usage-common-message
+    source /etc/${BPN}/local.usage
     exit 1
 }
 
-non-stty-separator() {  # expects TERMWIDTH to be set in environment
-    local msg preface msg_len;
-    [ ! -z "$2" ] && preface="$2" || preface=$(hostname);
-    msg="${BYon}---[${BRon} $preface ${LBon}$1 ${BYon}]";
-    msg_len=$(( ${#msg} - $(( ${#BYon} + ${#BRon} + ${#BBon} + ${#BYon} + ${#Boff} )) ));
-    echo -en "$msg" && echo -n $(repeat "-" $(( ${TERMWIDTH} - $(( $msg_len + ${#Boff} )) ))) && echo -e ${Boff} && return 0 || return 1
-}
-
-non-stty-right_status ()
-{
-    local msg status=$1;
-    [[ $status -eq 0 ]] && msg="${BBon}[ ${BGon}Ok ${BBon}]${Boff}" || msg="${BBon}[ ${BRon}!! ${BBon}]${Boff}";
-    echo -en "\r" && CUF $(( ${TERMWIDTH} - 7 )) && echo -e "$msg" && return 0 || return 1
-}
+# non-stty-separator() ...... moved to /usr/sbin/script_header_joetoo_extended
+# non-stty-right_status () ..  moved to /usr/sbin/script_header_joetoo_extended
 
 list_unused_disks() {
     # set this now because doing so will be an inappropriate use of io control for stdin during while loop's redirection for "read line"
@@ -639,7 +636,7 @@ layout_cryptsetup() {
 checkroot
 separator "$(hostname)" "${PN}"
 initialize_variables || die "failed to initialize variables"
-[ $# -ne 1 ] && usage
+[ $# -ne 1 ] && myusage
 OUTPUTDEVICE=$1
 validate_device ${OUTPUTDEVICE} || die "failed to validate device [ ${OUTPUTDEVICE} ]"
 validate_config || die "failed to validate config"
@@ -648,7 +645,7 @@ if [ $LUKS ] ; then
     finalize_config || die "failed to finalize config"
 fi
 
-display_configuration
+display_configuration || die "failed to display_configuration"
 
 format_warning || die "failed format warning somehow, oddly"
 
diff --git a/dev-sbc/crossbuild-tools/cb-mkdev b/dev-sbc/crossbuild-tools/cb-mkdev
--- a/dev-sbc/crossbuild-tools/cb-mkdev
+++ b/dev-sbc/crossbuild-tools/cb-mkdev
@@ -10,6 +10,11 @@
     #    the image file is ready to be transferred to a real block device, finalized, and deployed
 
 source /usr/sbin/script_header_joetoo
+message_n "sourcing BUILD ..."
+source /etc/crossbuild-tools/BUILD ; right_status $?
+message_n "sourcing BPN ..."
+source /etc/crossbuild-tools/BPN ; right_status $?
+source /usr/sbin/script_header_joetoo_extended
 
 #-----[ variables ]-----------------------------------------------------
 
@@ -18,10 +23,9 @@ VERBOSE=$TRUE
 verbosity=3
 PN=$(basename $0)
 
-
 response=""
 
-varlist="PN BUILD OUTPUTDEVICE BOARD TARGET TARGET_ARCH QEMU_ARCH"
+varlist="PN BPN BUILD OUTPUTDEVICE BOARD TARGET TARGET_ARCH QEMU_ARCH"
 varlist+=" layout_number"
 varlist+=" starting_step stopping_step mkdevstatusfile"
 varlist+=" bool.RESUME bool.INTERACTIVE"
@@ -56,48 +60,10 @@ msg2_sequence=(
 
 #-----[ functions ]-----------------------------------------------------
 
-message_n "sourcing BUILD ..."
-source /etc/crossbuild-tools/BUILD ; right_status $?
-
 message_n "sourcing cb-common-functions ..."
 source /usr/sbin/cb-common-functions ; right_status $?
 
-usage() {
-  N=$(( ${#command_sequence[@]} -1 ))
-  separator "${PN}-${BUILD}" "$(hostname)"
-  E_message "${BRon}Usage: ${BGon}${PN} [-[options]] -b|--board <BOARD> -o <OUTPUTDEVICE>${Boff}"
-  message "${BYon}Valid Options --${Boff}"
-  message "  -i | --interactive..................: run interactively; confirm execution of each step"
-  message "  -n | --noninteractive...............: run non-interactively; proceed automatically with each step"
-  message "  -s | --status.......................: return status (next step, step_number)"
-  message "  -r | --resume.......................: resume proccessing (with next step, from mkenvstatusfile)"
-  message "  -o | --outputdevice <OUTPUTDEVICE>..: specify DEVICE to be formatted and flashed"
-  message "  -b | --board <BOARD>................: specify BOARD (selects crossbuilt TARGET to use as source)"
-  message "  -v | --verbose......................: increase verbosity"
-  message "  -q | --quiet........................: decrease verbosity"
-  message "  -[0-${N}].............................: save N to status file and resume at step N"
-  echo
-  message "${BMon}Note: single-character options (except o & b) may be combined. For example -${Boff}"
-  message "  ${BGon}${PN} --verbose -nqr11 -o /dev/nvme0n1 -b bcm2712-rpi-cm5-cm5io${Boff}"
-  message "  ${BYon}would resume non-interactively at step 11 with normal verbosity${Boff}"
-  message "  ${BYon}to lay out and format /dev/nvme0n1 and flash it with the contents of"
-  message "  the /usr/bcm2712-rpi-cm5-cm5io.img board image file${Boff}"
-  echo
-  message "${BMon}Other notes:${Boff}"
-  message "   - options -i (interactive) is on by default"
-  message "   - option  -r (resume) sets starting_step to value in mkenvstatusfile [ $mkenvstatusfile ]"
-  message "   - option  -[0-${N}] sets starting_step (default 0) to the specified value"
-  message "   - exactly one valid block device may be specified (user will be prompted otherwise)"
-  message "   - ${PN} will default to a previously mounted BOARD image file, if a new one"
-  message "     is not specified on the command line; user may override with prompt response"
-  usage-common-message
-  message "${BYon}Command sequence steps:${Boff}"
-  for ((s=0; s<${#command_sequence[@]}; s++))
-  do
-    echo -e "    ${LBon}${s}: ${command_sequence[$s]}${Boff}"
-  done
-  exit 1
-}
+# usage moved to script_header_joetoo_extended, which will source /etc/${BPN}/local.usage
 
 initialize_variables() {
     [ $verbosity -lt 2 ] && message_n "initializing ..." || message "initializing ..."
@@ -107,6 +73,10 @@ initialize_variables() {
     FLAGGED=$FALSE
     d_message_n "sourcing BUILD ..." 2
     source /etc/crossbuild-tools/BUILD && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    d_message_n "setting PN = $(basename $0)" 2
+    PN=$(basename $0) && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    d_message_n "sourcing BPN ..." 2
+    source /etc/crossbuild-tools/BPN && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
     d_message_n "setting old_dir = $(pwd)" 2
     export old_dir=$(pwd) && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
     d_message_n "setting default starting_step = 0" 2
@@ -115,8 +85,6 @@ initialize_variables() {
     export stopping_step=$(( ${#command_sequence[@]} - 1 )) && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
     d_message_n "setting default mkdevstatusfile = /root/bin/mkcrossbuilddev_status" 2
     export mkdevstatusfile="/root/bin/mkcrossbuilddev_status" && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
-    d_message_n "setting PN = $(basename $0)" 2
-    PN=$(basename $0) && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
     d_message_n "setting default layout_number = 1" 2
     layout_number=1 && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
     d_message_n "setting default INTERACTIVE true" 2
@@ -251,6 +219,7 @@ eselect-layout() {
 
 post-flash-cleanup() {
     separator "(post-flash-cleanup)" ${PN}
+    message "${BYon}post-flash-cleanup is not implemented yet${Boff}"
     # umount outputdevice
     # umount BOARD/TARGET
     # provide parting instructions
@@ -259,29 +228,28 @@ post-flash-cleanup() {
 #-----[ main script ]---------------------------------------------
 checkroot
 separator ${PN} $(hostname)
-  if [ $# -eq 1 ] ; then
-    # option s (status) is the only one that can appear alone on the command line
-    if [[ "$1" != "-"*"s"* ]] && [[ "$1" != "--status" ]] ; then
-      E_message "invalid argument [${arglist}]"
-      usage
-    fi
-  fi
+# option s (status) is the only one that can appear alone on the command line
+if [ $# -eq 1 ] ; then if [[ "$1" != "-"*"s"* ]] && [[ "$1" != "--status" ]] ; then
+    E_message "invalid argument [${arglist}]"
+    usage
+fi; fi
 
-initialize_variables     # set defaults
+validate_status_file ${mkdevstatusfile} || die "failed validate_status_file ${mkdevstatusfile}"
+
+# initialize variables and set default values
+initialize_variables || die "Failed to initialize_variables"
 
 d_echo "cmdline: $*" 5
 d_echo "processing cmdline args: $@" 5
 
-msg="processing cmdline ..."
-[ $verbosity -lt 2 ] && message_n "${msg}" || message "${msg}"
-process_cmdline "${@}"   # override defaults, sets BOARD or TARGET
-right_status $?
+# over-ride configuration with commandline input
+separator ${PN} "(process_cmdline)"
+process_cmdline ${@} || die "Failed to process_cmdline"
 
+validate_target ${BOARD} || die "failed to validate_target [${BOARD}]"
+display_configuration || die "failed to display_configuration"
 sanity_check || die "failed sanity_check"
-validate_target ${BOARD} || die "failed validate_target ${BOARD}"
-validate_status_file ${mkdevstatusfile} || die "failed validate_status_file ${mkdevstatusfile}"
-display_configuration || die "failed display_configuration"
-run_sequence ${mkdevstatusfile} || die "failed run_sequence"
+run_sequence ${mkdevstatusfile} || die "failed to run_sequence"
 
 echo
 cd $old_dir
diff --git a/dev-sbc/crossbuild-tools/cb-mkenv b/dev-sbc/crossbuild-tools/cb-mkenv
--- a/dev-sbc/crossbuild-tools/cb-mkenv
+++ b/dev-sbc/crossbuild-tools/cb-mkenv
@@ -20,6 +20,11 @@
 #    workflow scripts (cb-mkenv and cb-complete-image)
 
 source /usr/sbin/script_header_joetoo
+message_n "sourcing BUILD ..."
+source /etc/crossbuild-tools/BUILD ; right_status $?
+message_n "sourcing BPN ..."
+source /etc/crossbuild-tools/BPN ; right_status $?
+source /usr/sbin/script_header_joetoo_extended
 
 #-----[ variagles ]-----------------------------------------------------
 
@@ -28,10 +33,9 @@ VERBOSE=$TRUE
 #verbosity=1
 verbosity=2
 PN=$(basename $0)
-
 response=""
 
-varlist="PN BUILD BOARD TARGET TARGET_ARCH QEMU_ARCH STAGE3_SELECTOR"
+varlist="PN BPN BUILD BOARD TARGET TARGET_ARCH QEMU_ARCH STAGE3_SELECTOR"
 varlist+=" profile_number"
 varlist+=" starting_step stopping_step mkenvstatusfile"
 varlist+=" bool.RESUME bool.INTERACTIVE"
@@ -100,49 +104,10 @@ msg2_sequence=(
 
 #-----[ functions ]-----------------------------------------------------
 
-message_n "sourcing BUILD ..."
-source /etc/crossbuild-tools/BUILD ; right_status $?
-
 message_n "sourcing cb-common-functions ..."
 source /usr/sbin/cb-common-functions ; right_status $?
 
-usage() {
-  N=$(( ${#command_sequence[@]} -1 ))
-  separator "${PN}-${BUILD}" "$(hostname)"
-  E_message "${BRon}Usage: ${BGon}${PN} [-[options]] -b|--board <BOARD>${Boff}"
-  message "${BYon}Valid Options --${Boff}"
-  message "  -i | --interactive......: run interactively; confirm execution of each step"
-  message "  -n | --noninteractive...: run non-interactively; proceed automatically with each step"
-  message "  -s | --status...........: return status (next step, step_number)"
-  message "  -d | --destroy..........: just clean target/board environment"
-  message "  -c | --create...........: clean,then create/populate a target/board cross-compiler and environment"
-  message "  -r | --resume...........: resume proccessing (with next step, from mkenvstatusfile)"
-  message "  -b | --board <BOARD>....: specify BOARD (selects TARGET) for crossbuild environment"
-  message "  -t | --target <TARGET> .: specify TARGET for crossbuild environment"
-  message "  -v | --verbose..........: increase verbosity"
-  message "  -q | --quiet............: decrease verbosity"
-  message "  -[0-${N}].................: save N to status file and resume at step N"
-  echo
-  message "${BMon}Note: single-character options (except b or t) may be combined. For example -${Boff}"
-  message "  ${BGon}${PN} --verbose -nqr11 -t armv6j-unknown-linux-gnueabihf${Boff}"
-  message "  ${BYon}would resume non-interactively at step 11 with normal verbosity${Boff}"
-  nessage "  ${BYon}creating a generic-armv6j board image on the selected target${Boff}"
-  echo
-  message "${BMon}Other notes:${Boff}"
-  message "   - options -i (interactive) is on by default"
-  message "   - options -c (create) and -d (destroy) are off by default and set starting_step=0"
-  message "   - option  -r (resume) sets starting_step to value in mkenvstatusfile [ $mkenvstatusfile ]"
-  message "   - option  -[0-${N}] sets starting_step to the specified value"
-  message "   - if a BOARD is specified, TARGET will be selected, overriding any -t setting"
-  message "   - if no BOARD is specified, TARGET must be, implying a generic TARGET environment"
-  usage-common-message
-  message "${BYon}Command sequence steps:${Boff}"
-  for ((s=0; s<${#command_sequence[@]}; s++))
-  do
-    echo -e "    ${LBon}${s}: ${command_sequence[$s]}${Boff}"
-  done
-  exit 1
-}
+# usage() ... moved to script_header_joetoo_extended, suplemented by /etc/${BPN}/local.usage
 
 initialize_variables() {
     [ $verbosity -lt 2 ] && message_n "initializing ..." || message "initializing ..."
@@ -152,6 +117,10 @@ initialize_variables() {
     FLAGGED=$FALSE
     d_message_n "sourcing BUILD ..." 2
     source /etc/crossbuild-tools/BUILD && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    d_message_n "setting PN = $(basename $0)" 2
+    PN=$(basename $0) && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    d_message_n "sourcing BPN ..." 2
+    source /etc/crossbuild-tools/BPN && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
     d_message_n "setting old_dir = $(pwd)" 2
     export old_dir=$(pwd) && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
     d_message_n "setting default starting_step = 0" 2
@@ -160,8 +129,6 @@ initialize_variables() {
     export stopping_step=$(( ${#command_sequence[@]} - 1 )) && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
     d_message_n "setting default mkenvstatusfile = /root/bin/mkcrossbuildenv_status" 2
     export mkenvstatusfile="/root/bin/mkcrossbuildenv_status" && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
-    d_message_n "setting PN = $(basename $0)" 2
-    PN=$(basename $0) && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
     d_message_n "setting default INTERACTIVE true" 2
     export INTERACTIVE=$TRUE && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
     d_message_n "setting default VERBOSE true" 2
@@ -180,6 +147,8 @@ initialize_variables() {
 emerge-host-world() {
     [[ $INTERACTIVE ]] && emerge_options="-uavDNgk" || emerge_options="-uvDNgk"
     emerge ${emerge_options} @world --keep-going
+    result=$?
+    return $result
 }
 
 emerge-cross-rust-std() {
@@ -208,7 +177,6 @@ get-max-profile-number() {
 
 profile_number_prompt()  {
     ps=$1; echo; echo; CUU; SCP;
-#    get-max-profile-number bcm2709-rpi-2-b >/dev/null ; max_num=$?
     get-max-profile-number ${BOARD} >/dev/null ; max_num=$?
     message_n "$ps [0-${max_num}]: " && read profile_number;
     isnumber $profile_number ; result=$?
@@ -351,29 +319,29 @@ wget-stage3() {
 #-----[ main script ]---------------------------------------------
 checkroot
 separator ${PN} $(hostname)
-  if [ $# -eq 1 ] ; then
-    # option s (status) is the only one that can appear alone on the command line
-    if [[ "$1" != "-"*"s"* ]] && [[ "$1" != "--status" ]] ; then
-      E_message "invalid argument [${arglist}]"
-      usage
-    fi
-  fi
+# option s (status) is the only one that can appear alone on the command line
+if [ $# -eq 1 ] ; then if [[ "$1" != "-"*"s"* ]] && [[ "$1" != "--status" ]] ; then
+    E_message "invalid argument [${arglist}]"
+    usage
+fi; fi
 
-initialize_variables     # set defaults
+validate_status_file ${mkenvstatusfile} || die "Failed to validate_status_file"
+
+# initialize variables and set default values
+initialize_variables || die "Failed to initialize_variables"
 
 d_echo "cmdline: $*" 5
 d_echo "processing cmdline args: $@" 5
 
-msg="processing cmdline ..."
-[ $verbosity -lt 2 ] && message_n "${msg}" || message "${msg}"
-process_cmdline "${@}"   # override defaults, sets BOARD or TARGET
-right_status $?
+# over-ride configuration with commandline input
+separator ${PN} "(process_cmdline)"
+process_cmdline ${@} || die "Failed to process_cmdline"
 
-sanity_check && \
-validate_target ${BOARD} && \
-validate_status_file ${mkenvstatusfile} && \
-display_configuration && \
-run_sequence ${mkenvstatusfile}
+validate_target ${BOARD} || die "Failed to validate_target [${BOARD}]"
+display_configuration || die "Failed to display_configuration"
+
+sanity_check  || die "Failed sanity_check"
+run_sequence ${mkenvstatusfile} || die "Failed to run_sequence"
 
 echo
 cd $old_dir
diff --git a/dev-sbc/crossbuild-tools/cb-mktemplateimage b/dev-sbc/crossbuild-tools/cb-mktemplateimage
--- a/dev-sbc/crossbuild-tools/cb-mktemplateimage
+++ b/dev-sbc/crossbuild-tools/cb-mktemplateimage
@@ -5,38 +5,71 @@
 #
 
 source /usr/sbin/script_header_joetoo
+message_n "sourcing BUILD ..."
+source /etc/crossbuild-tools/BUILD ; right_status $?
+message_n "sourcing BPN ..."
+source /etc/crossbuild-tools/BPN ; right_status $?
+source /usr/sbin/script_header_joetoo_extended
+
 VERBOSE=$TRUE
 #verbosity=2
 verbosity=3
 
 PN=$(basename $0)
 
-imagefile=/etc/crossbuild-tools/admin_files/TEMPLATE_SBC_IMAGE_FILE.img
 
-# image and partition sizes
-image_size_mb=20480
-partition1_size_mb=512
-partition2_size_mb=$((image_size_mb - partition1_size_mb))
+#-----[ variables ]-----------------------------------------------------
 
-message_n "sourcing BUILD ..."
-source /etc/crossbuild-tools/BUILD ; right_status $?
+varlist="IMAGE_TYPE imagefile image_size_mb partition1_size_mb partition2_size_mb BREAK bool.VERBOSE verbosity"
+
+
+#-----[ functions ]-----------------------------------------------------
 
 message_n "sourcing cb-common-functions ..."
 source /usr/sbin/cb-common-functions ; right_status $?
 TARGET=""
 
-usage() {
-    message "${BRon}usage: ${BGon}${PN} <s|f>${Boff}"
-    echo -e "${BYon}    [sS]: sparse | [fF]: fixed size${Boff}"
+myusage() {
+    message "${BRon}usage: ${BGon}${PN} <BOARD>${Boff}"
+    source /etc/${BPN}/local.usage
     exit
 }
 
-display-config() {
-    message "IMAGE_TYPE ...........: ${IMAGE_TYPE}"
-    message "imagefile ............: ${imagefile}"
-    message "image_size_mb ........: ${image_size_mb}"
-    message "partition1_size_mb ...: ${partition1_size_mb}"
-    message "partition2_size_mb ...: ${partition2_size_mb}"
+initialize_variables() {
+    [ $verbosity -lt 2 ] && message_n "initializing ..." || message "initializing ..."
+    initialize_vars ${varlist}
+
+    # set default values
+    FLAGGED=$FALSE
+    d_message_n "sourcing BUILD ..." 2
+    source /etc/crossbuild-tools/BUILD && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    d_message_n "setting PN = $(basename $0)" 2
+    PN=$(basename $0) && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    d_message_n "sourcing BPN ..." 2
+    source /etc/crossbuild-tools/BPN && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+
+    d_message_n "setting default imagefile = /etc/crossbuild-tools/admin_files/TEMPLATE_SBC_IMAGE_FILE.img" 2
+    imagefile=/etc/crossbuild-tools/admin_files/TEMPLATE_SBC_IMAGE_FILE.img && \
+        d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    d_message_n "setting default image_size_mb = 20480" 2
+    image_size_mb=20480 && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    d_message_n "setting default partition1_size_mb = 512" 2
+    partition1_size_mb=512 && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    d_message_n "setting default partition2_size_mb = $((image_size_mb - partition1_size_mb))" 2
+    partition2_size_mb=$((image_size_mb - partition1_size_mb)) && \
+        d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    d_message_n "setting default VERBOSE true" 2
+    export VERBOSE=$TRUE && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    d_message_n "setting default verbosity = 3" 2
+    export verbosity=3 && d_right_status $? 2 || ( d_right_status $? 2 && FLAGGED=$TRUE )
+    if [[ $FLAGGED ]] ; then
+        E_message "failed clean exit; note red flags above"
+        return 1
+    else
+        message "initialization complete"
+        return 0
+    fi
+    return 0
 }
 
 prepare() {
@@ -55,6 +88,7 @@ prepare() {
         E_message "Note red flags above. Please clean up before continuing"
         exit 1
     fi
+    return 0
 }
 
 mksparseimagetemplate() {
@@ -124,16 +158,20 @@ mktemplate-common() {
 #-----[ main script ]---------------------------------------------
 checkroot
 separator ${PN} $(hostname)
-[ $# -ne 1 ] && usage
-IMAGE_TYPE=$1
+[ $# -ne 0 ] && myusage
 
-prepare
+# initialize variables and set default values
+initialize_variables || die "Failed to initialize_variables"
+prepare || die "failed prepare()"
+display_configuration || die "failed to display_configuration"
 
-display-config
-
+# previously written to take argument 1 to be assigned to IMAGE_TYPE, but
+# cb-setup is hard-coded using "cb-mktemplateimage s" -- so hard code it
+# here instead and avoid having to accomodate in common local.usage cli options
+IMAGE_TYPE="s"
 case ${IMAGE_TYPE:0:1} in
-    [sS] ) mksparseimagetemplate ;;
-    [fF] ) mkimagetemplate ;;
+    [sS] ) mksparseimagetemplate || die "failed to mksparseimagetemplate" ;;
+    [fF] ) mkimagetemplate || die "failed to mkimagetemplate" ;;
     * ) E_message "Invalid argument [ ${IMAGE_TYPE} ]" ; usage ;;
 esac
 
diff --git a/dev-sbc/crossbuild-tools/cb-setup b/dev-sbc/crossbuild-tools/cb-setup
--- a/dev-sbc/crossbuild-tools/cb-setup
+++ b/dev-sbc/crossbuild-tools/cb-setup
@@ -4,15 +4,19 @@
 # copy appropriate template files into crossbuild target filesystem
 #
 
+
 source /usr/sbin/script_header_joetoo
+message_n "sourcing BUILD ..."
+source /etc/crossbuild-tools/BUILD ; right_status $?
+message_n "sourcing BPN ..."
+source /etc/crossbuild-tools/BPN ; right_status $?
+source /usr/sbin/script_header_joetoo_extended
+
 VERBOSE=$TRUE
 #verbosity=2
 verbosity=3
 
 PN=$(basename $0)
-
-message_n "sourcing BUILD ..."
-source /etc/crossbuild-tools/BUILD ; right_status $?
 
 message_n "sourcing cb-common-functions ..."
 source /usr/sbin/cb-common-functions ; right_status $?
@@ -20,10 +24,10 @@ TARGET=""
 
 imagefile=/etc/crossbuild-tools/admin_files/TEMPLATE_SBC_IMAGE_FILE.img
 
-usage() {
+myusage() {
     message "${BRon}usage: ${BGon}${PN} <BOARD>${Boff}"
-    usage-common-message
-    exit 1
+    source /etc/${BPN}/local.usage
+    exit
 }
 
 setup-board-image() {
@@ -92,23 +96,24 @@ setup-board-image() {
         cp /etc/crossbuild-tools/admin_files/TEMPLATE_SBC_IMAGE_FILE.img /usr/${BOARD}.img && \
         right_status $? || ( right_status $? && exit 1 )
     fi
-
     # loopmount board image file on target directory
     # (moved to cb-mount, called by cb-mkenv)
+    return 0
 }
 
 #-----[ main script ]---------------------------------------------
 checkroot
 separator ${PN} $(hostname)
-[ $# -ne 1 ] && usage
+[ $# -ne 1 ] && myusage
 BOARD=$1
-validate_target ${BOARD}
+
+validate_target ${BOARD} || die "failed to validate_target [${BOARD}]"
 
 old_dir="$(pwd)"
 cd /usr/
 message "now working in parent of crossbuild target directory: [${Mon}$(pwd)${Boff}]"
 
-setup-board-image
+setup-board-image || die "failed to setup-board-image"
 
 echo
 cd $old_dir
diff --git a/dev-sbc/crossbuild-tools/cb-umount b/dev-sbc/crossbuild-tools/cb-umount
--- a/dev-sbc/crossbuild-tools/cb-umount
+++ b/dev-sbc/crossbuild-tools/cb-umount
@@ -5,22 +5,25 @@
 #
 
 source /usr/sbin/script_header_joetoo
+message_n "sourcing BUILD ..."
+source /etc/crossbuild-tools/BUILD ; right_status $?
+message_n "sourcing BPN ..."
+source /etc/crossbuild-tools/BPN ; right_status $?
+source /usr/sbin/script_header_joetoo_extended
+
 VERBOSE=$TRUE
 #verbosity=2
 verbosity=3
 
 PN=$(basename $0)
 
-message_n "sourcing BUILD ..."
-source /etc/crossbuild-tools/BUILD ; right_status $?
-
 message_n "sourcing cb-common-functions ..."
 source /usr/sbin/cb-common-functions ; right_status $?
 TARGET=""
 
-usage() {
+myusage() {
     message "${BRon}usage: ${BGon}${PN} <BOARD>${Boff}"
-    usage-common-message
+    source /etc/${BPN}/local.usage
     exit 1
 }
 
@@ -31,8 +34,7 @@ umount-board() {
         E_message "${BYon}the following devices are mounted on /usr/${TARGET} --${Boff}"
         mount | grep "on /usr/${TARGET}"
         message_n "running umount -R /usr/${TARGET} ..."
-        umount -R /usr/${TARGET}
-        right_status $?
+        umount -R /usr/${TARGET} && right_status $? || die "failed to umount -R /usr/${TARGET}"
     else
         message "nothing is mounted on /usr/${TARGET} ; continuing"
     fi
@@ -41,19 +43,19 @@ umount-board() {
     loop_dev=$(losetup -a | grep "/usr/${BOARD}.img" | cut -d':' -f1)
     if [ -n "${loop_dev}" ] ; then
         message_n "detaching ${loop_dev} ..."
-        losetup -d ${loop_dev}
-        right_status $?
+        losetup -d ${loop_dev} && right_status $? || die "failed to losetup -d ${loop_dev}"
     else
         message "no loop device is attached to /usr/${BOARD}.img ; continuing"
     fi
+    return 0
 }
 
 #-----[ main script ]---------------------------------------------
 checkroot
 separator "(${BOARD})" "${PN}"
-[ $# -ne 1 ] && usage
+[ $# -ne 1 ] && myusage
 BOARD=$1
-validate_target ${BOARD}
+validate_target ${BOARD} || die "Failed to validate_target [${BOARD}]"
 
 old_dir="$(pwd)"
 cd /usr/
