typo

diff --git a/dev-sbc/crossbuild-tools/cb-flash-device b/dev-sbc/crossbuild-tools/cb-flash-device
--- a/dev-sbc/crossbuild-tools/cb-flash-device
+++ b/dev-sbc/crossbuild-tools/cb-flash-device
@@ -209,13 +209,13 @@ prep-newroot() {
         echo -e " ${BGon}yes${Boff}" ; right_status $TRUE
     fi
     # whether already mounted or just mounted, we can now go to newroot_mountpoint
-    #   and if there is a mount-the-rest script, run it ( flash-device() )
+    #   and if there is a mount-the-rest script, run it ( mount-newroot() )
     return 0
 }
 
-flash-device() {
-    separator "(flash-device)" ${PN}
-    d_message "in flash-device" 5
+mount-newroot() {
+    separator "(mount-newroot)" ${PN}
+    d_message "in mount-newroot" 5
     old_dir=$(pwd)
     message_n "moving from $(pwd) to ${newroot_mountpoint} ..."
     cd ${newroot_mountpoint} && right_status $? || die "failed to cd ${newroot_mountpoint}"
@@ -225,10 +225,16 @@ flash-device() {
         die "failed to find ./ -iname 'mount-the-rest*' -type f -executable"
 
     # DANGER Will Robinson - check this first
-    exec ${mounttherestscript}
+#    exec ${mounttherestscript}
+    source ${mounttherestscript}
+    return 0
+}
 
+copy-content() {
+    separator "(copy-content)" ${PN}
+    d_message "in copy-content" 4
     # ok - now copy content
-    msg= "about to run cp -av /usr/${TARGET}/* ${newroot_mountpoint}/ \n"
+    msg="about to run cp -av /usr/${TARGET}/* ${newroot_mountpoint}/ \n"
     msg+="are you sure you want to continue"
     response="" ; new_prompt "${msg}"
     case ${response:0:1} in
@@ -276,7 +282,8 @@ display_configuration
 echo
 format_warning || die "failed format warning somehow, oddly"
 
-flash-device
+mount-newroot || die "failed to mount-newroot"
+copy-content || die "failed to copy-content"
 
 separator "(wrapping up)" ${PN}
 message_n "moving from $(pwd) to ${old_dir} ..."
