forgot to hit ctrl-s in vs-code last time
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-sbc/crossbuild-tools/cb-layout-device b/dev-sbc/crossbuild-tools/cb-layout-device
--- a/dev-sbc/crossbuild-tools/cb-layout-device
+++ b/dev-sbc/crossbuild-tools/cb-layout-device
@@ -887,10 +887,42 @@ layout_cryptsetup_lvm() {
     separator "${PN}" "(${FUNCNAME[0]})"
     d_message "in ${FUNCNAME[0]}" 4
 
-    # luks_partition_device and edev were set in luks_lvm_config (and shown in display_configuration)
-
-    # dd random data to the luks "part" name
-    myCmd="dd if=/dev/urandom of=${luks_partition_device} bs=4M status=progress"
+    # luks_partition_device and edev were set in luks_lvm_config
+    #   (and shown in display_configuration)
+    # use dd to write random data to the luks "part" name
+    #   oflag=direct writes direct to disk (dont need sync after)
+    # note that dd will exit with error 1 (disk full) if it does not know how much to write,
+    #   so calculate that using blockdev commands (sys-apps/util-linux) --
+    #     raw size in bytes
+    total_bytes=$(blockdev --getsize64 "${luks_partition_device}")
+    #     physical sector size (usually 4096 or 512)
+    sector_size=$(blockdev --getpbsz "${luks_partition_device}")
+    #     calculate the largest multiple of sector_size that is -le 4MB
+    #       and perfectly divides total_bytes
+    preferred_bs_bytes=$((4 * 1024 * 1024))
+    #       start close to the preferred size but use a multiple of sector_size
+    #         (integer division rounds)
+    bs_bytes=$(( (preferred_bs_bytes / sector_size) * sector_size ))
+    #       work downward until bs_bytes is an even multiple
+    while [ $bs_bytes -gt $sector_size ]; do
+        if [ $((total_bytes % bs_bytes)) -eq 0 ]; then break; fi
+        bs_bytes=$((bs_bytes - sector_size))
+    done
+    # final bs_bytes SHOULD now a perfect divisor of total_bytes and multiple of sector_size
+    #   however in rare circumstances (virtual disk, etc.), the disk might not be perfectly
+    #   build with integer number of sectors... so detect that
+    if [ $((total_bytes % bs_bytes)) -eq 0 ]; then
+        count=$((total_bytes / bs_bytes))
+        EXPECT_DISK_FULL=$FALSE
+    else
+        W_message "Warning: Partition size is not a multiple of sector size. Expecting 'No space left'"
+        # round up the number of sector-sized blocks to write
+        count=$(( (total_bytes + bs_bytes - 1) / bs_bytes ))
+        EXPECT_DISK_FULL=$TRUE
+    fi
+    # build the dd command
+    myCmd="dd if=/dev/urandom of=${luks_partition_device}"
+    myCmd+=" bs=${bs_bytes} count=${count} status=progress oflag=direct"
     msg="about to run [${myCmd}]\n"
     msg+="(you can safely skip this step if you have done it before)\n"
     msg+="(y: yes; s: skip; n: exit program)"
@@ -903,8 +935,22 @@ layout_cryptsetup_lvm() {
     case ${response:0:1} in
         [yY] )
             maybe_format_warning || die "failed format_warning somehow"
-            # ensure disk-write is complete before reporting
-            ${myCmd} && sync || die "failed to execute ${myCmd}"
+            # exit codes from the dd cmd above are 0: success, 1: general error (disk full, I/O error, permission denied)
+            #   or over 100 for shell errors (e.g. 126 dd not executable, or 127 dd not found ..)
+            #   and exit code 130 means the user hit CTRL-C to quit
+
+            ${myCmd}
+            rc=$?
+            case $rc in
+                0   ) : ;;  #success
+                1   )
+                    if [ ! $EXPECT_DISK_FULL ]; then die "general failure; dd exit code [$rc]"; fi ;;
+                126 ) die "dd not executable; dd exit code [$rc]" ;;
+                127 ) die "dd not found; dd exit code [$rc]" ;;
+                130 ) die "process interrupted by user; dd exit code [$rc]" ;;
+                137 ) die "killed (OOM or kill -9); dd exit code [$rc]" ;;
+                *   ) die "unrecognized failure; dd exit code [$rc]" ;;
+            esac
             ;;
         [nN] ) die "aborting, as instructed" ;;
         [sS] ) message "skipping, as instructed" ;;
@@ -1292,7 +1338,7 @@ arglist="$@"
 [ $# -eq 1 ] && [[ "$1" != "-"*"s"* ]] && [[ "$1" != "--status" ]] && E_message "invalid argument(s) [$arglist]" && usage
 [ $# -lt 4 ] && E_message "invalid argument(s) [$arglist]" && usage
 
-# basic common approach - 
+# basic common approach -
 # initialize variables (local function)
 # validate_status_file  (script_header_joetoo_extended)
 # process_cmdline (script_header_joetoo_extended)
