final tweaks on cb-mkenv and cb-mkimp (added cb-umount and stockpile.  also initial mods to cb-layout-device and cb-flash-device, but the latter still need much more work to finalize cb-mkdev

diff --git a/dev-sbc/crossbuild-tools/cb-mkdev b/dev-sbc/crossbuild-tools/cb-mkdev
--- a/dev-sbc/crossbuild-tools/cb-mkdev
+++ b/dev-sbc/crossbuild-tools/cb-mkdev
@@ -36,6 +36,7 @@ varlist+=" BREAK bool.VERBOSE verbosity old_dir"
 #    basic finalize-chroot script provided for cb-mkenv)
 
 command_sequence=(
+'cb-mount ${BOARD}'
 'validate-image'
 'eselect-layout'
 'cb-layout-device ${OUTPUTDEVICE}'
@@ -44,6 +45,7 @@ command_sequence=(
 )
 
 msg1_sequence=(
+'mount BOARD image on TARGET'
 'validate source (crossbuilt BOARD and TARGET)'
 'eselect cb-layout-device.conf'
 'layout OUTPUTDEVICE'
@@ -52,6 +54,7 @@ msg1_sequence=(
 )
 
 msg2_sequence=(
+'mounting BOARD image on TARGET'
 'validating source (crossbuilt BOARD and TARGET)'
 'selecting cb-layout-device.conf'
 'laying out OUTPUTDEVICE'
@@ -192,12 +195,21 @@ eselect-layout() {
     # or suggest one based on board image type (straight SD card, luks-encrypted NVMe stick, etc)
     # export layout variables (partition1_size_mb, DEV_HOSTNAME, root_vg, crypt_keydev, etc.)
     message "setting default layout ..."
-    eselect cb-layout-device set 1
     eselect cb-layout-device list | grep '\*'
+    message_n "getting current layout number"
+    layout_number=$(eselect cb-layout-device list | grep '\*' | cut -d'[' -f2 | cut -d ']' -f1)
+    result=$?
+    if [ $result -eq 0 ] ; then
+        echo -en " (${layout_number})"
+    else
+        echo -en " (${BRon}failed${Boff})"
+    fi
+    right_status $result
+
     d_message "INTERACTIVE: $(status_color $INTERACTIVE)$(TrueFalse $INTERACTIVE)${Boff}" 3
     if [[ $INTERACTIVE ]] ; then
         msg="${BYon}Would you like to select a different layout?\n"
-        msg+="${BWon}    y: yes select new | s: no; continue with default | n: no; exit${Boff}"
+        msg+="${BWon}  ( y: yes select new | s: no; continue with default | n: no; exit )${Boff}"
         response="" ; new_prompt "${msg}"
     else
         response="s"  # keep default profile and continue
diff --git a/dev-sbc/crossbuild-tools/cb-mkimg b/dev-sbc/crossbuild-tools/cb-mkimg
--- a/dev-sbc/crossbuild-tools/cb-mkimg
+++ b/dev-sbc/crossbuild-tools/cb-mkimg
@@ -6,13 +6,13 @@
 
     # pre-requisite: cb-mkenv has been fully completed, with possible exception of its chroot step
     # this script expects --
-    #    a working image file is set up and mounted on the appropriate target directory (cb-setup)
-    #    the image file has stage3 already extracted, and a working crossdev crosscompile (cb-mkenv)
-    #    the image has been populated with joetoo cross-build configs (cb-populate-target)
-    #    ${TARGET}-emerge has been run for both @system and @world sets (cb-mkenv)
-    #    the image has a working qemu, for qemu-chroot (cb-buildtarget-qemu)
-    # It is not necessary for the cb-mkenv's chroot step and subsequent native chroot-emerge @world
-    # to have been done.  We'll re-do that here, after establishing actual repositories for the image
+    #    NO image file(s) are mounted
+    #    a completed ${BOARD}.img crossbuild environment image file is available
+    #        the image file has stage3 already extracted, and a working crossdev crosscompile (cb-mkenv)
+    #        the image has been populated with joetoo cross-build configs (cb-populate-target)
+    #        ${TARGET}-emerge has been run for both @system and @world sets (cb-mkenv)
+    #        the image has a working qemu, for qemu-chroot (cb-buildtarget-qemu)
+    #        Note: completed environment does not have its own repositories
 
 # Note: as of build 0.1.4, these additional functions were moved to cb-common-functions:
 #    sanity_check() display_configuration(), process_cmdline(),
@@ -45,8 +45,8 @@ PN=$(basename $0)
 response=""
 
 varlist="PN BPN BUILD BOARD TARGET TARGET_ARCH QEMU_ARCH"
-varlist+=" profile_number"
-varlist+=" starting_step stopping_step mkimgstatusfile"
+varlist+=" LLVM_TARGET default_profile"
+varlist+=" BREAK starting_step stopping_step mkimgstatusfile"
 varlist+=" bool.RESUME bool.INTERACTIVE"
 varlist+=" BREAK bool.VERBOSE verbosity old_dir"
 
@@ -55,21 +55,32 @@ varlist+=" BREAK bool.VERBOSE verbosity old_dir"
 #    basic finalize-chroot script provided for cb-mkenv)
 
 command_sequence=(
+'cb-mount ${BOARD}'
 'validate-image'
 'cb-populate-image ${BOARD}'
 'cb-chroot-target-image ${BOARD}'
-)
+'save-hostname'
+'cb-umount ${BOARD}'
+'stockpile-img')
 
 msg1_sequence=(
+'mount BOARD image on TARGET'
 'validate image construction and assembly'
 'repopulate image additional content'
 'cb-chroot into target image ${BOARD}'
+'save hostname for use in stockpile image name'
+'un-mount BOARD image'
+'add image to deployable image stockpile'
 )
 
 msg2_sequence=(
+'mounting BOARD image on TARGET'
 'validating image construction and assembly'
 'repopulating image additional content'
 'cb-chrooting into target image ${BOARD}'
+'saving hostname for use in stockpile image name'
+'un-mounting BOARD image'
+'adding image to deployable image stockpile'
 )
 
 #-----[ functions ]-----------------------------------------------------
@@ -172,6 +183,50 @@ validate-image() {
         message "by the finalize-chroot-for-image script upon first login with"
         message "cb-chroot-target-image, which is the last stop in workflow of this script (cb-mkimg)"
     fi
+    return 0
+}
+
+save-hostname() {
+    # (must be done after finalize-chroot-for-image but before cb-umount)
+    # save the hostame before un-mounting the image
+    # we'll need it to name the stockpiled image file
+    message_n "reading hostname"
+    read HN < /usr/${TARGET}/etc/hostname && \
+        echo -en " (${HN})" || die "failed to read hostname"
+    right_status $TRUE
+    export my_hostname="${HN}"
+}
+
+stockpile-img() {
+    # (should be run after finalize-chroot-for-image and cb-umount have both completed)
+    # copy the completed ${BOARD}.img file so it can be used as a deployable
+    # start point for development of the scpecific system for which it was created
+    # receive hostname as $1
+
+    stockpile=/home/joe/sbc-stockpile
+
+    # use my_hostname to create output filename
+    message_n "assigning stockpile output filename"
+    outfile="${BOARD}_${my_hostname}.img" && \
+        echo -en " (${BGon}ok${Boff})" || die "failed to assign stockpile filename"
+    right_status $TRUE
+
+    # create stockpile directory if it doesn't exist
+    message_n "examining stockpile"
+    if [ ! -d ${stockpile} ] ; then
+        echo -en " (${BRon}not found${Boff})"
+        mkdir -p ${stockpile} && \
+            echo -en " (${BGon}created${Boff})" || die "failed to create stockpile"
+    else
+        echo -en " (${BGon}found${Boff})"
+    fi
+    right_status $TRUE
+
+    # copy /usr/${BOARD}.img to ${stockpile}/${BOARD}.env
+    message_n "stockpiling as ${outfile}"
+    cp /usr/${BOARD}.img ${stockpile%/}/${outfile} && \
+        echo -en " (${BGon}copied${Boff})" || die "failed copy to stockpile"
+    right_status $TRUE
     return 0
 }
 
diff --git a/dev-sbc/crossbuild-tools/mkimg-files/common/usr/sbin/finalize-chroot-for-image b/dev-sbc/crossbuild-tools/mkimg-files/common/usr/sbin/finalize-chroot-for-image
--- a/dev-sbc/crossbuild-tools/mkimg-files/common/usr/sbin/finalize-chroot-for-image
+++ b/dev-sbc/crossbuild-tools/mkimg-files/common/usr/sbin/finalize-chroot-for-image
@@ -46,9 +46,9 @@ varlist+=" BREAK lv.chroot_emerge"
 command_sequence=(
 'validate-prerequisites'
 'check-reload-config'
+'set-hostname'
 'set-password root'
 'set-timezone'
-'set-hostname'
 'remove-kernelsources-mountpoint'
 'sync-repo joetoo'
 'add-user'
@@ -71,9 +71,9 @@ command_sequence=(
 msg1_sequence=(
 'validate prerequisites'
 'check and reload config'
+'set hostname'
 'set root password'
 'set timezone'
-'set hostname'
 'remove kernel sources mountpoint'
 'sync repo joetoo'
 'add user'
@@ -91,9 +91,9 @@ msg1_sequence=(
 msg2_sequence=(
 'validating prerequisites'
 'checking and reloading config'
+'setting hostname'
 'setting root password'
 'setting timezone'
-'setting hostname'
 'removing kernel sources mountpoint'
 'syncing repo joetoo'
 'adding user'
@@ -421,8 +421,15 @@ add-user() {
     fi
 
     # set password for this user
-    set-password ${candidate} && ( right_status $? && return 0 ) || \
+    set-password ${candidate} && right_status $? || \
         ( right_status $? && FLAGGED=$TRUE && return 1 )
+
+    # assign ownership of all content in the users home directory to the user
+    message_n "recursively assigning ownership of /home/${candidate} to ${candidate}"
+    chown -R "${candidate}":"${candidate}" "/home/${candidate}" && \
+        echo -en " (${BGon}success${Boff})" || die "failed to assign ownership for ${candidate}"
+    right_status $TRUE
+    return 0
 }
 
 fix-inittab() {
