update cb-buildtarget-qemu, cb-mkenv to refine cross-rust preparation, and cb-common-functions to update for textual default profile selection by name rather than profile numbers which change when (e.g. profile 17.1) profiles are removed from or added to the portage tree

diff --git a/dev-sbc/crossbuild-tools/cb-mkenv b/dev-sbc/crossbuild-tools/cb-mkenv
--- a/dev-sbc/crossbuild-tools/cb-mkenv
+++ b/dev-sbc/crossbuild-tools/cb-mkenv
@@ -194,14 +194,25 @@ prepare-cross-rust() {
     # change this if we have to modify the system
     export RUST_LLVM_CHANGE_FLAG=$FALSE
 
-    # verify that USE flag "dev-lang/rust rust-src" is in CHOST's package.use
     host_package_use="/etc/portage/package.use/joetoo"
+    # verify that USE flag "dev-lang/rust rust-src" is in CHOST's package.use
     message_n "looking for \"dev-lang/rust rust-src\" in ${host_package_use}"
     if grep -qF -- "dev-lang/rust rust-src" "${host_package_use}" ; then
         echo -en " (${BGon}found${Boff}))"
     else
         echo -en " (${BRon}not found${Boff}))"
         echo -e "\ndev-lang/rust rust-src" >> "${host_package_use}" || die "failed to append rust-src use flag"
+        export RUST_LLVM_CHANGE_FLAG=$TRUE
+    fi
+    right_status $TRUE
+
+    # verify that USE flag "dev-lang/rust-bin rust-src" is in CHOST's package.use
+    message_n "looking for \"dev-lang/rust-bin rust-src\" in ${host_package_use}"
+    if grep -qF -- "dev-lang/rust-bin rust-src" "${host_package_use}" ; then
+        echo -en " (${BGon}found${Boff}))"
+    else
+        echo -en " (${BRon}not found${Boff}))"
+        echo -e "\ndev-lang/rust-bin rust-src" >> "${host_package_use}" || die "failed to append rust-src use flag"
         export RUST_LLVM_CHANGE_FLAG=$TRUE
     fi
     right_status $TRUE
@@ -243,7 +254,51 @@ prepare-cross-rust() {
     fi
     right_status $TRUE
 
-    # now validate or create /etc/portage/env/dev-lang/rust
+    # now set up cross-rust in CHOSTs crossdev repo
+
+    VALID_LINK=$FALSE
+    message "creating rust-std link in crossdev repo (to CHOSTs rust-std ebuilds) ..."
+    old_dir="$(pwd)"
+    cd /var/db/repos/crossdev/cross-${TARGET} && \
+    message "now working in crossdev repo: [${Mon}$(pwd)${Boff}]"
+    message_n "looking for link"
+    if [ -L rust-std ] ; then
+        echo -en " (found, "
+        # link forund - right target?
+        target_path=$(readlink -f rust-std)
+#        olv_verbosity=$verbosity ; verbosity=5
+#        d_message "target_path: [${target_path}]" 4
+#        verbosity=$old_verbosity
+        if [[ "${target_path}" == "/var/db/repos/gentoo/sys-devel/rust-std" ]] ; then
+            # link points to correct target
+            echo -en "${BGon}valid${Boff})"
+            VALID_LINK=$TRUE
+        else
+            # link does not point to correct target -- remove it
+            echo -en "${BRon}invalid${Boff})"
+            rm rust-std && echo -en "(removed)" || die "failed to remove invalid rust-std link"
+        fi
+    else
+        echo -en " (not found)"
+        # no link found
+    fi
+    if [ ! $VALID_LINK ] ; then
+        # valid link does not yet exist or invalid one was removed -- create it
+        ln -s /var/db/repos/gentoo/sys-devel/rust-std && \
+            echo -en "(${BGon}created${Boff})" || die "failed to create link for rust-std"
+    fi
+    # if we got here (didn't die above) close action as OK
+    right_status $TRUE
+    echo
+    cd $old_dir
+    message "now working in previous directory: [${Mon}$(pwd)${Boff}]"
+
+    # now unmask rust-std in CHOSTs package.accept_keywords
+    message_n "unmasking rust-std in CHOSTs package.accept_keywords ..."
+    echo "cross-${TARGET}/rust-std **" >> /etc/portage/package.accept_keywords/cross-target-rust-std && \
+        right_status $? || die "failed to unmasking rust-std in CHOSTs package.accept_keywords"
+
+    # now validate or create /etc/portage/env/dev-lang/rust per-package env setting
     # (should be installed by this package's ebuild)
     message_n "examining /etc/portage/env/dev-lang/rust"
     if [ -e /etc/portage/env/dev-lang/rust ] ; then
