add step in cb-mkenv to configure make.conf for crossbuilding; also update cb-dashboard
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-sbc/crossbuild-tools/cb-mkenv b/dev-sbc/crossbuild-tools/cb-mkenv
--- a/dev-sbc/crossbuild-tools/cb-mkenv
+++ b/dev-sbc/crossbuild-tools/cb-mkenv
@@ -56,6 +56,7 @@ command_sequence=(
 'quickpkg-toolchain'
 'symlink-repos'
 'TARGET-emerge-joetoo-platform-meta'
+'configure-make-conf-for-crossbuilding'
 'run-dispatch-conf'
 'edit-make-conf'
 'edit-package-use-platform'
@@ -68,7 +69,7 @@ command_sequence=(
 'prepare-cross-rust'
 'rebuild-rust-and-llvm'
 'emerge-cross-rust-std'
-'switch-to-make-conf-chroot'
+'configure-make-conf-for-chroot'
 'edit-make-conf'
 'cb-chroot-target ${BOARD}'
 'cb-umount ${BOARD}'
@@ -89,6 +90,7 @@ msg1_sequence=(
 'run quickpkg-toolchain'
 'symlink repositories'
 '${TARGET}-emerge platform-specific configs'
+'configure make.conf for crossbuilding'
 'run dispatch-conf'
 'edit make.conf'
 'edit package.use/joetoo_platform'
@@ -101,7 +103,7 @@ msg1_sequence=(
 'prepare to build cross-${TARGET}/rust-std'
 'rebuild rust and llvm with new configuration if changed'
 'emerge cross-${TARGET}/rust-std'
-'switch to chroot version of make.conf'
+'configure make.conf for chroot'
 'edit make.conf'
 'chroot into new ${TARGET} environment'
 'un-mount BOARD image'
@@ -122,6 +124,7 @@ msg2_sequence=(
 'running quickpkg-toolchain'
 'symlinking repositories'
 '${TARGET}-emerging platform-specific configs'
+'configuring make.conf for crossbuilding'
 'running dispatch-conf'
 'editing make.conf'
 'editing package.use/joetoo_platform'
@@ -134,7 +137,7 @@ msg2_sequence=(
 'preparing to build cross-${TARGET}/rust-std'
 'rebuilding rust and llvm with new configuration if changed'
 'emerging cross-${TARGET}/rust-std'
-'switching to chroot version of make.conf'
+'configuring make.conf for chroot'
 'editing make.conf'
 'chrooting into new ${TARGET} environment'
 'un-mounting BOARD image'
@@ -220,13 +223,33 @@ emerge-host-world() {
     return $result
 }
 
-switch-to-make-conf-chroot() {
+configure-make-conf-for-crossbuilding() {
+    # remove any pending version of make.conf and accept delivery of chroot and crossbuild versions
+    message_n "accepting pending ._cfgxxxx_make.conf installs ..."
+    for x in /etc/portage/._cfg*make.conf; do rm $x || die "failed to rm $x"; done
+    for x in /etc/portage/._cfg*make.conf.crossbuild; do 
+        mv $x make.conf.crossbuild || die "failed to mv $x make.conf.crossbuild"
+    done
+    for x in /etc/portage/._cfg*make.conf.chroot; do
+        mv $x make.conf.chroot || die "failed to mv $x make.conf.chroot"
+    done
+    right_status $TRUE
+    # change to the chroot version of make.conf installed by joetoo-platform-meta
+    message_n "configuring make.conf for crossbuilding ..."
+    newfile="/usr/${TARGET}/etc/portage/make.conf.crossbuild"
+    oldfile="/usr/${TARGET}/etc/portage/make.conf"
+    cp "${newfile}" "${oldfile}" || die "failed to cp ${newfile} ${oldfile}"
+    right_status $TRUE
+    return 0
+}
+
+configure-make-conf-for-chroot() {
     # change to the chroot version of make.conf installed by joetoo-platform-meta
     newfile="/usr/${TARGET}/etc/portage/make.conf.chroot"
     oldfile="/usr/${TARGET}/etc/portage/make.conf"
-    message "about to overwrite ${oldfile} with ${newfile}"
-    confirm_continue_or_exit
+    message_n "configuring make.conf for chroot ..."
     cp "${newfile}" "${oldfile}" || die "failed to cp ${newfile} ${oldfile}"
+    right_status $TRUE
     return 0
 }
 
