trying to fix cross-rust as prerequisite for cb-mkupd
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-sbc/crossbuild-tools/cb-mkupd b/dev-sbc/crossbuild-tools/cb-mkupd
--- a/dev-sbc/crossbuild-tools/cb-mkupd
+++ b/dev-sbc/crossbuild-tools/cb-mkupd
@@ -246,7 +246,7 @@ validate_prerequisites() {
     separator "${PN}" "(${FUNCNAME[o]})"
 
     # Verify that the STOCKPILE UPDATEIMAGE exists
-    # do this first so we can assign BOARD and validate_targer
+    # do this first so we can assign BOARD and run validate_target to assign TARGET
     message "verifying <UPDATEIMAGE> ..."
     if [ -f "${STOCKPILE%/}/${UPDATEIMAGE}" ] ; then
         message_n "deriving BOARD"
@@ -318,10 +318,22 @@ validate_prerequisites() {
             echo -e -n " (${BRon}not found${Boff})"
             right_status 1
             E_message "TARGET sub-repo will need to be re-generated (Ok to continue)"
+            E_message "Note: cross-rust will not work until prepare-cross-rust() runs"
         else
             echo -e -n " (${BGon}found${Boff})"
             right_status $TRUE
             message "TARGET sub-repo exists and will be updated (Ok to continue)"
+            # now verify that the rust-std symlink is present in the crossdev repository for TARGET
+            message_n "looking for /var/db/repos/crossdev/cross-${TARGET}/rust-std"
+            if [ ! -L /var/db/repos/crossdev/cross-${TARGET}/rust-std ] ; then
+                echo -e -n " (${BRon}not found${Boff})"
+                right_status 1
+                E_message "running prepare-cross-rust()"
+                prepare-cross-rust || die "failed to prepare-cross-rust"
+            else
+                echo -e -n " (${BGon}found${Boff})"
+                right_status $TRUE
+            fi  # rust-std symlink existence
         fi # sub-repo existence
     fi  # repo existence
 
