bugfix setting permissions on finalize chroot scripts by cb-populate- scripts
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-sbc/crossbuild-tools/cb-populate-img b/dev-sbc/crossbuild-tools/cb-populate-img
--- a/dev-sbc/crossbuild-tools/cb-populate-img
+++ b/dev-sbc/crossbuild-tools/cb-populate-img
@@ -66,11 +66,11 @@ install_files_from_source "${CUSTOM_SOURCE_DIR%/}/" || \
 
 # make scripts executable in chroot (joetoo-meta should have deployed them with emerge-world)
 DESTINATION="/usr/${TARGET}/usr/sbin"
-message_n "setting permissions on scripts in ${DESTINATION} ..."
-chmod +x ${DESTINATION}/script_header_joetoo* && \
-chmod +x ${DESTINATION}/finalize-chroot-img && \
-chmod +x ${DESTINATION}/install_my_local_ca_certificates && \
-right_status $? || ( right_status $? && exit 1 )
+for x in "script_header_joetoo*" "finalize-chroot*" "install_my_local_ca_certificates"; do
+    message_n "setting permissions on ${DESTINATION}/$x ..."
+    eval "chmod +x ${DESTINATION}/$x" || die "failed to chmod +x ${DESTINATION}/$x"
+    right_status $TRUE
+done
 
 echo
 cd $old_dir
diff --git a/dev-sbc/crossbuild-tools/cb-populate-upd b/dev-sbc/crossbuild-tools/cb-populate-upd
--- a/dev-sbc/crossbuild-tools/cb-populate-upd
+++ b/dev-sbc/crossbuild-tools/cb-populate-upd
@@ -66,25 +66,11 @@ install_files_from_source "${CUSTOM_SOURCE_DIR%/}/" || \
 
 # make scripts executable in chroot (joetoo-meta should have deployed them with emerge-world)
 DESTINATION="/usr/${TARGET}/usr/sbin"
-message "setting permissions on files in ${DESTINATION}"
-message_n "script_headers ..."
-chmod +x ${DESTINATION}/script_header_joetoo* >/dev/null 2>&1
-case $? in
-    0 ) right_status $TRUE ;;
-    * ) right_status 1 ;;
-esac
-message_n "finalize-chroot-upd ..."
-chmod +x ${DESTINATION}/finalize-chroot-upd >/dev/null 2>&1
-case $? in
-    0 ) right_status $TRUE ;;
-    * ) right_status 1 ;;
-esac
-message_n "install_my_local_ca_certificates ..."
-chmod +x ${DESTINATION}/install_my_local_ca_certificates >/dev/null 2>&1
-case $? in
-    0 ) right_status $TRUE ;;
-    * ) right_status 1 ;;
-esac
+for x in "script_header_joetoo*" "finalize-chroot*" "install_my_local_ca_certificates"; do
+    message_n "setting permissions on ${DESTINATION}/$x ..."
+    eval "chmod +x ${DESTINATION}/$x" || die "failed to chmod +x ${DESTINATION}/$x"
+    right_status $TRUE
+done
 
 echo
 cd $old_dir
