standardize setting/resetting of verbosity
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-sbc/crossbuild-tools/cb-setup b/dev-sbc/crossbuild-tools/cb-setup
--- a/dev-sbc/crossbuild-tools/cb-setup
+++ b/dev-sbc/crossbuild-tools/cb-setup
@@ -4,7 +4,6 @@
 # copy appropriate template files into crossbuild target filesystem
 #
 
-
 source /usr/sbin/script_header_joetoo
 message_n "sourcing BUILD ..."
 source /etc/crossbuild-tools/BUILD ; right_status $?
@@ -14,7 +13,8 @@ source /usr/sbin/script_header_joetoo_extended
 
 VERBOSE=$TRUE
 #verbosity=2
-verbosity=3
+# set default verbosity only if it is not already set
+[ -z $verbosity ] && verbosity=3
 
 PN=$(basename $0)
 
@@ -22,7 +22,7 @@ message_n "sourcing cb-common-functions ..."
 source /usr/sbin/cb-common-functions ; right_status $?
 TARGET=""
 
-imagefile=/etc/crossbuild-tools/admin_files/TEMPLATE_SBC_IMAGE_FILE.img
+imagefile="/etc/crossbuild-tools/admin_files/TEMPLATE_SBC_IMAGE_FILE.img"
 
 usage() {
     message "${BRon}usage: ${BGon}${PN} <BOARD>${Boff}"
@@ -36,10 +36,10 @@ setup-board-image() {
     if [ ! -f ${imagefile} ] ; then
         E_message "template imagefile ${imagefile} does not exist; calling cb-mktemplateimage"
         # using sparse image format (for now)
-        cb-mktemplateimage s; result=$?
+        cb-mktemplateimage s ; result=$?
         if [[ ${result} -ne 0 ]] ; then
-            E_message "cb-mktemplateimage ${BRon}failed${Boff}"
-            FLAGGED=$TRUE
+            die "failed cb-mktemplateimage s"
+#            FLAGGED=$TRUE
         else
             message "cb-mktemplateimage ${BGon}succeeded${Boff}"
         fi
