bugfix cb-umount e2fsck directory index optimization
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-sbc/crossbuild-tools/cb-umount b/dev-sbc/crossbuild-tools/cb-umount
--- a/dev-sbc/crossbuild-tools/cb-umount
+++ b/dev-sbc/crossbuild-tools/cb-umount
@@ -59,19 +59,19 @@ umount-board() {
 	umount -l /usr/${TARGET}/dev{/shm,/pts,} 2>/dev/null || E_message "failed to umount -l /usr/${TARGET}/dev{/shm,/pts,}"
         umount -R /usr/${TARGET} || die "failed to umount -R /usr/${TARGET}"
         right_status $TRUE
+
+        # run fsck with optimization
+        message_n "optimizing directory indexes with e2fsck -fD ..."
+        # -f forces check, -D optimizes/reindexes, -y assumes yes to all
+        e2fsck -fD /dev/loop0p2 -y >/dev/null 2>&1
+        result=$?
+        case $result in
+            0|1|2 ) right_status $TRUE ;;  # 0: clean; 1: fixed; 2: fixed->reboot (N/A for .img)
+            * ) die "${BRon}e2fsck failed!${Boff} exit code: [${Mon}${result}${Boff}]" ;;
+        esac
     else
         message "nothing is mounted on /usr/${TARGET} ; continuing"
     fi
-
-    # run fsck with optimization
-    message_n "optimizing directory indexes..."
-    # -f forces check, -D optimizes/reindexes, -y assumes yes to all
-    e2fsck -fD /dev/loop0p2 -y >/dev/null 2>&1
-    result=$?
-    case $result in
-        0|1|2 ) right_status $TRUE ;;  # 0: clean; 1: fixed; 2: fixed->reboot (N/A for .img)
-        * ) die "${BRon}e2fsck failed!${Boff} exit code: [${Mon}${result}${Boff}]" ;;
-    esac
 
     # inspect for loop devices attached to BOARD image file and detach them
     message "looking for loop device attached to /usr/${BOARD}.img ..."
