bugfix cb-umount fallocate for resparsification
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-sbc/crossbuild-tools/cb-umount b/dev-sbc/crossbuild-tools/cb-umount
--- a/dev-sbc/crossbuild-tools/cb-umount
+++ b/dev-sbc/crossbuild-tools/cb-umount
@@ -85,13 +85,26 @@ umount-board() {
     fi
 
     # use fallocate to resparsify the image file
-    message_n "using ${BBon}fallocate ${BMon}-d${Boff} to resparsify /usr/${BOARD}.img"
-    fallocate -d /usr/${BOARD}.img  || die "failed to resparsify /usr/${BOARD}.img"
-    right_status $TRUE
-    apparent_size=$(du -h --apparent-size /usr/${BOARD}.img | awk '{print $1}')
-    actual_size=$(du -h /usr/${BOARD}.img | awk '{print $1}')
-    message "${BYon}/usr/${BOARD}.img${Boff} apparent: ${Mon}${apparent_size}${Boff} actual: ${Gon}${actual_size}${Boff}"
-
+    if [ -f /usr/${BOARD}.img ] ; then
+        response=""
+        msg="${BYon}Do you want to remove zero-filled space (resparsify) this image?${Boff}\n"
+        msg+="${BWon}(y|Y: yes; s|S: skip; n|N: no, abort) ${Boff}"
+        new_prompt "${msg}"
+        case ${response:0:1} in
+            [yY] )  # zero-fill and remove empty space to facilitate "resparsification" of sparse image
+                message_n "using ${BBon}fallocate ${BMon}-d${Boff} to resparsify /usr/${BOARD}.img"
+                fallocate -d /usr/${BOARD}.img  || die "failed to resparsify /usr/${BOARD}.img"
+                right_status $TRUE
+                apparent_size=$(du -h --apparent-size /usr/${BOARD}.img | awk '{print $1}')
+                actual_size=$(du -h /usr/${BOARD}.img | awk '{print $1}')
+                message "${BYon}/usr/${BOARD}.img${Boff} apparent: ${Mon}${apparent_size}${Boff} actual: ${Gon}${actual_size}${Boff}"
+                ;;
+            [sS] ) message "skipping, as instructed" ;;
+            *    ) die "aborting, as instructed" ;;
+        esac
+    else
+        message "no /usr/${BOARD}.img exists; resparsification skipped"
+    fi
     return 0
 }
 
