tweak output formats for finalize-chroot scripts
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-sbc/crossbuild-tools/mkimg-files/common/usr/sbin/finalize-chroot-common-functions b/dev-sbc/crossbuild-tools/mkimg-files/common/usr/sbin/finalize-chroot-common-functions
--- a/dev-sbc/crossbuild-tools/mkimg-files/common/usr/sbin/finalize-chroot-common-functions
+++ b/dev-sbc/crossbuild-tools/mkimg-files/common/usr/sbin/finalize-chroot-common-functions
@@ -96,10 +96,16 @@ get-check-config() {
     # source /root/.cb-config and validate TARGET (fatal if failure)
     # also assign BOARD, etc. I am ... (non-fatal if failure)
     # validation moved to validate_CHOST(); consider these tentative assignments
+    message_n "sourcing /root/.cb-config"
     if [ -e /root/.cb-config ] ; then
         source /root/.cb-config || die "failed to source /root/.cb-config"
+        echo -e -n " (${BGon}ok${Boff})"
+        right_status $TRUE
     else
+        echo -e -n " (${BRon}not found${Boff})"
+        right_status 1
         E_message "/root/.cb-config not found"
+        return 1
     fi
 
     # use indirect variable assignment to load data from name-spaced
@@ -113,23 +119,24 @@ get-check-config() {
     configvarlist+=" STAGE3_SELECTOR default_profile LLVM_TARGET"
 #    for x in ${configvarlist}; do varname="cb_${x}" ; eval $x=${!varname}; done
 # replace unsafe eval method
+    message_n "performing indirect variable assigments"
     for x in ${configvarlist}; do
         varname="cb_${x}"
         # Use printf -v for safe, indirect assignment
         # This assigns the value of ${!varname} to the variable named by $x
-        printf -v "$x" "%s" "${!varname}"
+        printf -v "$x" "%s" "${!varname}" || die "failed indirect variable assignment for $x"
+        echo -e -n " ."
     done
-
-
-    message "tentatively assigned BOARD, TARGET, etc. ..."
     right_status $TRUE
-    message "  BOARD ............: $BOARD"
-    message "  TARGET ...........: $TARGET"
-    message "  TARGET_ARCH ......: $TARGET_ARCH"
-    message "  QEMU_ARCH ........: $QEMU_ARCH"
-    message "  STAGE3_SELECTOR ..: $STAGE3_SELECTOR"
-    message "  default_profile ..: $default_profile"
-    message "  LLVM_TARGET ......: $LLVM_TARGET"
+
+    message "${BYon}tentatively assigned these globals${Boff} --"
+    message "  ${LBon}BOARD ............: ${Mon}${BOARD}${Boff}"
+    message "  ${LBon}TARGET ...........: ${Mon}${TARGET}${Boff}"
+    message "  ${LBon}TARGET_ARCH ......: ${Mon}${TARGET_ARCH}${Boff}"
+    message "  ${LBon}QEMU_ARCH ........: ${Mon}${QEMU_ARCH}${Boff}"
+    message "  ${LBon}STAGE3_SELECTOR ..: ${Mon}${STAGE3_SELECTOR}${Boff}"
+    message "  ${LBon}default_profile ..: ${Mon}${default_profile}${Boff}"
+    message "  ${LBon}LLVM_TARGET ......: ${Mon}${LLVM_TARGET}${Boff}"
 
     return 0
 }
@@ -173,10 +180,10 @@ validate-eix-db-dir() {
         echo -en " (creating)"
         mkdir -p /var/cache/eix/ ; result=$?
         if [ $result -eq 0 ] ; then
-            echo -en " ${BGon}(success)${Boff}"
+            echo -en " (${BGon}success${Boff})"
             right_status $TRUE
         else
-            echo -en " ${BRon}(fail)${Boff}"
+            echo -en " (${BRon}fail${Boff})"
             right_status 1
             SOFARSOGOOD=$FALSE
         fi
@@ -186,10 +193,10 @@ validate-eix-db-dir() {
     message_n "setting permissions for /var/cache/eix"
     chown portage:portage /var/cache/eix ; result=$?
     if [ $result -eq 0 ] ; then
-        echo -en " ${BGon}(success)${Boff}"
+        echo -en " $({BGon}success${Boff})"
         right_status $TRUE
     else
-        echo -en " ${BRon}(fail)${Boff}"
+        echo -en " (${BRon}fail${Boff})"
         right_status 1
         SOFARSOGOOD=$FALSE
     fi
diff --git a/dev-sbc/crossbuild-tools/mkimg-files/common/usr/sbin/finalize-chroot-img b/dev-sbc/crossbuild-tools/mkimg-files/common/usr/sbin/finalize-chroot-img
--- a/dev-sbc/crossbuild-tools/mkimg-files/common/usr/sbin/finalize-chroot-img
+++ b/dev-sbc/crossbuild-tools/mkimg-files/common/usr/sbin/finalize-chroot-img
@@ -166,14 +166,14 @@ validate-prerequisites-img() {
     #   call get-check-config to read .cb-config and tentatively assign ${TARGET}
     message "calling get-check-config function to read /root/.cb-config"
     get-check-config || die "failed to get-check-config"
-    message_n "(${BGon}success${Boff}"
+    message_n "(${BGon}success${Boff})"
     right_status $TRUE
 
     # (2) build-chroot_emerge-command -- assign ${chroot_emerge} using ${TARGET}
     #   build a command with which to run the emerge program in this chroot environment (depends on ${TARGET}
     message_n "building chroot_emerge command"
     build-chroot_emerge-command >/dev/null 2>&1 || die "failed to build-chroot_emerge-command"
-    echo -e -n " (${BGon}success${Boff}"
+    echo -e -n " (${BGon}success${Boff})"
     right_status $TRUE
 
     # (3) sync-repo gentoo -- populate repo gentoo to assign profile using ${chroot_emerge}
@@ -181,7 +181,7 @@ validate-prerequisites-img() {
     #   ( depends on ${chroot_emerge} set by build-chroot_emerge-command() )
     message "calling function to sync repo gentoo (ensure valid profile)"
     sync-repo gentoo || die "failed to sync-repo gentoo"
-    message_n "(${BGon}success${Boff}"
+    message_n "(${BGon}success${Boff})"
     right_status $TRUE
 
 ### maybe rename this validate-chost()
@@ -191,13 +191,13 @@ validate-prerequisites-img() {
     #   depends on profile set up by sync-repo() gentoo
     message "calling validate_CHOST function to run portageq envvar CHOST"
     validate_CHOST || die "failed to validate_CHOST"
-    message_n "(${BGon}success${Boff}"
+    message_n "(${BGon}success${Boff})"
     right_status $TRUE
 
     # (5) validate-eix-db-dir -- validate or create the eix db
     message "calling function to validate eix database directory"
     validate-eix-db-dir || die "failed to validate-eix-db-dir"
-    message_n "(${BGon}success${Boff}"
+    message_n "(${BGon}success${Boff})"
     right_status $TRUE
 
     return 0
@@ -210,7 +210,7 @@ set-password() {
     message "please set the password for user [${user}] on this image"
     passwd "${user}" ; result=$?
     if [ $result -eq 0 ] ; then
-        message "${BGon}(success)${Boff}"
+        message "(${BGon}success${Boff})"
         return 0
     else
         E_message "failed to set passwd for user [${user}]"
@@ -223,8 +223,8 @@ set-timezone() {
     #  set timezone
     message_n "setting local timezone (America/New_York) for joetoo ..."
     ln -sf ../usr/share/zoneinfo/${mytimezone} /etc/localtime && \
-    ( echo -en " ${BGon}(success)${Boff}" && right_status $result  && return 0 ) || \
-    ( echo -en " ${BRon}(fail)${Boff}" && right_status $result && FLAGGED=$TRUE && return 1 )
+    ( echo -e -n " (${BGon}success${Boff})" && right_status $result  && return 0 ) || \
+    ( echo -e -n " (${BRon}fail${Boff})" && right_status $result && FLAGGED=$TRUE && return 1 )
 }
 
 set-hostname() {
@@ -277,7 +277,7 @@ set-hostname() {
     if [[ "${response}" == [yY] ]] ; then
         message_n "setting hostname: ${candidate}"
         echo "${candidate}" > /etc/hostname && \
-            echo -en " ${BGon}(success)${Boff}" || die "failed to set hostname"
+            echo -e -n " (${BGon}success${Boff})" || die "failed to set hostname"
             right_status $TRUE
     else
         E_message "candidate hostname provided, then rejected"
@@ -294,16 +294,16 @@ remove-kernelsources-mountpoint() {
         # mountpoint already exists - remove it
         rm -r /usr/src/linux ; result=$?
         if [ $result -eq 0 ] ; then
-            echo -en " ${BGon}(removed)${Boff}"
+            echo -e -n " (${BGon}removed${Boff})"
             right_status $TRUE
         else
-            echo -en " ${BRon}(fail)${Boff}"
+            echo -e -n " (${BRon}fail${Boff})"
             right_status 1
-            FLAGGED=$TRUE 
+            FLAGGED=$TRUE
             return 1
         fi  # successful removal
     else
-        echo -en " ${BGon}(not found)${Boff}"
+        echo -e -n " (${BGon}not found${Boff})"
         right_status $TRUE
     fi  # mountpoint exists
     return 0
@@ -315,26 +315,26 @@ prep-eix-db-dir() {
     message "preparing the eix database directory ..."
     message_n "looking for /var/cache/eix"
     if [ ! -d /var/cache/eix ] ; then
-        echo -en " (creating)"
+        echo -e -n " (creating)"
         mkdir -p /var/cache/eix/ ; result=$?
         if [ $result -eq 0 ] ; then
-            echo -en " ${BGon}(success)${Boff}"
+            echo -e -n " (${BGon}success${Boff})"
             right_status $TRUE
         else
-            echo -en " ${BRon}(fail)${Boff}"
+            echo -e -n " (${BRon}fail${Boff})"
             right_status 1
             SOFARSOGOOD=$FALSE
         fi
     else
-        echo -en " (found)" ; right_status $TRUE
+        echo -e -n " (found)" ; right_status $TRUE
     fi
     message_n "setting permissions for /var/cache/eix"
     chown portage:portage /var/cache/eix ; result=$?
     if [ $result -eq 0 ] ; then
-        echo -en " ${BGon}(success)${Boff}"
+        echo -e -n " (${BGon}success${Boff})"
         right_status $TRUE
     else
-        echo -en " ${BRon}(fail)${Boff}"
+        echo -e -n " (${BRon}fail${Boff})"
         right_status 1
         SOFARSOGOOD=$FALSE
     fi
@@ -349,7 +349,7 @@ add-user() {
     response=""
     while [[ ! "${response}" == [yYsS] ]] ; do
         echo
-        echo -en "${BGon}*${Boff} set username for routine daily user: "
+        echo -e -n "${BGon}*${Boff} set username for routine daily user: "
         read candidate
         message "you responded [ ${candidate} ]"
         new_prompt "is this correct?"
@@ -357,8 +357,8 @@ add-user() {
     if [[ "${response}" == [yY] ]] ; then
         message_n "setting up user ${candidate}"
         useradd -m -G wheel,console,audio,cdrom,video,cdrw,usb,users,portage -s /bin/bash ${candidate} && \
-        ( echo -en " ${BGon}(success)${Boff}" && right_status $result ) || \
-        ( echo -en " ${BRon}(fail)${Boff}" && right_status $result && FLAGGED=$TRUE && return 1 )
+        ( echo -e -n " (${BGon}success${Boff})" && right_status $result ) || \
+        ( echo -e -n " (${BRon}fail${Boff})" && right_status $result && FLAGGED=$TRUE && return 1 )
     else
         E_message "candidate username provided, then rejected"
         message "please make a note to manually run the following command when you have time --"
@@ -373,7 +373,7 @@ add-user() {
     # assign ownership of all content in the users home directory to the user
     message_n "recursively assigning ownership of /home/${candidate} to ${candidate}"
     chown -R "${candidate}":"${candidate}" "/home/${candidate}" && \
-        echo -en " (${BGon}success${Boff})" || die "failed to assign ownership for ${candidate}"
+        echo -e -n " (${BGon}success${Boff})" || die "failed to assign ownership for ${candidate}"
     right_status $TRUE
     return 0
 }
@@ -381,12 +381,12 @@ add-user() {
 fix-inittab() {
     message_n "fixing /etc/inittab s0..."
     sed -i 's|^s0:|#s0:|' /etc/inittab && result=$? && \
-    ( echo -en " ${BGon}(success)${Boff}" && right_status $result  && return 0 ) || \
-    ( echo -en " ${BRon}(fail)${Boff}" && right_status $result && FLAGGED=$TRUE && return 1 )
+    ( echo -e -n " (${BGon}success${Boff})" && right_status $result  && return 0 ) || \
+    ( echo -e -n " (${BRon}fail${Boff})" && right_status $result && FLAGGED=$TRUE && return 1 )
     message_n "fixing /etc/inittab f0..."
     sed -i 's|^f0:|#f0:|' /etc/inittab && result=$? && \
-    ( echo -en " ${BGon}(success)${Boff}" && right_status $result  && return 0 ) || \
-    ( echo -en " ${BRon}(fail)${Boff}" && right_status $result && FLAGGED=$TRUE && return 1 )
+    ( echo -e -n " (${BGon}success${Boff})" && right_status $result  && return 0 ) || \
+    ( echo -e -n " (${BRon}fail${Boff})" && right_status $result && FLAGGED=$TRUE && return 1 )
 }
 
 write-fstab() {
@@ -394,14 +394,14 @@ write-fstab() {
     message_n "determining root_dev ..."
     root_mountpoint="/"
     root_dev=$(mount | grep " ${root_mountpoint} " | awk '{print $1}') && \
-    ( echo -en " (${root_dev})" && right_status $result ) || \
-    ( echo -en " ${BRon}(fail)${Boff}" && right_status $result && FLAGGED=$TRUE && return 1 )
+    ( echo -e -n " (${root_dev})" && right_status $result ) || \
+    ( echo -e -n " (${BRon}fail${Boff})" && right_status $result && FLAGGED=$TRUE && return 1 )
     # get boot_dev
     boot_mountpoint="/boot"
     message_n "determining boot_dev ..."
     boot_dev=$(mount | grep " ${boot_mountpoint} " | awk '{print $1}') && \
-    ( echo -en " (${boot_dev})" && right_status $result ) || \
-    ( echo -en " ${BRon}(fail)${Boff}" && right_status $result && FLAGGED=$TRUE && return 1 )
+    ( echo -e -n " (${boot_dev})" && right_status $result ) || \
+    ( echo -e -n " (${BRon}fail${Boff})" && right_status $result && FLAGGED=$TRUE && return 1 )
     # get blkid data for root_dev
     message_n "getting blkid data for root_dev"
     eval $(blkid | grep ${root_dev} | sed "s|${root_dev}: ||") ; result=$?
@@ -409,10 +409,10 @@ write-fstab() {
         root_fstype=${TYPE}
         root_uuid=${UUID}
         root_partuuid=${PARTUUID}
-        echo -en " (fstype: [${root_fstype=}] partuuid: [${root_partuuid}])"
+        echo -e -n " (fstype: [${root_fstype=}] partuuid: [${root_partuuid}])"
         right_status $result
     else
-        echo -en " ${BRon}(fail)${Boff}"
+        echo -e -n " (${BRon}fail${Boff})"
         right_status $result
         FLAGGED=$TRUE
         return 1
@@ -424,10 +424,10 @@ write-fstab() {
         boot_fstype=${TYPE}
         boot_uuid=${UUID}
         boot_partuuid=${PARTUUID}
-        echo -en " (fstype: [${boot_fstype=}] partuuid: [${boot_partuuid}])"
+        echo -e -n " (fstype: [${boot_fstype=}] partuuid: [${boot_partuuid}])"
         right_status $result
     else
-        echo -en " ${BRon}(fail)${Boff}"
+        echo -e -n " (${BRon}fail${Boff})"
         right_status $result
         FLAGGED=$TRUE
         return 1
@@ -440,17 +440,17 @@ write-fstab() {
     # write (append) fstab line for /boot and / (PARTUUIDs will have to be changed after image is written to media (e.g. sd card)
     message_n "writing (appending) fstab line for /boot ..."
     echo -e "PARTUUID=${boot_partuuid}\t${boot_mountpoint}\t\t${boot_fstype}\t\t${boot_opts}\t\t${boot_dp}" >> /etc/fstab && \
-    ( echo -en " ${BGon}(success)${Boff}" && right_status $result  && return 0 ) || \
-    ( echo -en " ${BRon}(fail)${Boff}" && right_status $result && FLAGGED=$TRUE )
+    ( echo -e -n " (${BGon}success${Boff})" && right_status $result  && return 0 ) || \
+    ( echo -e -n " (${BRon}fail${Boff})" && right_status $result && FLAGGED=$TRUE )
     message_n "writing (appending) fstab line for / ..."
     echo -e "PARTUUID=${root_partuuid}\t${root_mountpoint}\t\t${root_fstype}\t\t${root_opts}\t\t${root_dp}" >> /etc/fstab && \
-    ( echo -en " ${BGon}(success)${Boff}" && right_status $result  && return 0 ) || \
-    ( echo -en " ${BRon}(fail)${Boff}" && right_status $result && FLAGGED=$TRUE )
+    ( echo -e -n " (${BGon}success${Boff})" && right_status $result  && return 0 ) || \
+    ( echo -e -n " (${BRon}fail${Boff})" && right_status $result && FLAGGED=$TRUE )
     # write (append) a placeholder fstab line for swap
     message_n "writing (appending) fstab placeholder line for /var/cache/swap/swap1 ..."
     echo -e "/var/cache/swap/swap1\tnone\t\tswap\t\tsw\t\t0 0" >> /etc/fstab && \
-    ( echo -en " ${BGon}(success)${Boff}" && right_status $result  && return 0 ) || \
-    ( echo -en " ${BRon}(fail)${Boff}" && right_status $result && FLAGGED=$TRUE )
+    ( echo -e -n " (${BGon}success${Boff})" && right_status $result  && return 0 ) || \
+    ( echo -e -n " (${BRon}fail${Boff})" && right_status $result && FLAGGED=$TRUE )
     return 0
 }
 
@@ -459,10 +459,10 @@ make-mountpoints() {
     for x in card stick thumb image gentoo from to key temp ; do
         message_n "mountpoint ${x}"
         if [ ! -d /mnt/${x} ] ; then
-            echo -en " (making)"
+            echo -e -n " (making)"
             mkdir -p /mnt/${x} ; right_status $?
         else
-            echo -en " (exists)" ; right_status $TRUE
+            echo -e -n " (exists)" ; right_status $TRUE
         fi
     done
 }
@@ -476,12 +476,12 @@ add-default-runlevel-services() {
     for x in $list ; do
         message_n "interface ${x}"
         if [ ! -L /etc/init.d/net.${x} ] ; then
-            echo -en " (linking)"
+            echo -e -n " (linking)"
             ln -s /etc/init.d/net.lo /etc/init.d/net.${x} ; result=$?
-            ( echo -en " ${BGon}(success)${Boff}" && right_status $result ) || \
-            ( echo -en " ${BRon}(fail)${Boff}" && right_status $result && SOFARSOGOOD=$FALSE )
+            ( echo -e -n " (${BGon}success${Boff})" && right_status $result ) || \
+            ( echo -e -n " (${BRon}fail${Boff})" && right_status $result && SOFARSOGOOD=$FALSE )
         else
-            echo -en " (already linked)" ; right_status $TRUE
+            echo -e -n " (already linked)" ; right_status $TRUE
         fi
     done
     # add links for services in default runlevel
@@ -490,12 +490,12 @@ add-default-runlevel-services() {
     for x in $list ; do
         message_n "examining ${x}"
         if [ ! -L /etc/runlevels/default/${x} ] ; then
-            echo -en " (linking)"
+            echo -e -n " (linking)"
             ln -s /etc/init.d/${x} /etc/runlevels/default/${x} ; result=$?
-            ( echo -en " ${BGon}(success)${Boff}" && right_status $result ) || \
-            ( echo -en " ${BRon}(fail)${Boff}" && right_status $result && SOFARSOGOOD=$FALSE )
+            ( echo -e -n " (${BGon}success${Boff})" && right_status $result ) || \
+            ( echo -e -n " (${BRon}fail${Boff})" && right_status $result && SOFARSOGOOD=$FALSE )
         else
-            echo -en " (already linked)" ; right_status $TRUE
+            echo -e -n " (already linked)" ; right_status $TRUE
         fi
     done
     if [[ $SOFARSOGOOD ]] ; then
