collect-system-files-0.1.0.tbz2 ssh functions extracted to script_header_joetoo_ssh and collect-system-files refactored for j_msg and updated script_header_joetoo; fix to load ssh header
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-sbc/collect-system-files/collect-system-files b/dev-sbc/collect-system-files/collect-system-files
--- a/dev-sbc/collect-system-files/collect-system-files
+++ b/dev-sbc/collect-system-files/collect-system-files
@@ -15,6 +15,7 @@ if [ -f "$header" ]; then
     source_finding="was already sourced"
   else
     . "$header"
+    . "${header}_ssh"   # also source the ssh module
     source_finding="sourced"
   fi
 else
@@ -27,6 +28,14 @@ if command -v toc >/dev/null 2>&1 && command -v run_sequence >/dev/null 2>&1 ; t
   printf '%s\n' " success; header ${source_finding}"
 else
   printf '%s\n' " Failed; header not sourced; cannot continue"; exit 1
+fi
+
+# verify sourced script_header ssh key management module
+printf '%s' "Checking for ssh header commands to confirm sourcing"
+if command -v load_key >/dev/null 2>&1 && command -v run_sequence >/dev/null 2>&1 ; then
+  printf '%s\n' " success; ssh header ${source_finding}"
+else
+  printf '%s\n' " Failed; ssh header not sourced; cannot continue"; exit 1
 fi
 
 #-----[ variables ]----------------------------------------------------
