jus-6.7.6.tbz2 - refactor for j_msg
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/app-portage/jus/rus b/app-portage/jus/rus
--- a/app-portage/jus/rus
+++ b/app-portage/jus/rus
@@ -38,12 +38,12 @@
 
 script_header_installed_dir="/usr/sbin"
 header="${script_header_installed_dir%/}/script_header_joetoo"
-echo "header: $header"
+printf '%s\n' "header: $header"
 
 if [ -f "$header" ]; then . "$header"; else printf '%s' "failed to source header; cannot continue"; exit 1; fi
 printf '%s' "Checking for header commands to confirm sourcing"
 if command -v toc >/dev/null 2>&1 && command -v run_sequence >/dev/null 2>&1 ; then
-handle_result $? ; else printf '%s\n' "Failed; header not sourced; cannot continue"; exit 1; fi
+handle_result $? ${notice} ; else printf '%s\n' "Failed; header not sourced; cannot continue"; exit 1; fi
 
 #-----[ variables ]----------------------------------------------------
 
@@ -102,15 +102,15 @@ PN=${0##*/}  # equivalent to =$(basename "$0") but w/o subshell and function cal
 initialize_command_sequence() # (POSIX) initialize command sequence for joetoo cli framework
 { ics_ret=0
   _ics_FLAGGED=$FALSE
-  info_msg_n "creating tempfile for command sequnce"
+  j_msg -${info} -m -n "creating tempfile for command sequnce"
   cmd_seq_file=$(mktemp /tmp/${PN}.XXXXXX)
-  info_handle_result $? "$cmd_seq_file" '' || _ics_FLAGGED=$TRUE
+  handle_result $? "$cmd_seq_file" '' ${info} || _ics_FLAGGED=$TRUE
 
-  info_msg_n "setting trap to remove tempfile on EXIT"
+  j_msg -${info} -m -n "setting trap to remove tempfile on EXIT"
   trap 'rm -f "$cmd_seq_file"' EXIT
-  info_handle_result $? "trap set" ''  || _ics_FLAGGED=$TRUE
+  handle_result $? "trap set" '' ${info} || _ics_FLAGGED=$TRUE
 
-  notice_msg_n "initializing command sequence"
+  j_msg -${notice} -p -n "initializing command sequence"
   num_cmds=0   # global variable holding the length of the sequence
 # heredoc needs to be on the left edge; no leading whitespace
 # initialize/clear the command sequence file
@@ -130,15 +130,15 @@ rebuild_system${US}Rebuild system set with new toolchain
 rebuild_world${US}Rebuild world set with new toolchain
 pkgsync start${US}Re-start syncing packages with other nodes
 EOF
-  handle_result $? "num_cmds: $num_cmds" '' || _ics_FLAGGED=$TRUE
+  handle_result $? ${notice} "num_cmds: $num_cmds" '' || _ics_FLAGGED=$TRUE
 
-  info_msg_n "initailizing starting_step"
+  j_msg -${info} -m -n "initailizing starting_step"
   starting_step=1
-  info_handle_result $? "$starting_step" '' || _ics_FLAGGED=$TRUE
+  handle_result $? "$starting_step" '' ${info} || _ics_FLAGGED=$TRUE
 
-  info_msg_n "initializing stopping step"
+  j_msg -${info} -m -n "initializing stopping step"
   stopping_step="$num_cmds"
-  info_handle_result $? "$stopping_step" '' || _ics_FLAGGED=$TRUE
+  handle_result $? "$stopping_step" '' ${info} || _ics_FLAGGED=$TRUE
 
   [ "$_ics_FLAGGED" ] && ics_ret=1
   export num_cmds
@@ -159,9 +159,9 @@ EOF
 initialize_rus_variables()
 { irv_ret=0; _irv_FLAGGED="$FALSE"
 
-  info_msg "assigning logFile"
+  j_msg -${info} -m "assigning logFile"
   logFile=/var/log/rus.log
-  info_handle_result $? "$logFile" "" || _irv_FLAGGED="$TRUE"
+  handle_result $? "$logFile" "" ${info} || _irv_FLAGGED="$TRUE"
 
   # 'WARNING, if config_dir is other than /etc/${PN} and if config_dir is in varlist' -
   # it will get initialized (erased) when app_configure runs initialize_vars
@@ -180,63 +180,63 @@ initialize_rus_variables()
   # It is done this way for rus, because I wanted to keep rus configs in
   # /etc/jus/rus/ rathern than have the ebuild separate them out to /etc/rus/
 
-  info_msg_n "assigning config_dir"
+  j_msg -${info} -m -n "assigning config_dir"
   config_dir=/etc/jus/rus
-  info_handle_result $? "$config_dir" "" || _irv_FLAGGED="$TRUE"
+  handle_result $? "$config_dir" "" || _irv_FLAGGED="$TRUE"
 
-  info_msg_n "assigning INTERACTIVE"
+  j_msg -${info} -m -n "assigning INTERACTIVE"
   export INTERACTIVE=$TRUE
-  info_handle_result $? "$(TrueFalse $INTERACTIVE)" "" || _irv_FLAGGED="$TRUE"
+  handle_result $? "$(TrueFalse $INTERACTIVE)" "" ${info} || _irv_FLAGGED="$TRUE"
 
-  info_msg_n "assigning LOGGING"
+  j_msg -${info} -m -n "assigning LOGGING"
   export LOGGING=$TRUE
-  info_handle_result $? "$(TrueFalse $LOGGING)" "" || _irv_FLAGGED="$TRUE"
+  handle_result $? "$(TrueFalse $LOGGING)" "" ${info} || _irv_FLAGGED="$TRUE"
 
   # initialize RESUME - can be overridden by sourced config below (and cmdline)
-  info_msg_n "assigning default RESUME"
+  j_msg -${info} -m -n "assigning default RESUME"
   export RESUME=$FALSE
-  info_handle_result $? "$(TrueFalse $RESUME)" '' || _irv_FLAGGED="$TRUE"
+  handle_result $? "$(TrueFalse $RESUME)" '' ${info} || _irv_FLAGGED="$TRUE"
 
-  info_msg_n "assigning app_customization_root"
+  j_msg -${info} -m -n "assigning app_customization_root"
   app_customization_root=/etc/jus/rus
-  info_handle_result $? "$app_customization_root" "" || _irv_FLAGGED="$TRUE"
+  handle_result $? "$app_customization_root" "" ${info} || _irv_FLAGGED="$TRUE"
 
-  info_msg_n "assigning status_file"
+  j_msg -${info} -m -n "assigning status_file"
   status_file="${HOME}/.config/rus.status"
-  info_handle_result $? "$status_file" "" || _irv_FLAGGED="$TRUE"
+  handle_result $? "$status_file" "" ${info} || _irv_FLAGGED="$TRUE"
 
-  info_msg_n "assigning key_packages1"
+  j_msg -${info} -m -n "assigning key_packages1"
   key_packages1=(
     'sys-libs/glibc'
     'sys-devel/binutils'
     'dev-build/libtool'
     'sys-devel/gcc'
   )
-  info_right_status $? || _irv_FLAGGED="$TRUE"
+  right_status $? ${info} || _irv_FLAGGED="$TRUE"
 
-  info_msg_n "assigning key_packages2"
+  j_msg -${info} -m -n "assigning key_packages2"
   key_packages2=(
     'sys-kernel/linux-headers'
     'sys-devel/gcc-config'
   )
-  info_right_status $? || _irv_FLAGGED="$TRUE"
+  right_status $? ${info} || _irv_FLAGGED="$TRUE"
 
-  info_msg_n "setting DISTCC = \$FALSE"
+  j_msg -${info} -m -n "setting DISTCC = \$FALSE"
   DISTCC=$FALSE
-  info_right_status $? || _irv_FLAGGED="$TRUE"
+  right_status $? ${info} || _irv_FLAGGED="$TRUE"
 
     # default setting - my be over-ridden by command line option (n vs d)
-  info_msg_n "assigning default rus_features"
+  j_msg -${info} -m -n "assigning default rus_features"
   rus_features=" -distcc -getbinpkg"
-  info_handle_result $? "$rus_features" "" || _irv_FLAGGED="$TRUE"
+  handle_result $? "$rus_features" "" ${info} || _irv_FLAGGED="$TRUE"
 
-  info_msg_n "assigning default rus_makeopts"
+  j_msg -${info} -m -n "assigning default rus_makeopts"
   rus_makeopts="-j$(nproc)"
-  info_handle_result $? "$rus_makeopts" "" || _irv_FLAGGED="$TRUE"
+  handle_result $? "$rus_makeopts" "" ${info} || _irv_FLAGGED="$TRUE"
 
-  info_msg_n "sourcing make.conf in a subshell, to assign PKGDIR"
-  PKGDIR=$( . /etc/portage/make.conf; echo $PKGDIR )
-  info_handle_result $? "$PKGDIR" "" || _irv_FLAGGED="$TRUE"
+  j_msg -${info} -m -n "sourcing make.conf in a subshell, to assign PKGDIR"
+  PKGDIR=$( . /etc/portage/make.conf; printf '%s\n' "$PKGDIR" )
+  handle_result $? "$PKGDIR" "" ${info} || _irv_FLAGGED="$TRUE"
 
   validate_dir "$config_dir"   # does its own announce/act/report-results
 
@@ -246,48 +246,48 @@ initialize_rus_variables()
   validate_dir "$config_dir"   # does its own announce/act/report-results
 
   # BUILD="string" should be located in config_dir (which is other than /etc/${PN})
-  info_msg_n "sourcing BUILD variable assignment"
+  j_msg -${info} -m -n "sourcing BUILD variable assignment"
   . "${config_dir}/BUILD"
-  info_handle_result $? "$BUILD" '' || _irv_FLAGGED="$TRUE"
+  handle_result $? "$BUILD" '' ${info} || _irv_FLAGGED="$TRUE"
 
   # if the package has a config source it here (for config_dir other than /etc/${PN})
-  info_msg "looking for config file(s) in /etc/${PN}"
+  j_msg -${info} -m "looking for config file(s) in /etc/${PN}"
   config_files=""
   validate_dir "$config_dir"
   for _c_file in $(find "$config_dir" -maxdepth 1 -name "*.conf" -type f); do
     # accumulate found files in config_files, prepending a space only if it is not the first entry
     config_files="${config_files:+ }$_c_file"
-    info_msg_n "sourcing $_c_file"
+    j_msg -${info} -m -n "sourcing $_c_file"
     . "$_c_file"
-    info_handle_result $? "$_c_file" "" || _irv_FLAGGED="$TRUE"
+    handle_result $? "$_c_file" "" ${info} || _irv_FLAGGED="$TRUE"
   done
-  info_msg "config_files: [$config_files]"
+  j_msg -${info} -m "config_files: [$config_files]"
 
   # tier 3 - application customization and extension  (for config_dir other than /etc/${PN})
   # this should reside in app_customization_root directory
   # contains handle_local_arg(), handle_local_compound_arg(), and handle_local_usage
   # find (validates) *_local.cmdline_arguments; assign first match
-  info_msg_n "looking for *local.cmdline_arg_handler "
+  j_msg -${info} -m -n "looking for *local.cmdline_arg_handler "
   local_cmdline_arg_handler=$(find "${app_customization_root%/}/" -name "*local.cmdline_arg_handler" | head -n 1 )
   _c_result=$?
   _c_handler="${local_cmdline_arg_handler:-"none found"}"
    # =${var##*/} is =$(basename $var) but w/o subshell and function call
-   info_handle_result $_c_result "${_c_handler##*/}" "error" || _c_FLAGGED=$TRUE
+   handle_result $_c_result "${_c_handler##*/}" "error" ${info} || _c_FLAGGED=$TRUE
   if [ -f "$local_cmdline_arg_handler" ]; then
-    info_msg_n "sourcing local_cmdline_arg_handler"
+    j_msg -${info} -m -n "sourcing local_cmdline_arg_handler"
     . "$local_cmdline_arg_handler"
-    info_handle_result $? "sourced" "error sourcing local_cmdline_arg_handler" || _c_FLAGGED=$TRUE
+    handle_result $? "sourced" "error sourcing local_cmdline_arg_handler" ${info} || _c_FLAGGED=$TRUE
   fi
 
   # use POSIX method of indirect variable assignment to display the existence of local handlers
   for x in handle_local_arg handle_local_compound_arg handle_local_usage; do
-    info_msg_n "setting variable to display whether $x EXISTS"
+    j_msg -${info} -m -n "setting variable to display whether $x EXISTS"
     _c_extester="${x}_EXISTS"
     command -v "$x" >/dev/null 2>/dev/null ; _c_result=$?
     if [ "$_c_result" -eq 0 ] ; then eval "${_c_extester}=$TRUE"; else eval "${_c_extester}=$FALSE"; fi
     d_do '
       printf " (%b%s%b)" "$(eval status_color \$$_c_extester)" "$(eval TrueFalse \$$_c_extester)" "${Boff}" "$info"
-      right_status "$_c_result"
+      right_status "$_c_result" ${info}
     ' "$info"
   done
 
@@ -338,10 +338,10 @@ rebuild_toolchain()
 
 remove_pkgdir() # safely remove contents for binary package direcory PKGDIR
 { rp_ret=0
-  [ ! -d "${PKGDIR}" ] && { error_msg "PKGDIR [${PKGDIR}] is not a valid directory"; return 1 ; }
+  [ ! -d "${PKGDIR}" ] && { j_msg -${err} "PKGDIR [${PKGDIR}] is not a valid directory"; return 1 ; }
   warn_msg "${BYon}Warning: abount to remove all contents from PKGDIR [$PKGDIR]"
   confirm_continue_or_exit
-  rm -rfv "${PKGDIR}" || { error_msg "failed to rm -rfv ${PKGDIR}"; return 1 ; }
+  rm -rfv "${PKGDIR}" || { j_msg -${err} "failed to rm -rfv ${PKGDIR}"; return 1 ; }
   return $rp_ret
 }
 
@@ -355,68 +355,68 @@ set_distcc() {
   case $1 in
     $FALSE ) rus_features=" -distcc -getbinpkg" ;;
     $TRUE  ) rus_features=" distcc -getbinpkg" ;;
-    *     ) error_msg "Internal error - invalid parameter sent to set_distcc [$1]"; exit 1 ;;
+    *     ) j_msg -${err} "Internal error - invalid parameter sent to set_distcc [$1]"; exit 1 ;;
   esac
 }
 
 get_number()        # set external variable $answer based on reponse to prompt $1
-{ ps=$1; echo_msg; echo_msg; CUU; SCP; notice_msg_n "$ps [0-9]: " && read answer;
+{ ps=$1; j_msg -${notice} -mp; j_msg -${notice} -mp; CUU; SCP; j_msg -${notice} -p -n "$ps [0-9]: " && read answer;
 #while ! expr "${answer:0:1}" : [0-9] >/dev/null;  # answer not a regex match
 while ! expr "${answer:0:1}" : \[0-9\] >/dev/null;  # answer not a regex match
-do RCP; echo_e_msg_n "$(repeat ' ' $(termwidth))";  ## blank the line
-RCP; notice_msg_n "$ps [0-9]: " && read answer; done; }
+do RCP; j_msg -${notice} -mp -n "$(repeat ' ' $(termwidth))";  ## blank the line
+RCP; j_msg -${notice} -p -n "$ps [0-9]: " && read answer; done; }
 
 get_answer()        # set external variable $answer based on reponse to prompt $1
-{ ps=$1; echo_msg; echo_msg; CUU; SCP; notice_msg_n "$ps [yngYNG]: " && read answer;
+{ ps=$1; j_msg -${notice} -mp; j_msg -${notice} -mp; CUU; SCP; j_msg -${notice} -p -n "$ps [yngYNG]: " && read answer;
 while ! expr "${answer:0:1}" : \[yngYNG\] >/dev/null;  # answer not a regex match
-do RCP; echo_e_msg_n "$(repeat ' ' $(termwidth))";  ## blank the line
-RCP; notice_msg_n "$ps [yngYNG]: " && read answer; done; }
+do RCP; j_msg -${notice} -mp -n "$(repeat ' ' $(termwidth))";  ## blank the line
+RCP; j_msg -${notice} -p -n "$ps [yngYNG]: " && read answer; done; }
 
 pick_gcc()          # pick the appropriate gcc
 { gcc-config -l; get_number "Select gcc profile from list above";
-notice_msg "setting gcc-config $answer" && gcc-config ${answer};
-notice_msg "sourcing /etc/profile" && source /etc/profile; }
+j_msg -${notice} -p "setting gcc-config $answer" && gcc-config ${answer};
+j_msg -${notice} -p "sourcing /etc/profile" && source /etc/profile; }
 
 pick_binutils()          # pick the appropriate gcc
 { binutils-config -l; get_number "Select binutils profile from list above";
-notice_msg "setting binutils-config $answer" && binutils-config ${answer};
-notice_msg "sourcing /etc/profile" && source /etc/profile; }
+j_msg -${notice} -p "setting binutils-config $answer" && binutils-config ${answer};
+j_msg -${notice} -p "sourcing /etc/profile" && source /etc/profile; }
 
 pkgsync()            # stop/start syncing packages
 {
 action="$1"
-echo_msg; notice_msg "action: ${action}"
+j_msg -${notice} -mp; j_msg -${notice} -p "action: ${action}"
 cslinelist=($(grep -n cloudsync /etc/crontab | cut -d':' -f1))
 if [[ "${action}" == "stop" ]]
 then
-  notice_msg "commenting out cloudsync cron job in crontab";
+  j_msg -${notice} -p "commenting out cloudsync cron job in crontab";
   for ((i=0; i<${#cslinelist[@]}; i++))
   do
-    notice_msg "maybe comment line: ${cslinelist[i]}"
+    j_msg -${notice} -p "maybe comment line: ${cslinelist[i]}"
     sed -i "${cslinelist[i]} s|^.|#&|" /etc/crontab;
   done;
-  notice_msg "stopping rsyncd"
+  j_msg -${notice} -p "stopping rsyncd"
   /etc/init.d/rsyncd stop
-  notice_msg "restarting cronie"
+  j_msg -${notice} -p "restarting cronie"
   /etc/init.d/cronie restart
 elif [[ "${action}" == "start" ]]
 then
-  notice_msg "un-commenting cloudsync cron job in crontab"
+  j_msg -${notice} -p "un-commenting cloudsync cron job in crontab"
   # if it is not already commented, then comment it
   for ((i=0; i<${#cslinelist[@]}; i++))
   do
-    notice_msg "maybe uncomment line: ${cslinelist[i]}"
+    j_msg -${notice} -p "maybe uncomment line: ${cslinelist[i]}"
     sed -i "${cslinelist[i]} s|^#||" /etc/crontab
   done
-  notice_msg "restarting rsyncd"
+  j_msg -${notice} -p "restarting rsyncd"
   /etc/init.d/rsyncd restart
-  notice_msg "restarting cronie"
+  j_msg -${notice} -p "restarting cronie"
   /etc/init.d/cronie restart
 else
-  error_msg "Invalid action passed to pkgsync; exiting"
+  j_msg -${err} "Invalid action passed to pkgsync; exiting"
   exit
 fi
-notice_msg "done pkgsync ${action}"
+j_msg -${notice} -p "done pkgsync ${action}"
 }
 
 #-----[ main script ]----------------------------------------------------
@@ -428,26 +428,26 @@ app_configure || die "failed to app_configure"
 
 # re-assign varlist variables appended at the top of the script and thus
 # over-written by app_configure
-#info_msg_n "(re)assigning LOCALIZED"
+#j_msg -${info} -m -n "(re)assigning LOCALIZED"
 #LOCALIZED=$TRUE
-#info_handle_result $? "$(TrueFalse $LOCALIZED)" "failed to reassign LOCALIZED"
-#info_msg_n "(re)assigning INITIALIZED_ME"
+#handle_result $? "$(TrueFalse $LOCALIZED)" "failed to reassign LOCALIZED" ${info}
+#j_msg -${info} -m -n "(re)assigning INITIALIZED_ME"
 #INITIALIZED_ME="yes"
-#info_handle_result $? "$INITIALIZED_ME" "failed to reassign INITIALIZED_ME" "$notice"
+#handle_result $? "$INITIALIZED_ME" "failed to reassign INITIALIZED_ME" "${info}"
 
 initialize_rus_variables || die "failed to initialize_rus_variables"
 
 d_do show_config "$info"  # show config prior to processing cmdline only at info/debug verbosity
-info_msg "(BEFORE process_cmdline)"
+j_msg -${info} -m "(BEFORE process_cmdline)"
 
 process_cmdline "$@" || die "failed to process_cmdline"
 
 show_config
-info_msg "(AFTER process_cmdline)"
+j_msg -${info} -m "(AFTER process_cmdline)"
 
 run_sequence "$status_file" "$starting_step" "$stopping_step"
 result=$?
 separator "$PN-$BUILD" "(Done)"
-notice_msg_n "$PN complete. Results:"
-handle_result $result "exemplary success" "exemplary failure"
+j_msg -${notice} -p -n "$PN complete. Results:"
+handle_result $result "rus success" "rus failure" ${notice}
 exit $result
